### ISSUE TITLE
Github update dependencies fails with private registry

### ISSUE THREAD

**Issue by eriklztiqqe** [projen/projen#1006]
We have multiple repositories, which have dependencies towards AWS CDK constructs in private npm registries (Github packages, later possibly Cloudsmith).

To access these constructs we thus need NPM_TOKEN exposed, but the update dependencies workflow does not include this, only GITHUB_TOKEN.
This causes the workflow to fail each time and we get an email notification about it. Currently, that includes about 13-14 repositories, and there will be more.

This is kind of related to #815, which also concerns the lack of exposed variables, but a different use case.

**Comment by jumic** [comment]
You can use `workflowBootstrapSteps` to add additional steps to your workflow. I used the following code snippet:
```ts
workflowBootstrapSteps: [{
  name: 'npmjs login',
  run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc',
  env: {
    NPM_TOKEN: '${{ secrets.NPM_TOKEN }}',
  },
}],
```
It creates file `.npmrc` including the `NPM_TOKEN`. In my example project I was able to use a private package from npm.js in my upgrade workflow.
