### ISSUE TITLE
Add a more abstract Project base class

### ISSUE THREAD

**Issue by mmcculloh-dms** [projen/projen#1011]
The existing Project class has quite a few things in it. If one is making a new project type, it would be nice to be able to limit what's inherited from the base to be able to pick and choose components more freely. 

Of the options provided to the base class, these seem to be the "core" options:
- name
- parent
- outdir
- projectType
- logging
- projenrcJson

**Comment by eladb** [comment]
Yes, I agree that we should make `Project` less opinionated. This is mostly related to the coupling we have today between `Project` and GitHub (and even VSCode). The current design is too tightly coupled. I'd like to see more abstractions around workflows for example that will enable that decoupling.

**Comment by mmcculloh-dms** [comment]
Would it be sufficient to create a new class, Like `BaseProject` or something, and have the current `Project` extend it?

**Comment by eladb** [comment]
I rather we "shift down" and keep `Project` pure. Let me have a look at this. Might be able to do something in short order.
