### ISSUE TITLE
feat req: Include test utils or test snapshots

### ISSUE THREAD

**Issue by joostvdwsd** [projen/projen#1016]
this PR https://github.com/projen/projen/pull/992 broke all our test because the test utils file was also excluded.

Would be nice to have the in-memory snapshot available for external modules. This can be by including the test utils as-is in the package (maybe in a different place).

Another option would be to add the method testSnapshot() to the projen class. This is maybe not perfect when looking from production/test code but it will give a lot of extra freedom for testing

**Comment by eladb** [comment]
Why not just put the test utilities under `src/test-util.ts` so it does not get excluded? I would argue that if this is "production code" then it shouldn't live under `__tests__`.

**Comment by joostvdwsd** [comment]
That was indeed my first point. It is used by us as dev dependency and in that case it can be considered production code. Want me to create a PR? Will take a bit of time for me due to a lot of other stuff

**Comment by eladb** [comment]
Oh, now I understand. You are utilizing projen's test utilities in your project by importing the private API into your project.

Yes, totally happy to expose this as a public API if there is utility to that. Contributions are welcome.
