### ISSUE TITLE
Types deps.Dependency and deps.DependencyType are not exported

### ISSUE THREAD

**Issue by eriklz** [projen/projen#1044]
The Project base class has a deps property that stores dependencies, and a method getDependency() on this one.
However, due to the related types such as deps.DependencyType and deps.Dependency not being exported, it does not work so well to use in unit tests for a custom project type due to type errors.

It would be great if these types were exported, or other means to test/check what dependencies are in place.

**Comment by Chriscbr** [comment]
It looks like these types should be getting exported since they appear in the API reference (https://github.com/projen/projen/blob/03d142ea235fe8b9b45d898aab513857634a67b9/API.md). Is it possible they're getting imported wrong? I'm able to access `DependencyType` in my projenrc.js file like this: 

```js
const { deps, TypeScriptProject } = require('projen');

const dep = deps.DependencyType.BUILD;
```

**Comment by eriklz** [comment]
Oh right, my mistake - I tried to import DependencyType directly from projen. Works fine with importing the deps namespace.
