### ISSUE TITLE
Add option to disable self-mutation commits

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1046]
These commits can be undesirable in some situations since they don't trigger new workflow runs (since they are pushed by GITHUB_TOKEN). In particular, if a user sets up additional jobs (e.g. PR linters or integration tests) as part of the build task, a self-mutation commit might get generated and self-approved, overriding the fact that one of the other jobs may have failed.

A more general solution might be to design a high-level API for configuring various "checks" that people want to run on PRs, and somehow configure self-mutation to only occur if all of the jobs have succeeded. (Or, to figure out some workaround around GitHub's limitations to allow workflows to run on the self-mutation commit).

**Comment by eladb** [comment]
I was certain we already have a switch for this but apparently we don't.

https://github.com/projen/projen/blob/03d142ea235fe8b9b45d898aab513857634a67b9/src/node-project.ts#L569

**Comment by eladb** [comment]
We've solved this. These commits now trigger workflows by using a PAT

**Comment by Chriscbr** [comment]
Ah I see, yes this is the `mutableBuild` option that is currently enabled by default. Nice! I'll go ahead and close this
