### ISSUE TITLE
Bump version of Jest dependency

### ISSUE THREAD

**Issue by mtimbs** [projen/projen#1049]
Projen automatically adds Jest as a dependency for TypeScript apps (along with Jest types). It currently pins to version 26, this causes issues with recent CDK versions that have a requirement >= version 27.

Any chance of updating Projen to use Jest 27 (along with "@types/jest": "^27.1.1",and "ts-jest": "^27.1.1"). I'd have opened a PR myself but I couldn't easily see where these are managed

**Comment by Chriscbr** [comment]
I'm having trouble reproducing this - when I create a new TypeScript app, I see jest version 27 in my package.json.

**Comment by mtimbs** [comment]
Apologies I should have checked a fresh install. The problem was trying to run an update from an older version that shipped with 26. It couldn't resolve without manual intervention.
