### ISSUE TITLE
RFC: AWS Lambda function project

### ISSUE THREAD

**Issue by hoegertn** [projen/projen#105]
What about a new project type for Lambda functions. It would be a TypeScript project but with type definitions, middleware etc as dependencies and some opinionated defaults for Lambda functions.

It could even generate the handler code and then hand over to the business logic implementation.

It would be optimized to be used with the NodeJsFunction construct of the AWS CDK.

We can collect ideas here and then draft a PR for this.

**Comment by eladb** [comment]
My personal preference is to master lambda code inside the CDK repo and not as a separate repo. We should create CDK projects!

**Comment by hoegertn** [comment]
Definitely inside the same repo but in another folder.

I am thinking of a projen type for Lambda functions and use it within the same projen file. It would manage all project files in a sub-directory.

**Comment by eladb** [comment]
Oh interesting... so you can specify deps per function?

Isn't `NodejsFunction`/parcel handling tree shaking anything that's not needed (copy @jogold)?

**Comment by dariusjs** [comment]
What about for a polyglot project where your CDK project is in typescript but the functions that it deploys are python. In amplify there is a "amplify add function"  which ends up creating a structure like this on an initialised project.

```
├── amplify
│   ├── #current-cloud-backend
│   │   └── amplify-meta.json
│   ├── backend
│   │   ├── amplify-meta.json
│   │   ├── api
│   │   ├── backend-config.json
│   │   └── function
│   └── team-provider-info.json
└── src
    └── aws-exports.js
```

So a "projen add function" could also do the boiler plating utilising poetry to generate this:
```
├── LICENSE
├── cdk.json
├── functions
│   └── importantlambda
│       ├── README.rst
│       ├── pyproject.toml
│       ├── src
│       └── tests
├── package.json
├── src
│   └── main.ts
├── test
│   └── app.test.ts
├── tsconfig.jest.json
├── tsconfig.json
├── version.json
└── yarn.lock
```

**Comment by hoegertn** [comment]
That is a great further use case for m idea.

Does projen support that the project root is not the current dir but a sub-directory?

**Comment by tejle** [comment]
This addition of sub-projects should be done in `.projenrc.js` to maintain the generated structure.

**Comment by hoegertn** [comment]
Definitely. You can just add a TypeScriptApp to your projen-file and for project.synth(<dir>) provide the sub-folder to out the project into.

So the technical foundation is there and I will just propose TypeScriptApp derivative with some opinionated Lambda defaults.

**Comment by pszabop** [comment]
> Definitely. You can just add a TypeScriptApp to your projen-file and for project.synth(dir) provide the sub-folder 

I tried to do subdir projects and have found a lot of "find everything in the directory tree that matches" issues with projen and other tools.  there are not enough ignore options to make it work.

For example, jest searches all subdirectories for the files `*test*.ts`.  

So is that a proposal to make it work, or did I do something wrong?

**Comment by pgollucci** [comment]
I have the CDK=ts, lambda=python use case but I don't use amplify.

**Comment by pszabop** [comment]
> Oh interesting... so you can specify deps per function?

Yes, many of my functions have different dependencies.  For example in an API gateway some handler functions like a POST handler may need to generate a UUID, a GET would not.  (that's a very simple example, but lambda code varies as widely as any code out there).

I prefer to trim as much as possible from Lambda functions as uploading them to S3 takes time, and some dependent modules are very big, avoid the pain if they are not needed.

**Comment by hoegertn** [comment]
Given the advancement of the AWS CDK and new projen features, I think this is no longer relevant.

**Comment by dariusjs** [comment]
@hoegertn  which are the new features you mention ? I might have missed those which could make this work

**Comment by hoegertn** [comment]
My main reason is that with esbuild it is pretty fast and easy to put your Lambda code under the same src folder as your CDK code so no need for a subproject anymore.

On the other hand, generic subprojects are now supported in Projen.

**Comment by dariusjs** [comment]
For clarity for anyone else reading the thread, this construct helps out  by building small lambda's using esbuild https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-nodejs.NodejsFunction.html

**Comment by eladb** [comment]
Readme: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html

**Comment by akshay-nm** [comment]
I understand that this is an old thread, but I am still scratching my head trying to setup an http api backed by aws lambda using projen.

I followed this: https://projen.io/docs/integrations/aws/
and I have a lambda.ts, function.ts pair in my src. 

Where do I add deps for my functions? Am i supposed to do it in .projenrc.ts? 

```
const project = new awscdk.AwsCdkTypScriptApp({
  ...
  deps: []  
  ...
})
```

What should I do to setup a lambda layer?

**Comment by mrgrain** [comment]
Dependencies should be added to the projen project and are bundled into a single file during deployment.

Layers don't currently have any additional support in projen. However all features of the AWS CDK are still available.
