### ISSUE TITLE
GitHub releaseWorkflow does not work if my project is a subproject

### ISSUE THREAD

**Issue by rix0rrr** [projen/projen#1055]
I had a `new ReactTypeScriptProject({` at the root, and some workflows were created in `.github/workflows`.

However, when I made my project a subproject (in preparation of having multiple projects in my repository), the GitHub workflows disappear:

```ts
const parent = new Project({
});

new web.ReactTypeScriptProject({
  parent,
  outdir: 'packages/cdk-docrender',

  // ...
  releaseToNpm: true,
  releaseWorkflow: true,
  package: true,
});
```

How am I supposed to configure repository-wide GitHub workflows for subprojects?

----

(Also: the subproject feature is *extremely* underdocumented, which is to say: not documented at all. I had to go through multiple issues, then find the `CompositeProject` PR, only to find it was reverted and replaced with the `parent` property)

**Comment by Chriscbr** [comment]
There is one doc that covers this feature, but I don't fault you for not finding it: https://github.com/projen/projen/blob/main/docs/subproject.md

Subprojects are very half-baked currently. @eladb thoughts?
