### ISSUE TITLE
nodeProject upgrade fails due to old version of node being used

### ISSUE THREAD

**Issue by ahammond** [projen/projen#1057]
I found the following error in `chore(deps): upgrade dependencies` auto-generated PR's action.

```
error yargs@17.1.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
```

I think we should be running new(er) node for this? The project involved is an `AwsCdkConstructLibrary` which is building cdk v2 constructs.

**Comment by eladb** [comment]
Duplicate with #1050
