### ISSUE TITLE
bump cdktf contructs depdency to v10

### ISSUE THREAD

**Issue by pahud** [projen/projen#1076]
cdktf 0.6.0 now depends on constructs v10. Maybe we should update the dependency version at:

https://github.com/projen/projen/blob/042f6cddaf1f333737dcf2876ee5e16e7b245405/src/cdktf-construct.ts#L28

see - https://github.com/hashicorp/terraform-cdk/blob/148899e05999cb1f2fd7d1136c123410e0ea1efb/docs/upgrade-guide/upgrading-to-0.6.md#upgrading-a-typescript--javascript-cdktf-project

**Comment by pahud** [comment]
copy @skorfmann  wdyt?

**Comment by skorfmann** [comment]
> copy @skorfmann wdyt? Is it safe to simply update this file?

Yes - that will do 👍

**Comment by Chriscbr** [comment]
Contributions are welcome.
