### ISSUE TITLE
Programmatic project bootstrapping

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1081]
In a projenrc.js file, creating a Project and then calling `project.synth()` will create the project in the appropriate directory, but normally it does not generate the projenrc file (since it is expected that the user is managing/creating this file).

We would like to add behavior so that running the project synthesis _does_ create a projenrc.js (or projenrc.java, etc.) file in the same directory as the project.

Currently it's possible to achieve this using some special flags that projen uses under the hood:

```ts
const project = new TypeScriptProject({
  __new__: {
    fqn: 'projen.TypeScriptProject',
    args: {
      outdir: '/tmp/outdir',
      defaultReleaseBranch: 'main',
      name: 'MyProject',
    },
    comments: false,
  },
  outdir: '/tmp/outdir',
  defaultReleaseBranch: 'main',
  name: 'MyProject',
});
project.synth();
```

But perhaps we could standardize this API like so:

```ts
const project = new TypeScriptProject({
  bootstrap: true,
  
  // (optional) flags provided in "projen new"
  bootstrapOptions: {
    rcFile: '.projenrc.js',
    synth: true,
    post: true,
    comments: false,
    git: false
  },

  outdir: '/tmp/outdir',
  defaultReleaseBranch: 'main',
  name: 'MyProject',
});
project.synth();
```

**Comment by Chriscbr** [comment]
@eladb WDYT of this API?

**Comment by eladb** [comment]
I am not sure I fully understand the motivation for this feature. Can you provide some context for the use case?

**Comment by eladb** [comment]
Can we just expose the [`createProject()`](https://github.com/projen/projen/blob/5659d5f1da726e90e52a549c41949d414c857528/src/cli/create.ts#L51) as a public JSII-compatible API instead?

Something like:

```ts
import { Projects } from 'projen';

Projects.createProject({ ... });
```
