### ISSUE TITLE
How to create construct including DockerImageCode

### ISSUE THREAD

**Issue by trondhindenes** [projen/projen#1088]
I'm trying to use Projen to package a cdk construct that creates (among other) a lambda function using a DockerImageCode. The image is built on the fly, which means that the "asset folder" must be included in the module that Projen generates (I'm targetting npm and python packages). 

How can I instruct Projen to include an arbitrary src folder?

**Comment by davidpanofsky** [comment]
I believe you can do something like this in your `.projenrc.js` file:
```
project.package.addField('files', ['src/whatever/*']);
```

I ended up taking a different tactic for a lambda I wanted to bundle in the construct at build time:
```
project.compileTask.prependExec('esbuild --bundle src/lambda.js --outfile=lib/lambda/index.js --target=node14 --platform=node --external:aws-sdk');
```

It ain't pretty but at least the users of my construct do not need to do the bundling.

**Comment by trondhindenes** [comment]
Nice, will check those out. Thanks!
