### ISSUE TITLE
<npx projen new java> generates a project with error in pom.xml

### ISSUE THREAD

**Issue by desiby** [projen/projen#1092]
`npx projen new java` generates a new java project with an errornous pom.xml. The error is at the projen dependency version number.
Steps to reproduce:
 - run command in a new empty directory `npx projen new java`
 - then run` npx projen`
Expected: no errors in pom.xml
Actual: compiler reports following error: 
_`Could not resolve dependencies for project org.acme:my-app:jar:0.1.0: Could not find artifact com.github.eladb:projen:jar:0.28.20 in central (https://repo.maven.apache.org/maven2)`_
turns out Maven can't load the Projen dependency and seems like version number 0.28.20 could be the problem?
(I tried to force/overwrite with version 0.25.0 and it worked although not recommended)

**Comment by Chriscbr** [comment]
Ah I think this is because we recently changed the Maven group ID of projen from `com.github.eladb` to `io.github.cdklabs`. Thanks for reporting this bug!
