### ISSUE TITLE
Issues with github action release step

### ISSUE THREAD

**Issue by jasonFerre** [projen/projen#1142]
When the release step execute the command: release | git diff --ignore-space-at-eol --exit-code, more detail bellow:

Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /__w/druid-cdk-construct/druid-cdk-construct)

![image](https://user-images.githubusercontent.com/68281626/137730749-9ea13f7e-be24-4dad-a9b4-b18a6c07ef68.png)
![image](https://user-images.githubusercontent.com/68281626/137730879-df1b12cd-246a-4caa-bfa9-4c74af1393f2.png)
![image](https://user-images.githubusercontent.com/68281626/137731079-599f218d-dd8f-49a3-af86-b2687324745f.png)

**Comment by jasonFerre** [comment]
> Can you check what version of projen you are running? I think this may have been fixed by #1139 (in version v0.30.3).

@Chriscbr, I'm working on projen version  0.30.3

The error persist when execute command: release | git diff --ignore-space-at-eol --exit-code
Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /__w/druid-cdk-construct/druid-cdk-construct)

I've checked if the bump is setting version for the right tag -  this step is ok 

![image](https://user-images.githubusercontent.com/68281626/137791744-04d1f4a6-80b6-4493-b5e8-d1f251d3b9ce.png)
![image](https://user-images.githubusercontent.com/68281626/137792069-bf8a71da-cb5b-478f-a113-f53b831203e9.png)

**Comment by gotodeploy** [comment]
I hit this problem today but I fixed it by deleting .jsii file that unexpectedly git-indexed.

```sh
git rm -r --cached .
git add .
git status --ignored
```
