### ISSUE TITLE
`projen test` does a useless compile

### ISSUE THREAD

**Issue by rix0rrr** [projen/projen#1143]
Given a `TypeScriptAppProject`, `yarn test` runs the following:

```
$ npx projen test
....
🤖 test » test:compile | tsc --noEmit --project tsconfig.dev.json
🤖 test | jest --passWithNoTests --all --updateSnapshot
```

So: a compile with `--noEmit` followed by a `jest` run configured to run with `ts-jest`.

The `test:compile` step is unnecessary and slow.

**Comment by mmcculloh-dms** [comment]
AFAIK `ts-jest` only type checks files that are loaded/referenced, so technically it's not 100% redundant if your tests are not somehow touching all modules. But yeah I would agree that it shouldn't be a default anyways

**Comment by eladb** [comment]
@mmcculloh-dms thanks for the additional info. Since we compile the entire source tree immediately after tests, I guess we should be covered. No?
