### ISSUE TITLE
`projen test` updates snapshots by default

### ISSUE THREAD

**Issue by rix0rrr** [projen/projen#1144]
Given a `TypeScriptAppProject`, `yarn test` does the following:

```
$ npx projen test
....
🤖 test | jest --passWithNoTests --all --updateSnapshot
```

The `--updateSnapshot` is dangerous: if I run this in CI, `yarn test` will not actually validate my snapshots, but happily update them in place even if my tests should by all rights have failed.

The answer is not "anti-tamper protection": that will tell me that files have changed, it will not give me the nice error message and diff that `jest` would have given me if the snapshot test was allowed to fail in the first place. Plus, you can't assume that the tests will always be run with the synthesized GitHub workflow that includes anti-tamper protection: it might equally well run in a CodePipeline/CodeBuild setup, and that job might not even have access to the git repo to compare for any diffs.

**Comment by msessa** [comment]
+1 for exposing the behavior as an option. changing the default will probably lead to an  [XKCD#1172](https://xkcd.com/1172/) type situation.

**Comment by caviliar** [comment]
Hi, we are having a similar issue. We have updated to the latest version of projen and I can't get `yarn test` to run without updating snapshots. `antitamper` has been removed and I don't think there is a similar flag. @rix0rrr did you manage to solve this?

```
"test": {
      "name": "test",
      "description": "Run tests",
      "steps": [
        {
          "exec": "jest --passWithNoTests --all --updateSnapshot"
        },
        {
          "spawn": "eslint"
        }
      ]
    },
```

**Comment by caviliar** [comment]
i got annoyed enough (i do some code. run tests. they automatically update snapshots). kinda pointless. 

added this to projenrc:
```
project.tasks.tryFind('test').reset('jest --passWithNoTests --all')
```

not the prettiest or there could be a better way... but if you want the previous behaviour back then hacking the `test` task back to the previous projen version did the trick for us. (until i come across the recommended way).

**Comment by jtnz** [comment]
What is the intention of `projen test`? I feel like I'm constantly fighting against this behavior. Are we supposed to run `yarn test` in CI, then manually fail _if_ git is dirty afterwards? That doesn't sound very nice to me. And it's not just limited to `jest` either; `eslint` has `--fix`, which means if you run `yarn test` with the default behavior, the snapshots will be updated _and_ `eslint` will fix things like missing semicolons and trailing commas.

Today I tried improving on @caviliar 's solution with:
```
project.testTask.steps.forEach(step => {
  if (step.exec) {
    step.exec = step.exec.replace(' --updateSnapshot', '');
  }
});

const eslint = project.tasks.tryFind('eslint');
const eslintUpdate = project.tasks.addTask('eslint:update', {
  exec: eslint.steps[0].exec,
});

project.tasks.tryFind('eslint').steps.forEach(step => {
  if (step.exec) {
    step.exec = step.exec.replace(' --fix', '');
  }
});
```
This is not manageable though as we have _many_ CDK repos that will all require the same "fix".

Surely `yarn test` should just fail if snapshots are out of date and `eslint` isn't happy, and if you're doing dev work then you run `yarn test:update` to bring in those expected changes to `git`.

**Comment by Chriscbr** [comment]
Here's a proposal - let me know if this makes sense.

Current way things work:
1. There's a `test` task which intentionally updates files. There's also a `test:update` task (in JS-based project types), but it currently does the same thing.
2. The `mutableBuild` option determines whether to add a GitHub workflow step to push snapshot changes / eslint fixes back to your PR as a new commit (if you're not using GitHub, it does nothing).

Proposed way things should work:
1. `test` task does not intentionally update files. `test:update` task does intentionally update files (by passing the appropriate flags to `jest` and `eslint` etc).
2. The `mutableBuild` option is split into `mutableBuildTask` and `mutableBuildWorkflow`. `mutableBuildTask` will determine whether the default `build` task runs `test` or `test:update` (irrespective of whether you're running them locally or in CI/CD). `mutableBuildWorkflow` will do what `mutableBuild` did, but will also do nothing if `mutableBuildTask` is false.

In the future, `mutableBuildTask: false` should also cause running `npx projen` in CICD to fail immediately if it detects any configuration files that need to be updated, but this requires some more technical changes to projen's synthesis engine.

**Comment by jtnz** [comment]
@Chriscbr I think that proposal sounds reasonable, as long as `mutableBuildTask` is `false` by default :wink:.

My only other comment is that `mutableBuildWorkflow` isn't clear that it relates to GitHub. Perhaps that should live under `githubOptions`?

**Comment by 5nafu** [comment]
@jtnz 
> Today I tried improving on @caviliar 's solution with:

Thanks for your suggestion, but unfortunately, this did not work for us.
In the latest Version of projen, the `step.exec` is read only.

We used your suggestion and migrated it to:
```
// Create new task eslint:update that has the same exec as eslint
const eslintTask = project.tasks.tryFind('eslint');
const eslintUpdate = project.tasks.addTask('eslint:update', {
  exec: eslintTask!.steps[0]!.exec!,
});
const testUpdate = project.tasks.tryFind('test:update');
testUpdate!.spawn(eslintUpdate);

// Remove '--fix' (write) of eslint task
const newEslintCommand = eslintTask!.steps[0]!.exec!.replace(' --fix', '');
eslintTask!.reset(newEslintCommand);

const testTask = project.tasks.tryFind('test');
// Remove '--updateSnapshot' from test task
const newTestCommand = testTask!.steps[0]!.exec!.replace(' --updateSnapshot', '');
console.log(newTestCommand);
testTask!.reset(newTestCommand);
testTask!.spawn(eslintTask!);
```

Additionally for others trying this out, please add it *before* `project.synth();` 😁

**Comment by mrgrain** [comment]
Let's add the same thing for eslint then!
