### ISSUE TITLE
1-buster-slim breaks workflows using cdk v2.0.0-rc.25

### ISSUE THREAD

**Issue by ahammond** [projen/projen#1173]
My PR's build is failing with
```
error @aws-cdk/assert@2.0.0-rc.25: The engine "node" is incompatible with this module. Expected version ">= 14.15.0". Got "12.22.7"
```
while trying to upgrade All The Things in my corp `cdk-library`. 
```
❯ npx projen --version
0.27.51
```
One of the things I see is that the upgrade swapped:
```js
      image: jsii/superchain:node14
      image: jsii/superchain:1-buster-slim
```
in the workflows. I don't know what `1-buster-slim` is, but... it looks like it's breaking stuff.

Workaround in `.projenrc.js`:
```js
  workflowContainerImage: 'jsii/superchain:node14', // Workaround buster-slim issue
```

**Comment by wchaws** [comment]
I met the same issue

**Comment by gardnerjh** [comment]
I came across this same issue and I got around it by adding `minNodeVersion: '14.17.0'` to my `.projenrc.js` file.
