### ISSUE TITLE
Unable to pass cli options

### ISSUE THREAD

**Issue by gmukul01** [projen/projen#1177]
I am trying to pass cli options but the cli options are not getting passed to final script.

![image](https://user-images.githubusercontent.com/3636885/139064494-30fc63bf-a5c7-45f5-b5cd-fda596afad86.png)
 

This is the task in `task.json`
![image](https://user-images.githubusercontent.com/3636885/139064541-cdf89dbf-8287-40a6-a42f-3911eb9868d1.png)

**Comment by Chriscbr** [comment]
Closing since this is tracked in #356 (please give it a +1 if you're interested in that feature!)
