### ISSUE TITLE
Do not release when only dev dependencies or yarn.lock changed

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1178]
It's possible that it's not necessary to release new versions of libraries when there are no changes that affect the library's consumers. For example, in this commit to projen, the only changes are to yarn.lock, which is not included with the published package: https://github.com/projen/projen/commit/0eb817453b61f49f2f640779e1598a11cfd7a1df. Likewise, dev dependencies are not installed transitively so it does not necessarily make sense to release when only the dev dependencies have changed in package.json (assuming none of the other build artifacts are affected by the dev dependency change).

One way to implement this might be to run `npm diff` after bumping and building during the `release` task, and to error or exit early if it detects no changes. However, this does make the release process more complicated / could introduce new failures modes.

Another way to implement this could be to implement such a check during the projen upgrade workflow, and automatically add a label to the PR (and then, the release workflow might look for this label and no-op if it sees this label on the commit).

**Comment by eladb** [comment]
Keep

**Comment by mrgrain** [comment]
Replaced in favor of #2179 which uses conventional commits for a similar behaviour.
