### ISSUE TITLE
Projen marker incorrectly refers to projenrc.js

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1179]
Even if a project uses `.projenrc.ts`, the marker inserted in projen-generated files still says:

```Generated by projen. To modify, edit .projenrc.js and run "npx projen".```

**Comment by pgollucci** [comment]
src/file.ts
4:import { PROJEN_MARKER, PROJEN_RC } from "./common";
92:        : `${PROJEN_MARKER}. To modify, edit ${PROJEN_RC} and run "npx projen".`;
184:    const containsMarker = contents?.includes(PROJEN_MARKER);


closable

**Comment by mrgrain** [comment]
Or simply change to text to refer to `projenrc` and docs

**Comment by mrgrain** [comment]
Fixed!
