### ISSUE TITLE
AwsCdkTypeScriptApp should releaseToNpm

### ISSUE THREAD

**Issue by ahammond** [projen/projen#1185]
I'm experimenting with the idea that CDK apps should be treated as artifacts for the purposes of CD. To do this, I need an artifact: a build and packaged CDK app. I tried adding a `releaseToNpm: true` with the other stuff necessary to publish to GitHub Packages (because death to npmjs.org), and got

```
Run npx -p jsii-release@latest jsii-release-npm
npx: installed 8 in 2.528s
Publishing under the following dist-tag: latest
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /__w/aws-base-infra/aws-base-infra/dist/js/**.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/__w/aws-base-infra/aws-base-infra/dist/js/**.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2021-10-29T17_58_53_664Z-debug.log
ERROR
Error: Process completed with exit code 1.
```

I'm not convinced that this is the Right Way to go (using packaged, versioned CDK apps), but I thought this would work.

**Comment by mmcculloh-dms** [comment]
I can speak to how I'm currently doing this, for better or worse. Might be of use for discussion.

My CDK projects are typescript (projen). Synthesis creates a cloud assembly per environment, all are stored in cdk.out. Publishing the npm package includes the cdk.out directory as well as the exact version of the cdk cli. This allows the immutable artifact to go through a usual CI/CD progression while getting the benefit of a build-once-deploy-many methodology.
