### ISSUE TITLE
Lambda bundles: cannot test generated functions without compilation

### ISSUE THREAD

**Issue by eladb** [projen/projen#1196]
By default, jest tests are executed without compilation. This implies that the bundle file created under `lib/` does not exist (we even `rm -fr lib/` before we run tests to ensure tests are pure).

I think what we need is to create the bundles under some other top-level directory (e.g. `assets/` or `resources/`) and always reference them from there.

**Comment by Chriscbr** [comment]
It looks like doesn't affect tests in https://github.com/cdklabs/construct-hub because we put tests in `__tests__` and run "compile" before "test" during a full build.

**Comment by eladb** [comment]
Indeed. But still, my plan is to put bundles under `assets/` instead of `lib/` so that they can be referenced consistently

**Comment by eladb** [comment]
Resolved
