### ISSUE TITLE
Question on Nuget Package Signing

### ISSUE THREAD

**Issue by ammarkarachi** [projen/projen#1202]
Is there a way to sign Nuget packages with Projen? I see that in the nuget release runs `npx -p jsii-release@latest jsii-release-nuget` but I see no workflow that enables signing these packages.

**Comment by Chriscbr** [comment]
I think this might be a better feature request for https://github.com/cdklabs/jsii-release - perhaps suggest it there? I'm not familiar with the Nuget package signing, but if the capability is added there it should be relatively easy to support that in projen.

**Comment by ammarkarachi** [comment]
Sounds good I will try to find it there
