### ISSUE TITLE
Projen is not webpack-able

### ISSUE THREAD

**Issue by alexforsyth** [projen/projen#1230]
Projen references some files by location, so I can't easily webpack projen as a dependency.

https://github.com/projen/projen/blob/main/src/license.ts#L40

**Comment by eladb** [comment]
Isn't it possible to tell webpack to include these files in the bundle?

**Comment by alexforsyth** [comment]
Unclear exactly how to do that without crazy aliasing. I dont think should be solved by a consumer of projen as it requires knowledge of internal projen implementation details like locations of asset directories and all that.

I'm not 100% sure how to solve this problem at all.
