### ISSUE TITLE
project.cdkConfig.plugin does not change cdk.json

### ISSUE THREAD

**Issue by OperationalFallacy** [projen/projen#1244]
Hi,

```
const { AwsCdkTypeScriptApp } = require("projen");

const project = new AwsCdkTypeScriptApp({
  cdkVersion: "1.133.0",
  devDeps: ["cdk-assume-role-credential-plugin"]
});

project.cdkConfig.plugin = ['cdk-assume-role-credential-plugin'];
console.log(project);
project.synth()
```

And then running `npx projen` doesn't add plugin config to cdk.json

**Comment by tiararodney** [comment]
This is tricky... As far as I can see, the `plugin` property is currently not implemented for [`src/awscdk/cdk-config.ts::CdkConfig`](https://github.com/projen/projen/blob/main/src/awscdk/cdk-config.ts#L77).

I discerned two impediments for a feature implementation:

1. There is no definitive way of discerning CDK plugin npm packages from other npm packages, as their only attributes are package names prefixed with `cdk-` and suffixed with `-plugin`.
2. If one was to try and fish the plugins of `dependencies`, and/or `peerDependencies` fields of the future package manifest, this can only be achieved through observing the `options` passed to [`src/awscdk/awscdk-app-ts::AwsCdkTypeScriptApp`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-app-ts.ts#L43) during construction. Package dependencies are only resolved after the `cdk.json` has been rendered. In addition, dependency resolution is private to [`src/javascript/node-package.ts::NodePackage`](https://github.com/projen/projen/blob/main/src/javascript/node-package.ts#L315).

Fishing for CDK plugin npm packages could be done similar to this (within the [`src/awscdk/awscdk-app-ts::AwsCdkTypeScriptApp`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-app-ts.ts#L43) constructor):

```typescript
const cdkPlugins = ( options.deps ?? [] ).reduce( ( plugins:string[], dep:string ) => { 

    if ( dep.startsWith( 'cdk-' ) && dep.endsWith( '-plugin' ) ) {

        plugins.push( dep );
    }

    return plugins;
}, [] );
```

The resulting `cdkPlugins` can then be passed onto the `this.cdkConfig` constructor. <s>However, `(options.deps ?? [])` is pretty fugly.</s> This will result in a lackluster implementation 💩

**My proposition for an implementation:**

1. Extend the [`src/awscdk/awscdk-deps.ts::AwsCdkDepsCommonOptions`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-deps.ts#L9) interface, to include `cdkPlugins?:string[]`.
2. Optionally, plugin names may be matched against the `cdk-` prefix and `-plugin` suffix.
2. Make the [`src/awscdk/awscdk-app-ts::AwsCdkTypeScriptApp`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-app-ts.ts#L43) constructor add all CDK plugins as additional dependencies through `this.addDevDeps`.
3. Make the [`src/awscdk/cdk-config.ts::CdkConfig`](https://github.com/projen/projen/blob/main/src/awscdk/cdk-config.ts#L77) constructor add a `plugin` field to the [`new JsonFile()`](https://github.com/projen/projen/blob/main/src/awscdk/cdk-config.ts#L102)
