### ISSUE TITLE
Self-mutation commit makes running workflows silently no-op

### ISSUE THREAD

**Issue by rix0rrr** [projen/projen#1246]
On this PR: https://github.com/cdklabs/cdk-ops/pull/1815

* GitHub Actions "build" started running, it was going to do a "cdk diff" that I want to see
* For whatever reason, some GitHub workflow that Projen creates decided it wanted to add a `chore: self mutation` commit
* The addition of this commit canceled the running "build" workflow: https://github.com/cdklabs/cdk-ops/runs/4286695636?check_suite_focus=true
* Because they don't want to hit an infinite loop, GitHub Actions pushes never trigger workflows. Since the latest commit was added by GitHub Actions, the new "build" workflow that was supposed to replace the old one silently no-ops: https://github.com/cdklabs/cdk-ops/pull/1815/checks?check_run_id=4286717896

The end result is:
* "build" didn't run (so I never get to see the result of my "cdk diff")
* What's worse: the UI makes it **look** like the workflow ran successfully. So if it was doing something like running unit tests, potential failures would not be caught and I might accidentally merge a broken PR.

![image](https://user-images.githubusercontent.com/524162/142866980-57ff57b4-e0e2-4e12-bdb1-610a32fd11d5.png)

**Comment by eladb** [comment]
The `build` workflow will submit a success status check after self-mutation, so generally extending the `build` workflow with additional jobs is not a great idea.

What I would do instead is define a separate workflow (triggered by PRs) that will take care of submitting a diff comment.

**Comment by rix0rrr** [comment]
Is it not a good idea to have projen throw an error when you are trying to extend a workflow that you're not supposed to extend then?

**Comment by eladb** [comment]
Definitely a good idea
