### ISSUE TITLE
Valid SPDX 2.2 license expression in .projenrc.js causes error

### ISSUE THREAD

**Issue by mikavuo** [projen/projen#1259]
Hello,

I tried to add a user-defined, valid SPDX license identity for my CDK project and found out that the current projen implementation does not accept it.

Reproducing error:
1. Write into .projenrc.js: _license: 'LicenseRef-MyFancyLicense'_
2. Run npx projen
3. The following error is shown
/usr/local/share/npm-global/lib/node_modules/projen/lib/license.js:21
            throw new Error(`unsupported license ${spdx}`);

Why do I think that this is a bug:
As given in the SPDX standard https://spdx.github.io/spdx-spec/SPDX-license-expressions/ the format "LicenseRef-"1*(idstring) 
e.g. LicenseRef-MyFancyLicense is a valid license identity.
=> The correct behaviour accepts user-defined LiceseRef- statements.

Extra info in case this interests you:
As a reference implementation for free associations, I can mention the REUSE tool https://github.com/fsfe/reuse-tool that can be used for SPDX standard copyright and license markings, license downloads and linting + producing SPDX SBoM (in licensing perspective at least).

**Comment by tiararodney** [comment]
+1 

as mentioned in #1370, the npm manifest `license` field also supports a JSON object for further specifying attributes such as `url`. Therefore the attribute type of `license` is also faulty.
