### ISSUE TITLE
Feature Request: Let Mergify merge ProjenUpgrade PRs once build passes

### ISSUE THREAD

**Issue by pahud** [projen/projen#126]
`ProjenUpgrade` PRs now require manually merge and is a little bit annoying.

Would be great if we allow Mergify to merge it for us just like how it works with dependabot PRs.

more discussion here: https://twitter.com/pahudnet/status/1310870742746034176

## Proposed Solution:

We probably can add a rule here:
https://github.com/eladb/projen/blob/ccb0aa946d9be7c328676396b58c9cb0bba1aebb/src/node-project.ts#L632-L658

And I was wondering if we should provide an opt-out option and where would be the best place to hold this option.

**Comment by pahud** [comment]
The challenge would be the mergify rule conditions:


```ts
conditions: [
  'author=*****',
  'status-success=build',
  'title=chore: upgrade projen',
],
```

As the projenupgrade workflow runs with the `PROJEN_GITHUB_TOKEN` secret, we can hardly defile the condition rule by the `author` name. Not sure how to define a reasonable condition rules for it.

**Comment by eladb** [comment]
I feel the title should be sufficient, no? We can also automatically apply labels as part of the PR submission

**Comment by pahud** [comment]
> I feel the title should be sufficient, no? We can also automatically apply labels as part of the PR submission

I feel the author would still be mandatory just like we trust `dependabot[bot]`. If we don't restrict the author, PRs from anyone matches the title will just let mergify merge, no?

**Comment by pahud** [comment]
I think we probably should not auto merge the projen upgrade PRs for users, instead, users are encouraged to configure their own `.projenrc.js`.  The mergify rules condition is very flexible and powerful and if we auto merge for users, they might feel very surprised. Maybe we should let users decide their own conditions.

I am configuring the rule like this in my `.projenrc.js` and I feel very comfortable as I can control its behavior.

```ts
project.mergify.addRule({
  name: 'Merge approved pull requests with auto-merge label if CI passes',
  conditions: [
    '#approved-reviews-by>=1',
    'status-success=build',
    'label=auto-merge',
    'label!=do-not-merge',
    'label!=work-in-progress',
  ],
  actions: {
    merge: {
      method: 'merge',
      commit_message: 'title+body',
    },
  },
});
```

All I need now is to create a GH action that applies `auto-merge` label for those projenupgrade PRs and optionally another action for auto approval.

**Comment by eladb** [comment]
I like the `auto-merge` label approach. External contributors can't apply labels.

**Comment by eladb** [comment]
#Let's add a mergify rule that will [auto-approve](https://doc.mergify.io/actions.html#review) PRs with the label `auto-approve` and then we can add this label to the projen created PR.

**Comment by eladb** [comment]
Okay, we'll go with `auto-merge`. On it.

**Comment by Chriscbr** [comment]
Closing as this appears to be resolved
