### ISSUE TITLE
bug: jsii with `projen new awscdk-construct` broken due to `@types/jest` in `jest@27.4.0`

### ISSUE THREAD

**Issue by pflorek** [projen/projen#1264]
Running `npx projen new awscdk-construct` or running `npx projen upgrade` on an existing construct project will break jsii.

`npx projen build`, `npx projen compile`, `npx jsii` will throw following errors:

```shell
👾 build » compile | jsii --silence-warnings=reserved-word --no-fix-peer-dependencies
[2021-11-30T01:27:07.040] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
warning JSII6: A "peerDependency" on "constructs" at "^3.2.27" means you should take a "devDependency" on "constructs" at "3.2.27" (found "undefined")"
node_modules/@types/jsdom/base.d.ts:24:40 - error TS2304: Cannot find name 'DocumentFragment'.

24         static fragment(html: string): DocumentFragment;
                                          ~~~~~~~~~~~~~~~~
node_modules/@types/jsdom/base.d.ts:41:28 - error TS2304: Cannot find name 'Node'.

41         nodeLocation(node: Node): ElementLocation | null;
                              ~~~~
node_modules/@types/jsdom/base.d.ts:172:19 - error TS2304: Cannot find name 'HTMLScriptElement'.

172         element?: HTMLScriptElement | HTMLLinkElement | HTMLIFrameElement | HTMLImageElement | undefined;
                      ~~~~~~~~~~~~~~~~~
node_modules/@types/jsdom/base.d.ts:172:

...
```

`@types/jsdom` got added as dependency in jest:

https://github.com/facebook/jest/commit/3d04f33daa3b9ec21838c9177ab7acab8c983155

removing jest or manual removal of `@types/jsdom` from node_modules will make jsii happy again. downgrading with projen is forbidden and throws an error. If it makes sense to add `dom` to jsii's base-tsconfig, it's just not configurable from outside.

Could this slipped through some upgrade-dependencies tasks?

**Comment by eladb** [comment]
Looking into add `dom` to the generated jsii tsconfig...

**Comment by eladb** [comment]
As a workaround, if you are using `yarn`, you can add this to your projenrc:

```js
project.package.addField('resolutions', {
  'jest-environment-jsdom': '27.3.1',
});
```

**Comment by minche-tsai** [comment]
> As a workaround, if you are using `yarn`, you can add this to your projenrc:
> 
> ```js
> project.package.addField('resolutions', {
>   'jest-environment-jsdom': '27.3.1',
> });
> ```

Thanks, it's resolved.
