### ISSUE TITLE
Feature Request: Cache list of projen-managed files

### ISSUE THREAD

**Issue by mmcculloh-dms** [projen/projen#1265]
When projen prunes it has to go through files to find the marker. If generated files were instead written into some sort of files.json in the .projen file, pruning could instead read from that list (which I guess would also contain itself). This provides the obvious efficiency bonus as well as the added benefit of a simple way to inspect what files are being managed.

In the case that some files get orphaned somehow, a cli/project arg can be added to do a full cleanup like the current behavior. This would have to be done manually, but I think it would make sense to optimize the more common case that files are being properly tracked between projen invocations.

**Comment by eladb** [comment]
Sounds like a reasonable approach. Contributions are welcome!

I'd put a simple textual list under `.projen/files`.
