### ISSUE TITLE
Make publish:git configurable?

### ISSUE THREAD

**Issue by willdady** [projen/projen#1267]
My project is using `AwsCdkConstructLibrary` with `releaseTrigger: ReleaseTrigger.manual()` set. When running `yarn build` Projen automatically creates a commit, tags it and pushes it to my remote. I'd like more control over this. 

I'm wanting to run a pipeline in Gitlab which runs `yarn release` whenever a commit is pushed to my **main** branch. As `yarn release` pushes automatically I need to be able to tell Gitlab to NOT start another pipeline when this push occurs. Gitlab supports this with the option `-o ci.skip`

Currently publish:git does this:

```
git push --follow-tags origin main
```

I'd like it to do this:

```
git push --follow-tags -o ci.skip origin main
```

A way to override the git command would probably suffice?

**Comment by eladb** [comment]
Sounds reasonable, contributions are welcome!

Basically, I'd add something like `gitPushFlags?: string[]` to [`GitPublishOptions`](https://github.com/projen/projen/blob/e53b28af1e838b1ea54cbd7553a9fdab0a91df37/src/release/publisher.ts#L744)
