### ISSUE TITLE
AWS CDK v2 Support

### ISSUE THREAD

**Issue by meeuw** [projen/projen#1288]
CDK v2 has been released!

https://aws.amazon.com/about-aws/whats-new/2021/12/aws-cloud-development-kit-cdk-generally-available/

Would it be possible to initialize a new CDK v2 project using projen?

**Comment by zxkane** [comment]
Running `projen upgrade` is updating v2 alpha package to rc version, which is unexpected behavior. 

```
 @aws-cdk/aws-apigatewayv2-alpha                  2.0.0-alpha.11  →  2.0.0-rc.24     
 @aws-cdk/aws-apigatewayv2-integrations-alpha     2.0.0-alpha.11  →  2.0.0-rc.24     
 @aws-cdk/aws-appsync-alpha                       2.0.0-alpha.11  →  2.0.0-rc.24     
 @aws-cdk/aws-glue-alpha                          2.0.0-alpha.11  →  2.0.0-rc.24     
 @aws-cdk/aws-lambda-python-alpha                 2.0.0-alpha.11  →  2.0.0-rc.24     
 @aws-cdk/aws-neptune-alpha                       2.0.0-alpha.11  →  2.0.0-rc.24  
```

**Comment by wchaws** [comment]
I got `error aws-cdk-lib@2.0.0: The engine "node" is incompatible with this module. Expected version ">= 14.15.0". Got "12.22.7"` when upgraded to cdk v2
 https://github.com/projen/projen/issues/1173

**Comment by HenrikFricke** [comment]
I was able to update my Projen project without any problems. I simply updated the Projen config and the imports.

Projen config: https://github.com/HenrikFricke/aws-cdk-newsletter/blob/main/.projenrc.js#L13-L29
Imports: https://github.com/HenrikFricke/aws-cdk-newsletter/blob/main/src/main.ts#L1-L15

Credits to @bracki 🙏

**Comment by eladb** [comment]
Good to know!
