### ISSUE TITLE
Build hanging at docgen step after upgrading to v0.37

### ISSUE THREAD

**Issue by willdady** [projen/projen#1292]
I've just upgraded projen to v0.37. When I try run `yarn build` the build becomes stuck at the following line:

```
👾 build » post-compile » docgen | jsii-docgen
```

This was working fine before upgrading. Previous version of projen was v0.34.25. 

I've run both `yarn install` and `npx projen` within my project root after running `yarn upgrade-projen`. Running Node v14.17.1.

I am NOT setting the `docgen` option in my `awscdk.AwsCdkConstructLibrary` constructor. The docs for `awscdk.AwsCdkConstructLibrary` says `docgen` defaults to false so why is `jsii-docgen` even running at all? Also, if I _explicitly_ set it to false I get the following error:

```
👾 build » post-compile » docgen | jsii-docgen
/bin/sh: jsii-docgen: command not found
👾 Task "build » post-compile » docgen" failed when executing "jsii-docgen" (cwd: /Users/Will/projects/flybuys-cdk)
error Command failed with exit code 1.
```

**Comment by henrysachs** [comment]
I'm seeing something similar but my build isn't failing just taking a lot of time. Have you found a solution? I thought about upgrading jsii-docgen and hopefully fixing it that way 😅
