### ISSUE TITLE
projen fails when creating new projects

### ISSUE THREAD

**Issue by idealo-ricardo-band** [projen/projen#1294]
I try to create a new AWS CDK project with `projen new awscdk-app-ts`. This works but projen fails afterwards with this error every time I run it:

```
$ projen
👾 default | node .projenrc.js
/home/username/myproject/.projenrc.js:2
const project = new AwsCdkTypeScriptApp({
                ^

TypeError: AwsCdkTypeScriptApp is not a constructor
    at Object.<anonymous> (/home/username/myproject/.projenrc.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
👾 Synthesis failed: Task "default" failed when executing "node .projenrc.js" (cwd: /home/username/myproject)
```

**Comment by eladb** [comment]
Can you please verify that you are using the latest version of projen to create the project?

**Comment by idealo-ricardo-band** [comment]
```
npx projen --version
0.37.1
```

I created the project with an older version. So it seems this doesn't happen in the newer version. I'll test if I can upgrade projen manually. Maybe then it works again.

**Comment by idealo-ricardo-band** [comment]
I found the problem. The projenrc.js used to start like this:

```js
const { AwsCdkTypeScriptApp } = require('projen');
const project = new AwsCdkTypeScriptApp({
```

When I create a project with the new projen version the file looks like this:

```js
const { awscdk } = require('projen');
const project = new awscdk.AwsCdkTypeScriptApp({
```

I changed that in my other projects and now these work again. Some kind of notice about that kinda major change would've been nice. Or at least a better error message because I think everyone who upgrade will run into that error soon.

**Comment by eladb** [comment]
@idealo-ricardo-band thanks for reporting!

**Comment by Chriscbr** [comment]
@eladb Yeah that is odd. :/ I'll take a look. I've manually updated the release notes with the list of breaking changes for now

**Comment by Chriscbr** [comment]
An earlier list displayed all of the breaking changes correctly (https://github.com/projen/projen/releases/tag/v0.33.0). I think I just formatted my PR description wrong, if I had to take a guess it's because I bulleted the list with dashes instead of asterisks, since I don't see any other differences

**Comment by idealo-ricardo-band** [comment]
I didn't look for breaking changes. I usually rely on semantic versioning for that. But that sadly not the case with projen. I will keep a closer look to the release notes from now on.
Thx for the help!

**Comment by eladb** [comment]
Projen follows semantic versioning. Since it is pre-1.0.0, breaking changes will result a bump in the second component (eg the `x` in `0.x.y`.

It's a common practice with pre 1.0 releases.

**Comment by idealo-ricardo-band** [comment]
Sure. No problem with that. Great to here that breaking changes after 1.x will be visible easier. I'll follow the release notes closer now. Thx for clarifying!

**Comment by 24601** [comment]
I am experiencing a similar problem with `TypeScriptProject` and it is *not* a legacy/older project, was created with a fresh install of the latest release. 

❯ projen
👾 default | node .projenrc.js
/Users/basitmustafa/Documents/GitHub/agileonboarding/aob/lib/systems-integration/client-side-token-processor/.projenrc.js:2
const project = new TypeScriptProject({
                ^

TypeError: TypeScriptProject is not a constructor
    at Object.<anonymous> (/Users/basitmustafa/Documents/GitHub/agileonboarding/aob/lib/systems-integration/client-side-token-processor/.projenrc.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
👾 Synthesis failed: Task "default" failed when executing "node .projenrc.js" (cwd: /Users/basitmustafa/Documents/GitHub/agileonboarding/aob/lib/systems-integration/client-side-token-processor)

I was able to fix it by changing .projen.js to:

```
const { typescript } = require('projen');
const project = new typescript.TypeScriptProject({
  defaultReleaseBranch: 'main',
  name: 'client-side-token-processor',

  deps: ['dapr-client'] /* Runtime dependencies of this module. */,
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
  // release: undefined,      /* Add release management to this project. */
});
project.synth();
```

from (which was created with 0.41.0)

```
const { TypeScriptProject } = require('projen');
const project = new TypeScriptProject({
  defaultReleaseBranch: 'main',
  name: 'client-side-token-processor',

  deps: ['dapr-client'] /* Runtime dependencies of this module. */,
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
  // release: undefined,      /* Add release management to this project. */
});
project.synth();

```

**Comment by Chriscbr** [comment]
Reopening since it seems like there might still be an issue.

**Comment by mbonig** [comment]
Appears issue could be right around here?

https://github.com/projen/projen/blob/a84b57a3460c797ed39bca14e62c99fe8c9a3e40/src/javascript/projenrc.ts#L17

**Comment by eladb** [comment]
@24601 I am unable to reproduce this with projen v0.44.0:

```sh
$ npm i -g projen
$ mkdir repro && cd repro
$ projen new typescript
$ projen
```

Here's a [screencast](https://asciinema.org/a/zYg5oeyaDGajYeCocKus57BJB).

**Comment by AndrewGuenther** [comment]
Just as a heads up, I used projen for the first time today and out-of-the-box on the latest version ran into this same issue.

Repro steps:

```
npx projen --version
> 0.59.3

npx projen new awscdk-construct
```

This will generate a `.projenrc.js` file with the following:

```typescript
const { AwsCdkConstructLibrary } = require('projen');
const project = new AwsCdkConstructLibrary({
...
});
project.synth();
```

And if you try to run `yarn build` you'll get the following error:
```
TypeError: AwsCdkConstructLibrary is not a constructor
```

So something is definitely still busted here...
