### ISSUE TITLE
`srcdir`- option for `AwsCdkTypeScriptAppOptions` does not work.

### ISSUE THREAD

**Issue by jolo-dev** [projen/projen#1301]
My code snippet for creating an `AwsCdkTypeScriptApp`

```ts
const options: AwsCdkTypeScriptAppOptions = {
//.. some configs
srcdir: 'infrastructure',
}

new awscdk.AwsCdkTypeScriptApp(options);
```

And then when running `npx projen`, I get `Error: sources are expected under the "src" directory`.

Seems like it is not allowed to have a different `srcdir`:

https://github.dev/projen/projen/blob/0e1ab52cc6c6995c94aa2dce38bc9cd271f89a65/src/awscdk/awscdk-app-ts.ts#L94

**Comment by eladb** [comment]
Yes, seems like like this is not supported at the moment for CDK apps in TypeScript. I am assuming there are some downstream assumptions behind this check.

We can try to remove this check and see what breaks. Could be an obsolete limitation. Contributions are welcome!

**Comment by jolo-dev** [comment]
Thanks, @eladb for your reply.

Okay, let me try to remove it and see where it breaks.

**Comment by eladb** [comment]
🙏

**Comment by jolo-dev** [comment]
Fixed: https://github.com/projen/projen/pull/1304
