### ISSUE TITLE
Missing Lambda auto-discover documentation?

### ISSUE THREAD

**Issue by willdady** [projen/projen#1307]
Where is the Lambda auto-discover feature documented?

It looks like #1070 added `docs/aws-lambda.md` however that seems to no longer exist?

I've been working with Projen for a few days now and only by accident discovered this feature exists when reading through issues.

It would be great if this was documented in the README as it's a pretty killer feature of Projen.

**Comment by willdady** [comment]
I can see the documentation now lives in `docs/awscdk.md`. As mentioned above, I think this could be surfaced a little better in the top-level README.

**Comment by eladb** [comment]
We generally need to create a doc site for Projen that surfaces all docs.

Closing for now.
