### ISSUE TITLE
Support ephemeral credentials in codeArtifactOptions of CDK construct libs

### ISSUE THREAD

**Issue by bilalq** [projen/projen#1313]
Today, it seems like projen supports doing an assumeRole call, but only after it has used persistent IAM user credentials to do so. Instead, I'd prefer to see this support ephemeral creds from the get-go. 

~A simple stop-gap solution might be to accept a `sessionToken` parameter as an optional input.~ 

EDIT: Projen really only looks for Github secret keys and won't accept env vars set elsewhere. Though maybe it doesn't need to look for them? I dug through the source and saw it's deferring to jsii-release. ~Based on the code here, maybe this would just work out of the box by defaulting to env vars? https://github.com/cdklabs/jsii-release/blob/master/bin/jsii-release-npm#L23-L34~

EDIT AGAIN: Seems like there are some issues that block usage of ephemeral credentials. See comments below for details.

It'd be nice if the docs nudged people to using the new OIDC feature for federating Github to AWS: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

Right now, this is the interface:

```typescript
/**
 * @experimental
 */
export interface CodeArtifactOptions {
    /**
     * (experimental) GitHub secret which contains the AWS access key ID to use when publishing packages to AWS CodeArtifact.
     *
     * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
     *
     * @default "AWS_ACCESS_KEY_ID"
     * @experimental
     */
    readonly accessKeyIdSecret?: string;
    /**
     * (experimental) GitHub secret which contains the AWS secret access key to use when publishing packages to AWS CodeArtifact.
     *
     * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
     *
     * @default "AWS_SECRET_ACCESS_KEY"
     * @experimental
     */
    readonly secretAccessKeySecret?: string;
    /**
     * (experimental) ARN of AWS role to be assumed prior to get authorization token from AWS CodeArtifact This property must be specified only when publishing to AWS CodeArtifact (`registry` contains AWS CodeArtifact URL).
     *
     * @default undefined
     * @experimental
     */
    readonly roleToAssume?: string;
}
```

**Comment by bilalq** [comment]
I just updated/edited the description above. Looks like the env variables aren't being used directly, so the OIDC flow should just work because jsii-release is just delegating to the AWS CLI? In that case, this issue should be more focused on doc updates, maybe?

**Comment by bilalq** [comment]
Wait, nvm, I forgot the projen is generating the release flow itself. 

You can add something like this in your projenrc:

```typescript
  releaseWorkflowSetupSteps: [
    {
      name: 'Retrieve AWS Credentials',
      uses: 'aws-actions/configure-aws-credentials@master',
      with: {
        'role-to-assume': 'arn:aws:iam::1234567890:role/example-role',
        'role-session-name': 'CDKConstructReleaseGithub',
        'aws-region': 'us-east-2',
      },
    },
  ],
```

However, the generated release flow sets env variables based on Github secrets no matter what and doesn't set the session token. 

```yml
      - name: Release
        run: npx -p jsii-release@latest jsii-release-npm
        env:
          NPM_DIST_TAG: latest
          NPM_REGISTRY: zoya-finance-031851463847.d.codeartifact.us-east-2.amazonaws.com/npm/zoya-internal/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

I think that workflow generation needs changing so it can accommodate ephemeral credentials.

**Comment by eladb** [comment]
I think it would be nice to add first-class support for this. Contributions are welcome

**Comment by bilalq** [comment]
Hey, I'd like to request that this be re-opened. I took a stab at this and am drafting my PR description now.
