### ISSUE TITLE
What is awscdk.IntegrationTest?

### ISSUE THREAD

**Issue by mattsb42-aws** [projen/projen#1315]
We recently updated to `0.37.0` and suddenly `projen` is generating `integ:` tasks in our `AwsCdkConstructLibrary` packages for any file that ends in `.integ.ts` and including some variant of those tasks as part of the `test` task. When these run, they do...something with "snapshots"...but I don't know what. Looking through the API docs, the only thing I can find that seems to have anything to do with this is the `awscdk.IntegrationTest` construct[1] but the docs don't say anything about what that is or what it does, just including a vague reference to them being "Cloud integration tests."

What are these things and where can I find anything that explains what they are, what they do, or how to use them?

[1] https://github.com/projen/projen/blob/main/API.md#class-integrationtest--

**Comment by Chriscbr** [comment]
AWS CDK Integration tests are described here: https://github.com/projen/projen/blob/main/docs/awscdk.md#integration-snapshot-tests.

We should add options so that it's possible for `*.lambda.ts` files to be auto-discovered but not `*.integ.ts` files, and vice versa.

**Comment by mattsb42-aws** [comment]
TIL about the `docs/` directory.

What is the recommended entry point to the AWS CDK docs? The only docs I've ever seen on searches/etc are the `API.md` and it looks like there's a lot of useful stuff in `docs/` that I never would have found.

**Comment by henrysachs** [comment]
I think we should close this Issue and create a new one. There it could be discussed if projen maybe gets a documentation website? Maybe generate one with vuepress from the docs directory or something like that.

**Comment by eladb** [comment]
Yes, sounds great. If you are interested to try and pick up the work to create a docsite that will be more than awesome. 

Closing this one for now
