### ISSUE TITLE
Support pre-commit hooks / commitlint to simplify usage of conventional commits

### ISSUE THREAD

**Issue by Hi-Fi** [projen/projen#1317]
Currently Projen created projects support nicely conventional commits, but doesn't offer way to ensure that commit messages are in valid format. First check would be good to make at the pre-commit hook by checking the commit message.

There were couple of related tickets that had went to stale:
- #277 
- #727 

More generic approach would support e.g. Husky for other hooks, too, but that's kind of stretch goal and main thing would be to ensure that commits that are pushed to origin are (mostly) valid.

[Example of commitlint with Husky](https://adarshaacharya.com.np/blog/setup-husky-precommit-hooks).

**Comment by dontirun** [comment]
I've implemented husky `pre-push`, `pre-commit`, and `commit-msg` hooks on an external module that I am currently working on. Would be happy to make a PR if this is something that is wanted.

**Comment by eladb** [comment]
Can you share the code?

**Comment by dontirun** [comment]
Sure! Here is a minimal recreation of what I did

```typescript
import { FileBase, TextFile, javascript } from 'projen';

export class HuskyMinimal extends javascript.NodeProject {
  /**
   * The file with Husky pre-push hooks
   */
  public readonly huskyPrePush: TextFile;
  /**
   * The file with Husky pre-commit hooks
   */
  public readonly huskyPreCommit: TextFile;

  constructor(options: javascript.NodeProjectOptions) {
    super(options);
    this.addDevDeps(
      'husky@^7',
      'lint-staged',
      'commitlint',
      '@commitlint/config-conventional'
    );
    this.huskyPrePush = new TextFile(this, '.husky/pre-push', {
      executable: true,
      lines: [
        `#${FileBase.PROJEN_MARKER}`,
        'git diff HEAD --quiet',
        'npx projen test',
      ],
    });
    this.package.addField('lint-staged', {
      '*': ['npx projen eslint', 'git add -u'],
    });
    this.huskyPreCommit = new TextFile(this, '.husky/pre-commit', {
      executable: true,
      lines: [`#${FileBase.PROJEN_MARKER}`, 'npx lint-staged'],
    });
    new TextFile(this, '.husky/commit-msg', {
      executable: true,
      lines: [
        `#${FileBase.PROJEN_MARKER}`,
        'npx --no -- commitlint --edit "$1"',
      ],
    });
    this.package.addField('commitlint', {
      extends: ['@commitlint/config-conventional'],
    });
  }
}

```

**Comment by Hi-Fi** [comment]
@eladb  @pgollucci Is this commitlint/husky usage something that's not coming to projen, as both PRs related to this seemed to be closed due silence? Meaning PRs:
- #727
- #1444
