### ISSUE TITLE
Improve prettier support

### ISSUE THREAD

**Issue by bilalq** [projen/projen#1318]
There are two major problems with the way prettier works in projen today:

### Problem 1: Setting `prettier` to true in eslintOptions causes unnecessary red lines in IDEs

Let's say you have something like this in your `.projenrc.ts`
```typescript
eslintOptions: {
  dirs: ['src'],
  devdirs: ['test'],
  prettier: true,
},
```

The eslint setup runs prettier rather than just shutting off its own formatting rules right now. This results in red squiggly lines while editing that would go away once I hit save. That's really annoying. Prettier's own docs go into why this is generally not recommended: https://prettier.io/docs/en/integrating-with-linters.html

Having a projen option to choose whether to run with the prettier config or plugin for eslint would be much nicer. Let formatting run via prettier and linting via eslint.

### Problem 2: Prettier configuration options aren't supported

I know [the prettier team wishes they hadn't added support for options](https://prettier.io/docs/en/option-philosophy.html), but the reality is that they're here to stay and there are people like me that would opt for a different tool if it didn't support some (I can't stand semi-colons). As it stands, I have a manually managed/curated `.prettierrc.yml` file outside of projen that *mostly* works. None of the generated code respects it, which I guess isn't a huge deal. And of course, it's not managed by projen. Prettier supports configuration being defined in package.json, so if options are accepted in projen, they can be set there.

**Comment by henrysachs** [comment]
I really like this idea, would it be sufficient to be able to just pass all prettier options to projen and generate the corresponding prettierrc file? Because I think I could probably do a PR for that.

**Comment by henrysachs** [comment]
so i'm on it but question regarding 1. I saw that the corresponding extends is already set in the eslint config. So I'm not that deep into prettier can you be more specific what would be needed furthermore?
