### ISSUE TITLE
AwsCdkTypeScriptApp still uses deprecated assert library

### ISSUE THREAD

**Issue by pgarbe** [projen/projen#1326]
The AwsCdkTypeScriptApp still has a [hard coded](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-app-ts.ts#L106) do the deprecated assert library. 

To keep it kind of compatible, I'd move that line to the CDK v1 block, and add the assertion library in the v2 block. 

I can provide a pull request, but would like to discuss how it should look like as it might be a breaking change.

**Comment by eladb** [comment]
Yes, definitely should be major-version aware. Contributions are welcome.
