### ISSUE TITLE
upgrade workflow doesn't update integration test snapshots for bundled lambdas

### ISSUE THREAD

**Issue by misterjoshua** [projen/projen#1348]
When an AwsCdkConstructLibrary self-updates by cron, the PR doesn't catch integration test snapshot changes.

This is undesirable if you're using an integration test with an asset derived from the lambda bundling feature. When said asset depends on an external dependency, an update to this dependency will likely change the asset hash. When this happens, the upgrade workflow succeeds, producing a PR that fails to build when it tries to assert the integration test snapshots:

![image](https://user-images.githubusercontent.com/644092/146284961-93a16980-51fc-4b65-9a07-b55d97b23454.png)

**Comment by jumic** [comment]
@misterjoshua Thank you for implementing a solution for this issue. I also have the requirement that the integration tests must be updated after the upgrade workflow.

Did your example in the PR work in your project? I added a similar line in my project.
```ts
project.upgradeWorkflow?.postUpgradeTask.spawn(
  project.tasks.tryFind("integ:process-metrics:snapshot")
);
```

Unfortunately, the build failed. Do you have the same problem? Or did it work in your repo?

```bash
0s
Run echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
Error: Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch.
diff --git a/test/__snapshots__/main.test.ts.snap b/test/__snapshots__/main.test.ts.snap
index 843fc07..714c1c0 100644
--- a/test/__snapshots__/main.test.ts.snap
+++ b/test/__snapshots__/main.test.ts.snap
@@ -3,16 +3,16 @@
 exports[`Snapshot 1`] = `
 Object {
   "Parameters": Object {
-    "AssetParametersa9d1a1055146c29b4c9721ff343b4b0c0ff441af8764fa63a8ada7de79087b42ArtifactHashC86D1B10": Object {
-      "Description": "Artifact hash for asset \\"a9d1a1055146c29b4c9721ff343b4b0c0ff441af8764fa63a8ada7de79087b42\\"",
+    "AssetParameters578010e11ae57f70bbb085f7e4cc7c3bbaa9991c141af8830c073f097589e958ArtifactHashDE61A8A8": Object {
+      "Description": "Artifact hash for asset \\"578010e11ae57f70bbb085f7e4cc7c3bbaa9991c141af8830c073f097589e958\\"",
       "Type": "String",
     },
```

**Comment by misterjoshua** [comment]
@jumic It worked for me from a locally-linked projen build to my test project, but I haven't tried the newly released version on my projects yet.

In your example, are those jest snapshots? #1476 targets the `IntegrationTest` feature you'd get from `integ:process-metrics:assert` which uses `diff` rather than jest per se. I imagine that if you added a jest run with `--updateSnapshot` you could get similar updates to those snapshots as well.

**Comment by jumic** [comment]
@misterjoshua Thanks for the hint. I only focussed on the integration test (which was indeed updated) and forgot about the jest test case. I added task `test:update`, now it works.

```ts
project.upgradeWorkflow?.postUpgradeTask.spawn(project.tasks.tryFind("bundle"));
project.upgradeWorkflow?.postUpgradeTask.spawn(
  project.tasks.tryFind("test:update")
);
project.upgradeWorkflow?.postUpgradeTask.spawn(
  project.tasks.tryFind("integ:process-metrics:snapshot")
);
```

**Comment by misterjoshua** [comment]
> I added task `test:update`, now it works.

Great, I'm glad! Thanks for figuring the jest part out! That'll be handy.
