### ISSUE TITLE
AwsCdkTypeScriptApp seems to have incorrect type definition for CDK context values

### ISSUE THREAD

**Issue by aripalo** [projen/projen#1349]
Projen documentation defines CDK context as:
```
context (Map<string, string>) Additional context to include in cdk.json. 
```

Which in [`cdk-config.ts`](https://github.com/projen/projen/blob/a969ca9858175d23158e2a5a0eda7a523c8c73ea/src/awscdk/cdk-config.ts#L9-L15) Projen code is defined:
```ts
export interface CdkConfigCommonOptions {
  /**
   * Additional context to include in `cdk.json`.
   *
   * @default - no additional context
   */
  readonly context?: { [key: string]: string };
```

… but [CDK itself (via `constructs` package)](https://github.com/aws/constructs/blob/c37850f79500b748727ec828a122230e28f3bc0b/src/construct.ts#L220) defines Context values as `any`:
```ts
public tryGetContext(key: string): any {
    const value = this._context[key];
    if (value !== undefined) { return value; }

    return this.scope && this.scope.node.tryGetContext(key);
}
```

CDK core uses context values in `cdk.json` that are simple key-value pairs, but even it uses both string and boolean types:
```
"@aws-cdk/core:stackRelativeExports": "true",
"@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
```

Also context retrieved via lookups and stored into `cdk.context.json` may contain lists and objects.

Even CDK docs state:
> Context keys are strings, and values may be any type supported by JSON: numbers, strings, arrays, or objects. 

I've been using CDK for quite some time and I have both CDK apps & constructs that read configuration data from `cdk.json` context that may contain for example nested objects:
```json
"context": {
  "foo": {
     "num": 1,
     "nested": {
        "text": "hello"
     }
   },
   "bar": {
      "num": 2,
      "nested": {
        "text": "world"
      }
   }
}
```

Now that I am starting to use Projen, I'm wondering why the disconnect between Projen and CDK itself.

Is there some reason why one should stick to `Map<string, string>`? Or is this just an unintentional mismatch with CDK and Projen?

**Comment by aripalo** [comment]
For example if the reason is to stick to simple key-value pairs with `string` values has something to do with cross-language support for JSII, then wondering why CDK core still support `any` values 🤔

**Comment by Chriscbr** [comment]
Sounds like a bug - contributions are welcome! 🙂

**Comment by eladb** [comment]
I don't see a problem fixing the projen type definition to allow `any` as the value for context.
