### ISSUE TITLE
TypeError: AwsCdkConstructLibrary is not a constructor

### ISSUE THREAD

**Issue by infoservicesllc-lab** [projen/projen#1358]
Hello,

Tried to initialise a new CDK construct project and stuck with this issue. I have tried it in different systems but the behaviour is same. Appreciate any help with this

Projen version: 0.45.3

% npx projen
👾 default | node .projenrc.js
/Users/blah/blah/.projenrc.js:2

const project = new AwsCdkConstructLibrary({
                ^

TypeError: AwsCdkConstructLibrary is not a constructor
    at Object.<anonymous> (/Users/blah/blah/.projenrc.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

👾 Synthesis failed: Task "default" failed when executing "node .projenrc.js" 

.projenrc.js
++++++++

const { AwsCdkConstructLibrary } = require('projen');
const project = new AwsCdkConstructLibrary({
  author: 'Author1,
  authorAddress: 'author1@gmail.com',
  cdkVersion: '1.95.2',
  defaultReleaseBranch: 'main',
  name: 'blah2',
  repositoryUrl: 'https://github.com/rblah/blah.git',

  // cdkDependencies: undefined,      /* Which AWS CDK modules (those that start with "@aws-cdk/") does this library require when consumed? */
  // cdkTestDependencies: undefined,  /* AWS CDK modules required for testing. */
  // deps: [],                        /* Runtime dependencies of this module. */
  // description: undefined,          /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],                     /* Build dependencies for this module. */
  // packageName: undefined,          /* The "name" in package.json. */
  // release: undefined,              /* Add release management to this project. */
});

project.synth();

**Comment by infoservicesllc-lab** [comment]
Changed from

const { AwsCdkConstructLibrary } = require('projen');
const project = new AwsCdkConstructLibrary({

to

const { awscdk } = require('projen');
const project = new awscdk.AwsCdkConstructLibrary({

That worked. Thanks to this post: https://github.com/projen/projen/issues/1294#issuecomment-986907322

**Comment by eladb** [comment]
Dup #1294
