### ISSUE TITLE
PR linter that checks if docs or tests are updated

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1361]
In the AWS CDK monorepo, we use a linter that checks if docs have been updated when a "feat" commit is added, and checks if unit tests were updated when a "fix" commit is added. These linters can be opted out of by adding the "pr-linter/exempt-readme" or "pr-linter/exempt-test" labels to the PR respectively. This turns adding docs/unit tests to an explicit "opt-out" decision instead of an "opt-in" one.

Something similar could be useful to have in projen

**Comment by yattoni** [comment]
I'm working on implementing this

**Comment by mrgrain** [comment]
Not looking to add not complex custom workflows to projen ownership. If we find an action that does this, we can rethink the feature request.
