### ISSUE TITLE
RFC: gitlab CI support

### ISSUE THREAD

**Issue by dariusjs** [projen/projen#137]
I've created this as an RFC, as I am not sure if these types of extensions are considered. It would be nice if Github as the default workflow was configurable so you could have different providers such as Gitlab.

Currently the NodeBuildWorkflow has tight coupling with the GithubWorkflow class as it extends it on node-project. If the relationship was different gitlab CI support could be added.

Gitlab CI places a file called .gitlab-ci.yml in the root of a project, a little different to Githubs ./workflows structure. Sample gitlab CI files are here.
https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

I've tried working on this myself, but wasn't sure how to proceed because of the class extension.

**Comment by robertd** [comment]
Gitlab's package registry support would be great too. They’ve recently released package registry support for everyone to use in their core offerings (https://about.gitlab.com/releases/2020/08/22/gitlab-13-3-released/#package-registry-now-available-in-core)

**Comment by jackdreinhardt** [comment]
Agreed. I see a lot of potential abstracting projects from CI providers. Ideally, the developer could choose any provider (GitHub Workflows, Gitlab CI, TravisCI, CircleCI, etc). The developer could also choose to generate a 'headless' project if projen doesn't yet support their project type, where only CI files are generated.

**Comment by eladb** [comment]
I like this direction. I've been working in that direction here: https://github.com/projen/projen/pull/387

**Comment by ThomasSteinbach** [comment]
Cool. Projen is very interesting, however better gitlab support would be nice.

**Comment by delprofundo** [comment]
Yeah I feel the same as Thomas. Trying to understand what we need to do with GitLab is bewildering and from the silence at the end of issues asking Q's about it its clear its not worth GL users time.

**Comment by mrgrain** [comment]
Yes @delprofundo there is unfortunately no out-of-the-box support for any of the higher lever projects at the moment.
What we have is some helper classes to create gitlab configuration: https://projen.io/gitlab.html

So the general process would be:
- Use the project you want
- Manually rebuild the GitHub Actions workflow in GitLab
- Remove or ignore the unneeded GH Actions workflows

Now to why there's not much help around these steps, I can only guess. But my bet would be that there simply aren't that many active projen users using GitLab (or CircleCI). I'm aware that's a cycle of negative reinforcement (lack of users -> lack of help & lack of constructs -> lack of users). The project would need someone to really push this forward. If you or anyone else is interested, I'm certainly happy to guide them towards a solution.
