### ISSUE TITLE
Autowire mergify conditions based on workflow jobs

### ISSUE THREAD

**Issue by iliapolo** [projen/projen#1378]
Proposal to add a property to the [`Job`](https://github.com/projen/projen/blob/main/src/github/workflows-model.ts#L6) model:

```ts
/**
   * Marking a job as required will cause mergify to enforce this job passes CI
   * before merging PRs.
   *
   * @default false
   */
readonly required?: boolean;
```

## Use Case

We've recently been adding some integration tests to a few projects, that run in a separate workflow, decoupled from the build task. 

```ts
const integ = new project.github.addWorkflow('integ');

// this should somehow cause the mergify configuration to add
// a condition on the `e2e` job.
integ.addJob('e2e', { required: true })
```

In fact, projen itself does this, and currently uses an escape hatch to wire mergify:

https://github.com/projen/projen/blob/ddff75364944bfd468b927b475fb00eed3f3bd6f/.projenrc.js#L196

Lets remove the need for this hack.

**Comment by Chriscbr** [comment]
I think the Job model itself should not need to be aware of what "Mergify" is.

**Comment by iliapolo** [comment]
Agreed, but I think its ok for to be aware of a required/not-required for merge job. 

When we move to GitHub actions, we'll need to also configure it to enforce this.

**Comment by Chriscbr** [comment]
I guess what I mean to say is perhaps this behavior should be defined at a higher level of abstraction. I think keeping a boundary between the typed GitHub actions/workflow schema and the functionality we provide on top of it is important - like separating L1s and L2s.

What would adding a job that has the `required` field do on workflows that don't interact with source code (e.g. that don't have the `pull-request` or `pull-request-target` triggers defined), such as the stale workflow?

**Comment by eladb** [comment]
I am picking this one

**Comment by iliapolo** [comment]
@Chriscbr Thanks for the clarification, yeah I agree the location I suggested is misplaced.
