### ISSUE TITLE
RFC .projenrc.ts support

### ISSUE THREAD

**Issue by andrestone** [projen/projen#14]
For more complex projects, specially with the monorepo support, wouldn't it be interesting to:

`npx projen init typescript --types`

Then generate a .projenrc.ts file instead of the .js and incorporate a check on the cli to compile on the fly if .ts file is there?

**Comment by eladb** [comment]
Yes, why not?

**Comment by eladb** [comment]
I am having seconds thoughts here. Let's keep it in the backlog for now and see how far we can get with JavaScript.

**Comment by eladb** [comment]
This will also require `ts-node`

**Comment by andrestone** [comment]
Maybe `npx ts-node` as it is in CDK?

**Comment by eladb** [comment]
That would mean that every time you run projen ts-node will be executed or it has to be installed globally (which means that `which ts-node` should just work. 

This is related to perhaps adding support for other languages. Would be nice to be able to also author projenrc in python for example, which will also have some ambient prerequisites.

I am open to doing that: we can auto-discover the .projenrc file type based on its extension and then require the user to have the "runtime" pre-installed in their system.

**Comment by skyrpex** [comment]
There's also https://github.com/antfu/esno, which uses `esbuild` to transpile on the fly. I use it with CDK and am pretty happy with it.

Maybe a file like `cdk.json` would help here to make it customizable?

**Comment by eladb** [comment]
`esbuild` does not perform type checking as far as I know,  Correct?

**Comment by skyrpex** [comment]
Exactly, it just executes the code. Maybe that's not what you want in this scenario.

**Comment by eladb** [comment]
Projenrc in typescript is now supported via:

```shell
projen new typescript --projenrc-ts
```
