### ISSUE TITLE
Anti tamper check should be required

### ISSUE THREAD

**Issue by iliapolo** [projen/projen#1423]
In https://github.com/projen/projen/pull/1383 we added an `anti-tamper` check that will run on PR's originating from forks. This is instead of running a malfunctioning self-mutation step that fails the build. 

However, the `anti-tamper` job is not currently defined as a required job, this means that PR's originating from forks that result in self-mutation, might be accidentally merged.

**Comment by eladb** [comment]
Both here and in #1422 I am wondering if the correct behavior is for the build job to simply fail (while still running self-mutation/anti-tamper).

It will better reflect the actual situation and will simplify the conditions
