### ISSUE TITLE
Expose `subprojects` property

### ISSUE THREAD

**Issue by moltar** [projen/projen#1433]
Is there a reason why `subprojects` property is marked as private?

It makes it impossible to traverse the sub-project tree to add config to the root project.

E.g. adding monorepo `workspaces` config to the `package.json` file.

**Comment by moltar** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by skyrpex** [comment]
I find this necessary too. As a workaround, my monorepo project handles subprojects manually...

**Comment by mrgrain** [comment]
We should totally do this.
