### ISSUE TITLE
Caching dependencies in GitHub Actions

### ISSUE THREAD

**Issue by moltar** [projen/projen#1439]
There appears to be no caching of the deps in the GitHub Action Workflows.

Shall this be added? This can greatly speed up runs.

**Comment by eladb** [comment]
Yes that will be amazing. Contributions?

**Comment by moltar** [comment]
Does this need to support all of the package managers, right? Any tips on where to dig in within projen.

I am somewhat familiar with the GH Action caching setup already.

Just new to projen.

**Comment by moltar** [comment]
Can we use this for NPM? https://github.com/bahmutov/npm-install

**Comment by moltar** [comment]
If this is ok, I will create a PR

**Comment by Chriscbr** [comment]
Is it possible to use the built-in functionality for caching provided in the `setup-node` action? https://github.com/actions/setup-node#caching-packages-dependencies

**Comment by moltar** [comment]
Would this be the place to change?

https://github.com/projen/projen/blob/ade63d68f35fae65d3a90a03496f843c682043ea/src/javascript/node-project.ts#L849-L863

I think we need to set the correct package manager based on the properties in the constructor.
