### ISSUE TITLE
Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code"

### ISSUE THREAD

**Issue by moltar** [projen/projen#1440]
Getting this error on GitHub Action release workflow run consistently:

```
Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /home/runner/work/projen-turborepo/projen-turborepo)
```

Project: https://github.com/moltar/projen-turborepo

**Comment by moltar** [comment]
I think this is the result of me setting the version explicitly in the `package.json` file. When I set it back to `0.0.0` and let projen manage it, then the error went away. So it's "user fault".

However, I think the following two things need to be addressed:

- More clarity on the release process
- Better error message

**Comment by eladb** [comment]
@moltar Does this help at all? https://github.com/projen/projen/blob/main/docs/releases.md

**Comment by moltar** [comment]
Yeah, I've seen the docs before. But it's just not clear that this happens within the CI env.

Even though I come from the background of doing the same with semantic release, I still got stumbled on this.
