### ISSUE TITLE
jest picks up tests from `dist/*`

### ISSUE THREAD

**Issue by moltar** [projen/projen#1441]
Repro:

- Using `JsiiProject` type
- Add test to `test/foo.test.ts`
- Run `projen build`
- Run `projen build` again

Observe:

```
👾 build » test | jest --passWithNoTests --all --updateSnapshot
jest-haste-map: Haste module naming collision: projen-turborepo
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/package.json
    * <rootDir>/dist/package.json

 PASS  test/sub-projects.test.ts
 PASS  test/synth.test.ts
 PASS  dist/test/sub-projects.test.ts
 PASS  dist/test/synth.test.ts
```

**Comment by moltar** [comment]
Temporary solution:

```ts
project.jest?.addIgnorePattern('<rootDir>/dist/*')
```

Btw, on the same note, does it make sense to include `<rootDir>` value by default in `addIgnorePattern`?

Example:

```ts
project.jest?.addIgnorePattern('dist/*')
```

Should result in:


```json
    "testPathIgnorePatterns": [
      "/node_modules/",
      "<rootDir>/dist/*"
    ],
```

**Comment by eladb** [comment]
Yes pretty nasty.

Contributions are welcome!

**Comment by MarkMcCulloh** [comment]
Instead of changing the behavior of the ignore, perhaps the `testMatch` can just be more surgical. So instead of:

```
"**/__tests__/**/*.ts?(x)",
"**/?(*.)+(spec|test).ts?(x)"
```

It can be something like:

```
"src/**/__tests__/**/*.ts?(x)",
"(src|test)/?(*.)+(spec|test).ts?(x)"
```

Using the set source and test paths.

On a related note, the `dist` folder should probably not have tests in it anyways. or any typescript files for that matter.
