### ISSUE TITLE
upgrade-deps build fails with "Your lockfile needs to be updated"

### ISSUE THREAD

**Issue by jumic** [projen/projen#1443]
In my projen project, the upgrade workflow ran successfully and created a pull request.
However, the build workflow in this PR failed.

Error message in step 'Install dependencies':
```
Run yarn install --check-files --frozen-lockfile
yarn install v1.22.17
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

projen version: 0.47.13

Generated pull request: https://github.com/jumic/iot-app/pull/6

Is this a bug in projen? Or should I try to resolve it running `projen upgrade` manually and hope the error doesn't appear again?

Thanks.

**Comment by jumic** [comment]
Additional information after running `projen upgrade` on my local machine:

`"@types/jest": "*",` has been changed to `"@types/jest": "^27.4.0",` in `package.json`.

In `yarn.lock` the version has also been updated:
```
"@types/jest@*":
  version "27.4.0"
  resolved "https://registry.yarnpkg.com/@types/jest/-/jest-27.4.0.tgz#037ab8b872067cae842a320841693080f9cb84ed"
  integrity sha512-gHl8XuC1RZ8H2j5sHv/JqsaxXkDDM9iDOgu0Wp8sjs4u/snb2PVehyWXJPr+ORA0RPpgw231mnutWI1+0hgjIQ==
  dependencies:
    jest-diff "^27.0.0"
    pretty-format "^27.0.0"
```

Command `yarn install --check-files --frozen-lockfile` failed with the same error.

After running `yarn install` without option `--frozen-lockfile`, file `yarn.lock` has been updated again (version number in first line is changed):
```
"@types/jest@^27.4.0":
  version "27.4.0"
  resolved "https://registry.yarnpkg.com/@types/jest/-/jest-27.4.0.tgz#037ab8b872067cae842a320841693080f9cb84ed"
  integrity sha512-gHl8XuC1RZ8H2j5sHv/JqsaxXkDDM9iDOgu0Wp8sjs4u/snb2PVehyWXJPr+ORA0RPpgw231mnutWI1+0hgjIQ==
  dependencies:
    jest-diff "^27.0.0"
    pretty-format "^27.0.0"
```

That means the problem is related to updating `@types/jest`.

**Comment by eladb** [comment]
Seems like a bug and I suspect #1435 is the culprit, but I need to dig a bit further to determine the root cause. Thanks for reporting. In the meantime, you should be able to update your lockfile by just running `yarn` and pushing a commit into the branch.

**Comment by eladb** [comment]
OK, see #1451

**Comment by jumic** [comment]
@eladb Thank you very much. Your fix solved the issue.
