### ISSUE TITLE
Allow PR builds to update pacakge lockfile

### ISSUE THREAD

**Issue by eladb** [projen/projen#1454]
Since we have self-mutation, let's allow packaeg lockfiles to be updated in PR builds. This will only actually happen for PRs that originate from branches in this repository (and not from forks).

**Comment by eladb** [comment]
@Chriscbr @iliapolo @RomainMuller thoughts about this?

**Comment by iliapolo** [comment]
Yeah, I don't see a reason not to. Essentially self-mutation means we are not running in a locked environment, so the lock file should be open as well.
