### ISSUE TITLE
Permission denied error for Lambda function with `prettier` option

### ISSUE THREAD

**Issue by jumic** [projen/projen#1457]
I enabled the `prettier` option which was introduced in #1450. My projects includes a [Lambda function](https://github.com/projen/projen/blob/main/docs/awscdk.md#aws-lambda-functions). The Lambda Function construct is generated by projen (as a readonly file). 

`projen build` shows this error:

```bash
👾 build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js

Oops! Something went wrong! :(

ESLint: 8.6.0

Error: EACCES: permission denied, open '/Users/julian/dev/projen-prettier-lambda/src/example-function.ts'
👾 Task "build » test » eslint" failed when executing "eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js" (cwd: /Users/julian/dev/projen-prettier-lambda)
```

The generated CDK construct for the Lambda function is not formatted correctly. However, the file cannot fixed because it is readonly.

Projen version: 0.50.0

Example project: https://github.com/jumic/projen-prettier-lambda

Ideas:
- Change readonly files to writeable when projen executes eslint/prettier.
- Generate valid file in [lambda-function.ts](https://github.com/projen/projen/blob/2ef39f895b255dc4c844947f29fb0568eb6f4088/src/awscdk/lambda-function.ts#L163-L205) if `prettier` is enabled.

**Comment by eladb** [comment]
Ha!

We should auto add this generated source file to prettierignore.
