### ISSUE TITLE
The Version component does not support alternate branch names for the default branch

### ISSUE THREAD

**Issue by hoegertn** [projen/projen#146]
The scripts generated by the `Version` component assume the main branch to be called `master`. There should be a way to configure this, as new projects tend to use `main`.

**Comment by pgollucci** [comment]
@mergifyio refresh

**Comment by pgollucci** [comment]
https://github.com/projen/projen/pull/150

This can be closed right?

**Comment by Chriscbr** [comment]
Yep, closing
