### ISSUE TITLE
Add `.npmrc` abstraction

### ISSUE THREAD

**Issue by moltar** [projen/projen#1460]
Would be great to have an `.npmrc` file class and instance on the Node project with some common methods/getters.

https://docs.npmjs.com/cli/v8/configuring-npm/npmrc

**Comment by hoegertn** [comment]
Something like this? https://github.com/projen/projen/blob/main/src/javascript/npm-config.ts

What other features would you like to see?

**Comment by moltar** [comment]
Oh ... yeah, that's the one! 😅 Thanks!
