### ISSUE TITLE
Request: non hidden .projenrc.js 

### ISSUE THREAD

**Issue by mrpackethead** [projen/projen#1461]
I'm using projen inside a codebuild container.   The buildspec,  .projenrc.js,  and some additional files are placed in an S3 bucket.  This is all deployed via cdk  ( specifically s3_assests )..    Its not possible to have a 'hidden' object in S3, if you try, the file just doe'snt get tot he codebuild. 

My work around right now, is to create a projenrc.js as part of the s3 assest.   Codebuild copies the projenrc.js to .projenrc.js before projen is executed. 

It would be kind of handy just to be able to specifiy which projenrc.js file you'd like to use..

**Comment by moltar** [comment]
Isn't that what `--rc` command parameter is for?

```
      --rc       path to .projenrc.js file     [string] [default: "xyz/.projenrc.js"]
```

**Comment by mrpackethead** [comment]
Id' tryed this, and it just woud'nt work for me.  :-( i tryed again this morning and it does. Clearly i'd done something wrong.  well that solves that issue..

I'm still curious though, my is the default to have a hidden file?
