### ISSUE TITLE
Error: Task "build" is locked for changes

### ISSUE THREAD

**Issue by moltar** [projen/projen#1479]
Why is the build task locked?

How do you add build commands?

For example, we want to build a React app, but also Storybook when `projen build` is called.

https://github.com/projen/projen/blob/e5899dd04a575209424a08fe90bde99e07ac6c7b/src/project-build.ts#L87

**Comment by eladb** [comment]
Please see https://github.com/projen/projen/blob/main/docs/build.md

**Comment by moltar** [comment]
Ah, thanks. Sorry, I tried to Google the error and search the issues, but this didn't come up :)

**Comment by bestickley** [comment]
I ran into this issue as well, wanted to share code for others so they can find answer faster. See below.
Also docs link above is broken. See: https://projen.io/docs/publishing/build
```ts
function copyContainerfiles() {
  const bundleTask = project.tasks.tryFind("bundle");
  if (bundleTask) {
    bundleTask.exec(
      "cp src/nextjs-compute/fargate/Containerfile lib/nextjs-compute/fargate/Containerfile",
    );
    bundleTask.exec(
      "cp src/nextjs-compute/lambda/Containerfile lib/nextjs-compute/lambda/Containerfile",
    );
  }
}
```
