### ISSUE TITLE
rfc: migrating existing projects to projen

### ISSUE THREAD

**Issue by gradybarrett** [projen/projen#148]
## Idea

Hi Elad!

What about a migrator/generator that helps port existing projects to projen?

## Context
I've been porting a CDK construct that I just started over to projen, and due to our restrictive CI environment, I ended up shutting a lot of features off. It would be cool to have a generator that spits out at least a rough .projenrc.js to get you started, based on existing configs and known patterns.

I don't feel qualified yet to contribute to this effort, but am looking forward to digging into the code in the future. 

Love this idea by the way. It's been a point of frustration for me for a long time and I always thought something like this would be really useful. I never consider it on this scale though. Very cool!

**Comment by eladb** [comment]
Thanks for the feedback. I doubt that it will be possible to offer a very robust experience of "disassembling" an existing project into it's projen setup. It's not very different from trying to take a compiled executable and produce legible high level code from it, especially given projen is quite opinionated on a lot of fronts. Happy to look at a more concrete proposal, but I am not sure the cost/benefit of trying to implement this make sense.

**Comment by gradybarrett** [comment]
Did you find that that was the case with [cdk-dasm](https://github.com/aws/aws-cdk/tree/master/packages/cdk-dasm)? I suppose the use case is a bit different since direct usage of L1's was never really the goal. Do you see a similar layering of constructs happening in projen over time, or do you see API's always staying fairly low-level, like they are now?

I agree that the experience would be fairly rudimentary, and limited to the opinions held by a given project type. I don't see it as a silver bullet as much as providing a place to start a conversion process.

I've seen a few issues starting to pop up for supporting non-Github-based projects and tools. If that type of support is in the cards, then as the number of supported artifacts in a project grows, the task of converting an existing project could become somewhat daunting. So perhaps the cost/benefit ratio starts to even out later down the road?

I'll keep this in the back of my head while exploring and if something more concrete comes to mind I'll drop it here.
