### ISSUE TITLE
Files managed by projen are deleted and recreated

### ISSUE THREAD

**Issue by moltar** [projen/projen#1484]
When I run `projen` in the root of the repo, it seems like all of the files under projen management get deleted, and then re-created again.

This causes VS Code's Source Control panel to generate a massive diff of all of the files it discovers, of which there are many, as when the `.gitignore` file gets deleted, VS Code scans the entire `node_modules` dir.

I'm using projen with sub-project, which is the main divination from the norm. I am not sure if this is the relevant part, or if it's just causing the issue due to the number of files under projen's management.

**Comment by moltar** [comment]
Also, when `projen default` run fails, the project is left in a bad state - the files remain deleted.

**Comment by MarkMcCulloh** [comment]
With `files.json`, I think It should now be possible to only delete files that were managed by projen on the previous run. That should prevent orphaned files, which I figured was the point of the file cleanup system in the first place.

Not sure if there's opposition to just overwriting files. Even better, skipping the cleaning on still-managed files can benefit from [this recent optimation](https://github.com/projen/projen/blob/main/src/file.ts#L135) as well.
