### ISSUE TITLE
Yarn build skips jsii-pacmak - v0.50.9

### ISSUE THREAD

**Issue by infoservicesllc-lab** [projen/projen#1489]
Hello,

Projen Version: 0.50.9

Issue: Running "yarn build" doesn't run jsii-pacmak during package but instead copies all files from "src" and "test" to "dist" directory.

yarn build
yarn run v1.22.17
$ npx projen build
👾 build » default | node .projenrc.js
[1/4] 🔍  Resolving packages...
success Already up-to-date.
👾 build » compile | jsii --silence-warnings=reserved-word --no-fix-peer-dependencies
👾 build » post-compile » docgen | jsii-docgen
👾 build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js
**👾 build » package | mkdir -p dist**
👾 build » package | rsync -a . dist --exclude .git --exclude node_modules
✨  Done in 260.94s.

"yarn build" was working 2 days ago and below was the output of last 3 lines that calls jsii-pacmak

👾 build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js
**👾 build » package | jsii-pacmak**
✨  Done in 1397.45s.

Temp Fix:

As of now, I have created a script that calls the below which is properly generating the necessary packages in "dist"

npx projen compile
npx projen test
npx projen package-all

Can we fix the issue with "yarn build" as many of our jenkins jobs are failing

**Comment by Chriscbr** [comment]
I believe this decoupling was an intended change made in https://github.com/projen/projen/pull/1359 so that packaging can be customized in CI/CD environments. For example, the user can tell their CI provider to either to run the `package-all` job, or to run each `package-<lang>` job in parallel if their CI/CD tool supports such a capability.

If you prefer the old behavior, it's possible you could customize the `packageTask` property of your `Project` in your projenrc file, e.g. `project.packageTask.spawn(project.tasks.tryFind("package-all"))`.

**Comment by infoservicesllc-lab** [comment]
Thanks @Chriscbr, this was helpful. I'm just wondering what's the best way to make our CI pipeline to use a specific Projen version to avoid these breaking changes as "npx projen" always get the latest projen. Is there a specific version that I can tag with.

npx projen@0.50.9

**Comment by willdady** [comment]
I'm getting the same issue. Have just upgraded Projen and this broke. Am using Gitlab for CI, not Github Actions. 

It's this part which copies files from the root directory to the `dist` directory IF the `CI` environment variable is set to a non-empty string.

```
👾 release » build » package | if [ ! -z ${CI} ]; then mkdir -p dist && rsync -a . dist --exclude .git --exclude node_modules; else npx projen package-all; fi
```

It's not clear what the benefit of simply copying these files to this directory is? Would be good to get some clarity on the purpose of checking for the `CI` variable? In Gitlab the `CI` variable is [set automatically in pipelines](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html).

I was able to solve this by changing ...

```
yarn release
```
... to

```
CI='' yarn release
```

**Comment by Chriscbr** [comment]
@iliapolo might be able to give more context here?

**Comment by mrgrain** [comment]
I don't like the tight coupling with `CI`, but this currently the indented behavior. Workarounds for old behavior are available.
