### ISSUE TITLE
API.md too big to show anymore

### ISSUE THREAD

**Issue by kaizen3031593** [projen/projen#1507]
This is what I get when I'm looking up the API now in projen:

![Screen Shot 2022-01-10 at 4 22 43 PM](https://user-images.githubusercontent.com/36202692/148841922-d400c1f5-e4b0-46e9-8396-c82dc3500e1d.png)

The "view raw" is basically unusable as well. Wondering if this is a chance for a necessary documentation overhaul. Happy to help if so.

An additional problem is that the links in the "Getting Started" section (which I use heavily right now haha), would link directly to the relevant API, and now I have to search through the raw markdown to get the API reference I'm looking for.

**Comment by eladb** [comment]
Yeah it's about time we rendered a proper doc site.
