### ISSUE TITLE
Cannot link local projen fork to new package

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#151]
I was interested in adding a new project type to projen, but I've seemed to hit a roadblock. My plan was to use [yarn link](https://classic.yarnpkg.com/en/docs/cli/link/) to create a symlink between a local version of projen and a test package in which I'm going to use it. However, when I try this and run `yarn projen` to actually synthesize things (in the test package), projen automatically deletes the symlink and runs `yarn install` to replace it with the latest version of projen, overriding the symlink. It seems to be caused by https://github.com/eladb/projen/blob/8aa5e311e298acc11a5df833fcc838bd70401a01/src/node-project.ts#L999

I was able to work around this temporarily commenting out some of the symlinking lines, but is there a better way to test things? I imagine there's some kind of escape hatch in place, but I couldn't seem to figure it out.

**Comment by eladb** [comment]
Yeah, it's an annoying wrinkle in projen development. We should definitely do something about it. Any suggestions?

**Comment by eladb** [comment]
What I normally do is:

```ts
rm -fr node_modules/projen && projen
```

Projen will then automatically symlink itself to `node_modules` before executing so you get the local version.

LMK if this works and maybe we can automatically detect this scenario and do it for the user.

**Comment by Chriscbr** [comment]
> What I normally do is:

Yeah I think this is working for me for now, thanks. 👍

**Comment by pgollucci** [comment]
alias pje=/path/to/external/bin/projen
alias pjl=bin/projen

?

**Comment by gradybarrett** [comment]
I've used [Yalc](https://www.npmjs.com/package/yalc) with some success over the past year. It's a bit annoying to introduce a heavier-weight tool at times, but sometimes it's nice to be able to interact with packages as if they're actually published, if only "locally", in order to sidestep symlink issues altogether.
