### ISSUE TITLE
Local linking of CDK constuct to app experience is not optiman due static devDependencies versioning

### ISSUE THREAD

**Issue by Hi-Fi** [projen/projen#1521]
Currently (intentionally) dev dependencies are put as static versions while peer dependencies have caret or static (depending on settings).

This mainly relates to `aws-cdk-lib` and `constructs` dependencies. When testing with app quite often local linking requires first to drop versions of those dependencies at app side to be able to include locally construct development version.

This is split from #1409.

**Comment by Hi-Fi** [comment]
I have moved to approach where I run `npm pack` at the construct side, and then refer to that one from actual application stack creation side. This has 2 extra steps (pack + install -u), but dependencies get handled correctly.

**Comment by mrgrain** [comment]
Running `projen build` and referring to the bundled output is the recommended way at the moment. In general, I think this is an issue with package managers.

**Comment by mattiamatrix** [comment]
> Running `projen build` and referring to the bundled output is the recommended way at the moment. In general, I think this is an issue with package managers.

Hey @mrgrain can you please clarify the steps for the recommended way? Should I do `npm install` `link` or `path` to test locally in a different app?
