### ISSUE TITLE
Running yarn test on windows doesn't find any tests to run

### ISSUE THREAD

**Issue by pflorek** [projen/projen#1522]
If I issue `yarn test` on windows, zero tests are found.

If I modify `jest.testMatch` in `package.json` from `<rootDir>/(test|src)/**/?(*.)+(spec|test).ts?(x)` to `<rootDir>/@(test|src)/**/*(*.)@(spec|test).[t]s?(x)` tests are found.

If I add the following to `.projenrc.js`:

```
  jestOptions: {
    jestConfig: {
      testMatch: ["**/__tests__/**/*.[jt]s?(x)", "**/?(*.)@(spec|test).[tj]s?(x)"],
    },
  },

```

the `package.json` is not updated.

I found this, but not sure if it could be overwritten somewhere else https://github.com/projen/projen/blob/a71ea69e42c0c02679db375912004ff5ea4ed8ad/src/javascript/jest.ts#L603 ?

**Comment by Console32** [comment]
keep, could you remove the <rootDir> substitution ? 
running `projen` on a new project (aws-cdk & typescript) creates:

```
   "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.ts?(x)",
      "<rootDir>/(test|src)/**/?(*.)+(spec|test).ts?(x)"
    ],
    ```
    
replacing rootDir with `**` fixes it. 
Hotfix above is working, but can we get this solved?
