### ISSUE TITLE
Build/Tests working on windows

### ISSUE THREAD

**Issue by mmcculloh-dms** [projen/projen#1529]
Projen itself can't currently be built on windows for a few reasons. One is due to the usage of bash for bootstrapping, which is pretty easy to get around. One of the biggest reasons is that many tests simply do not work on windows (by design). Typically this is due to the task subsystem.

I think it would be lovely to allow projen to be fully buildable on windows, including the testing portion. This may require segregating tests as it makes sense that you can't run certain commands on windows. Or we could have system-conditional logic within tests, but that seems a little scary.

**Comment by gmeligio** [comment]
I think this can be closed since the projen build and test tasks are working on Windows. Here is the build workflow https://github.com/projen/projen/blob/f212132bd15ab0b608beebdd5795c16f631f13cb/.github/workflows/build.yml
