### ISSUE TITLE
CDK construct + app deploying pipeline

### ISSUE THREAD

**Issue by avanderm** [projen/projen#1532]
Hey,

Looking for guidance.

I've been looking at projen as a means to provide conventions/constructs/... in the company I'm working for, in a multitude of languages. I've had good results with projen. One thing I wanted to do is to have a subproject layout; the main project is the constructs library, and just one subproject which is a CDK Typescript app deploying a CDK pipeline to build the construct library and publish it to CodeArtifact. Most of our existing work can be used for that.

However, and this is probably a very beginner question, is there a way that I can share the main project constructs with the app subproject, since we want to already use some of the constructs/aspects in our pipeline. It's a chicken/egg problem and in our current pure CDK implementation the codebases are just merged. We'd like to keep the code separate for cleanliness, which gives us:

```
const { awscdk, javascript } = require('projen');

const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Antoine Vandermeersch',
  authorAddress: 'avdmeers@gmail.com',
  cdkVersion: '2.1.0',
  defaultReleaseBranch: 'main',
  name: 'composite-test',
  repositoryUrl: 'https://github.com/avdmeers/composite-test.git',

  packageManager: javascript.NodePackageManager.NPM,

  buildWorkflow: false,
  mergify: false,
  rebuildBot: false,
  releaseWorkflow: false,

  // deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
});

project.synth();

const pipeline = new awscdk.AwsCdkTypeScriptApp({
  author: 'Antoine Vandermeersch',
  authorAddress: 'avdmeers@gmail.com',
  cdkVersion: '2.1.0',
  defaultReleaseBranch: 'main',
  name: 'pipeline-test',
  repositoryUrl: 'https://github.com/avdmeers/composite-test.git',

  packageManager: javascript.NodePackageManager.NPM,

  outdir: 'pipeline',
  parent: project,

  buildWorkflow: false,
  mergify: false,
  rebuildBot: false,
  releaseWorkflow: false,

  // deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
});

pipeline.synth();
```

None of existing projen fields for the project classes seem to indicate that I can include the codebase of the parent with that of the child. What am I missing?

Thanks in advance!

**Comment by Chriscbr** [comment]
Right now managing multiple packages/projects in the same repo using [subprojects](https://github.com/projen/projen/blob/main/docs/subproject.md) still is a bit tricky / not a robust feature at the moment.

For publishing construct libraries, the main paths we've been experimenting with so far have been supporting it through CI/CD tools. Currently there's a [publisher](https://github.com/projen/projen/blob/main/docs/publisher.md) component to publish to NPM or CodeArtifact via GitHub, but we'd also like to support Gitlab CI and other tools as well.
