### ISSUE TITLE
"npx projen new typescript-app" generates wrong imports

### ISSUE THREAD

**Issue by eduardweigandt0770** [projen/projen#1582]
Running `npx projen new typescript-app` generates the following .projen.js file imports:
```js
const { TypeScriptAppProject } = require('projen');
const project = new TypeScriptAppProject({
[...]
});
```
the working one needs to be:
```js
const { typescript } = require('projen');
const project = new typescript.TypeScriptAppProject({
[...]
});
```

**Comment by kpapagno** [comment]
I am seeing the same behavior for a new awscdk typescript app.   ```npx projen new awscdk-app-ts```  For me in generates:
```
const { AwsCdkTypeScriptApp } = require('projen');
const project = new AwsCdkTypeScriptApp({
[...]
});
```
From what I can tell, this seems to be the correct one:
```
const { awscdk } = require('projen');
const project = new awscdk.AwsCdkTypeScriptApp({
[...]
});

**Comment by kpapagno** [comment]
I have solved my own issue, and it may work for you @eduardweigandt0770 as well.

1.  I deleted my npm cache at ~/.npm
2. I had a node_modules directory directly under my home folder that I deleted that had a copy of projen in it

Now when issuing the new project command, it generates as expected!

**Comment by eduardweigandt0770** [comment]
Yes, after deleting the ~/.npm cache it generates the right imports. thx
