### ISSUE TITLE
(python) pytestOptions.testdir is not used

### ISSUE THREAD

**Issue by straygar** [projen/projen#1620]
`pytestOptions` of `PythonProject` accepts a `testdir` property, which should allow specifying the folder pytest should use to find the tests.

However, it appears this property is never actually used: [pytest.ts](https://github.com/projen/projen/blob/main/src/python/pytest.ts#L34-L39).

**Comment by marciocadev** [comment]
The test directory tells the location where test samples will be created

https://github.com/projen/projen/blob/e71fd9bde81b6631ffe803fce23ebc4d7a2ab696/src/python/pytest.ts#L34-L39

it´s used here

https://github.com/projen/projen/blob/e71fd9bde81b6631ffe803fce23ebc4d7a2ab696/src/python/python-project.ts#L282-L285

**Comment by straygar** [comment]
I guess documentation could be improved in this case? And possibly adding another prop to change where pytest will look for tests?  (e.g. if I have unit and end-to-end/integration tests, and I only want projen to run stuff under `tests/unit`)
