### ISSUE TITLE
(AwsCdkConstructLibrary) give options to set jest runner

### ISSUE THREAD

**Issue by flochaz** [projen/projen#1640]
in order to leverage [jest-runner-groups](https://www.npmjs.com/package/jest-runner-groups) I would need to set jest runner.

As a workaround I use jq: https://github.com/flochaz/aws-dynamodb-table-multi-gsis/blob/main/.projenrc.js#L32 but it would be great to be able to set that natively. Or even better be able to add/modify any (deep) attribute in package.json .

**Comment by Chriscbr** [comment]
That's a clever hack! 😉 

Though I believe there is a way to customize the jest runner - please try if this works:

```ts
const project = new AwsCdkConstructLibrary({
  // ...
  jestOptions: {
    jestConfig: {
      runner: "groups",
    },
  },
});
```

I'm guessing the jest options might have not been easy to discover. Perhaps we can add more info about jest in our [docs](https://projen.io/). (related: https://github.com/projen/projen/issues/1593)

**Comment by flochaz** [comment]
Indeed 🤦 ... I thought I don't know how I missed that ...
