### ISSUE TITLE
tsconfig.json include does not get updated

### ISSUE THREAD

**Issue by nickehunt-idm** [projen/projen#1643]
I have custom template files that are text that are imported into my constructs when needed that need to be included in the output / lib directory when classes are called.  I added the custom 'include' in the tsconfig options to get the custom.  I tried in the both the tsconfig: and compiler options but that is not updating the tsconfig.json to include the additional files in the lib directory when doing the build.  Is there a way to force this?

option 1 - not working
```
tsconfig: {
    include: [
      'src/cloudwatch/blueprints/*.txt',
    ],
```

option 2 - not working
```
compilerOptions: {
    include: [
      'src/cloudwatch/blueprints/*.txt',
    ],
```

option 3 - not working
```
include: [
    'src/cloudwatch/blueprints/*.txt',
  ],
```
Would appreciate any help so can get this packaged up / included in the library publishing.

Thanks
Nick

**Comment by echeung-amzn** [comment]
This seems related to https://github.com/aws/jsii/issues/965

**Comment by nickehunt-idm** [comment]
yes, same thing, did not see a resolution to those.  Did try the escape hatches and was not able to get it working since the tsconfig.json gets overwritten...

**Comment by mrgrain** [comment]
This is by design in jsii. There is no good way to achieve this, currently jsii has to manage its `tsconfig.json`
