### ISSUE TITLE
expose maxWorkers in jestConfig

### ISSUE THREAD

**Issue by saudkhanzada** [projen/projen#1645]
Currently, `jestConfig` does not expose the [maxWorkers](https://jestjs.io/docs/configuration#maxworkers-number--string) prop. Although it is possible to specify it using an escape hatch. 

`project.jest.config.maxWorkers = 1;
`

**Comment by Chriscbr** [comment]
Pull requests are welcome.

**Comment by ologbonowiwi** [comment]
The job is expose the `maxWorkers` prop on this file? https://github.com/projen/projen/blob/5a474a1172e1cf2b40639a897a4a765ed45ffb0b/src/javascript/jest.ts
