### ISSUE TITLE
ts-patch flag

### ISSUE THREAD

**Issue by sam-goodwin** [projen/projen#1651]
To support projects like https://github.com/sam-goodwin/functionless, we can add a flag, `tsPatch`, to the `TypeScriptProjectOptions`. 

```ts
new TypeScriptProject({
  tsPatch: true
})
```

This flag would add ts-patch as a `devDep` and set the following `prepare` script:
```
"prepare": "ts-patch install -a"
```

See: https://github.com/nonara/ts-patch

This script patches the typescript entry points with support for typescript transformers in `tsconfig.json`:

```json
{
  "compilerOptions": {
    "plugins": [{
       "transform": "plug-in-module"
     }]
  }
}
```

Is this enough of a value add to warrant a first class field or should it be left to a custom script?

**Comment by Chriscbr** [comment]
I might be OK accepting this if it's in its own component / doesn't require modification of TypeScriptProject. (like a class which takes TypeScriptProject as its first constructor argument etc.) It could also make sense making this external / vending it in a library that takes projen as a peer dependency.

**Comment by sam-goodwin** [comment]
For my understanding, what's the concern with modifying TypeScriptProject?

**Comment by Chriscbr** [comment]
I'm mostly think about maintainability, and trying to minimize the API surface area of the base project types.

Long term I think projen's model might be simpler to work with if the constructors of project types are dumbed down so they're just instantiating a bunch of components, as it starts to get confusing when project types start owning cross-component logic, or start including logic like "add this script if eslint is enabled, but only if jest is disabled, but not if the version of node is less than 12..." etc

But to clarify, I think it's alright if the API is only one or two fields like `tsPatch` and `tsPatchOptions`, and just update the constructor to add a component like so 🙂:
```ts
if (...) {
  new TsPatch(this, options.tsPatchOptions);
}
 ```
 
I ought to write some kind of design guidelines like we have for the AWS CDK, but some of this is still kind of needs to be researched a bit more

**Comment by sam-goodwin** [comment]
Got it. That makes sense. I quite like the idea of shipping its own component. 

```ts
new TsPatch(project, {
  plug-ins: ..
});
```

> I ought to write some kind of design guidelines like we have for the AWS CDK, but some of this is still kind of needs to be researched a bit more

Yes! Code is beautiful and there are obviously patterns and tenets. Documenting them explicitly would help contributors.

**Comment by mrgrain** [comment]
Issue cleanup. I see this as a third-party component.
