### ISSUE TITLE
AttributeError: module 'projen.github' has no attribute 'workflows'

### ISSUE THREAD

**Issue by agdimech** [projen/projen#1653]
I am building some custom Project Types and as such have extended the TypeScriptProject. I am able to successfully compile, package and publish my lib into js and python, however when importing my package in a python consuming app I am running into the following issue:

```Traceback (most recent call last):
  File "infra/pipeline.py", line 3, in <module>
    from pipeline_stack import PipelineStack
  File "/Users/dimecha/Projects/foo/packages/infra/infra/pipeline_stack.py", line 1, in <module>
    from aws_prototyping_sdk import pdk_pipeline
  File "/Users/dimecha/Projects/foo/packages/infra/.env/lib/python3.7/site-packages/aws_prototyping_sdk/__init__.py", line 75, in <module>
    from . import pdk_projen
  File "/Users/dimecha/Projects/foo/packages/infra/.env/lib/python3.7/site-packages/aws_prototyping_sdk/pdk_projen/__init__.py", line 361, in <module>
    jsii_type="aws-prototyping-sdk.pdk_projen.NxMonorepoProject",
  File "/Users/dimecha/Projects/foo/packages/infra/.env/lib/python3.7/site-packages/aws_prototyping_sdk/pdk_projen/__init__.py", line 502, in NxMonorepoProject
    projenrc_json_options: typing.Optional[projen.ProjenrcOptions] = None,
AttributeError: module 'projen.github' has no attribute 'workflows'
```

The published Python package is here: https://pypi.org/project/aws-prototyping-sdk/

I suspect that there is an issue with how the `workflows` subpackage in the projen python distributable is set up and it appears to be the only one which is nested underneath a github module as per the below screengrab.

![tree](https://user-images.githubusercontent.com/51220968/156302810-d065a253-afdc-432f-9ace-5e758ed455a4.png)

**Comment by agdimech** [comment]
Did a little digging....

It appears my hunch was right and the github module is being imported as follows: 

`import projen.github.workflows`

If I compare this to what the base class python module does, it should look more like this:

```python
from projen.github.workflows import (
    JobStep as _JobStep_c3287c05, Triggers as _Triggers_e9ae7617
)
```

And obviously all references to `projen.github.workflows.Triggers/JobStep` would be replaced by these aliases.

I tested this by modifying the generated py in my .env and can confirm this fixes the issue. Any idea what is causing this to be imported differently?

**Comment by Chriscbr** [comment]
Hmm if I understand correctly this is a python-exclusive issue. This is probably a [jsii](https://github.com/aws/jsii) issue then -- could you file an issue there? (We can still leave this one open.)
