### ISSUE TITLE
Bug: upgrade -task doesn't honor versions set in .projenrc causing task to fail

### ISSUE THREAD

**Issue by Hi-Fi** [projen/projen#1659]
Typescript uses a bit strange versioning, so we have it "locked" in `.projenrc.js` to `4.4.4`.

Issue is, that `upgrade` task would first update all packages, and then Projen would run and put those specified versions to use. This causes now `upgrade` to fail, as e.g. `typedoc` package (that we use to generate documentation for users) has following:
```
npm ERR! peer typescript@"4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x || 4.5.x" from typedoc@0.22.12
```
# Expected behaviour

Upgrade command should have those version "locks" already in place when running, so it wouldn't momentarily go to other versions. 

This should handle both "exposed" versions (cdk, constructs, typescript), and also manually set versions (using `@` in the `dependencies`, `devDependencies` or `peerDependencies`).

**Comment by Chriscbr** [comment]
You might be able to workaround this (so at least other packages can be upgraded) by passing `"typescript"` to the `exclude` field in `depsUpgradeOptions`.

**Comment by Hi-Fi** [comment]
@Chriscbr Workaround/fix is also to run `projen` after the failure, so it would update "locked" versions to correct ones and make install (which now passes, as `.projenrc` has e.g. typescript version set to 4.4.4).

But I think that neither of these should be needed, as I already have the version told in configuration. 

Of course this also comes from the typescript "almost semver" versioning, but as version is separately settable I think it should also reflect to update command.

I think that Projen
- should exclude packages where version is set from `npm-check-updates` (like it already does for projen due to it's separate script)
- allow npm/yarn upgrade task to handle those "locked" versions according how those are in package.json (plain,caret or tilde).

**Comment by Chriscbr** [comment]
> I think that Projen ... should exclude packages where version is set from `npm-check-updates` (like it already does for projen due to it's separate script)

Sure, this makes sense to me. As long as a version is "pinned" to a specific version (not a version range), then the upgrade-deps task should not try updating that package. Pull requests are welcome.

**Comment by Hi-Fi** [comment]
PR works for NodeProject, but not those who extend it as  upgrade steps are done before project specific dependencies are handled. So some refactoring still to do.
