### ISSUE TITLE
Feature Request: Initialize .projenrc.js with commented out project options

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#168]
Quality of life / convenience feature.

The idea is when `.projenrc.js` gets generated, it should include a list of the available options out of the box, similar to how they are provided when you run `tsc --init` in a new repository, which produces:

```js
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    ...
```

I see that jsii is being used to generate API docs right now -- maybe there's some way to hook into that or leverage it to perform this automatically?

**Comment by eladb** [comment]
Yes. This idea came to mind and should be achievable.

**Comment by pszabop** [comment]
Yes please.  As a new user I'm finding it difficult to figure out what I can do.  Any documentation help would be a plus.
