### ISSUE TITLE
cdk8s-app-py project type

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1680]
Create a `Cdk8sPythonApp` project type that mirrors the experience of `Cdk8sTypeScriptApp`, but instead which extends from the `PythonProject` type. For any extended logic that can be shared with `Cdk8sTypeScriptApp`, consider extracting it into components as we currently do in the AwsCdk project types: https://github.com/projen/projen/blob/71ad8c75dd2b1a577356520772353278b4048d8b/src/awscdk/awscdk-app-py.ts#L81-L98

**Comment by marciocadev** [comment]
I looked into `cdk8s-app-ts.ts` and agree with you

Extract task from `cdk8s-app-ts.ts` and put in a exclusive file it's a great way to reused this piece of code in future.

**Comment by Chriscbr** [comment]
Pull requests are welcome 🙂

**Comment by marciocadev** [comment]
I will start work on this issue
