### ISSUE TITLE
lock down GitHub Actions to specific SHA

### ISSUE THREAD

**Issue by ahammond** [projen/projen#1702]
Per GH security docs: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

I think we should consider locking down all GH Actions that we reference by SHA instead of by tag.

e.g. Before:
```
uses: actions/checkout@v3
```

After:
```
uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
```

Thoughts?

**Comment by Chriscbr** [comment]
Yes I think this is a good idea. One exception might could be that actions published by GitHub themselves (under the `actions` org) are probably okay to refer to by tag, since they are basically official.

Pull requests are welcome.

**Comment by ahammond** [comment]
@Chriscbr do you know of anyone who wants to earn some $$$ doing this on contract? I'm willing to bet I can get my boss to simply hire this done.

**Comment by xiehan** [comment]
Came here looking for this -- our company is starting to roll this out as a security requirement so we're going to need this within the next couple of months. FWIW they decided to treat even GitHub's official actions as untrusted (i.e. requiring a SHA), only actions published by our own company are considered trusted and don't require a SHA. So perhaps if there's some way to make that configurable, that would be ideal.
