### ISSUE TITLE
pnpm lockfile error after changing project package manager to pnpm

### ISSUE THREAD

**Issue by kinderlars** [projen/projen#1704]
I keep getting the error message 
```
ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with package.json

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
```
when running `projen upgrade` after changing the project package manager to `packageManager: NodePackageManager.PNPM`. 

Tested it with a regular TS project and a TS CDK project. 
E.g. 
```
const project = new awscdk.AwsCdkTypeScriptApp({
  cdkVersion: '2.16.0',
  defaultReleaseBranch: 'main',
  name: 'test-app',
  packageManager: NodePackageManager.PNPM
});
project.synth();
```

Any ideas on how to fix this through projen?

**Comment by skyrpex** [comment]
I got struck by the same problem. If I execute the tasks manually, the error doesn't exist. Somehow, pnpm is using frozen-lockfile even though the parameter is not set. I could fix the problem editing the `renderInstallCommand` in `node-package.js` as follows:

```js
return ["pnpm i", ...(frozen ? ["--frozen-lockfile"] : ["--no-frozen-lockfile"])].join(" ");
```

That forces not to use frozen lockfile.
