### ISSUE TITLE
Update projen to require node v14

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1739]
Node v12 is EOL in April 30, 2022 (ref: https://nodejs.org/en/about/releases/). Updating this will ensure we're able to pick up fresh/stable dependencies that depend on node v14 and above, and that we aren't aren't susceptible to security vulnerabilities in old node versions.

**Comment by pgollucci** [comment]
@Chriscbr This can be closed.

**Comment by Chriscbr** [comment]
I believe this is still relevant, currently projen still supports node v12: https://github.com/projen/projen/blob/42d638ba1e4227a4551950e78fadfda99e7d5a9e/package.json#L120
