### ISSUE TITLE
Integration tests depend on live version of projen

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1741]
Even if we link against our local built version of projen for the test, there are frequently very rare, and very hard to debug errors in integration tests because the tests will try creating a new project, and somewhere downstream it will try installing projen from the internet as part of the "npm install"/"yarn install". It's possible to disable this partially by passing flags like `--no-synth`, but then we're unable to validate some parts of projen's behavior.

A robust solution for this is to set up a proper integration test environment in which we use a proxy registry such as [Verdaccio](https://verdaccio.org/) to host our "test" version of projen, so in the integration test, whenever anything tries fetching the latest version of projen, it will always receive the local version as if it's a live package fetched from npm.

**Comment by mrgrain** [comment]
That was fixed recently https://github.com/projen/projen/pull/3483
