### ISSUE TITLE
`tsconfig.json` in jsii projects

### ISSUE THREAD

**Issue by eladb** [projen/projen#176]
In jsii projects, `tsconfig.json` is normally created by the compiler (`jsii`) during compilation and therefore is currently not managed by projen and currently ignored in `.gitingore`. This means that when a fresh jsii project is checked out, there is no `tsconfig.json` until the project is compiled, which is not required for other typescript projects (since jest is configured to compile the sources).

We need to:
1. Create an initial tsconfig.json (read-write, with the jsii marker, so jsii can override).
2. Make sure it's checked into the repo.

**Comment by zxkane** [comment]
pls also add [tsc support of jsii configuration](https://aws.github.io/jsii/user-guides/lib-author/configuration/#tsc), it allows customize the `tsconfig.json` generated by jsii. It might reuse the existing `tsconfig` for jsii `tsc` section.

**Comment by thtliife** [comment]
@eladb this is my workaround in .projenrc.ts:

```typescript
const project = new VueJsProject({
  name: 'my-vuejs-sample',
  description: "my awesome vue project",
  // ...
  devDeps: [
    'projen-vuejs'
  ],
/* customize tsconfig (projen actually applies this to `tsconfig.dev.json` */
tsconfig: {
  compilerOptions: {
    baseUrl: './',
    paths: {
      '@': [ './src' ]
    }
  }
}
});

/* add this to sort out tsconfig customisation for all files under the `./src` folder */
if (!project.disableTsconfig) {
  new JsonFile(project, 'src/tsconfig.json', {
    obj: {
      extends: '../tsconfig.dev.json'
    }
  });
}
/* tsconfig fixt */

project.synth();

```

I also add a very similar thing to my personalized external modules like:

```typescript
if (!options.disableTsconfig) {
  new JsonFile(this, 'src/tsconfig.json', {
    committed: true,
    readonly: true,
    obj: {
      extends: '../tsconfig.dev.json'
    }
  });
}
```

Hope this helps
