### ISSUE TITLE
No way to disable auto-merge

### ISSUE THREAD

**Issue by sacharya-sp** [projen/projen#1765]
Looks like the mergify configuration comes with an auto-merge rule by default, and there's no way to disable it. The option `mergifyOptions` has the ability to add additional auto-merge rules, but no way to remove the default rule.

I'm looking specifically at the `AwsCdkTypeScriptApp` project, but I'm seeing that this issue applies to other projects as well.

**Comment by Chriscbr** [comment]
Hey @sacharya-sp - I did some digging and it looks like this rule is automatically added by a component named `AutoMerge`, but projen's API is missing a way to easily disable this.

Right now, the closest workaround is to specify `mergify: false` and then creating `new Mergify(project, { ...options })` in your projenrc file.

We can easily add an option like `autoMerge: false` which will disable the creation of these default rules. Would that solve your issue more cleanly?

**Comment by sacharya-sp** [comment]
Thanks Chris, this workaround works for me. It's a bit hard to find - it may not be apparent for other Projen users that the Mergify settings can be overridden by instantiating Mergify (rather than modifying the Project). An `autoMerge` option would certainly be easier to use for those who want to use Mergify without the default auto-merge rule.
