### ISSUE TITLE
cdk8s import location is not compatible with projen projects

### ISSUE THREAD

**Issue by eladb** [projen/projen#177]
cdk8s imports normally go to an `imports` directory under the project root. This is incompatible with the fact that projen typescript projects require that all sources go under `src/`. https://github.com/awslabs/cdk8s/issues/335 proposes that it will be possible to configure the output for `import` in `cdk8s.yaml` so that imports can go in the right place.

We need to make sure this is supported for cdk8s projects.

**Comment by pgollucci** [comment]
I believe this is fixed by https://github.com/projen/projen/pull/699 and can be closed. @eladb

**Comment by eladb** [comment]
Keep

**Comment by eladb** [comment]
@pgollucci can you confirm that this is fixed?

**Comment by misterjoshua** [comment]
@eladb This doesn't appear to be fixed after all. https://github.com/projen/projen/issues/1534
