### ISSUE TITLE
Feature Request:   Create CDK integration test apps for a CDK construct

### ISSUE THREAD

**Issue by pszabop** [projen/projen#178]
I am creating a [construct for exporting/importing VPCs](https://github.com/pszabop/cdk-vpc-export-import) since CDK's support for that is missing/undocumented.

I need to integration test the construct (i.e. an actual deployment that tests that network traffic passes).  (I've already encountered misconfiguration issues that prove I need this kind of test, as much or more than actual unit tests).  This means I have several options, all with issues.  I also want to use [AWS's CI Pipeline](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/)  to automate deployment (and maybe running) of the integration tests, though I'm open to other solutions.

My options appear to be:

1. Create an [awscdk-app-ts](https://github.com/eladb/projen/blob/master/API.md#projen-awscdktypescriptapp) project.  However this is different than a [awscdk-construct](https://github.com/eladb/projen/blob/master/API.md#projen-awscdkconstructlibrary) project so I won't be able to publish a construct from this type of project.

1. Create an  [awscdk-construct](https://github.com/eladb/projen/blob/master/API.md#projen-awscdkconstructlibrary) (which I did already) project but then I cannot create apps using this project type

1. Create an [awscdk-construct](https://github.com/eladb/projen/blob/master/API.md#projen-awscdkconstructlibrary) in the main directory, add a subdirectory called `integration-tests`, and then put an [awscdk-app-ts](https://github.com/eladb/projen/blob/master/API.md#projen-awscdktypescriptapp) in that directory.  I'm uncertain how the automated Github and NPM integrations will interact with each other. 

1.  Create a separate repo for the [awscdk-app-ts](https://github.com/eladb/projen/blob/master/API.md#projen-awscdktypescriptapp) to test the other repo's [awscdk-construct](https://github.com/eladb/projen/blob/master/API.md#projen-awscdkconstructlibrary).  Not sure I like this, it means I'll be releasing untested NPM modules to npmjs.org.

1.  Using `yarn pack`, copy the package over to a second repository that is [awscdk-app-ts](https://github.com/eladb/projen/blob/master/API.md#projen-awscdktypescriptapp) project.  then untar the resulting tarred package in the second repository, and run the tests.  The problem with this method is yet a third repository will be needed to automate this process since it is manual.  Or make a bad assumption about the local paths of the workspaces (e.g. hard code `..\<cdklib_repo>`.  3 repos for automated integration tests seems excessively tedious.

Any ideas on the best approach here?

**Comment by pszabop** [comment]
Some problems with "create an integration-tests directory":

1. The `npmignore` option must be set to ignore this directory
1. The `jestOptions` options must be set to ignore this directory
1. There doesn't appear to be a way to get `projen` to ignore a directory.  That should probably be a feature request

**Comment by pgollucci** [comment]
@Chriscbr this what I was alluding to in the #287 discussion

**Comment by pszabop** [comment]
This sounds like subproject?

https://github.com/projen/projen/pull/332

**Comment by misterjoshua** [comment]
I'd like an easier way to do this as well. I've been using a gimmicky hack where I define the integration test in the src directory like this:

**src/integ.my-integ.ts**

```ts
import { App, CfnOutput, Construct, Stack, StackProps } from '@aws-cdk/core';

export class MyInteg extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new CfnOutput(this, 'ApiAddress', {
      value: 'Hello',
    });
  }
}

const app = new App();
new MyInteg(app, 'my-integ');
```

Then I can deploy `MyInteg` by running `cdk deploy --app 'npx ts-node src/integ.my-integ.ts'`

I use a snapshot test run by jest to make sure nothing changes so it tests with each build:

**test/snapshot.my-integ.test.ts**
```ts
import { App } from '@aws-cdk/core';
import { MyInteg } from '../src/integ.my-integ';

test('integ.my-integ', () => {
  const app = new App();
  const stack = new MyInteg(app, 'my-integ');

  expect(stack).toMatchSnapshot();
});
```

**Comment by eladb** [comment]
Don't close.

**Comment by misterjoshua** [comment]
Update since my last comment on how I'm integration testing:

I've been able to move the integration tests over to `test` and I use a few tricks to make them easier to work with. I include `aws-cdk` and `ts-node` as `devDeps` so that I can do the following:

**.projenrc.js***
```js
project.package.setScript('integ:do-things', 'cdk --app "ts-node -P tsconfig.jest.json test/integ/integ.do-things.ts"');
```

You can then run `yarn integ:do-things deploy` or `yarn integ:do-things diff` to manually deploy the apps so that they can be tested on AWS.

The apps themselves look something like this:

**test/integ/integ.do-things.ts**
```ts

/** @internal */
export class IntegDoThings extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps = {}) {
    super(scope, id, props);

    // Do your thing here.
  }
}

if (!module.parent) {
  // This part activates when this file is the entrypoint and
  // not when it's imported by a snapshot test.
  const app = new cdk.App();
  new IntegDoThings(app, 'integ-do-things', {
    env: {
      account: process.env.CDK_DEFAULT_ACCOUNT,
      region: process.env.CDK_DEFAULT_REGION,
    },
  });
}
```

And the snapshot tests look like this:

**test/integ/integ.do-things.test.ts**
```ts
test('snapshot', () => {
  const app = new cdk.App();

  const stack = new IntegDoThings(app, 'integ-do-things');
  expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
});
```

**Comment by eladb** [comment]
This is already supported
