### ISSUE TITLE
Adding npmrc for private registry with workflowBootstrapSteps fails on build.yml / package-js

### ISSUE THREAD

**Issue by 5nafu** [projen/projen#1799]
In reference to #1006, we added the following snippet to our `.projenrc.ts`:

```
const project = new awscdk.AwsCdkConstructLibrary({
  //...
  workflowBootstrapSteps: [
    {
      name: 'Login to GitHub npm registry',
      id: 'npm_auth',
      run: 'echo -e "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> ~/.npmrc',
      env: {
        'NPM_TOKEN': '${{ secrets.NPM_PULL_SECRET }}'
      },
    },
  ],
});
```

This will work  for the initial jobs of the `build.yml` and `release.yml` workflows but will fail on the the following jobs as the `$HOME` directory is not shared between jobs.
Therefore the `Install Dependencies` steps of `build.yml/package-js` and `release.yml/release_npm` workflows/jobs will fail.

Pleas advise if this is a bug or if we are using the wrong API for what we need to do.

**Comment by 5nafu** [comment]
Alternatively maybe the `workflowBootstrapSteps` could be added to each `job`-Part, and not only to the initial one. 
My theory would be that the parameter is basically being used to either install dependencies or add login information. And both would actually be needed in all work environments. And as each `job` does get their own environment (including `$HOME`), the `Bootstrap` would need to be done all the time.

I saw [node-project.ts#L835](https://github.com/projen/projen/blob/a64180a673f1d436f3515148e89cc3d5b9b0590c/src/javascript/node-project.ts#L835) where the different parts are added to the initial job, maybe this could be used in the "other" jobs. But, unfortunately, I could not find any code part, where the "other" jobs for the build and release workflows are added.

**Comment by mpiltz** [comment]
I was just working on the same issue and found example from Projen's test-files.
I added .npmrc in separate step:
`const npmConfig = new NpmConfig(project);
npmConfig.addConfig("@my-namespace:registry", "https://npm.pkg.github.com");
npmConfig.addConfig("//npm.pkg.github.com/:_authToken", "${PRIVATE_GITHUB_TOKEN}");
npmConfig.addConfig("engine-strict", "true");`
Then i added my private token as job level environment-variable. I believe this same escape hatch could be used to target individual steps also in a job, but it haven't tried it yet.
`project
  .github!.tryFindWorkflow("release")!
  .file!.addOverride("jobs.release_npm.env.PRIVATE_GITHUB_TOKEN", "${{ secrets.PRIVATE_GITHUB_TOKEN }}");`

**Comment by roamingthings** [comment]
I'm running into similar issues where I have to pull dependencies from a private repository in order to publish the package for rpm and maven.

I wonder if it would make sense to add something like

```ts
    prePublishSteps.push(...this.workflowBootstrapSteps);
```
at https://github.com/projen/projen/blob/70ff293936149446b80229b5ab29c38c1f41746c/src/cdk/jsii-project.ts#L436

On the other hand this would require the field `workflowBootstrapSteps` at https://github.com/projen/projen/blob/70ff293936149446b80229b5ab29c38c1f41746c/src/javascript/node-project.ts#L427 to be made `protected` instead of private.

**Comment by roamingthings** [comment]
On the other hand I wonder if this change would have any 'breaking' side-effects for existing projects.

**Comment by mrgrain** [comment]
> I'm running into similar issues where I have to pull dependencies from a private repository in order to publish the package for rpm and maven.

Can you confirm what you exactly mean by this? 

> On the other hand I wonder if this change would have any 'breaking' side-effects for existing projects.

Generally speaking the description of [workflowBootstrapSteps](https://github.com/projen/projen/blob/70ff293936149446b80229b5ab29c38c1f41746c/src/javascript/node-project.ts#L132-L137) would allow that. At the other hand the package-x and publish-x steps of jsii are different in the sense that they expect everything to be set up already and copied in via the artifact from the build step. But clearly the reality is that this doesn't always work like that.

The premium solution would be to add a bunch of extra options to `JsiiProject` that allows adding extra steps for package-x and publish-x and/or each language individually.

**Comment by roamingthings** [comment]
> Can you confirm what you exactly mean by this?

I'm trying to build an `AwsCdkConstructLibrary` that publishes a JS (NPM) and Java (Maven) artifact to my (private) GitHub repository. The publishing itself is working fine. However, I'm also relying on another constructs library that is available in a private GitHub repository. For this reason each time that `yarn install` runs it requires a pointer and the credentials (GitHub token) to download the private dependency.

Initially I have been the same approach like @5nafu with the same issue. Release to npm/java didn't get the `workflowBootstrapSteps` steps and `yarn install` failed.

Using the suggestion from @mpiltz I have now been able to have all `yarn install` steps successfully download the dependency. But I'm now at a point where `maven` in the java packaging task also requires the repository location and credentials to access the Java version of the private constructs dependency. I don't know yet how to add a maven repository definition to the maven packaging task.

I assume that publishing a Python artifact would have a similar issue.

**Comment by mrgrain** [comment]
Thanks! I wanted to make sure I understand the requirements better. 👍🏻 

--- 

Conceptually I think the split between `release` and `publish` doesn't work at the moment. It's done so that we can release and build once, and then package and and publish for each language. However the split has not been done to the full extend, as `yarn install` is still required. So from that angle, `workflowBootstrapSteps` would still be needed for each of the languages.

**Comment by roamingthings** [comment]
As I mentioned above providing `yarn install` with the credentials is only have of the solution.
I've no idea how to also pass this information to the maven (and all the other) packaging tasks for AwsCdkConstructLibrary projects.

**Comment by mrgrain** [comment]
> As I mentioned above providing `yarn install` with the credentials is only have of the solution. I've no idea how to also pass this information to the maven (and all the other) packaging tasks for AwsCdkConstructLibrary projects.

I'm not very familiar with Maven. Sorry.

projen uses tools for this. I'd check if they support what you need to do, and other wise open an issue/PR for the respective tool:

- For packing: https://github.com/aws/jsii/tree/main/packages/jsii-pacmak https://aws.github.io/jsii/user-guides/lib-author/quick-start/set-up/
- For publishing: https://github.com/cdklabs/publib#maven

**Comment by rjmackay** [comment]
For anyone needing a workaround in the interrim, this works:
```js
project.github!.tryFindWorkflow('build')!.file!.patch(
  JsonPatch.add('/jobs/package-js/steps/1', {
    name: 'Setup NPM Token',
    run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc',
    env: {
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}',
    },
  })
)
```

**Comment by asdcamargo** [comment]
I created a PR to address this issue following what was suggested by @5nafu:
https://github.com/projen/projen/pull/2311

**Comment by rjmackay** [comment]
This same issue still exists for the `release_npm` job, since `yarn install` will fail if you have any private dependencies. Should I open a new issue or could you reopen this one?

**Comment by mrgrain** [comment]
New issue please. The PR explicitly tests for workflow bootstrap steps being added to `release_npm`. Not sure what's going on with your project.
