### ISSUE TITLE
Task.reset option uses wrong interface?

### ISSUE THREAD

**Issue by ruggero-visintin** [projen/projen#1806]
Hi Guys,

Maybe it's intended, but I find it quite odd that the `Task.reset` method uses `options?: TaskStepOptions` instead of `options?: TaskOptions)`.

Shouldn't it be like this:
```
reset(command?: string, options?: TaskOptions): void
```

**Comment by mrgrain** [comment]
`Task.reset` currently provides a shortcut to replace the task with a single new command (`TaskStep`). So the options make sense.

However the resetting could be done better in general. Closing in favor of #1904
