### ISSUE TITLE
Python-based projects can no longer use existing .projenrc.js files

### ISSUE THREAD

**Issue by mbonig** [projen/projen#1807]
I've got a number of projects that are PythonProject based, and now with the latest updates an `npx projen` no longer runs because it's trying to find a .projenrc.py file. I see options to turn that off, as well as turning on a .json option, but I need to still use the existing .projenrc.js files and don't see the option to do it.

To make this work, I've had to go hacking at the default task:

`this.tasks.tryFind('default')?.exec('node .projenrc.js');`

which isn't something I feel I should have to do to maintain backwards compatability.

**Comment by Chriscbr** [comment]
This looks like a regression when I updated .projenrc.py to be the default for Python projects a few months back. I've written up a small PR that I think will address this.
