### ISSUE TITLE
Feat request (jest): Ability to add more"ts-jest" globals for jest-config

### ISSUE THREAD

**Issue by shaunjoshi** [projen/projen#1822]
Hey folks, I am trying to add more globals under ts-jest to speed up tests. The `isolatedModules` flag needs to be set. 
This feature may already be implemented although I tried using the globals as follows:
```
const apiProject = new TypeScriptProject({
  defaultReleaseBranch: "mainline",
  name: "api,
  parent: repo,
  outdir: "packages/api",
  gitignore: ["build/", ".env"],
  jestOptions: {
    jestConfig: {
      preset: "ts-jest",
      globals: {
        "ts-jest": {
          isolatedModules: true,
        },
      },
    },
  },
```

The output jest-config still contains no flag and only:
```
{
  "globals": {
    "ts-jest": {
      "tsconfig": "tsconfig.dev.json"
    }
  },
```
instead of the desired:
```
{
  "globals": {
    "ts-jest": {
      "tsconfig": "tsconfig.dev.json",
      "isolatedModules": true,
    }
  },
```

Any guidance on how to add this flag to the jest config would be appreciated. I am following the guidance as suggested here which I have verified by manually editing the projen-generated `package.json`: https://stackoverflow.com/questions/68724389/jest-takes-10s-to-run-two-trivial-typescript-tests-how-do-i-determine-why-its

Thanks in advance.

**Comment by mrgrain** [comment]
Note that `ts-jest` has deprecated the use of `globals` . Same should apply for the transform config though.
