### ISSUE TITLE
Feature request: allow multiple source directories

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#183]
Related to #182.

A lot of code repositories just use a single directory for putting the main code in, typically `src`. But other repositories and templates/frameworks may suggest other organization of files at the root level. e.g. https://github.com/vercel/next.js/tree/canary/examples/with-typescript

We should enable projen users to specify multiple source directories in some fashion. As a result, the directories would be automatically added to _all_ related config files that have some notion of "entry" or "target" directories, such as `tsconfig.json`, `jest.config.js`, `eslintrc.json` and so on.

We can also enable multiple source directories for each of these components individually - but I think the global option is worth evaluating. Here is how it would look like on an individual component basis:

```ts
let srcDirs = ['components', 'pages', 'utils'];

const project = new TypeScriptProject({
  name: "my-app",
  eslintDirs: srcDirs,
  tscDirs: srcDirs,
  ...
});
```

This is not something I have any immediate need for, but I thought it's worth submitting this for tracking purposes / to gauge interest. 🙂

**Comment by eladb** [comment]
Sounds good. Should be fairly easy to support. Contributions are welcome

**Comment by pgollucci** [comment]
Does it make sense to pass srcDirs for each component in the rc or should the construct pass srcDirs to all components for you ?

**Comment by Chriscbr** [comment]
I think passing srcDirs to all relevant subcomponents for you would be a sensible default - but it should still be possible to override the choices on an per-component basis (e.g. if you don't want to lint a folder that has legacy code, but you still want to compile/build it). Overriding per-component srcdirs should probably through directly assigning to certain fields or calling an API.

Perhaps we could change the srcdir option/param to be an array of strings instead (or add a `srcdirs` flag and deprecate `srcdir`)? This might require changes in several places - but the endgoal though is to represent a simpler / more flexible mental model. If a specific project type like a CDK app requires there to be only one source directory, then a runtime check could be added to the constructor to validate that the srcDirs list is length 1.

**Comment by eladb** [comment]
Don't close

**Comment by Chriscbr** [comment]
Reopening. This is a currently an issue since cdk8s projects (created with `projen new cdk8s-app-ts`) cannot use any cdk8s imports they generate, since the `src` and `imports` directories are separate and the generated `tsconfig.json` has `rootDir` set to `src`.

A temporary workaround for the above issue is to use an escape hatch:
```
project.tryFindObjectFile('tsconfig.json').addDeletionOverride('compilerOptions.rootDir');
```
