### ISSUE TITLE
wrong "authorOrganization" NodeProject field type

### ISSUE THREAD

**Issue by fabio-vitali-docebo** [projen/projen#1833]
HI, I'm afraid the NodeProject `authorOrganization` field type, now `boolean`, should be `string` instead.

(thank you for your amazing work!)

**Comment by Chriscbr** [comment]
Hi @fabio-vitali-docebo could you provide any extra information on this?

**Comment by fabio-vitali-docebo** [comment]
sure @Chriscbr I'm sorry. in projen package (`main` branch), `javascript/node-package.d.ts` file, the `NodePackageOptions` interface has the `authorOrganization` field marked as boolean. I think it should be a string.

**Comment by fabio-vitali-docebo** [comment]
(.projenrc.js `authorOrganization` field value renders the `author.organization` field of the package.json)

**Comment by fabio-vitali-docebo** [comment]
the scaffolding job works as expected

**Comment by tompahoward** [comment]
From what I can find, I can't tell `author.organziation` should be a field in the `package.json`, let alone if it should be a `string` or `boolean`. @fabio-vitali-docebo do you have a reference that says it should be a `string`?

`author` is a `Maintainer` https://github.com/npm/types/blob/master/index.d.ts#L17
And a `Maintainer` has a `name`, `email` and `url` https://github.com/npm/types/blob/master/index.d.ts#L17
No mention of an `organization` field.

The docs at https://docs.npmjs.com/cli/v8/configuring-npm/package-json#people-fields-author-contributors don't mention an `organization` field either.

From what I can see, `author.organization` was added in https://github.com/projen/projen/commit/e773a0dcab0ace15cabca4db8dbc95924248e7ad

@eladb, sorry I'm no expert here, can you help us find where `author.organization` comes from? Is it an old field that's no longer in the npm code/docs or is it an extension that other tools use? TIA

**Comment by Chriscbr** [comment]
@fabio-vitali-docebo @tompahoward I was able to found the source! It's an additional field used by jsii: https://aws.github.io/jsii/user-guides/lib-author/configuration/

Closing this out since I think the mystery is solved :)
