### ISSUE TITLE
(AwsCdkTypeScriptApp): Add exclude/include methods for cdk.json

### ISSUE THREAD

**Issue by ryansonshine** [projen/projen#1898]
In building a typescript app that creates a CodeCommit repository using files from inside the repository; it would be helpful if to have `addExclude` and `addInclude` methods on the `cdkConfig` allowing me to add additional includes and excludes to `cdk.json`. This would be similar to the methods found on `tsconfig`.

If there's a better way to go about this please let me know. If not, I can find the time to put in a PR if the team is open to reviewing it.

**Comment by Chriscbr** [comment]
That makes sense to me, PRs are welcome! I believe this is the component that would need changing: https://github.com/projen/projen/blob/main/src/awscdk/cdk-config.ts
