### ISSUE TITLE
Question: Npm and Py package versions stuck at 0.0.0

### ISSUE THREAD

**Issue by fsalamida** [projen/projen#1899]
Hi All,
I have published new [construct project](https://github.com/aws-samples/cdk-aws-iotfleetwise) and while github releases keep increasing the npm and py packages are stuck at 0.0.0. What am I doing wrong?

**Comment by tompahoward** [comment]
You're not doing anything wrong. 

> projen uses git tags to read the latest version, while maintaining the package.json version to 0.0.0

https://cdk-dev.slack.com/archives/C01BP9PQHPC/p1652778756729819?thread_ts=1652776545.517039&cid=C01BP9PQHPC

Docs at https://projen.io/releases.html

**Comment by fsalamida** [comment]
Thx
