### ISSUE TITLE
Editing Task Steps (Remove Specific Step Without Reseting)

### ISSUE THREAD

**Issue by joyliu-q** [projen/projen#1904]
In the `.projenrc` file (I'm using the `react-ts` app), it is not possible to conveniently edit the individual steps of a particular task in the `tasks.json` file.

## Current Method
To remove a specific step in a task, there is one way:
### Reset & Repopulate
```
project.buildTask.reset();
// Add stuff to buildTask afterwards
```
Here, you would look for the pre-existing task, nuke it, and refill it with your custom steps. This method is not very compatible if you're just trying to remove one singular thing (e.g. tests) from your build workflow and keep the rest as the projen standard (and change when projen updates).

### Editing steps field of a task directly
```
const newBuildSteps = project.buildTask.steps.filter(step => step.name !== "test");
project.buildTask.steps = newBuildSteps
```
In above, steps is immutable, so it's not possible to set the steps field. I'm assuming there's some reason for this immutability. 
### A `editTask` method
This doesn't exist, but would be pretty helpful to have.

**Comment by mrgrain** [comment]
`Task.reset` currently allows the user to replace the task with a single new command (TaskStep). This might be confusing, especially given the name. Maybe a fluent interface would be better `task.reset().add()` or adding something like `task.replace(new Task())`
