### ISSUE TITLE
Specifying 'publishConfig' in package.json

### ISSUE THREAD

**Issue by markusl** [projen/projen#192]
Use case: Building AWS CDK JSII construct and publishing to company internal Artifactory repository.

It would be good to have a possibility to specify this in `package.json`:

```json
  "publishConfig": {
    "registry": "https://company.com/api/npm/company-local/"
  },
```

**Comment by eladb** [comment]
This should also effect the NPM_REGISTRY config for jsii-release

**Comment by pgollucci** [comment]
The first part I can handle and get.  i don't get want you want in NPM_REGISTRY to change ?

**Comment by gradybarrett** [comment]
I think the assumption is, if you're publishing to a certain registry, you're probably also pulling packages from that same registry. Is that true?

Can we also add the ability to set the registry in a project-level npmrc? This would be useful for local development or in build environments where NPM_REGISTRY is not set.

For example, we work with a pretty limited CI tool and use an internal registry, so right now I add an npmrc to set the registry only for those projects that require internally published packages.

Is anyone working on this yet? If not I've love to take a stab at it.

**Comment by markusl** [comment]
In our environments, the developers are instructed to configure their `.npmrc` with something like this `registry = https://companyartifactory.com/api/npm/company-npm-general`.

The build environment we are using has a set of NPM credentials that would allow publishing to the internal repository as long as the `publishConfig` property would be in place.

**Comment by henrysachs** [comment]
@markusl  I tried myself on this if you have some suggestions I would be happy.

**Comment by markusl** [comment]
@henrysachs Are there any major open issues? We'd be happy to see this feature request merged

**Comment by kcwinner** [comment]
Wanted to leave a note (based on convo in cdk.dev Slack). This is achievable (though not "native") currently. You can do something like:
```js
...
project.addFields({
  'publishConfig': { "registry": "https://<ARTIFACT_DOMAIN_NAME>-<ACCOUNT_ID>.d.codeartifact.<REGION>.amazonaws.com/npm/<ARTIFACT_EPOSITORY_NAME>/" }
})

project.synth();
```

You'll have to also add an environment variable for the NPM registry. It's easy in [codebuild](https://github.com/kcwinner/advocacy/blob/master/external-projen-project-codeartifact/pipeline/src/lib/pipeline-stack.ts#L97). For GitHub you'll have to do something with the actions

I use this for working with AWS CodeCommit. Also tested (but I don't have an example) with GitHub.
Sources / examples:
* [my blog post](https://kennethwinner.com/2020/11/16/custom-projen-project-codeartifact/)
* [my github](https://github.com/kcwinner/advocacy/tree/master/external-projen-project-codeartifact)
