### ISSUE TITLE
Unable to change packageManager when using projen new

### ISSUE THREAD

**Issue by agdimech** [projen/projen#1932]
When running `npx projen new ... --package-manager=pnpm` I get the following error:

```
evalmachine.<anonymous>:7
  packageManager: javascript.NodePackageManager.PNPM,
                  ^

ReferenceError: javascript is not defined
```

This is due to the fact that the .projenrc file does not import the NodePackageManager from the javascript namespace.

**Comment by pflorek** [comment]
Can't reproduce with `npx projen@latest new typescript-app --package-manager=pnpm`

Creates

```typescript
const { javascript, typescript } = require('projen');
const project = new typescript.TypeScriptAppProject({
  defaultReleaseBranch: 'main',
  name: 'test',
  packageManager: javascript.NodePackageManager.PNPM,

  // deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
});
project.synth();
```

```shell
$ npx projen --version
0.58.15
```

**Comment by cgatt** [comment]
Similarly cannot reproduce with `npx projen@latest new node --package-manager=pnpm`

Creates

```js
const { javascript } = require("projen");
const project = new javascript.NodeProject({
  defaultReleaseBranch: "main",
  name: "demo",
  packageManager: javascript.NodePackageManager.PNPM,

  // deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
});
project.synth();
```

```console
$ npx projen --version
0.58.21
```

@agdimech Was there a particular Projen project type that this occurs with?

**Comment by agdimech** [comment]
> Similarly cannot reproduce with `npx projen@latest new node --package-manager=pnpm`
> 
> Creates
> 
> ```js
> const { javascript } = require("projen");
> const project = new javascript.NodeProject({
>   defaultReleaseBranch: "main",
>   name: "demo",
>   packageManager: javascript.NodePackageManager.PNPM,
> 
>   // deps: [],                /* Runtime dependencies of this module. */
>   // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
>   // devDeps: [],             /* Build dependencies for this module. */
>   // packageName: undefined,  /* The "name" in package.json. */
> });
> project.synth();
> ```
> 
> ```
> $ npx projen --version
> 0.58.21
> ```
> 
> @agdimech Was there a particular Projen project type that this occurs with?

Yes it is on a custom project type I have built. The command is:

`npx projen new --from aws-prototyping-sdk nx-monorepo --package-manager=pnpm`

**Comment by agdimech** [comment]
This occurs for external project types.

The issue appears to be here: https://github.com/projen/projen/blob/main/src/projects.ts#L126

As you can see, no imports are being prepended to the generated code which runs in the vm. The generated code should prepend the imports returned from renderJavascriptOptions and inject require (not global) into the vm context so they can be accessed from the VM.

**Comment by agdimech** [comment]
Any update on this one?

**Comment by mrgrain** [comment]
I can confirm this works now:

```console
npx projen@0.67.48 new --from aws-prototyping-sdk nx-monorepo --package-manager=pnpm
```
