### ISSUE TITLE
How to install it? 

### ISSUE THREAD

**Issue by fbrodrigorezino** [projen/projen#1936]
I saw a lot of documentation etc... how to contribute, but I didn't find a simple place telling how to install it.

Where is that?

**Comment by pflorek** [comment]
Most the time I use typescript and the projen awscdk flavours. I don't install it, [npx](https://docs.npmjs.com/cli/v7/commands/npx) does it.

```shell
npx projen
# or
npx projen@latest
```

And for developing projen itself
```shell
yarn && yarn build
```
