### ISSUE TITLE
Feature Request: During cleanup, ignore contents of `.npmignore` as well as `.gitignore` and `node_modules/`

### ISSUE THREAD

**Issue by pszabop** [projen/projen#194]
During cleanup, the code removes any files with the magic projen tags unless they are in `.gitignore` or `node_modules/`

This means if for any reason there are files with `PROJEN_MARKER` in sub directories, they get wiped out.  This seems rather dangerous to do to a global namespace as well as not allowing a sub directory to have its own projen file (for e.g. doing an integration test for a CDK project, see related issue).

If NPM is going to ignore the files, then projen probably should as well.

It might be cleaner to just add a `projenIgnoreFiles` option and avoid this kind of dependency on npm and git.

Related change:  https://github.com/eladb/projen/pull/70

code:  https://github.com/eladb/projen/blob/master/src/cleanup.ts

**Comment by pszabop** [comment]
There's another bug here (can file issue separately), .gitignore and .npmignore entries with lines that begin with `/` are not handled correctly.   the correspond files and root directories don't get ignored.

**Comment by hoegertn** [comment]
What is your use case to have a nested projen file instead of putting it in the root one?

**Comment by pszabop** [comment]
@hoegertn  

> what is your use case

It can take a CDK App Module to test a CDK Construct module

https://github.com/eladb/projen/issues/178

**Comment by pgollucci** [comment]
> @hoegertn
> 
> > what is your use case
> 
> It can take a CDK App Module to test a CDK Construct module
> 
> #178

I assume you mean like running lamba's or custom resources?

**Comment by pszabop** [comment]
> I assume you mean like running lamba's or custom resources?

Sure, or just doing synthesis an actual deployment to test for CFT deploy-time errors, which still happen quite a bit.

It looks like you are working on subprojects, which sound about what I want (though I haven't looked into detail)
