### ISSUE TITLE
`release` skipping version bump

### ISSUE THREAD

**Issue by Butterneck** [projen/projen#1971]
Hi,

I'm trying to create a new release for my project, but version bump is skipped and version remains to 0.0.0

```
$ yarn release 
yarn run v1.22.17
$ npx projen release
👾 release | rm -fr dist
👾 release » bump | condition: ! git log --oneline -1 | grep -q "chore(release):"
👾 release » bump | /nix/store/gv3jkcjmibv84nv6kcs0g8rh8dys1v98-nodejs-14.18.3/bin/node /Users/cdk-constructs/node_modules/projen/lib/release/bump-version.task.js
👾 Update /Users/cdk-constructs/package.json to latest resolved version: 0.0.0
👾 Tags listed on current commit:
✖ skip version bump on first release
✔ created /Users/cdk-constructs/dist/changelog.md
✔ outputting changes to /Users/cdk-constructs/dist/changelog.md
👾 release » build » default | node .projenrc.js
👾 release » build » compile | jsii --silence-warnings=reserved-word
```

What am I missing?

**Comment by marciocadev** [comment]
Version automatically bump when merge your PR to main

If you want to change from experimental to stable you need to set majorVersion on projenrc file

**Comment by Butterneck** [comment]
> Version automatically bump when merge your PR to main
I'm not using github workflow.

I expect though, that running `yarn release` bumps the version, am I wrong?

**Comment by mrgrain** [comment]
> I expect though, that running yarn release bumps the version, am I wrong?
That's correct. Except there is an exemption for the first release. Which is what you've encountered.

I'm not quite sure at the moment what the exact intention behind this exemption is. I suspect it has to do with already published libraries.

However, clearly the UX for you isn't great. Did you basically do the following steps:

-  npx projen new PROJECT-TYPE
- _make some change_
- git commit && git push
- yarn release
 

I'm trying to understand the flow here.

**Comment by Butterneck** [comment]
> > I expect though, that running yarn release bumps the version, am I wrong?
> 
> That's correct. Except there is an exemption for the first release. Which is what you've encountered. I'm not quite sure at the moment what the exact intention behind this exemption is. I suspect it has to do with already published libraries.
> 
> However, clearly the UX for you isn't great. Did you basically do the following steps:
> 
> * npx projen new PROJECT-TYPE
> * _make some change_
> * git commit && git push
> * yarn release
> 
> I'm trying to understand the flow here.

Yes, that's exactly what I did

**Comment by mrgrain** [comment]
@Butterneck Did you change the release trigger to manual? Because without that, projen expects to be released via a GitHub Action and the local `yarn release` command doesn't do what you might expect it would.

Regarding the "first release" thing. This is coming from [standard-version](https://github.com/conventional-changelog/standard-version#first-release) and I do think it makes sense to have it.

How it's currently setup, your first push (or manual release) would publish an initial version `0.0.0`. Every following release will then use conventional-changelog rules to determine the next version number. If you don't want to start with `0.0.0`, you should be able to set  always set any `version` in your `package.json`.

**Comment by Butterneck** [comment]
@mrgrain can you please explain what's the difference between running `yarn release` locally and on GitHub Action? It seems that the script is the same and I can't see anything that could modify it's behavior on GH Action.

> If you don't want to start with 0.0.0, you should be able to set always set any version in your package.json.

I don't think so, projen re-synthesize the package.json every time I run it, overriding any manual edit.

**Comment by mrgrain** [comment]
@Butterneck You can see the difference here https://github.com/mrgrain/projen-cdk-construct-test/compare/5023db9...89d5d78 (make sure to load the diff for all generated files).

But basically the release GitHub Actions workflow will do more than just run `yarn release` and likewise, if you change the `releaseTrigger` to `ReleaseTrigger.manual()`, the local command gets somer extra functionality added.

**Comment by mrgrain** [comment]
> I don't think so, projen re-synthesize the package.json every time I run it, overriding any manual edit.
Okay, then the other is to tag the current commit with the version you want to start with `git tag v0.3.7 -m"initial"`, that should also get you started with a different baseline.


I'm still thinking on how we can improve the docs here. Maybe `yarn release` should not exist at all if the releaseTrigger is GitHub Actions...

**Comment by mrgrain** [comment]
@Butterneck Documentation improvements aside, are you all good now are still having issues with the versioning?

**Comment by mrgrain** [comment]
Closing for now with the updated docs. There is a good argument to have `package.json` track the current version, but it comes with implication. We should discuss this in a separate issue.
