### ISSUE TITLE
enable building project from private github repository

### ISSUE THREAD

**Issue by AljoSt** [projen/projen#1984]
Hello,

First, I really like the idea behind projen :) But it seems like it's lacking the feature of creating a project based on a github template (?).  I would like to have the option to call `projen new --from <private_github_repo_url>` to start a new project. I couldn't find anything about this in the documentation and I'm a bit confused because it seems to me that this would be a very typical use-case.

Does this feature exist? Or is there a reason why it doesn't?

**Comment by andrestone** [comment]
https://github.com/projen/projen/issues/18#issuecomment-659260537

**Comment by AljoSt** [comment]
Thanks for that. From that, I don't really understand how to solve my problem though.
So in my case, I want to create python projects focused on machine learning. The only project type that is somewhat related is obviously a projen `python-project`. But this is very far from what I need. Should I now create a PR where I introduce a `python-ml-project` type to the projen ecosystem? Given that the layout and content of this type is very specific, surely it would make sense to have a very specific project-type?

**Comment by mrgrain** [comment]
@AljoSt Have you tried running `projen new --from <private_github_repo_url>`?

`--from` takes an npm spec and pretty much just passed it on to run `npm install --save-dev -f --no-package-lock <spec>`.

In theory this should work with a GitHub repo, private and public. Authentication might need sorting out.

--- 

A bigger issue will be that your repo needs to either contain the transpiled `.js` files or have an appropriate `postinstall` script setup.

**Comment by mrgrain** [comment]
@AljoSt Did this answer your question?

**Comment by mrgrain** [comment]
@AljoSt  I'm going to close this issue, assuming you've solved the problem. The feature should already be supported by projen.
