### ISSUE TITLE
Unable to create empty sample directory

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1990]
I was trying to create an empty sample directory for a project (just a directory whose contents aren't managed by projen) but found this did nothing:

```ts
new SampleDir(project, "foo", { files: {} });
```

This would be a bit odd if the directory is meant to be versioned controlled, because you cannot add empty directories to git, but in my scenario I had a build script / test that expected the directory to exist, and it was just for build storing artifacts (so I had it gitignored). Maybe the line above should create a directory instead of being a no-op?

Alternatively, maybe this is silly and we should just throw an error if `files` is empty.

**Comment by lazinessdevs** [comment]
I think the SampleDir class was named wrong.

You pass the destination folder and as options the file list and a source folder.

Basically this class should be named as CopyFiles or CopyFilesFrom

**Comment by mrgrain** [comment]
Breaking changes are fine, we are still in pre-release times.

Saying that, would it not make sense to keep `SampleDir` around? I like the semantic name of it and as far I understand `SampleDir` creates those files only once. The empty directory thing is seems like a missed implementation detail to me. The easiest fix might be to call `fs.mkdirpSync` on the target dir...

I'd expect `CopyFiles` to always do that. Tbh I almost expected us to already have Filesystem helpers... 🤔
