### ISSUE TITLE
Bumping to Projen ^0.60.0 causes Jest Test failure for Python Projects

### ISSUE THREAD

**Issue by agdimech** [projen/projen#2017]
I have a Jest Test that creates a new Python Project as follows:

```ts
import { PythonProject } from "projen/lib/python";
...

const pyProject = new PythonProject({
      outdir: "packages/test",
      authorEmail: "test@test.com",
      authorName: "test",
      moduleName: "py_subproject",
      name: "py-subproject",
      version: "0.0.0",
    });
```

When I run this test I get the following error:

```
TypeError: Class extends value undefined is not a constructor or null

      at Object.<anonymous> (../../node_modules/projen/src/awscdk/awscdk-app-py.ts:41:38)
      at Object.<anonymous> (../../node_modules/projen/src/awscdk/index.ts:3:1)
```

What is very strange is that `projen/src/**` does not exist in node_modules and nowhere in my code am I creating an `awscdk-app-py`.

This occurs when bumping versions to ^0.60.0 and is caused by this commit: https://github.com/projen/projen/commit/e5cc5145861b02ce9531e86215d826f60970909c

Strangely, if I change the import to a `require` the error is no longer thrown.

@marciocadev - Any idea what could be causing this? The only thing I can think of is there was an import change here: https://github.com/projen/projen/commit/e5cc5145861b02ce9531e86215d826f60970909c#diff-f937db55ea61185db729e05de728cb8d1c6f778873317aa2ae35945b24b812e2L10

**Comment by marciocadev** [comment]
Hi @agdimech

Unfortunately this seems to be some circular reference, I had this problem when I was creating the cdk8s-app-py and I managed to solve it by importing this way.

Please let me know if this solves your problem as I couldn't do it any other way.

Please 
```ts
import { python} from "projen/lib";
...

const pyProject = new python.PythonProject({
      outdir: "packages/test",
      authorEmail: "test@test.com",
      authorName: "test",
      moduleName: "py_subproject",
      name: "py-subproject",
      version: "0.0.0",
    });
```

**Comment by mrgrain** [comment]
Could either of you check if reverting the imports in `awscdk-app-py.ts` from
```ts
import { PythonProject, PythonProjectOptions, Pytest } from "../python";
```
back to
```ts
import { Pytest } from "../python/pytest";
import { PythonProject, PythonProjectOptions } from "../python/python-project";
```
would help? (And similar for the other file in that PR e.g. `cdk8s-app-py.ts`)

**Comment by marciocadev** [comment]
Apparently the problem was in the import section of `cdk8s-app-py`

So I change `cdk8s-app-py` from this
```ts
import { Component } from "../component";
import { DependencyType } from "../dependencies";
import { PythonProject, PythonProjectOptions } from "../python";
import { SampleFile } from "../sample-file";
import { YamlFile } from "../yaml";
import { Cdk8sDeps, Cdk8sDepsCommonOptions } from "./cdk8s-deps";
import { Cdk8sDepsPy } from "./cdk8s-deps-py";
```
to this
```ts
import { Component, DependencyType, YamlFile, SampleFile } from "..";
import { PythonProject, PythonProjectOptions } from "../python/python-project";
import { Cdk8sDeps, Cdk8sDepsCommonOptions } from "./cdk8s-deps";
import { Cdk8sDepsPy } from "./cdk8s-deps-py";
```

Now it works, I change the `awscdk-app-py` class and some tests to reflect the change

I'm open a new PR now

**Comment by mrgrain** [comment]
@marciocadev I'm concerned we didn't catch this in the PR. Are we missing some tests here?

**Comment by marciocadev** [comment]
I think to catch this error we have to make tests with imports from folder and from specific files

I can include more tests like this and I think all projects who extends from base languages projects need this kind of tests

**Comment by agdimech** [comment]
> @marciocadev I'm concerned we didn't catch this in the original PR. Are we missing some tests here?

We can potentially create an e2e tests package which runs as part of CI and deploys the to be released version of projen to an in memory verdaccio. We can then synth projects for core types and verify everything works as it should?
