### ISSUE TITLE
Webpack bundling for TypeScriptApp

### ISSUE THREAD

**Issue by hoegertn** [projen/projen#202]
I would love to have webpack support for a TypeScript application.

It would configure everything necessary to run webpack to bundle your project into one folder or zip file.

There are so many blueprints out there that an opinionated and generated solution would be great.

Any ideas?

**Comment by eladb** [comment]
What's the use case? Is it to build web apps? Does it make more sense to include this in react/nextjs projects?

**Comment by hoegertn** [comment]
Webpack is an often-used tool to bundle Lambda functions when not using the NodeJsFunction construct.

**Comment by pgollucci** [comment]
over parcel ?

**Comment by hoegertn** [comment]
I think there are currently parcel, webpack, and esbuild. No matter which one will be used in CDK I think it would be great to support them as project types/options for developers.
