### ISSUE TITLE
Projen removes trailing newline from `package.json` while npm adds it back

### ISSUE THREAD

**Issue by moltar** [projen/projen#2076]
There is a conflict with with projen and npm@8, where projen prefers no trailing new lines in the `package.json` file, but npm prefers having one, so there is sometimes a git diff for no reason.

A good example is running `projen --no-post` which will write the `package.json` file, but not run the `npm install` as a post job. You'll see that the `package.json` is not in a dirty state.

**Comment by mrgrain** [comment]
#2080 has an excellent write-up what needs to be fixed.

**Comment by moltar** [comment]
@dj-rabel Did such a great job, that I think his issue should remain open and this should be closed 😁

**Comment by dj-rabel** [comment]
Awesome, I'm glad that it's helpful!
Ah and actually I searched for open issues about this topic. But wasn't able to find this one, as of the typo in "new line". I think we should fix that, to allow other to find this one, too 😅

**Comment by mrgrain** [comment]
Thank you both! I followed the rule to keep the first issue. Hope you understand. 😃

**Comment by moltar** [comment]
There is another layer of annoyance discovered.

Because there is a check for the dirty `package.json` file to see if we need to run `npm install`, this new line forces projen to run install on _EVERY_ invocation of `projen default`. Which also means `projen build`.

With just 3 sub-projects in CI, our build times are  > 5 minutes.

Because projen will run `npm install` 8 times!

It will run `npm install` and `npm install --dev` (or whatever the flag is) in the root, and then in every sub package.

**Comment by moltar** [comment]
https://github.com/projen/projen/blob/b578083dd3e362a19dc77f6c234d9b5b6fb5326b/src/javascript/node-package.ts#L780-L787

**Comment by mrgrain** [comment]
@dj-rabel @moltar Just released a fix for this. LMK if this solves it for you.

**Comment by moltar** [comment]
🎉 Fixes this for sure! Thanks, @mrgrain!!

**Comment by dj-rabel** [comment]
> @dj-rabel @moltar I've just released a fix for this. LMK if this solves it for you.

Thanks for notifying ❤️ As for now, seems like it fixed the issue for me as well. Thanks for fixing :D
