### ISSUE TITLE
package.json newline option incorrectly set to false

### ISSUE THREAD

**Issue by dj-rabel** [projen/projen#2080]
Hello Guys,

I've found the comment on this line to actually not be true.
https://github.com/projen/projen/blob/a3c0556b69b29456ce61517ed534824bb67100b4/src/javascript/node-package.ts#L520

Here are the behaviors for npm and yarn in the versions I have. Yarn is latest for v1 and v3 branch. Npm slightly outdated with 8.18 to be the newest.

npm 8.5.0 -> "npm install" does not modify package.json at all
npm 8.5.0 -> "npm install/add \<package>" results in added newline at the end of package.json

yarn 1.22.18 -> "yarn install" does not modify package.json at all
yarn 1.22.18 -> "yarn add \<package>" results in added newline at the end of package.json

yarn 3.2.3 -> "yarn install" results in added newline at the end of package.json
yarn 3.2.3 -> "yarn add \<package>" results in added newline at the end of package.json

Sidenote:
I've tried using projen with yarn 3 (slightly modified the NodePackage as it isnt working with yarn 3 cause of --check-files) and here we're running in some kind of an infinite loop now as yarn 3 adds the newline on every run of yarn install ... Very annoying.

There is an issue on yarnpkg's github page, which notes that adding the newline at the end of the package.json file is the correct behavior of npm and yarn.
https://github.com/yarnpkg/yarn/issues/2675#issuecomment-303202323

Feels like this info about newline behavior of npm and yarn is out of date 🙈 

**EDIT:**
Just quickly wanted to mention a line which is connected to the false setting for the newline option and would need to be changed as well:
https://github.com/projen/projen/blob/a3c0556b69b29456ce61517ed534824bb67100b4/src/javascript/node-package.ts#L1246

**Comment by mrgrain** [comment]
Thanks for the detailed report. That's super helpful.

I think this is the same as #2076
Closing as duplicate.
