### ISSUE TITLE
How to disable package installation?

### ISSUE THREAD

**Issue by kamarol** [projen/projen#2087]
Hi,

Whenever i run "npx projen", it also installs the packages and creates `node_modules` folder. Since I'm using `rush` to manage my packages, this will interfere with the `node_modules` generated by rush. 

Is there a way to not run `yarn/npm/etc install` whenever we run `npx projen`?

**Comment by mrgrain** [comment]
You can try running `projen --no-post` but it also disables other stuff.

**Comment by kamarol** [comment]
works for me :) thanks
