### ISSUE TITLE
Auto suggest "Did mean ..." prevents external project use

### ISSUE THREAD

**Issue by zmully** [projen/projen#2093]
I have an external project that exports a project type "scala", but when I attempt to use this external project, there is autosuggestion (from yargs? maybe, I'm not quite sure where it's coming from) that prevents me from doing so. I've put up a demo repo of this at https://github.com/zmully/scala-test/

```
zmully@ubu2 /tmp/tmp.bQVo3NPiDa $ cd $(mktemp -d) && npx projen new scala --packageManager npm --from file:/home/zmully/gitwork/scala-test/
Did you mean java?
zmully@ubu2 /tmp/tmp.a6U3rrYc8S $ 
```

This external project type does work if I change the name of the type to something sufficiently different, like `zaiscala`.

Also, I'm not sure what `@pjid` is, or how it should be generated and maintained, but it's confusing that I have to both match the export and the value of the `@pjid` (in a comment) to get the project type to be found by `projen`. Is there something I'm missing about external types? 

I'm running projen 0.61.45 and npm 8.15.0 on node v16.16.0

**Comment by marciocadev** [comment]
If you publish this project to npmjs you can create a project with

npx projen new --from scala

**Comment by marciocadev** [comment]
`@pjid` it's used to create reference to projen documentation, you don't need this

Try to create a project this way

```ts
npx projen new --from file:/home/zmully/gitwork/scala-test
```

**Comment by mrgrain** [comment]
I like the idea of FQNs....
