### ISSUE TITLE
Example for projen release of AwsCdkConstructLibrary with CodeCommit, CodePipeline and CodeArtifact

### ISSUE THREAD

**Issue by joa44741** [projen/projen#2118]
Hey guys, 

first of all a big thank you for this amazing project! 
During the last weeks I'm browsing through lots of content regarding AWS CDK (e.g. CDK Day Youtube Videos) and now I'm starting to realize the power of projen.

I want to create an AwsCdkConstructLibrary for our company for internal use, so I've switched to a manual release because I want to use CodeCommit + CodePipeline instead of GitHub and I want to use CodeArtifact and an internal Nexus3 repository for the released packages.
Therefore I use these settings now: 
`github: false,`
`releaseTrigger: ReleaseTrigger.manual(),`

Unfortunately I was not able to find a documentation including a buildspec.yml that explains how "npx projen build", "npx projen release" and so on works inside a CodePipeline/CodeBuild project. 
Could you add this to the documentation maybe? 

Best wishes
Johnny

**Comment by mrgrain** [comment]
Hi Johnny,

Docs for [CodeArtifact](https://projen.io/publisher.html#publishing-to-aws-codeartifact) can be found here. I'm afraid there is not built-in support for CodeCommit or CodePipeline yet.

I don't see why CodeCommit would not work or work any different (it's just git after all).
- ❓  What kind of docs would you expect to see for using a different source version control provider?

CodePipeline will be more work. At the moment you will have to re-create the workflows yourself. Unfortunately there is also no support to author CodePipelines in projen, however I'd recommend you use AWS CDK for that anyway.

--- 
Manual releasing lacks certain bits of documentation. The process is broadly as follows:

- `projen release`
- Find release artifacts in `dist`
- Manually use the established release mechanism to publish the artifact for each language:
  - E.g. `npm publish dist/js/package.tar.gz` for npm
  - or [jsii-packmak](https://github.com/aws/jsii/tree/main/packages/jsii-pacmak) as one tool for all languages

**Comment by joa44741** [comment]
Thanks for the fast response.

You're totally right, CodeCommit is not causing any problem here, I just wanted to mention it for the sake of completeness. 

To be honest, I was just not sure how to start. 
Now I tried to rebuild the workflow that is generated automatically when using GitHub.
It's working but I'm feeling that it's somehow a "dirty" solution 😄 
Do you think this is the way to go?

Additional information by the way:
You wrote that you recommend using AWS CDK. 
I did and I'm using the package [aws-delivlib](https://github.com/cdklabs/aws-delivlib) 

Now I ended up with a buildspec for the build stage ([codebuild-git-wrapper](https://itnext.io/how-to-access-git-metadata-in-codebuild-when-using-codepipeline-codecommit-ceacf2c5c1dc) is used for git support in CodeBuild):
```
buildSpec: codebuild.BuildSpec.fromObject({
        version: "0.2",
        env: {
          "git-credential-helper": "yes",
          CI: "true",
        },
        phases: {
          build: {
            commands: [
              "scripts/codebuild-git-wrapper.sh ${REPO_URL} ${REPO_BRANCH}",
              "message=$(git log -1 --pretty=%B)",
              'echo "last commit message: $message"',
              [
                'if expr "${message}" : "^chore(release):.*" >/dev/null; ',
                'then',
                'echo "only Changelog --> stop here";',
                "aws codebuild stop-build --id ${CODEBUILD_BUILD_ID};",
                'fi',
              ].join(' '),
              "yarn install --check-files",
              'git config --global user.email "custom-aws-cdk-lib-pipeline@amazonaws.com"',
              'git config --global user.name "Custom Aws Cdk Lib Pipeline"',
              "npx projen build",
              "git add .",
              "changes=$(git diff --staged --patch)",
              [
                'if [ "$changes" = "" ];',
                'then',
                "npx projen release;",
                'else',
                'echo "changes have to be committed and pushed";',
                'git commit -s -m "chore: self mutation";',
                'git push origin main',
                "aws codebuild stop-build --id ${CODEBUILD_BUILD_ID};",
                'fi',
              ].join(' '),
            ],
          },
        },
        artifacts: {
          files: ["**/*"],
          "base-directory": "dist",
        },
      }),
    }
```

My buildspec for publishing the releases looks like:
```
buildSpec: codebuild.BuildSpec.fromObject({
        version: "0.2",
        phases: {
          install: {
            commands: [
              "pip install --upgrade pip",
              "pip install awscli --upgrade --user",
            ]
          },
          build: {
            commands: [
              "export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain mydomain --domain-owner 377992144700 --query authorizationToken --output text`",
              "export TWINE_USERNAME=aws",
              "export TWINE_PASSWORD=$CODEARTIFACT_TOKEN",
              "export TWINE_REPOSITORY_URL=`aws codeartifact get-repository-endpoint --domain mydomain --domain-owner 377992144700 --repository custom-pip --format pypi --query repositoryEndpoint --output text`",
              "npx -p publib publib-pypi python",
              "export NPM_TOKEN=$CODEARTIFACT_TOKEN",
              'export NPM_DIST_TAG="latest"',
              "repoendpoint=`aws codeartifact get-repository-endpoint --domain mydomain --domain-owner 377992144700 --repository custom-npm --format npm --query repositoryEndpoint --output text`",
              "export NPM_REGISTRY=${repoendpoint#https://}", // remove https://
              "npx -p publib publib-npm js",
            ],
          },
        },
      })
```

**Comment by mrgrain** [comment]
Apologies for the late response. I think rebuilding the workflow is indeed the way to go at the moment. Workflows don't have a lot of abstraction at the moment so unfortunately I don't see any other way to achieve this.
