### ISSUE TITLE
getfacl not found in v0.63.0?

### ISSUE THREAD

**Issue by anh-rivergon** [projen/projen#2134]
In v0.63.0 (could have been any release made on Sep-30), a new step "Backup artifact permissions" was added to the github workflow build.xml and triggered this error for us. Anyone else seeing the same issue -"getfack not found" ?

Run cd dist && getfacl -R . > permissions-backup.acl
  cd dist && getfacl -R . > permissions-backup.acl
  shell: sh -e {0}
  env:
    CI: true
/__w/_temp/9[2](https://github.com/a-cdk/ngx-app-stack/actions/runs/3161689264/jobs/5147555465#step:10:2)dd0f[3](https://github.com/a-cdk/ngx-app-stack/actions/runs/3161689264/jobs/5147555465#step:10:3)0-d[4](https://github.com/a-cdk/ngx-app-stack/actions/runs/3161689264/jobs/5147555465#step:10:4)6f-4688-a246-[5](https://github.com/a-cdk/ngx-app-stack/actions/runs/3161689264/jobs/5147555465#step:10:5)dcbb7d5ac03.sh: 1: /__w/_temp/92dd0f30-d4[6](https://github.com/a-cdk/ngx-app-stack/actions/runs/3161689264/jobs/5147555465#step:10:7)f-4688-a246-5dcbb[7](https://github.com/a-cdk/ngx-app-stack/actions/runs/3161689264/jobs/5147555465#step:10:8)d5ac03.sh: getfacl: not found
Error: Process completed with exit code 127.

**Comment by mrgrain** [comment]
Yes that was released today. What os or image does the workflow run on?

**Comment by mrgrain** [comment]
In hindsight we should have made this an opt-in step.

**Comment by mrgrain** [comment]
Cc @jmalins

**Comment by anh-rivergon** [comment]
The release.xml says "runs-on: ubuntu-latest" -- I ran with "npx projen new awscdk-construct" went with the out of the box configuration.

**Comment by mrgrain** [comment]
Thanks for the info. That's certainly expected to work. 🤔

**Comment by jmalins** [comment]
It looks like the default configuration of the `awscdk-construct` runs using the `jsii/superchain:1-buster-slim-node14` container image. We will need to add the `acl` package to the superchain image build in the JSII project. That should fix the default case.

That being said, you're right, there should also be an opt-out for the cases where users bring their own images.

I can submit a superchain PR this weekend, as that should be a one liner, but may not be able to get to a parameterized fix until Monday.

**Comment by mrgrain** [comment]
Thanks @jmalins ✅

Or maybe we don't even need an opt out but just have the steps not failing the whole Pipeline (and display a warning of sorts). 🤔

**Comment by jmalins** [comment]
@mrgrain I had the same thought overnight. If the backup/restore steps were to become no-ops when the `getfacl` / `setfacl` tools are missing, with a suitable warning to explain the situation, that could be ideal.

Having the tools in `ubuntu-latest` and `jsii/superchain:*` means the only exposure to the no-op/warning will be projects using custom containers. That shouldn't be many users and they should already be on high alert for tooling issues.

Plus, any opt-out prop would need to be drilled pretty deeply into the `build` and `release` packages. It also becomes vestigial API when GH gets their act together and fixes the underlying issue.

**Comment by mrgrain** [comment]
I have a PR ready (see link) for the non failure. Not sure if that's the best way to do it, but certainly the easiest.

**Comment by anh-rivergon** [comment]
For now, this got me past it. Optional is a good idea though

  workflowBootstrapSteps: [
    {
      name: 'Install acl #1',
      run: 'sudo apt-get update -y',
    },
    {
      name: 'Install acl #2',
      run: 'sudo apt-get install -y acl',
    }
  ]

**Comment by mrgrain** [comment]
I can confirm this is fixed now
