### ISSUE TITLE
Task "release" failed when executing "git diff

### ISSUE THREAD

**Issue by anh-rivergon** [projen/projen#2140]
The error is from the release.xml for awscdk-construct project.

I have read #1440  however, there does not seem to be a resolution or a root cause. GitHub action fails with the following from time to time and then it would work again. I have not been able to figure out the cause. I do not make manual modifications to package.json 

 project.synth();
\ No newline at end of file
👾 Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /__w/ngx-app-stack/ngx-app-stack)
Error: Process completed with exit code 1.

**Comment by anh-rivergon** [comment]
It would seem that if I executed "npm run build" locally before pushing to git, then the GitHub Actions would execute and complete "Release" successfully.

**Comment by mrgrain** [comment]
Hi @anh-rivergon  Can you provide more details of the failure?

Release pipelines are supposed to fail if they mutate the build. We don't want to release any change that hasn't been through a review or PR etc. However that error message should be obvious and explain the situation. I wonder what is missing.

Your second comment seems to be aligned with this. Glad you've got it resolved.

**Comment by anh-rivergon** [comment]
Building locally before the git push to github seems to have solved in permanently and consistently.

Here is an old error message

Ran all test suites.
👾 release » build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js
👾 release » build » package | if [ ! -z ${CI} ]; then rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist; else npx projen package-all; fi
👾 release » unbump | /usr/bin/node /__w/cloudfront-s3-static-site-construct/cloudfront-s3-static-site-construct/node_modules/projen/lib/release/reset-version.task.js
👾 release | git diff --ignore-space-at-eol --exit-code
diff --git a/API.md b/API.md
index 38ee896..3a3e57d 100644
--- a/API.md
+++ b/API.md
@@ -2,39 +2,39 @@
 
 ## Constructs <a name="Constructs" id="Constructs"></a>
 
-### CloudfrontS3StaticSiteConstruct <a name="CloudfrontS3StaticSiteConstruct" id="@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct"></a>
+### CloudfrontS3StaticSiteConstruct <a name="CloudfrontS3StaticSiteConstruct" id="@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct"></a>
 
-#### Initializers <a name="Initializers" id="@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.Initializer"></a>
+#### Initializers <a name="Initializers" id="@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.Initializer"></a>
 
 ```typescript
-import { CloudfrontS3StaticSiteConstruct } from '@mycdk/cloudfront-s3-construct-static-site'
+import { CloudfrontS3StaticSiteConstruct } from '@mycdk/cloudfront-s3-static-site-construct'
 
 new CloudfrontS3StaticSiteConstruct(scope: Construct, id: string, props: CloudfrontS3StaticSiteConstructProps)
 ```
 
 | **Name** | **Type** | **Description** |
 | --- | --- | --- |
-| <code><a href="#@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.Initializer.parameter.scope">scope</a></code> | <code>constructs.Construct</code> | *No description.* |
-| <code><a href="#@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.Initializer.parameter.id">id</a></code> | <code>string</code> | *No description.* |
-| <code><a href="#@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.Initializer.parameter.props">props</a></code> | <code><a href="#@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstructProps">CloudfrontS3StaticSiteConstructProps</a></code> | *No description.* |
+| <code><a href="#@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.Initializer.parameter.scope">scope</a></code> | <code>constructs.Construct</code> | *No description.* |
+| <code><a href="#@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.Initializer.parameter.id">id</a></code> | <code>string</code> | *No description.* |
+| <code><a href="#@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.Initializer.parameter.props">props</a></code> | <code><a href="#@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstructProps">CloudfrontS3StaticSiteConstructProps</a></code> | *No description.* |
 
 ---
 
-##### `scope`<sup>Required</sup> <a name="scope" id="@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.Initializer.parameter.scope"></a>
+##### `scope`<sup>Required</sup> <a name="scope" id="@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.Initializer.parameter.scope"></a>
 
 - *Type:* constructs.Construct
 
 ---
 
-##### `id`<sup>Required</sup> <a name="id" id="@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.Initializer.parameter.id"></a>
+##### `id`<sup>Required</sup> <a name="id" id="@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.Initializer.parameter.id"></a>
 
 - *Type:* string
 
 ---
 
-##### `props`<sup>Required</sup> <a name="props" id="@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.Initializer.parameter.props"></a>
+##### `props`<sup>Required</sup> <a name="props" id="@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.Initializer.parameter.props"></a>
 
-- *Type:* <a href="#@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstructProps">CloudfrontS3StaticSiteConstructProps</a>
+- *Type:* <a href="#@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstructProps">CloudfrontS3StaticSiteConstructProps</a>
 
 ---
 
@@ -42,11 +42,11 @@ new CloudfrontS3StaticSiteConstruct(scope: Construct, id: string, props: CloudfrontS
 
 | **Name** | **Description** |
 | --- | --- |
-| <code><a href="#@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstruct.toString">toString</a></code> | Returns a string representation of this construct. |
+| <code><a href="#@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstruct.toString">toString</a></code> | Returns a string representation of this construct. |
 
 
-### CloudfrontS3StaticSiteConstructProps <a name="CloudfrontS3StaticSiteConstructProps" id="@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstructProps"></a>
+### CloudfrontS3StaticSiteConstructProps <a name="CloudfrontS3StaticSiteConstructProps" id="@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstructProps"></a>
 
-#### Initializer <a name="Initializer" id="@mycdk/cloudfront-s3-construct-static-site.CloudfrontS3StaticSiteConstructProps.Initializer"></a>
+#### Initializer <a name="Initializer" id="@mycdk/cloudfront-s3-static-site-construct.CloudfrontS3StaticSiteConstructProps.Initializer"></a>
 
 ```typescript
-import { CloudfrontS3StaticSiteConstructProps } from '@mycdk/cloudfront-s3-construct-static-site'
+import { CloudfrontS3StaticSiteConstructProps } from '@mycdk/cloudfront-s3-static-site-construct'
 
 const cloudfrontS3StaticSiteConstructProps: CloudfrontS3StaticSiteConstructProps = { ... }
 ```
diff --git a/package.json b/package.json
index 65b099d..abea301 100644
--- a/package.json
+++ b/package.json
@@ -1,8 +1,8 @@
 {
-  "name": "@mycdk/cloudfront-s3-construct-static-site",
+  "name": "@mycdk/cloudfront-s3-static-site-construct",
   "repository": {
     "type": "git",
-    "url": "https://github.com/mycdknotreal/static-site-cloudfront-s3-construct.git"
+    "url": "https://github.com/mycdknotreal/cloudfront-s3-static-site-construct.git"
   },
   "bin": {
     "sync-all.sh": "bin/sync-all.sh"
👾 Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /__w/cloudfront-s3-static-site-construct/cloudfront-s3-static-site-construct)
Error: Process completed with exit code 1.

**Comment by mrgrain** [comment]
Yes that's consistent with my expectation. release requires that the build step does not change anything in the project. The fix is to run build manually and commit and push any changes.

Closing.
