### ISSUE TITLE
release fails at "git diff --ignore-space-at-eol --exit-code"

### ISSUE THREAD

**Issue by yanu23** [projen/projen#2152]
My release fails at

`Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code"`

Version is on 0.0.0 in package.json.
I'm using shared runners on gitlab and following container jsii/superchain:1-buster-slim-node16

Anyone has an idea, what I could do?

**Comment by mrgrain** [comment]
Usually this happens when the previous `build` step produced some changes that have not been committed yet.

Try to run `projen build` locally and commit any changes.

**Comment by yanu23** [comment]
Same issue after local build.

**Comment by mrgrain** [comment]
Can you share any more details? There should be output from the `git diff` command showing what exactly has changed.

**Comment by mrgrain** [comment]
I've also seen this when my builds aren't predictable. Mostly with bundling and checking in asset hashes, but I can imagine other situations.

**Comment by yanu23** [comment]
Locally git diff doesn't show any output and the pipeline does not show anything more than the error.

**Comment by mrgrain** [comment]
@yanu23 Did you manage to resolve this? What was the issue in the end?

**Comment by pchaganti** [comment]
Getting the same issue even after running a local build. Any one have any pointers?

thanks!
