### ISSUE TITLE
Missing version number support when adding new packages

### ISSUE THREAD

**Issue by abelmokadem** [projen/projen#216]
Just started using this project and I'm really surprised at what it can do. Just wanted to track an issue here.

Webstorm has a functionality that gets the latest version from npm and prompts you with the latest version in the editor for autocomplete. It would be nice if we can do the same for the projen file. 

![Screenshot 2020-10-21 at 13 40 56](https://user-images.githubusercontent.com/9717944/96715236-91b3aa80-13a3-11eb-94be-5f89d5712860.png)

I can imagine this could go in a separate webstorm plugin project perhaps.

**Comment by eladb** [comment]
The `dependencies`, `devDependencies` and other `xxxDependencies` are going to be deprecated in favor of `deps`, `devDeps` and `xxxDeps`.

**Comment by pgollucci** [comment]
I feel like this would be a vscode plugin not a projen component but maybe I'm confused?

**Comment by eladb** [comment]
We now discourage specifying version numbers in projenrc files and letting package managers handle them, so this is less relevant I believe.
