### ISSUE TITLE
Support skipping releases

### ISSUE THREAD

**Issue by ansgarm** [projen/projen#2179]
Hey 👋

We implemented a feature to skip releases for our CDKTF pre-built provider bindings if neither the underlying Terraform provider version nor the CDKTF version had been changed. This is mainly driven by the fact that releasing on every dependency update that was merged to `main` causes us to [run into limits in Registries such as PyPI](https://github.com/hashicorp/terraform-cdk/issues/2169).

However, our current approach uses some pretty ugly hacks and workarounds and I'd like to add proper support to Projen instead or at least properly expose options that enable us to set / override the required options.

We're currently doing this ([source](https://github.com/hashicorp/cdktf-provider-project/blob/ddc68e0a30396f5fb19fe9cca32759e422ec47bb/src/index.ts#L190-L206)):
```ts
    (this.tasks.tryFind("release")!.condition as unknown as any) =
      "node ./scripts/should-release.js";
    const releaseJobSteps: any[] = (
      this.github?.tryFindWorkflow("release") as any
    ).jobs.release.steps;
    const gitRemoteJob = releaseJobSteps.find((it) => it.id === "git_remote");
    assert(
      gitRemoteJob.run ===
        'echo ::set-output name=latest_commit::"$(git ls-remote origin -h ${{ github.ref }} | cut -f1)"',
      "git_remote step in release workflow did not match expected string, please check if the workaround still works!"
    );
    const previousCommand = gitRemoteJob.run;
    const cancelCommand =
      'echo ::set-output name=latest_commit::"release_cancelled"'; // this cancels the release via a non-matching SHA;
    gitRemoteJob.run = `node ./scripts/should-release.js && ${previousCommand} || ${cancelCommand}`;
    gitRemoteJob.name += " or cancel via faking a SHA if release was cancelled";
```

This basically consists of two parts:
1) Adding a `condition` to the `release` task to be able to skip building and bundling a release
2) Overriding the "check for new commits" Github workflow step in a way that it also aborts all further steps/jobs if a release was skipped

Part 2 was required because adding `condition` to the release did not cause the workflow (i.e. further workflow steps) to be cancelled because there seems no way for the workflow to know that it should be cancelled. This however, might be by design and I'm just misusing `condition` for something it was not designed to do.

Before I put up a PR, I'd need some guidance around the way you'd like to approach such a feature (I might be looking at this from a completely wrong angle).
My current idea would be the following:
1) Add some kind of option for a `skipRelease` task/script/executable (that works like `condition` on tasks)
2) If that option is set, add a pre-build step to the release Github Workflow which runs this step and records its exit code
3) If that option is set, add an `if` config to all following workflow steps & jobs to skip them if the release should be skipped.

What do y'all think about this? Would you propose a different approach? Do you think skipping a release is a worthwhile feature at all?

**Comment by mrgrain** [comment]
I love this idea, and found myself in need for something like this as well! ❤️ 

--- 

Regarding the User Experience, I was thinking `skipRelease` would be an array of commit scopes. e.g. `['chore', 'ci', 'docs']`   that would not be considered to be released. Obviously a generic "task/script/executable" would be more flexible, however getting the interface right might be tricky.

May I asked what your `should-release.js` currently does exactly?

---

Re GitHub Actions implementation, I think you've described the usual way to go. There might be a more clever way combining a separate job, `needs` and `if`, but you know... bikeshedding.

**Comment by ansgarm** [comment]
Ignoring certain commit scopes sounds like a good idea to implement that feature 👍

---

The `should-release.js` script ([source](https://github.com/hashicorp/cdktf-provider-project/blob/ddc68e0a30396f5fb19fe9cca32759e422ec47bb/src/scripts/should-release.ts), [rendered example](https://github.com/cdktf/cdktf-provider-null/blob/903b806b40715eea45ad64457c4508a85c37e33a/scripts/should-release.js)) currently reads the `package.json` of the last released version and checks whether the peer dependency on `cdktf` or the underlying Terraform provider version changed since then, if neither has happened, we skip that release.

But both of those conditions could (and probably already are) also be reflected in commit scopes. Ignoring certain commit scopes also allows us to force a release by creating a commit (e.g. using the `fix` scope) which our current workaround still lacks 😅

---

Do you have any pointers for me for where to start? I vaguely remember reading something about projen generating changelogs based on commits somewhere? It feels like that code might be related to what I'd be going for here. Both features might be using `conventional-commits` to parse the git history for example.

**Comment by mrgrain** [comment]
Excluding certain scopes from triggering an action is a common feature request in the conventional commits world, but I don't think the tools we use implement it. We use `standard-version` for bumping and `conventional-changelog` to generate the changelog. I don't think either of them support skipping scopes.

--- 

Implementation wise, I would probably start with `bump-version.ts` and change it to throw if no relevant changes are available. That way the feature will also support custom release implementations. Going from there, you'd then need to fix the GH release workflow to somehow stop or cancel itself or succeed with a warning (it shouldn't fail though), and obviously not attempting to actually release.

**Comment by ansgarm** [comment]
Hi @mrgrain 👋 Thanks for the guidance!

I started a draft in #2188 that uses the same tools as `conventional-commits` does. However, I'm having some trouble with JSII generating the `tsconfig.json` and requiring the `esModuleInterop` flag to be set for the current imports to work. I tried `require` calls but it seems that the current linter does not like those 😄 Do you happen to have an idea here?

My next step (after fixing the imports somehow) would be to catch this error in `bump-version.task.ts` and exit the process with a certain exit code which I could detect in the Github Action Workflow to have a way to differentiate an actual error from a "skip this release, but don't fail it" – Or do you have a better idea to pass back that kind of data from the `release` task?

**Comment by mrgrain** [comment]
@ansgarm I've pushed a fix **to your branch** to disable `esModuleInterop` in the `tsconfig.dev.json`. Jsii doesn't allow it so, we should be consistent here. It seems to pass your test now. 🎉

**Comment by mrgrain** [comment]
> My next step (after fixing the imports somehow) would be to catch this error in bump-version.task.ts and exit the process with a certain exit code which I could detect in the Github Action Workflow to have a way to differentiate an actual error from a "skip this release, but don't fail it" – Or do you have a better idea to pass back that kind of data from the release task?

Hmm. I supposed we could introduce a new task `bump:check` that is run just before bump. Locally it would fail the bump (and release) tasks. In CI we would run `bump:check` in a special workflow job/step. It would be doin the check twice, but that doesn't feel like a huge problem to me. Thoughts?
