### ISSUE TITLE
What to do if a dependency doesn't use semantic versioning correctly?

### ISSUE THREAD

**Issue by volkanunsal** [projen/projen#2220]
Hi. I depend on a package that uses non-standard semantic versioning for release candidate and alpha releases and semver package cannot parse them. Example:

```
2.0.0a1
2.0.0rc3
```

I'm stuck because the package I need to depend on isn't accepted by Python project, and I cannot override it.

**Comment by mrgrain** [comment]
Would an escape hatch work?
https://projen.io/escape-hatches.html

**Comment by volkanunsal** [comment]
I get this error:
```
Error: found file requirements.txt but it is not a ObjectFile. got: RequirementsFile
```

**Comment by volkanunsal** [comment]
Also tried this, but it doesn't work. Components must be synthesized after projects.

```
public postSynthesize(): void {
    const reqs = this.tryFindFile('requirements.txt');

    if (reqs) {
      const fp = this.outdir + '/' + reqs.path;
      const text = readFileSync(fp, 'utf-8').replace('1.18.0', '2.0.0rc3');
      console.log('foo: ', text);
      writeFileSync(reqs.path, text);
    }
  }
```

**Comment by volkanunsal** [comment]
This version works, but it's hacky. I'll close this issue for now. Might be a good idea to `addOverride` as an option to `RequirementsFile` component.

```ts
public postSynthesize(): void {
    const reqs = this.tryFindFile('requirements.txt');

    if (reqs) {
      const fp = this.outdir + '/' + reqs.path;
      const text = readFileSync(fp, 'utf-8').replace('1.18.0', '2.0.0rc3');
      execSync(`chmod 777 ${fp}`);
      writeFileSync(fp, text);
      execSync(`chmod 644 ${fp}`);
    }
  }
```
