### ISSUE TITLE
Add Task method to update a task

### ISSUE THREAD

**Issue by philipmw** [projen/projen#2243]
Sometimes a project wants to update the definition an existing task. This existing task is perhaps defined by a parent project class, so we don't have control over its `.addTask()` arguments.

To update a task today, we `.removeTask()` followed by `.addTask()` with a different definition. This works when the task is a leaf, but when it has a dependent task, `.removeTask()` fails with the error:

> Error: Unable to remove task "Xyz" because the following tasks depend on it: Foo

Now to update the task, we need to remove its dependent(s), replace it, followed by re-adding the dependents.

I propose we add `.updateTask()` that allows updating the definition without the pitfalls of `.removeTask()`.

(I don't know the full extent of how tasks can depend on each other, so I am not sure if there are cases where `.updateTask()` wouldn't work with dependencies, or if this is a trivial change.)

**Comment by mrgrain** [comment]
What is it you want to update on the task? Can you not achieve this with this?
```ts
const task = project.tasks.tryFind("name");

task.reset();
task.description = "new description"; 
````

**Comment by philipmw** [comment]
Thanks, @mrgrain -- that works! Resolving. :)
