### ISSUE TITLE
Seems like when we are using latest Projen version 0.65.29 we started facing some "unknown command" issue.

### ISSUE THREAD

**Issue by anshulgargamway** [projen/projen#2250]
Seems like when we are using latest Projen version 0.65.29 we started facing some "unknown command" issue.
Same command with older version works fine.

We have executed following command. Masked some sensitive info

`npx projen new --from @custom-project-scaffolders/springboot full --no-git --domain-entity testc --tier app --api`

Got following exception
`Unknown commands: testc, --tier, app, --api`

When we used the above command with older version of Projen. It worked alright.
Not sure if something is changed recently. If yes can you please let us know.

**Comment by mrgrain** [comment]
Hmm. Yes I suspect it would be due to this change 🤔 
https://github.com/projen/projen/pull/2246/files#diff-2304ffbbb1cb4987906a47b08b7c3b590fc542f4247b733844049776fd8591f2R17

**Comment by mrgrain** [comment]
@anshulgargamway I'm not entirely familiar with using external projects. When you are running 

```
npx projen new --from @custom-project-scaffolders/springboot --help
```

does it correctly list all the available options and their respective types?

You can try `npx projen new awscdk-app-ts --help` to see what I mean.

---

It looks like ` testc, --tier, app, --api` aren't recognized as args/options anymore. I'm investigating if the linked change can be achieved in an other way, or alternatively how external projects can keep receiving the correct args.

**Comment by mrgrain** [comment]
Alright, I have a fix ready https://github.com/projen/projen/pull/2252

**Comment by pflorek** [comment]
@anshulgargamway where to find the spring boot projen project `@custom-project-scaffolders/springboot`?

**Comment by anshulgargamway** [comment]
@pflorek : This Project is maintain as a private project currently.

**Comment by anshulgargamway** [comment]
@mrgrain : Thanks for fixing the same will wait for the PR to be merged and released
