### ISSUE TITLE
Enable markers for eslint configuration files

### ISSUE THREAD

**Issue by dj-rabel** [projen/projen#2253]
As I found in the docs of eslint, they do support comments for both, yaml as well as json configuration files. So theres nothing stopping us from adding the "generated by projen ..." comment to these.

Mentioned here: https://github.com/mozilla/addons-frontend/issues/942
In eslint docs here: https://eslint.org/docs/latest/user-guide/configuring/configuration-files#comments-in-configuration-files

Currently markers for both types of config files are disabled:
https://github.com/projen/projen/blob/6b7ab972023ea01988ea0693f115cec0f737be8c/src/javascript/eslint.ts#L382
https://github.com/projen/projen/blob/6b7ab972023ea01988ea0693f115cec0f737be8c/src/javascript/eslint.ts#L387

If you're fine with enabling it I would go ahead and open a pull request, changing both to true, as well as setting "allowComments: true" for the json variant to indicate it supporting comments. (adding "//": "~~ generated ..." to json, fails with an error. Might be why it was on false)
Reference to the flag im talking about: https://github.com/projen/projen/blob/6b7ab972023ea01988ea0693f115cec0f737be8c/src/json.ts#L34

Reason I come up with this: Found myself editing the file manually today, not realising it was managed by projen, as there was no comment indicating it inside the file.

**Comment by mrgrain** [comment]
Yes please!

Inline Json comments are relatively new, so I guess that's why it wasn't enabled. Heads up, you might have to change some tests, since the default setup breaks with inline Json comments.
