### ISSUE TITLE
Task release fails when executing git diff

### ISSUE THREAD

**Issue by pchaganti** [projen/projen#2263]
� Task "release:package-version-test" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /home/antaeus/test_project/packages/cdk-test-app)
error Command failed with exit code 1.

Ran **npm run build** locally to make sure all files were checked in. Using a release branch and not main. Kind of stuck at this point., Anyone has any pointers?

thx!

**Comment by mrgrain** [comment]
Can you link the build & repo? Would definitely need more details on the error.

**Comment by pchaganti** [comment]
Sorry cant link to the repo. it is a private ent repo.

Trying to use nx + projen with a monorepo that consists of a bunch of typescript packages. I can try and see if I can get an isolated project that can reproduce the issue. There were a couple of other GH issues that had the same error, but did not see a resolution. Any suggestions for how to go about using projen with a monorepo? 

thx for your help!

**Comment by mrgrain** [comment]
How are you using nx?

You might want to consider using [nx-monorepo](https://github.com/aws/aws-prototyping-sdk/tree/mainline/packages/nx-monorepo).

**Comment by pchaganti** [comment]
Will try it out. thanks!

**Comment by dicato** [comment]
I am running into the same error, also on a closed source project so I cannot link directly.

I'm trying to cut a `1.0.0` release on a new project. I've done the following:

1. added `majorVersion: 1` to `.projenrc.js`
2. added `releaseTrigger: ReleaseTrigger.manual()` to `.projenrc.ja`
3. tagged the latest commit on the `main` branch as `v1.0.0` via `git tag -a v1.0.0 -m "chore: cut v1 initial release."
4. run `npx projen release`

...and I receive the same error. 

When it fails, `package.json` is updated and `version` is set to `version: "0.0.0"`. This explains why `git diff --ignore-space-at-eol --exit-code` returns `1` because there are changes not staged for commit. 

If I commit this change, I receive a different error saying that tag `v1.0.0` already exists, which is true. 

If I delete the `v1.0.0` tag and rerun `npx projen release`, it completes successfully. *Something* caused the tagging and release process to get out of sync, but I am not sure what.

**Comment by mrgrain** [comment]
@dicato Check out this guide https://projen.io/releases.html
Especially the FAQ section.

---

In general: Obviously this is tricky for private projects, however this error is perfectly normal and expected in a number of circumstances. Unfortunately that mean you'll have to provide some details about what you are doing (text), how you are doing it (code snippets), and what's happening (logs that include more than just the error.)

**Comment by dicato** [comment]
Thanks @mrgrain - I was about to say I answered one of my own questions by rereading the docs:

https://projen.io/releases.html#why-is-the-version-in-packagejson-set-to-000

---

I was able to effectively cut a `1.0.1` release.
1. create the `v1.0.1` tag on the head of main
2. make a commit with a message of `fix:....`
3. run `npx project release`

I'm ok with that! 🤞 it might help @pchaganti

**Comment by pchaganti** [comment]
Trying to do a manual 0.0.1 release. Working off a branch and not main, as we want to iron out any issues before we move things over. Added releaseTrigger: ReleaseTrigger.manual() to .projenrc.js.

1. create the v0.0.0 tag on branch
2. push tags
3. run npx project release:package-version-test

Fails with the same
```
 � Task "release:branch_name" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /home/antaeus/test_project/base/cdk-test-app)
error Command failed with exit code 1.
```
Finding it quite difficult to relate the docs to an actual working manual release. This is a rather large monorepo, but for testing using only one package. Feel like maybe i am missing something in projenrc.js. Here is what I am using with some sensitive info taken out:

```
const testProject = new AwsCdkConstructLibrary({
  author: "pchaganti",
  authorAddress: "pchaganti@github.com",
  cdkVersion: "2.53.0",
  name: "@owner/cdk-test-app",
  defaultReleaseBranch: "package-version-test",
  repositoryUrl: "https://github.com/private_repo",
  outdir: "base/cdk-test-app",
  npmDistTag: 'latest',
  npmRegistryUrl: 'https://npm.pkg.github.com',
  repository: "https://github.com/private_repo/cdk-test-app.git",
  parent: project,
  release: true,
  releaseToNpm: true,
  releaseTrigger: ReleaseTrigger.manual(),
  devDeps: [
    'aws-cdk-lib@2.53.0',
    'constructs@10.0.5',
    "standard-version",
    "@types/babel__traverse@7.18.2"
  ],
  deps: [
    'aws-cdk-lib@2.53.0',
    'constructs@10.0.5'
  ],

  bundledDeps: [
    'source-map-support'
  ],
});
```

**Comment by pchaganti** [comment]
Here is the log from before the error. Looks like git diff is returning with some ouput. If I just run git diff by itself in the project root, it doesnt return anything.

```
       Time:        6.121 s, estimated 7 s
       Ran all test suites.
       � release:package-version-test | git diff --ignore-space-at-eol --exit-code
       diff --git a/.gitattributes b/.gitattributes
       index 1299013..7388788 100644
       --- a/.gitattributes
       +++ b/.gitattributes
       @@ -1,22 +1,6 @@
        # ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
        
       -*.snap linguist-generated
       -/.eslintrc.json linguist-generated
        /.gitattributes linguist-generated
       -/.github/pull_request_template.md linguist-generated
       -/.github/workflows/build.yml linguist-generated
       -/.github/workflows/pull-request-lint.yml linguist-generated
       -/.github/workflows/release.yml linguist-generated
       -/.github/workflows/upgrade-main.yml linguist-generated
       -/.gitignore linguist-generated
```

**Comment by mrgrain** [comment]
Well that's something at least. This is the safeguard working as it should be. _Something_ in your build behaves differently on the Workflow than locally (assuming you have run `projen` locally and checked all files in).

**Comment by pchaganti** [comment]
You are right. Will debug into this and try to track it down.

thanks!

**Comment by pchaganti** [comment]
Yep! somehow when the monorepo was initially setup, the package folder was referencing main while the rest of the proj was on a branch. The changes were not committed from the package folder. Not sure how that mix-up happened. 

I built it up again from scratch and dont have this error anymore. Was able to build a versioned release. Will test some more with the versions as well as publishing now to the private npm package repo.

thanks again for all your help in debugging this.

cheers!

**Comment by mrgrain** [comment]
Good luck with the private repository. I hear that's not quite straight forward either 😬
