### ISSUE TITLE
Add option to eject from dependency management.

### ISSUE THREAD

**Issue by rjmackay** [projen/projen#2273]
I find projen useful for setting up projects initially, and providing great CI flows. But I'd prefer to manage dependencies purely with npm (i.e. so `npm i --save some-dep` works as expected`).
It would be great if projen provided an option to either
1. Stop managing dependencies at all
2. Ignore extra dependencies: so it would make sure anything it knows about is present, but ignore others added to package.json manually

**Comment by mrgrain** [comment]
- Does `projen eject` work for your use case?
- Technically projen already supports that. But you have to create your own project for it.

---

I seriously doubt we will go down this route for bundled project types. There's just too much uncertainty about not controlling dependencies. Saying that, `package.json` ownership is in a bad I'm between place at the moment. I'd rather move it towards a world were it's also write protected and clearly managed by projen only, or maybe alternatively do some sort of "injection" mode with projen's changes being more like patch operations than fully generating the file.

**Comment by rjmackay** [comment]
> Does projen eject work for your use case?

Not really. We still use projen to manage other parts of our stack, and have a custom extension of the CDK project type that sets up default tasks, tsconfig, etc. so we'd lose some utility with it.

> Technically projen already supports that. But you have to create your own project for it.

Any guidance on how we could do that?

**Comment by rjmackay** [comment]
>  alternatively do some sort of "injection" mode with projen's changes being more like patch operations than fully generating the file.

This sounds like it might move closer towards what I was thinking. But totally understand that it's easier to just control the entire file.

**Comment by mrgrain** [comment]
> Any guidance on how we could do that?

There are no docs for this yet. But you can get inspired by the projects that ship with projen. There are also a few examples of third-party projects, e.g. [nx-monorepo](https://github.com/aws/aws-prototyping-sdk/tree/mainline/packages/nx-monorepo) or [pepperize/projen-awscdk-app-ts](https://github.com/pepperize/projen-awscdk-app-ts).

Since you don't want dependency management, you probably have to rebuild all of the Node stuff and start extending the existing `GitHubProject`
