### ISSUE TITLE
Tags issue with manual release

### ISSUE THREAD

**Issue by pchaganti** [projen/projen#2297]
Doing manual releases. Able to do the release and publish the package to a private GH repository. However the tag that should have been created in GH repo is not showing up.

To explain:

- My current GH repo has a tag v0.0.71.
- I make some changes and manually release a package.
- The package is created with v0.0.72 and published successfully to the GH package registry.
- The tags on the GH repo still show 0.0.71 as the last tag. 
- So when I try to do another release, it will complain about 0.0.72 already existing, as it is going off the v0.0.71 tag on the repo.

Is this a GH issue or am I doing something wrong? I could swear this was working just fine yesterday. I dont see any errors so I guess the tagging must be happening. I am working in a branch but not sure if that has anything to do with it, as tags are independent of a branch.

P.S: Also dist/changelog.md, dist/releasetag.txt, dist/version.txt all show the correct version of v0.0.72.

Any pointers?

thanks!

**Comment by mrgrain** [comment]
I'm not aware of any changes in that area. Would be helpful to know what commands you run exactly and how your configuration looks like.

Generally speaking the tag is either created by a `git push` or a `gh release create`. The lack of error messages is confusing but I suspect that either of these commands fails.

**Comment by pchaganti** [comment]
Will look into this more and see if I can track it down.

thanks!

**Comment by pchaganti** [comment]
Found the issue. Error on my part. Had the wrong branch name in one of the tasks which caused the tagging task to get skipped (we have a custom task for publishing).

thanks again for your help!
