### ISSUE TITLE
Supporting various types of tests

### ISSUE THREAD

**Issue by wojtekPi** [projen/projen#2328]
In projects you can have different types of tests (for example unittests, component tests, integration tests, etc.) and sometimes you want to run just particualr types of tests (e.g. unittests).

So I’m proposing a feature which address these needs. 
The idea is to add in configuration possibility to:
- define new type of tests
- define regex to recognise files which contain tests of particular type

This configuration will create correspondent tasks which could be run and this task will run only specific tests. 
As this is described in the diagram below:

![package json - projen-test-project  Codespaces  -… png-1](https://user-images.githubusercontent.com/6260102/209735918-4684f59f-4869-4d13-b12f-c3f295cd45a5.jpeg)

Note: Task `tests` (and related tasks), still run all tests (it’s backward compatible).

If you think it’s good improvement, I can create PR with implementation.

**Comment by mrgrain** [comment]
What's would the current code look like that this new feature would replace?

**Comment by wojtekPi** [comment]
> What is the current code, that this new feature would replace?

Well, this will not change existing one code - current tasks will behave in the same way, but there will be additional, more specific tasks (to run particular types of tests). 

And currently, code responsible for generating `test` task is in `src/javascript/jest.ts` file, so logic for creating the new tasks will be triggered there.
Here is this code:
![image](https://user-images.githubusercontent.com/6260102/209988353-2fb3bebb-839d-4f5f-b102-274dd82f50fc.png)

**Comment by mrgrain** [comment]
Apologies for not phrasing my question clear enough. Projen already allows a user to define custom tasks. I wonder what the code would be to create a `projen test:integration` task manually with the current APIs.

---

Side note: Your proposal mixes the naming convention `npm run test:integration` and `projen integration-test`. Was that on purpose?

Last point, it's also possible to run `projen test unit` which passed `unit` to jest as a search pattern.

**Comment by wojtekPi** [comment]
> I wonder what the code would be to create a `projen test:integration` task manually with the current APIs.

It will be something like this:
`  scripts: {
    'integration-test': 'jest integration',
  },`
  but in this case we need to manually keep this script up-to date with properties which are added to standard `test` task e.g. like: `--passWithNoTests --updateSnapshot` .


> Was that on purpose?

Yes - I have a feeling that `integration-test` is more inline with projen task naming convention (or style?) and `test:integration` is more in line with the naming convention of npm scripts, but it could be changed.

**Comment by mrgrain** [comment]
Something like this would be a current way to achieve something similar:
```
project.package.setScript('test:integration', 'projen test **/**.integration.ts');
```

**Comment by mrgrain** [comment]
Revisiting this, I don't think this is a route we want to go done at the moment. At least not in a general purpose sense.
We will continue to support different types where it makes sense, e.g. integration tests for jsii.
