### ISSUE TITLE
Feature Request: Configuration option to stop package.json version reset

### ISSUE THREAD

**Issue by mvs5465** [projen/projen#2334]
We cannot use git tags due to our release process so instead we track the version in package.json. There does not appear to be any way to disable the resetting of the version to 0.0.0 so we must constantly manually undo this action.

https://projen.io/releases.html#why-is-the-version-in-packagejson-set-to-000

**Comment by zmully** [comment]
We override this behavior in our `.projenrc.ts` by including `project.addFields({ version: '0.0.7' });` for example. Maybe that's a workaround for you too?

**Comment by mvs5465** [comment]
@zmully thanks, that works well!

**Comment by chealind** [comment]
Hi @mrgrain, is this workaround the only way to disable the package version reset? This version reset is enforced even when release management is explicitly disabled, which seems counter-intuitive.

**Comment by mrgrain** [comment]
> Hi @mrgrain, is this workaround the only way to disable the package version reset? This version reset is enforced even when release management is explicitly disabled, which seems counter-intuitive.

Yes this is currently the only way to prevent this.
I think you are right though, when release management is disabled we don't need to enforce it.
