### ISSUE TITLE
Define `ts-jest` config under `globals` is deprecated

### ISSUE THREAD

**Issue by Warkanlock** [projen/projen#2361]
Starting from yesterday, after upgrading ``projen`` configuration I started to received the following warning when running tests

```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```

The projen configuration file I'm using right now:
```
const { typescript } = require('projen');

const project = new typescript.TypeScriptProject({
  defaultReleaseBranch: 'main',
  name: 'layer',
  license: 'MIT',
  release: false,
  clobber: false,
  autoMerge: false,
  buildWorkflow: false,
  packageManager: 'yarn',
  dependabot: true,
  github: false,
  disableTsconfig: true,
  pullRequestTemplateContents: ['# Title \n## Description\n## Authors'],
  description:
    'This project serves the purpose of exposing information from **Veritas** to later expose methods to external customers who might be us or public consumers.',
  // devDeps: [], // developer dependencies, npx projen after update the list
  deps: [
    'lodash',
    'aws-sdk-client-mock',
    '@aws-sdk/client-dynamodb',
  ], // developer dependencies, npx projen after update the list
});

project.synth();
```

Any information on if this issue is recurrent or new?

**Comment by mrgrain** [comment]
New issue because they've apparently only now deprecated the use of `globals`.

Looks like we need to update this code:
https://github.com/projen/projen/blob/5fb78c9c6939719c806b171d77a7c4cec7d8fc35/src/typescript/typescript.ts#L444-L448

Saying that, I'm not sure if ts-jest v27 supports this yet. We have to use use v27 for JsiiProjects due to a TS version incompatibility. That shouldn't stop us from updating the default on the `TypeScriptProject` though (just might add slightly  more work).

**Comment by mrgrain** [comment]
Note to myself: Using `transform` is only support by ts-node >= v29. So we will need some sort of check for the used version.

**Comment by wenindoubt** [comment]
I just started a pull request for this fix, and I got super confused when I read `ts-node >= v29`. It took me a moment to realize you were talking about `ts-jest >= 29`.

I'll see what I can do here.

**Comment by mrgrain** [comment]
> I just started a pull request for this fix, and I got super confused when I read `ts-node >= v29`. It took me a moment to realize you were talking about `ts-jest >= 29`.

Of course. Very sorry about this confusion. I've amended my previous comment for future readers.

**Comment by wenindoubt** [comment]
I got the versioning working, but can't figure out how I would handle `>=29.0.0` and `<29.0.0` in the unit tests.

At the moment, the unit tests will succeed if you're currently `>=29.0.0`

Do you have any thoughts?

**Comment by mrgrain** [comment]
There's a (stale?) PR for it. As far as I'm concern it's deprecated but still working. So not super urgent yet.
I'd recommend you open a separate issue for your stuff.

**Comment by wenindoubt** [comment]
Hi guys, sorry! I've been super busy with life that I haven't found a chance to get back to this. I'll see if I can keep chugging along my pull request in the next 1-2 weeks. 🙏

**Comment by Warkanlock** [comment]
> Hi guys, sorry! I've been super busy with life that I haven't found a chance to get back to this. I'll see if I can keep chugging along my pull request in the next 1-2 weeks. 🙏

Let us know if anything is needed! I could not make it work other than using npm patch

**Comment by fiserv-plat-eng** [comment]
@mrgrain  - is there a workaround for this?

**Comment by moltar** [comment]
If anyone wants a quick-fix:

```ts
import type { typescript } from 'projen'
import type { JestConfigWithTsJest } from 'ts-jest'

interface FixJestOptions
  extends Pick<typescript.TypeScriptProject, 'tsconfigDev' | 'jest'> {}

/**
 * Overwrite Jest options to fix incompatibility.
 *
 * @see https://github.com/projen/projen/issues/2361
 * @see https://kulshekhar.github.io/ts-jest/docs/getting-started/options
 */
export function fixJest({ tsconfigDev, jest }: FixJestOptions): void {
  const jestConfig: JestConfigWithTsJest = {
    globals: {},
    transform: {
      '^.+\\.tsx?$': [
        'ts-jest',
        {
          tsconfig: tsconfigDev.fileName,
        },
      ],
    },
  }

  if (jest && jest.config) {
    Object.assign(jest.config || {}, jestConfig)
  }
}
```

**Comment by drernie** [comment]
Hello. I'm also seeing this issue.  I was told to use:

* https://github.com/aws/constructs/blob/06dc48876a14ec3e1f7b15a2e6678c691bacad45/.projenrc.ts
* https://github.com/aws/constructs/pull/1957/files#diff-bda22a3de7550efc76dd29e2a427a8d5abd5863f6e96a339ff47390d9bed7d14

However, that example uses `CdklabsJsiiProject`.  When using `awscdk.AwsCdkTypeScriptApp` I get an error for passing this parameter to the constructor:

```
  jsiiVersion: '~5.2.0',
```
Is there a simple workaround, or are we more-or-less stuck until someone actually fixes the issue?

**Comment by mrgrain** [comment]
You don't need the `jsii` stuff if I read @tinovyatkin workaround correctly, you need only the following, and make sure that you use `jest>=29` and `typescript>=4.3`.

```ts
// Fix Jest 29 warning about deprecated config in `globals` 
 project.jest!.config.transform ??= {}; 
 project.jest!.config.transform['\\.ts$'] = [ 
   'ts-jest', 
   project.jest?.config.globals['ts-jest'], 
 ]; 
 delete project.jest!.config.globals['ts-jest']; 
```

Generally speaking, as far as I'm aware, this is still just a warning and everything works just fine.

**Comment by drernie** [comment]
Thank you, this worked perfectly.  My OCD deeply appreciates the lack of clutter :-)
