### ISSUE TITLE
Getting error when testing the new project generation from existing projen module

### ISSUE THREAD

**Issue by saisirishaboppana** [projen/projen#2371]
I have created a new project inside existing projen repo and testing it as below

  script:
    - npm install
    - npm i -g projen
    - npx projen build
    - mkdir -p test/projen
    - cd test/projen
    - npx projen new --from  file:/builds/repo/existing_projen_module
    - npx projen build

Here I am trying to build the new project from existing projen module (Private to our organisation).

I am getting the below error when I run it on GitLab:

> npx projen --debug new --from  file:/builds/repo/existing_projen_module
> `-- (empty)
> added 1 package, and audited 73 packages in 2s
> 8 packages are looking for funding
>   run `npm fund` for details
> found 0 vulnerabilities
> 👾 installing external module file:/builds/repo/existing_projen_module
> added 1 package, and audited 75 packages in 4s
> 8 packages are looking for funding
>   run `npm fund` for details
> found 0 vulnerabilities
> 👾 Project definition file was created at file:/builds/repo/existing_projen_module/test/projen/.projenrc.ts
> Processing component: DataModelComponent
> Processing component: OpenAPIComponent
> Processing component: BootstrapComponent
> Processing component: ErrorCatalogComponent
> preSynthesizing component: BootstrapComponent
> preSynthesizing component: ErrorCatalogComponent
> Synthesizing component: ErrorCatalogComponent
> node:child_process:946
>     throw err;
>     ^
> Error: Command failed: npm ci
> npm ERR! code EUSAGE
> npm ERR! 
> npm ERR! The `npm ci` command can only install with an existing package-lock.json or
> npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
> npm ERR! later to generate a package-lock.json file, then try again.
> npm ERR! 
> npm ERR! Clean install a project
> npm ERR! 
> npm ERR! Usage:
> npm ERR! npm ci
> npm ERR! 
> npm ERR! Options:
> npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
> npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
> npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
> npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
> npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
> npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
> npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
> npm ERR! 
> npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
> npm ERR! 
> npm ERR! Run "npm help ci" for more info

Expected behavior:

Executing npx projen new --from  file:/builds/repo/existing_projen_module  should build the new project from already existing projen module.

Version:

GitLab - GitLab Enterprise Edition 15.8.0
Node Version - v18.12.1 (I have gave it a try with node 16 as well)
NPM version - 8.9.0
Programming language - Type script
Projen Version - 0.65.23

It is building locally but unable to build it in GitLab

**Comment by mrgrain** [comment]
Hi @saisirishaboppana and thanks for reporting this!

Can you help me understand your request better? Specifically, what is `file:/builds/repo/existing_projen_module`? 
`--from` is used to create projects from jsii modules. However this `existing_projen_module` directory appears to contain a `.projenrc` file. 🤔 

---

Either way, it looks like running `npm ci` fails due to the lack of a lockfile. That makes sense, since a new project wouldn't have a lockfile yet. At the moment `npm ci` is run whenever the env variable `CI` is set. You could try running it like this:
```console
# like this
CI= npx projen --debug new --from file:/builds/repo/existing_projen_module
# or maybe this is needed
env -u CI npx projen --debug new --from file:/builds/repo/existing_projen_module
```

Looks like a bug though and `projen new` should never attempt to install from a lockfile.

**Comment by saisirishaboppana** [comment]
> Hi @saisirishaboppana and thanks for reporting this!
> 
> Can you help me understand your request better? Specifically, what is `file:/builds/repo/existing_projen_module`? `--from` is used to create projects from jsii modules. However this `existing_projen_module` directory appears to contain a `.projenrc` file. 🤔
> 
> Either way, it looks like running `npm ci` fails due to the lack of a lockfile. That makes sense, since a new project wouldn't have a lockfile yet. At the moment `npm ci` is run whenever the env variable `CI` is set. You could try running it like this:
> 
> ```
> # like this
> CI= npx projen --debug new --from file:/builds/repo/existing_projen_module
> # or maybe this is needed
> env -u CI npx projen --debug new --from file:/builds/repo/existing_projen_module
> ```
> 
> Looks like a bug though and `projen new` should never attempt to install from a lockfile.

Hi @mrgrain , existing_projen_module is a projen repository and My aim is to create a folder in this existing projen repo and then cd to the newly created folder and run npx projen new --from file:/builds/repo/existing_projen_module.

Please let me know if I am clear on this and thanks for the solution,I will try running it.

**Comment by saisirishaboppana** [comment]
@mrgrain I have tested it with CI= npx projen --debug new --from file:/builds/repo/existing_projen_module ,build steps seems to work fine but there is an issue in eslint : > npx projen eslint
Initialized empty Git repository in /builds/repo/existing_projen_module/test/projen/.git/
Error: Command failed: git commit --allow-empty -m "chore: project created with projen"
Author identity unknown
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.

**Comment by mrgrain** [comment]
Sure you can do `--no-git` to not do the git stuff.

**Comment by saisirishaboppana** [comment]
> Sure you can do `--no-git` to not do the git stuff. Although it might be not very useful then anymore.

Thank you ,It resolved the issue.
