### ISSUE TITLE
Support for CodePipeline

### ISSUE THREAD

**Issue by pgarbe** [projen/projen#242]
Does it make sense to support CodePipeline the same way as GitHub actions?

**Comment by thomasklinger1234** [comment]
Out of interest: How is *support* meant? Because, CodePipeline can be configured through CLI, CloudFormation, CDK, Terraform etc.

**Comment by hoegertn** [comment]
The idea is to have Projen generate a CodePipeline setup instead of GitHub Actions

**Comment by thomasklinger1234** [comment]
That would be awsome!
