### ISSUE TITLE
Subprojects & monorepos

### ISSUE THREAD

**Issue by misterjoshua** [projen/projen#243]
I'd like to create components in subprojects of some main project, where the subprojects are in subdirectories. For instance, in a two-tier app and monorepo scenario, I might want to separate my React app from my serverless API by having them in different directories. In the case of an API-first design (swagger, openapi), I might even want a subproject for the API schema so that I can keep the API's interface logically distinct from the implementation.

I currently do this with yarn workspaces and it works very nicely for typescript, except for the boilerplate. It would be very nice to have the ability to do this using some native projen capability.

At present, I can synthesize to the subdirectories, but the projects aren't then in a position to add workflows or actions to `/.github/*`. It would be nice if they could.

I'm not too picky about the interface. If it makes sense to address this, I'm happy to help however I can.

**Comment by Chriscbr** [comment]
Possibly related to https://github.com/projen/projen/issues/9 ? I imagine there are more than one ways to handle subprojects, although it seems like lerna is one of the more popular tools currently available.

**Comment by misterjoshua** [comment]
> Possibly related to #9 ?

@Chriscbr Definitely related

> I imagine there are more than one ways to handle subprojects, although it seems like lerna is one of the more popular tools currently available.

I agree. Even in my own team, there are some varying opinions on how to handle subprojects. :) Rather than tackling this problem all at once, I've tried something simpler: PR #284 lets components synth into subdirs. This way I can have some flexibility in how I can layout my subprojects.

**Comment by misterjoshua** [comment]
Closing because for now, putting multiple projects in a projenrc will do.
