### ISSUE TITLE
PythonProject: add projenrc.ts support

### ISSUE THREAD

**Issue by kt-hr** [projen/projen#2451]
From the following code, pojenrc.py, projenrc.js and projenrc.json are supported.  
https://github.com/projen/projen/blob/main/src/python/python-project.ts#L216

Adding .projenrc.ts to this would be relatively easy and would improve the UX.

**Comment by mrgrain** [comment]
Nice idea! I don't think it's easy though, because suddenly we not only need `node` to be installed (which we do anyway), but also `typescript`. For node projects we do this via `package.json` which a python project doesn't have for obvious reasons.

**Comment by kt-hr** [comment]
@mrgrain thanks for the reply.
I looked at the code a bit and just thought it was something that could easily be added to an existing entry 😓 

I would like to start with the already implemented `.projenrc.js` to see how it works.
Is the following the expected workflow correct?

```sh
$ npx projen new python --projenrc-js=true
$ npm install projen # <-- Do I need to manually install projen to do the following synth?
$ npx projen
```

**Comment by mrgrain** [comment]
Almost. This is what would be required to work:
```console
$ npx projen new python --projenrc-ts
$ npx projen
```

Note that I have changed `js` to `ts` according to the issue. Also it's a boolean flag, so no need to specify `=true`.

> Do I need to manually install projen to do the following synth?

No. Projen is run using `npx` (or even `pipx` if desired).

**Comment by kt-hr** [comment]
@mrgrain thanks for the note about flag!

How does `.projenrc.js` refer to the projen module if I don't install projen locally?
Am I doing something wrong with my setup...

```sh
npx projen
👾 default | node .projenrc.js
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module 'projen'
Require stack:
- /Users/kt-hr/github/test-projen/.projenrc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/kt-hr/github/test-projen/.projenrc.js:1:20)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/kt-hr/github/test-projen/.projenrc.js' ]
}
```

My directory structure is as follows

```sh
tree -a -L 1
.
├── .env
├── .git
├── .gitattributes
├── .github
├── .gitignore
├── .projen
├── .projenrc.js
├── .venv
├── README.md
├── requirements-dev.txt
├── requirements.txt
├── test_projen
└── tests

8 directories, 6 files
```

**Comment by mrgrain** [comment]
Oh I see. So the js file doesn't work fully automatic at the moment either? 😅

**Comment by mrgrain** [comment]
This has been released in https://github.com/projen/projen/releases/tag/v0.68.19
