### ISSUE TITLE
Support generating release workflows for a subproject

### ISSUE THREAD

**Issue by rjmackay** [projen/projen#2490]
Slightly different from https://github.com/projen/projen/issues/450
We're not looking for a full monorepo, but often colocated an SDK project with our CDK APIs. It would be great if we could configure a release workflow for a subpath within our project. I'd be fine with doing this by manually calling/configuring the `Release` class, but it seems to assume there will only be one release class per project. It mostly just needs to be able to accept a working directory to run in instead of the project root.

I managed to hack something using the main release workflow, but it's obviously pretty fragile.
```
  const releaseJob = project.github.tryFindWorkflow('release')?.getJob('release') as Job
  if (releaseJob) {
    project.github.tryFindWorkflow('release')?.updateJob('release', {
      ...releaseJob,
      steps: releaseJob?.steps.map(step => {
        if (step.name === 'Install dependencies') {
          return {
            name: 'Install dependencies',
            workingDirectory: './sdk',
            run: 'npm ci',
          }
        }
        if (step.name === 'release') {
          return {
            name: 'release',
            run: 'npm run release:sdk',
          }
        }
        return step
      }),
    })
  }
```

**Comment by mrgrain** [comment]
Makes sense. But what is not working when passing the subproject to the component?

**Comment by rjmackay** [comment]
> Makes sense. But what is not working when passing the subproject to the component?

Missed this earlier. I don't really understand the question?
Github workflows get disabled in subprojects. If you force them to get re-enabled they'll get generated in the wrong places (ie. sdk/.github).

**Comment by rjmackay** [comment]
@mrgrain Happy to try a PR for this too, but I need some direction on how you think this should work.

**Comment by dkershner6** [comment]
Resolved with https://github.com/projen/projen/pull/3208?
