### ISSUE TITLE
TSConfig files should be gitignored by default

### ISSUE THREAD

**Issue by mvs5465** [projen/projen#2536]
When using `AwsCdkConstructLibrary` or `AwsCdkTypeScriptApp` two files `tsconfig.json` and `tsconfig.dev.json` will be automatically generated by JSII. These files should be in the projen gitignore by default because they are automatically generated upon `npx projen` invocation.

See here: https://github.com/aws/jsii/blob/main/packages/jsii/lib/compiler.ts#L386

**Comment by mrgrain** [comment]
A lot of files are generated by projen. Our general philosophy is that all files involved in building should be included in the repo. I'm aware that jsii has a different recommendation, but I guess at some point this comes down to personal preference.

If you don't want any(*) generated files to be commited, you can set `commitGenerated: false`.
If you just want to exclude some files, you can use [addGitIgnore](https://projen.io/api/API.html#addgitignorepattern-) et. al.

Let me know if this answers your question.

(*) Except the one that are absolutely necessary

**Comment by mvs5465** [comment]
Thanks @mrgrain that makes sense. To be clear `tsconfig.dev.json` is explicitly **included** by projen, but `tsconfig.json` is not set either way. Maybe these should be same?

**Comment by mrgrain** [comment]
Yes, `tsconfig.json` is a weird one because it is generated by `jsii` so we can't make it readonly. I reckon we could explicitly not ignore it though.

**Comment by mvs5465** [comment]
Got it!

Appreciate the feedback, I'd say this issue is good to go then.
