### ISSUE TITLE
Set `jsxImportSource` for `TypeScriptCompilerOptions`

### ISSUE THREAD

**Issue by zetashift** [projen/projen#2548]
To get [solid-start](https://start.solidjs.com/getting-started/what-is-solidstart) correctly configured I need be able to set [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) in the generated `tsconfig.json`.

For example a solid-starts example project looks like this: https://github.com/solidjs/solid-start/blob/main/examples/bare/tsconfig.json#L8

Is there anyway I can define this for my tsconfig using projen?

**Comment by mrgrain** [comment]
Yes please! PRs are welcome.

In the meantime, you can easily use overrides:
```ts
project.tsconfig?.file.addOverride('compilerOptions.jsxImportSource', 'solid-js');
project.tsconfig?.file.addOverride('compilerOptions.jsx', 'preserve');
```

**Comment by zetashift** [comment]
> Yes please! PRs are welcome.
> 
> In the meantime, you can easily use overrides:
> 
> ```ts
> project.tsconfig?.file.addOverride('compilerOptions.jsxImportSource', 'solid-js');
> project.tsconfig?.file.addOverride('compilerOptions.jsx', 'preserve');
> ```

TIL about `addOverride`! Nice. 
After $WORK stuff I'll open up the PR. Thank you, this help a lot :D
