### ISSUE TITLE
"releaseBranches" is not supported for APP projects

### ISSUE THREAD

**Issue by asmajlovicmars** [projen/projen#255]
Hi, I'm trying to use the "main" branch as a release branch instead of the "master", but getting an error. The api documentation for awscdk-app-ts  has it as an option, so I'm wondering is it possible to use a different name for a release branch? 

⚡ yarn projen
yarn run v1.19.1
$ node .projenrc.js
/Users/asmajlovic/code/o4ay-bus/node_modules/projen/lib/node-project.js:237
                throw new Error('"releaseBranches" is not supported for APP projects');
                ^

`
.projenrc.js:

const { AwsCdkTypeScriptApp } = require('projen');

const project = new AwsCdkTypeScriptApp({
  cdkVersion: "1.71.0",
  name: "o4ay-bus",
  deps: [
    "@aws-cdk/aws-sns",
    "@aws-cdk/aws-sns-subscriptions",
    "@aws-cdk/aws-lambda",
    "@aws-cdk/aws-lambda-event-sources",
    "@aws-cdk/aws-lambda-destinations",
    "@aws-cdk/aws-events",
    "@aws-cdk/aws-sqs",
    "@aws-cdk/aws-cloudwatch",
    "@aws-cdk/aws-iam",
    "@aws-cdk/aws-kms",
    "@aws-cdk/aws-stepfunctions",
    "@aws-cdk/aws-stepfunctions-tasks",
    "@aws-cdk/aws-apigatewayv2"],
  releaseBranches: ["main"]
});

project.synth();

`

**Comment by asmajlovicmars** [comment]
My bad, and apology.... just checked the projen code, and found out about defaultReleaseBranch. Now releases go to the main branch 😄

**Comment by eladb** [comment]
Would be nice to auto-discover the default branch during `projen new`

**Comment by asmajlovicmars** [comment]
> Would be nice to auto-discover the default branch during `projen new`

I noticed that has been already addressed. That's perfect!
