### ISSUE TITLE
Files in sub-projects are not correctly annotated as generated

### ISSUE THREAD

**Issue by dippi** [projen/projen#2560]
When creating any sub-class of `FileBase`, the file is annotated as generated using the `linguist-generated` attribute in `.gitattributes` (see #629).

This is achieved by calling the `annotateGenerated` method on the root project, while passing the path relative to the sub-project.
https://github.com/projen/projen/blob/e236e583070096e933649b35d205c257dcbc0422/src/file.ts#L98-L100

There are two possible ways to fix this issue:
1. Call `annotateGenerated` on the sub-project instead
2. Reconstruct the path relative to the root project

My preference is option 1, and I am currently working on a pull request to make this change. However, I am open to discussion.

**Comment by mrgrain** [comment]
Good catch and thanks for the PR!
