### ISSUE TITLE
Construct Library Build failing with `aws-cdk-lib@2.72.0` (looks like failing with `projen@0.70.0`)

### ISSUE THREAD

**Issue by FBosler** [projen/projen#2570]
I have an [aws-constructs project](https://github.com/everdropde/ed-aws-cdk-constructs), which runs nightly dependency upgrades. It seems like that the builds (in github) stopped working after the projen upgrade to `0.70.0` from `0.68.15`.
![image](https://user-images.githubusercontent.com/14016698/228801752-009b413b-acba-4445-94c0-0012961693e8.png)

Errors hint towards some difficulties with finding the modules:
![image](https://user-images.githubusercontent.com/14016698/228801523-d64809e5-33c1-4aa6-869a-32527752fc5d.png)

Any pointers towards fixing this would be appreciated.

![image](https://user-images.githubusercontent.com/14016698/228800499-0517fdad-d747-4899-82b9-b4953526c90a.png)

**Comment by mrgrain** [comment]
Thanks for reporting @FBosler ! 

We are aware and looking into it. It appears this is an issue with `aws-cdk-lib@2.72.0` (and not projen).
https://github.com/everdropde/ed-aws-cdk-constructs/pull/12/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR1339

No good workaround currently, except for not updating `aws-cdk-lib` but that's not super easy to do with projen.

**Comment by mrgrain** [comment]
This has been fixed upstream. LMK if it not works for you yet.
