### ISSUE TITLE
`Cannot find module 'projen' or its corresponding type declarations` starting from v0.71.5

### ISSUE THREAD

**Issue by gmukul01** [projen/projen#2616]
We have created a wrapper on top of `TypescriptAppProject` and while compiling the project we started getting this error `Cannot find module 'projen' or its corresponding type declarations` from the `v0.71.5`. Most probably this is something to do about this PR https://github.com/projen/projen/pull/2603

**Comment by mrgrain** [comment]
We've identified the issue and [this jsii PR](https://github.com/aws/jsii-compiler/pull/102) (plus a new release of projen)  should fix it.

**Comment by gmukul01** [comment]
@mrgrain The issue is fixed, thank you so much for quick resolution. :)
