### ISSUE TITLE
[node-package]: old package versions are pinned when using pnpm

### ISSUE THREAD

**Issue by cogwirrel** [projen/projen#2628]
When using `PackageManager.PNPM`, for any dependencies where we don't specify a version explicitly, we end up with projen pinning old versions of the package.

To reproduce:

* `npx projen new typescript --packageManager pnpm`
* Add `deps: ['aws-cdk-lib']`
* `pnpm projen`
* Notice `aws-cdk-lib@^2.0.0-alpha.0` is written to `package.json` (the latest is `2.76.0` at the time of writing!).

This seems to be due to `"*"` being written when no version is specified: https://github.com/projen/projen/blob/3c28310404f113ff71ccfc5e52e6267f10c716e6/src/javascript/node-package.ts#L1155

The [package.json docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#dependencies) mention that `*` means "any version", so it seems like it's actually an "implementation detail" that both `npm` and `yarn` both resolve the latest version, whereas `pnpm` does not 😞 .

It seems like Projen's intention is to have `yarn add`/`npm install`/`pnpm add` type behaviour for dependencies where the version isn't specified - ie. it resolves the latest version but pins it with a caret (`^`) in the `package.json`, so I do feel that this is a bug in projen.

I think the solution might be to use `latest` instead of `*` as the initial placeholder version, as I believe all 3 package managers will honour this. Though I can't see any official mention of `latest` in the [package.json docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#dependencies) so I'm not 100% sure if that's the right fix.

**Comment by mrgrain** [comment]
That's an interesting and fair point!

Few thoughts:

- If you don't want projen to manage the version, projen won't manage the versions for you. Obviously this doesn't hold up if projen makes that decision for you.
- `latest` isn't a standard. It's a tag that a lot of projects apply, but not all.
- You can always go in and manually change the version in package.json afterwards.
- `aws-cdk-lib@^2.0.0` would be alright actually. It's the alpha thingy that makes this annoying.

**Comment by mrgrain** [comment]
I found this setting which apparently has changed in pmpm@8
https://pnpm.io/npmrc#resolution-mode

**Comment by mrgrain** [comment]
We probably want a setting for pnpm that writes this .npmrc file for you by default.

**Comment by cogwirrel** [comment]
Ah nice find! Yeah I think defaulting resolution-mode to `highest` would make the most sense, so that the `pnpm` experience with projen's "pinning" is a bit closer to what you get with the other package managers :) This sounds much less intrusive than swapping the `*` to something else, and it sounds like there's no good alternative anyway if `latest` isn't standard :)

**Comment by cogwirrel** [comment]
Tested out the .npmrc setting and that works nicely:

```ts
const project = new TypeScriptProject({
  defaultReleaseBranch: "main",
  name: "pnpm-projen-old-version",
  packageManager: NodePackageManager.PNPM,
  deps: ['aws-cdk-lib'],
});

const npmrc = new NpmConfig(project);
npmrc.addConfig('resolution-mode', 'highest');
```

**Comment by mrgrain** [comment]
It's interesting that pnpm made the choice for `lowest` to be honest.
