### ISSUE TITLE
External project (--from) does not add devDeps

### ISSUE THREAD

**Issue by zmully** [projen/projen#2657]
In my custom external project (in my case, extending ` typescript.TypeScriptProject`), any `devDeps` need to be added with `this.addDevDeps()`, they can't be passed in the `super()` call. This isn't the case for non-devDeps. It looks like projen overwrites the `devDependencies` in the package.json when it injects the external project dependency but even after project initialization, the devDeps are not added on subsequent runs of  `npx projen`.

My external project looks similar to this:

```
export class CdktfProject extends typescript.TypeScriptProject {
  public constructor(options: CdktfOptions) {
  
    const baseOptions: Partial<typescript.TypeScriptProjectOptions> = {
      defaultReleaseBranch: 'main',
      deps: [
        'cdktf@^0.15.5',
        'constructs@^10.1.264',
        '@cdktf/provider-aws@^12.0.6',
      ],
      // this does not work
      devDeps: ['cdktf-cli'],
   ...
    };

    super({
      ...baseOptions,
      ...options,
    });
   // this works
    this.addDevDeps('cdtkf-cli');

.....
```

**Comment by mrgrain** [comment]
Thanks for reporting @zmully !

I'm sure we can handle the project initialisation better (although not exactly sure how). But looking at your code this behavior is expected. You're not deep merging your default devDeps with three ones passed into the constructor.

**Comment by zmully** [comment]
@mrgrain I'm not sure I understand the explanation. If I set the `devDep` in my `baseOptions` as described in the example above and I dump the options as passed to the constructor I get:

```{
      defaultReleaseBranch: 'main',
      deps: [
        'cdktf@^0.15.5',
        'constructs@^10.1.264',
        '@cdktf/provider-aws@^12.0.6',
        '@zephyr-ai/lib-cdk@^0.0.27'
      ],
      devDeps: [ '@zephyr-ai/prettier-config@^0.0.0' ],
      licensed: false,
      minNodeVersion: '18.0.0',
      packageManager: 'npm',
      prettier: true,
      prettierOptions: { ignoreFile: true },
      projenrcTs: true,
      entrypoint: 'src/index.ts',
      commitGenerated: true,
      sampleCode: false,
      jestOptions: {},
      npmignoreEnabled: false,
      github: false,
      vscode: false,
      buildWorkflow: false,
      releaseWorkflow: false,
      pullRequestTemplate: false,
      dependabot: false,
      mergify: false,
      autoMerge: false,
      clobber: false,
      name: 'test'
    }
```

So the `devDep` is there in the options, but when project is synth'ed, that devDep is not present in the package.json.

**Comment by mrgrain** [comment]
During `projen new` or synth, we pass `devDeps` as an option. In your code, you're passing the options on to `super` but you don't merge them correctly. They way you do it, and `devDeps` provided via options will always override your `baseOptions`. That's just how object destructuring works. 

I can't explain it any better, so here's JS fiddle: https://jsfiddle.net/nmxq394o/

**Comment by zmully** [comment]
Ah, sorry for being dense, I get your explanation now that I understand that `projen` injects a dev dependency that I'm not seeing in my unit tests.

**Comment by mrgrain** [comment]
Closing this for now, as the situation was resolved.
LMK if that's not right.
