### ISSUE TITLE
Typescript project release fails 

### ISSUE THREAD

**Issue by devnoo** [projen/projen#2717]
The release job generated by typescriptproject fails on github runs. 
It seem to me that due to the env CI: "true" it runs the install command with frozen dependencies directly after bumping the version, which cause yarn to fail because it says the lock file is out of date

**Comment by devnoo** [comment]
this seemed to be a workaround, but offcourse not nice:
project.tasks.tryFind('install:ci')?.reset('yarn install');

**Comment by mrgrain** [comment]
Thanks for reporting @devnoo  The release is working just fine in many repos. I suspect something else might be off in your setup. Can you share your project (if it's open source) or at least to configuration?

```
project.tasks.tryFind('install:ci')?.reset('yarn install');
```
This is quite dangerous. CI should not run an unconditional install.

**Comment by devnoo** [comment]
it is not opensource, can i  sent it to you

**Comment by devnoo** [comment]
can it be due to patching projen dependecy with patch-package?

**Comment by devnoo** [comment]
`
import { GithubCredentials } from 'projen/lib/github';
import { JobPermission } from 'projen/lib/github/workflows-model';
import { NpmAccess } from 'projen/lib/javascript';
import { CodeArtifactAuthProvider } from 'projen/lib/release';
import { TypeScriptProject } from 'projen/lib/typescript';

const project = new TypeScriptProject({

  projenrcTs: true,

  defaultReleaseBranch: 'main',
  name: '@dearhealth/projen',
  repository: 'https://github.com/dearhealth/libs-projen.git',
  deps: ['projen@^0.71.79', 'patch-package'],
  bundledDeps: ['@iarna/toml'],

  projenDevDependency: false,

  releaseToNpm: true,
  


  autoApproveUpgrades: true,
  autoApproveOptions: {},
  projenCredentials: GithubCredentials.fromApp(),
  githubOptions: {
    projenCredentials: GithubCredentials.fromApp(),

  },
  workflowNodeVersion: '16',

  depsUpgradeOptions: {

    workflowOptions: {
      labels: ['auto-approve'],
      projenCredentials: GithubCredentials.fromApp(),
      permissions: {
        idToken: JobPermission.WRITE,
        contents: JobPermission.WRITE,
        pullRequests: JobPermission.WRITE,
      },
    },
  },
  codeArtifactOptions: {
    authProvider: CodeArtifactAuthProvider.GITHUB_OIDC,
    roleToAssume: '${{ secrets.DEPLOYMENT_ROLE_DEV }}',

  },

  npmAccess: NpmAccess.RESTRICTED,
  npmRegistryUrl: 'https://dh-artifacts-915964404932.d.codeartifact.us-east-1.amazonaws.com/npm/npm-store/',

  scopedPackagesOptions: [{
    registryUrl: 'https://dh-artifacts-915964404932.d.codeartifact.us-east-1.amazonaws.com/npm/npm-store/',
    scope: '@dearhealth',

  }],

});
console.log(project.package.npmRegistryUrl)
// ugly hack because of yet another bug in projen
project.tasks.tryFind('install:ci')?.reset('yarn install');
project.npmrc.addConfig('always-auth', 'true');
project.setScript('postinstall', 'npx patch-package');
project.synth();
`

**Comment by mrgrain** [comment]
And your `package.json`?

**Comment by devnoo** [comment]
`{
  "name": "@dearhealth/projen",
  "repository": {
    "type": "git",
    "url": "https://github.com/dearhealth/libs-projen.git"
  },
  "bin": {
    "dhprojen": "bin/dhprojen"
  },
  "scripts": {
    "build": "npx projen build",
    "bump": "npx projen bump",
    "ca:login": "npx projen ca:login",
    "clobber": "npx projen clobber",
    "compile": "npx projen compile",
    "default": "npx projen default",
    "eject": "npx projen eject",
    "eslint": "npx projen eslint",
    "package": "npx projen package",
    "post-compile": "npx projen post-compile",
    "post-upgrade": "npx projen post-upgrade",
    "pre-compile": "npx projen pre-compile",
    "release": "npx projen release",
    "test": "npx projen test",
    "test:watch": "npx projen test:watch",
    "unbump": "npx projen unbump",
    "upgrade": "npx projen upgrade",
    "watch": "npx projen watch",
    "projen": "npx projen",
    "postinstall": "npx patch-package"
  },
  "devDependencies": {
    "@types/jest": "^27",
    "@types/node": "^16",
    "@typescript-eslint/eslint-plugin": "^5",
    "@typescript-eslint/parser": "^5",
    "eslint": "^8",
    "eslint-import-resolver-node": "^0.3.7",
    "eslint-import-resolver-typescript": "^3.5.5",
    "eslint-plugin-import": "^2.27.5",
    "jest": "^27",
    "jest-junit": "^15",
    "npm-check-updates": "^16",
    "standard-version": "^9",
    "ts-jest": "^27",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4"
  },
  "dependencies": {
    "@iarna/toml": "^2.2.5",
    "patch-package": "^7.0.0",
    "projen": "^0.71.79"
  },
  "bundledDependencies": [
    "@iarna/toml"
  ],
  "main": "lib/index.js",
  "license": "Apache-2.0",
  "publishConfig": {
    "registry": "https://dh-artifacts-xxx.d.codeartifact.us-east-1.amazonaws.com/npm/npm-store/"
  },
  "version": "0.0.0",
  "jest": {
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.ts?(x)",
      "<rootDir>/(test|src)/**/*(*.)@(spec|test).ts?(x)"
    ],
    "clearMocks": true,
    "collectCoverage": true,
    "coverageReporters": [
      "json",
      "lcov",
      "clover",
      "cobertura",
      "text"
    ],
    "coverageDirectory": "coverage",
    "coveragePathIgnorePatterns": [
      "/node_modules/"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/"
    ],
    "watchPathIgnorePatterns": [
      "/node_modules/"
    ],
    "reporters": [
      "default",
      [
        "jest-junit",
        {
          "outputDirectory": "test-reports"
        }
      ]
    ],
    "preset": "ts-jest",
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.dev.json"
      }
    }
  },
  "types": "lib/index.d.ts",
  "//": "~~ Generated by projen. To modify, edit .projenrc.ts and run \"npx projen\"."
}
`

generated by projen

**Comment by mrgrain** [comment]
Thanks for sharing. This looks all correct.

Can you find out more about what change is made by `projen bump`?
When working correctly, it should not cause a change.

**Comment by devnoo** [comment]
i think it was because i changed from Jsii project to Typescript project, and the jsii file got commited that way.
When i changed back to Jssi project this was at least the issue, the file being on gitignore, but in the repo, deleting it fixed it.
so closing for now
