### ISSUE TITLE
AwsCdkConstructLibrary and jest

### ISSUE THREAD

**Issue by helloworld121** [projen/projen#2733]
Hi there,

I just started to use projen, I like the idea pretty much. But I habe problems executing tests.
I generated a project for AwsCdkConstructLibrary. After generating it, I wanted to run the tests, but no tests where executed:
`npx projen test
👾 test | jest --passWithNoTests --updateSnapshot
No tests found, exiting with code 0
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                  
----------|---------|----------|---------|---------|-------------------
`
I guess it is related to this part in the generated package.json:
`  "jest": {
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.ts?(x)",
      "<rootDir>/(test|src)/**/*(*.)@(spec|test).ts?(x)"
    ],`
    
So I wanted to add a new pattern in the "projenrc.ts" file:
`  jest: true,
  jestOptions: {
    jestConfig: {
      testMatch: ['**/*.test.ts'],
    },
  },`

After running "npx projen", the new matching-pattern wasn't added to the package.json. 
But if I add the pattern manually to the package.json, the tests are executed.
Can someone take a look add it? 

Thank you,
Sebastian

**Comment by mrgrain** [comment]
Where are you putting your tests? It should just work if they are for example `test/foobar.test.ts`

**Comment by helloworld121** [comment]
Hi @mrgrain ,
thank you for the quick response :)

The name of the folder is "test". 
It is the folder, that was created after running the command "npx projen new awscdk-construct". 
I also reproduced the error, by running the command "npx projen new awscdk-construct" in an empty directory and executing "npm run test".
I was expecting at least one test to be found, because there is one in the created project structure (test/hello.test.ts)

This is the output. Sorry for the bad formatting. I guess I have some problems with pasting cmd output :D

$ npx projen new awscdk-construct
� Project definition file was created at C:\tmp\test-next\.projenrc.ts
� Installing dependencies...
� install | yarn install --check-files
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning jest > @jest/core > jest-runtime > @jest/fake-timers > @sinonjs/fake-timers@10.2.0: Use version 10.1.0. Version 10.2.0 has potential breaking issues
warning standard-version > stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 271.21s.
� Installing dependencies...
� install | yarn install --check-files
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 40.72s.

> test-next@0.0.0 eslint
> npx projen eslint

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.

=============
Initialized empty Git repository in C:/tmp/test-next/.git/
[main (root-commit) c0d1567] chore: project created with projen
 21 files changed, 8041 insertions(+)
 create mode 100644 .eslintrc.json
 create mode 100644 .gitattributes
 create mode 100644 .github/pull_request_template.md
 create mode 100644 .github/workflows/build.yml
 create mode 100644 .github/workflows/pull-request-lint.yml
 create mode 100644 .github/workflows/release.yml
 create mode 100644 .github/workflows/upgrade-main.yml
 create mode 100644 .gitignore
 create mode 100644 .mergify.yml
 create mode 100644 .npmignore
 create mode 100644 .projen/deps.json
 create mode 100644 .projen/files.json
 create mode 100644 .projen/tasks.json
 create mode 100644 .projenrc.ts
 create mode 100644 LICENSE
 create mode 100644 README.md
 create mode 100644 package.json
 create mode 100644 src/index.ts
 create mode 100644 test/hello.test.ts
 create mode 100644 tsconfig.dev.json
 create mode 100644 yarn.lock

SOMEONE@SOMEPC C:\tmp\test-next
$ npm run test

> test-next@0.0.0 test
> npx projen test

� test | jest --passWithNoTests --updateSnapshot
No tests found, exiting with code 0
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
� test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools projenrc .projenrc.ts
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.

=============

**Comment by mrgrain** [comment]
First guess: This is a windows issue. But I'll check on my machine.

I'll also look into changing the pattern.

**Comment by mrgrain** [comment]
Works with the latest version on MacOS
```console
$ npx projen@latest new awscdk-construct
...
$ npx projen test
👾 test | jest --passWithNoTests --updateSnapshot
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
 PASS  test/hello.test.ts
  ✓ hello (1 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |
 index.ts |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.376 s, estimated 2 s
```

**Comment by helloworld121** [comment]
Hi @mrgrain, 
thank you for those information.
Is it also possible to use projen under windows? Or is it mac only?

**Comment by mrgrain** [comment]
It's possible to use on Windows, but it's way less tested. Like you've seen here.
If you can, I recommend using [WSL on Windows](https://learn.microsoft.com/en-us/windows/wsl/install).

projen works well with any Unix devices.

---

There's a bug that causes this to not work:
``ts
  jest: true,
  jestOptions: { jestConfig: { testMatch: ['**/*.test.ts'], }, },
```

In the meantime you can do the following to change the match pattern:

```ts
// .projenrc.ts
import { awscdk } from 'projen';
const project = new awscdk.AwsCdkConstructLibrary({
  // settings
});

// Add this line 
project.jest?.addTestMatch('whatever');

project.synth();
```

**Comment by helloworld121** [comment]
Thank you @mrgrain. I will go with your approach, this is working

**Comment by mrgrain** [comment]
Bug has also been fixed.
