### ISSUE TITLE
Dots in ObjectFile keys are escaped

### ISSUE THREAD

**Issue by jrouly** [projen/projen#2749]
I'm trying to generate an `ObjectFile` (specifically an `IniFile`) that has dots (`.`) in the object keys. For example, this object:

```typescript
{
  'foo.*': {
    foo: 'bar',
  },
}
```

yields this ini file:

```ini
# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

[foo\.*]
foo=bar
```

I can't seem to find any way to disable this behavior.

**Comment by jrouly** [comment]
I assume [this function](https://github.com/projen/projen/blob/main/src/object-file.ts#L242-L262) is relevant. However I've tried escaping (`foo\.*`) and double escaping (`foo\\.*`) and even quadruple escaping (`foo\\\\.*`) with no luck.

**Comment by mrgrain** [comment]
This appears to be an issue with the `ini` library we use.

This shows the exact same behavior:
```js
require('fs').writeFileSync('./config.ini', require("ini").stringify({ "foo.*": {foo: 'bar'} }));
```

Happens with v2 and v4 of `ini`.

Not sure how we should convince it to not do that 🤔

**Comment by mrgrain** [comment]
Ah so apparently you are not supposed to add the `.` yourself.
This works:
```js
require('fs').writeFileSync('./config_modified.ini', require("ini").stringify({ "foo": {'*': {foo: 'bar'} }}))
```
Readable:
```
{
  'foo': {
    '*': {
      foo: 'bar',
    },
  },
}
```

**Comment by jrouly** [comment]
Oh gosh. I can see how that makes sense.

It's just a bit inconvenient for my particular use case ([mypy.ini](https://mypy.readthedocs.io/en/stable/config_file.html)) where dotted section headers don't represent nested objects necessarily, but are Python module patterns. For example

```ini
[mypy-site.*.migrations.*]
foo=bar
```

Which is, admittedly, pretty whack. I guess if the answer is that I just have to do some parsing and splitting on dots to structure objects appropriately, instead of just passing the pattern string (`"site.*.migrations.*"`) straight through to the object keys, I can work with that.

Thanks for answering so quickly.

**Comment by mrgrain** [comment]
Yeah I can see how that's annoying. I'm not entirely sure why `ini` escapes the dot in this case in the first place. Maybe you could open an issue there and see if they are willing to add an option for it.
