### ISSUE TITLE
feat(jest): allow test results processors + config

### ISSUE THREAD

**Issue by gradybarrett** [projen/projen#278]
This is useful in CI tools where limited test result parsing tools are available. In our case, we're pretty much forced to use JUnit formatting, and so use [jest-junit](https://www.npmjs.com/package/jest-junit).

I'd love to be opinionated about the output directory, but unfortunately, all of the processor modules out there implement different config interfaces.

Here's what I had in mind in it's most basic form:

```javascript
// .projenrc.js
const project = new TypeScriptProject({
  ...
  jestOptions: {
    testResultsProcessor: "jest-junit",
    testResultsProcessorConfig: {
      "jest-junit": {
        outputDirectory: "./test-reports"
      }
    }
  }
  ...
}

// output package.json
{
  "jest": {
    "testResultsProcessor": "jest-junit",
    ...
  },
  "jest-junit": {
    outputDirectory: "./test-reports"
  }
}
```

I see processors eventually have their own opinionated configuration objects long term, which would eliminate the need for `testResultsProcessorConfig`.

**Comment by gradybarrett** [comment]
I implemented the above interface in projen just for kicks but would love some feedback on viability and design before I invest in a particular direction.

**Comment by Chriscbr** [comment]
Adding extra fields to the jest section of package.json should be an easy add. I'm so-so about adding the processor options directly to the package.json through jestOptions - maybe that's something we can just let users do outside of the constructor? e.g.

```ts
project.manifest["jest-junit"] = {
    outputDirectory: "./test-reports"
};
```

I say this because it looks like some libraries like jest-junit and [jest-sonar-reporter](https://www.npmjs.com/package/jest-sonar-reporter) do put their config in package.json (like you showed), but some others like [jest-html-reporter](https://github.com/Hargne/jest-html-reporter/wiki/configuration) don't (they put it in a separate file), since none of this is standardized by jest. Thoughts?

**Comment by gradybarrett** [comment]
@Chriscbr I feel the same way about adding parser options through jestOptions. That's a good point about some packages only supporting external files when passed to `testResultsProcessor`. Do you have any experience using jest's [`reporters`](https://jestjs.io/docs/en/configuration#reporters-arraymodulename--modulename-options) config which lives inline with the other jest configs? I've only ever used `testResultsProcessor`.

I do think that the variability in implementation is pushing me down the custom reporter class route. I feel like that's more in the spirit of opinionated configuration that requires minimal customization to get working.

What do you think about the class route?

**Comment by gradybarrett** [comment]
After a bit more investigation I think appending to Jest's reporter's array is the "right" path forward. I read several issues referencing the future deprecation of `testResultsProcessor`, but I can't find any official jest documentation of that, so if anyone could confirm that would be greatly appreciated.

Based on that, at least for jest-junit, I like the idea of using reporter configs the best. It keeps all jest configs together and means we don't have to add additional files or parent-level package.json configs.

**Comment by Chriscbr** [comment]
I don't have a lot of experience with jest reporters, but it seems like like they are an more-or-equally used option, so I'm all for creating a specific component for Jest reporters - it definitely feels like something that would fit into the projen model. :-) 

I think by the same token it's possible we could allow istanbul coverage reporters (described [here](https://jestjs.io/docs/en/configuration#coveragereporters-arraystring--string-options)) to be specified using the same component, as long as the mental model / options required to specify it are similar enough.
