### ISSUE TITLE
Bug: Different upgrade behaviour with yarn and npx

### ISSUE THREAD

**Issue by pgarbe** [projen/projen#2788]
Not sure where it comes from, the upgrade behaviour between `yarn projen upgrade` and `npx projen upgrade` is different. It seems that the first one ignores the configuration in .npmrc. It resolves dependencies through registry.yarnpkg.com instead of our own registry.

The .npmrc contains a link to our internal registry that should be used for all packages.

```
registry=https://our-internal-registry
```

**Versions**
yarn: 1.22.19
projen: 0.71.129
npx: 9.5.1

The workaround `npx projen upgrade` works for us but I'm curious where this comes from (as I think it was different earlier)

**Comment by mrgrain** [comment]
Do you have some more logs?

`projen upgrade` runs a combination of `ncu`, `projen default` and `yarn/npm upgrade`.

Pure speculation, but maybe one of these commands has changed. Like it was hardcoded first and now we detect the package manager?

**Comment by eknowles** [comment]
I have the same issue (however I don't use classic yarn). I need to support both `~/.npmrc` and `~/.yarnrc.yml`

On yarn `> 1.x` you should be able to test this with `yarn config --why` to see what it is, by default it uses `https://registry.yarnpkg.com`. The why to change this is by setting the yarn config itself either manually setting the `~/.yarnrc.yml` or by using the cli commands.

```sh
yarn config set [--json] [-H,--home] <name> <value>
```

```sh
yarn config set npmRegistryServer https://our-internal-registry
```

`yarn` and `npm` work very differently, from where they store their configs to how they auth. Unfortunately `yarn` does not use `.npmrc`.

(side note, your yarn version is quite out of date, so my answer my depend on version > 3)
