### ISSUE TITLE
Try to write my own Construct 

### ISSUE THREAD

**Issue by henrysachs** [projen/projen#280]
Hi Guys,

im trying to write my own construct and would be happy to update the docs about the process. Currently i just tried to create a jsii project and copied a bit of config from projen itself. Now i created a class in the typescript file that should extend an already active projen config. 

```js
import { AwsCdkTypeScriptApp } from 'projen';

/**
 * (experimental) AWS CDK app in TypeScript.
 *
 * @experimental
 * @pjid henry-cdk
 */
export class HenryCDK extends AwsCdkTypeScriptApp {

  constructor() {
    super({
      cdkVersion: '1.70.0',
      name: 'henry-cdk',
    });
  }
}
```

But when I try to compile the Project i just get:

`Unable to resolve type "projen.AwsCdkTypeScriptApp". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").`

Isn't this the intended way of creating a custom construct? If not i'm also fine with understanding for of the concept. Also happy to deliver more configs from my project.

**Comment by pgollucci** [comment]
You need to use the `projen new awscdk-construct` -  AWS CDK construct library project to use that class no JSII.

**Comment by henrysachs** [comment]
But the Docs state:

`projen is bundled with many project types out of the box, but it can also work with project types and components defined in external jsii modules (the reason we need jsii is because projen uses the jsii metadata to discover project types & options in projen new).`

so i need a jsii module dont i?

**Comment by pgollucci** [comment]
I wouldn't read it that way.

**Comment by pgollucci** [comment]
AWSCDK App -> AWSCDK Construct -> AWS TS APP -> AWS JSII via OOP hierarchy, so you get JSII in all the ones to the left of it.  

I may have whiffed the order of JSII and TS app above.

**Comment by henrysachs** [comment]
Yeah I will try this tommorow. But I hope that I made clear that i try to use this construct as a projen —from Module.

**Comment by pgollucci** [comment]
I haven't done a `--from` myself yet.  Thats fairly new.

**Comment by henrysachs** [comment]
If you know someone a ping would be nice. 😬

**Comment by pgollucci** [comment]
ask in #projen on cdk.dev slack workspace. https://cdk-dev.slack.com/archives/C01BP9PQHPC

**Comment by pgollucci** [comment]
If the referenced module includes multiple project types, the type is required. Switches can also be used to specify initial values based on the project type APIs. You can also use any package syntax supported by yarn add like projen-vuejs@1.2.3, file:/path/to/local/folder, git@github.com/awesome/projen-vuejs#1.2.3, etc.

**Comment by pgollucci** [comment]
```bash
mkdir projen-foo
cd projen-foo

# this will be a jsii app; --from requires .jssi for now see .discover() in inventory.ts
projen new awscdk-app-ts
```

```ts
# in src/
export Foo extends projen.project {
  constructor(options: FooOptions) {
    super();
  }
}
```

```bash
projen
yarn install ; yarn build

cd /tmp
mkdir test
cd test
npx projen new --from file:../projen-foo
```

**Comment by henrysachs** [comment]
Hi Thanks for your efforts. You were awake when i was sleeping :D 
I tried to follow these steps but the yarn compile step just emits true.

**Comment by henrysachs** [comment]
just found a nice sample project: https://github.com/kcwinner/cdk-appsync-project
but i noticed that the from file parameter uses the string as the package.json key and not the value. Thats why from file imports dont work.

**Comment by pgollucci** [comment]
> Hi Thanks for your efforts. You were awake when i was sleeping :D
> I tried to follow these steps but the yarn compile step just emits true.

Its supposed to be be true for TS things.  We use ts-node which compiles at runtime.

**Comment by henrysachs** [comment]
I'm now at the stage that i published my package to npm because local imports dont work and receive this error: 
```
Error: No projects found after installing @ffa/cdk-seec. The module must export at least one class which extends projen.Project
```
when i write the projenrc myself and run npx projen it works.

**Comment by pgollucci** [comment]
Most likely you to do a yarn build to generate the .jsii file see my # comment above.

I'm interested in the file:/ import issue though

**Comment by henrysachs** [comment]
the jsii file is in the npm package: 

```
{
  "author": {
    "email": "henry.sachs@deutschebahn.com",
    "name": "Henry Sachs",
    "roles": [
      "author"
    ]
  },
  "bundled": {
    "yaml": "^1.10.0"
  },
  "dependencies": {
    "projen": "^0.3.107"
  },
  "dependencyClosure": {
    "projen": {
      "targets": {
        "js": {
          "npm": "projen"
        }
      }
    }
  },
  "description": "@ffa/cdk-seec",
  "docs": {
    "stability": "experimental"
  },
  "homepage": "https://github.com/henrysachs/projen-test.git",
  "jsiiVersion": "1.13.0 (build 385c325)",
  "keywords": [],
  "license": "Apache-2.0",
  "name": "@ffa/cdk-seec",
  "readme": {
    "markdown": "# CDK AppSync Project\n\nThis project is meant to be used with [projen's external module](https://github.com/eladb/projen#projects-in-external-modules) feature. It will quickly create an AWS AppSync API that uses the [cdk-appsync-transformer](https://github.com/kcwinner/aws-cdk-appsync-transformer).\n\nCurrently supports\n* [![GitHub package.json dependency version (prod)](https://img.shields.io/github/package-json/dependency-version/kcwinner/aws-cdk-appsync-transformer/@aws-cdk/core)](https://github.com/aws/aws-cdk)\n\n## How To Use\n\nSince the AppSync transformer uses version `1.63.0` of the AWS CDK we want to pin our version here as there are breaking changes that have not yet been merged into the transformer construct.\n\n```bash\nnpx projen new --from cdk-appsync-project --cdk-version-pinning true --cdk-version \"1.63.0\"\n```"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/henrysachs/projen-test.git"
  },
  "schema": "jsii/0.10.0",
  "targets": {
    "js": {
      "npm": "@ffa/cdk-seec"
    }
  },
  "types": {
    "@ffa/cdk-seec.SeecApp": {
      "assembly": "@ffa/cdk-seec",
      "base": "projen.AwsCdkTypeScriptApp",
      "docs": {
        "custom": {
          "pjid": "seec-projen"
        },
        "stability": "experimental",
        "summary": "AWS CDK AppSync Transformer App in TypeScript."
      },
      "fqn": "@ffa/cdk-seec.SeecApp",
      "initializer": {
        "docs": {
          "stability": "experimental"
        },
        "locationInModule": {
          "filename": "src/index.ts",
          "line": 14
        },
        "parameters": [
          {
            "name": "options",
            "type": {
              "fqn": "@ffa/cdk-seec.SeecAppOptions"
            }
          }
        ]
      },
      "kind": "class",
      "locationInModule": {
        "filename": "src/index.ts",
        "line": 13
      },
      "name": "SeecApp"
    },
    "@ffa/cdk-seec.SeecAppOptions": {
      "assembly": "@ffa/cdk-seec",
      "datatype": true,
      "docs": {
        "stability": "experimental"
      },
      "fqn": "@ffa/cdk-seec.SeecAppOptions",
      "interfaces": [
        "projen.AwsCdkTypeScriptAppOptions"
      ],
      "kind": "interface",
      "locationInModule": {
        "filename": "src/index.ts",
        "line": 5
      },
      "name": "SeecAppOptions"
    }
  },
  "version": "1.0.2",
  "fingerprint": ""
}
```

when using from file projen writes the filename itself as the keyname in the package.json but it needs to be the value.

**Comment by henrysachs** [comment]
I just copied the linked repo and tweaked some names. Also used a scoped package name.

**Comment by pgollucci** [comment]
I'm going to have to digest that one.  I need to step away until this afternoon

**Comment by pgollucci** [comment]
nice!

**Comment by henrysachs** [comment]
I'm not quite sure if this fixes my error with projen not finding the module.
