### ISSUE TITLE
Prettier and Eslint extends

### ISSUE THREAD

**Issue by thoroc** [projen/projen#2806]
When using the [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) the official docs advice for the following:

> Then, add "prettier" to the "extends" array in your .eslintrc.* file. Make sure to put it last, so it gets the chance to override other configs.

As this is not the behaviour of the eslint component, I have to resort to do the following hack to push `prettier` as the last item in the eslint's extends list:

```typescript

// hack to push prettier as the last item in extends for eslint
if (project.eslint !== undefined) {
  const eslintExtends = project.eslint['_extends'];
  const prettierIndex = eslintExtends.indexOf('prettier', 0);
  if (prettierIndex > -1) {
    eslintExtends.splice(prettierIndex, 1);
  }
  eslintExtends.sort();
}
project.eslint?.addExtends('prettier');
```

Is this correct? Am I missing something?

**Comment by mrgrain** [comment]
Just to confirm, your report here is that while `prettier` is added to the `extends` array, it is not added as the last item like it should be?

**Comment by thoroc** [comment]
That is correct, at least when adding other item to the `eslint`'s `extends` list.

If I add the following to the `eslint` config:

```typescript
project.eslint?.addExtends(
  'eslint:recommended',
  'plugin:@typescript-eslint/eslint-recommended',
  'plugin:@typescript-eslint/recommended',
  'plugin:import/errors',
  'plugin:import/warnings',
);
```

I end up with this `eslintrc` config:

```json
{
  ...
  "extends": [
    "plugin:import/typescript",
    "prettier",
    "plugin:prettier/recommended",
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  ...
}
```

Whereas this section should be:

```json
{
  ...
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/errors",
    "plugin:import/typescript",
    "plugin:import/warnings",
    "plugin:prettier/recommended",
    "prettier"
  ],
  ...
}
```

I have not found a way to better manipulate the `eslint` config outside a change to projen itself.

**Comment by thoroc** [comment]
Oh thank you. I'll check that out.
