### ISSUE TITLE
CDK construct build faill with "TypeError: ajv_1.default is not a constructor"

### ISSUE THREAD

**Issue by marcioemiranda** [projen/projen#2811]
Hello,

I have a CDK construct project that depends on another CDK construct project. Both of them are setup using projen.

Let's call then project A and project B. Project B depends on project A.
 
Everything used to work fine, but after a "npx projen upgrade" (as of today) I started to get the following error when building project B:
"TypeError: ajv_1.default is not a constructor"

Project A builds fine.

PS: On the same day I have also updated CDK cli, which is now higher than the one in the project.
```
$ cdk --version
2.88.0 (build 5d497f9)
```
 
The stack trace (when running "yarn build" on project B) shows the following:
```
👾 build » compile | jsii --silence-warnings=reserved-word
[2023-07-23T10:50:11.907] [ERROR] jsii/package-info - Unable to find a JSII dependency named "@druid-networks/druid-constructs" as "^0.0.18". If you meant to include a non-JSII dependency, try adding it to bundledDependencies instead.

Error: Error loading assembly from file /Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/@druid-networks/druid-constructs/.jsii:
**TypeError: ajv_1.default is not a constructor**
    at loadAssemblyFromFile (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/node_modules/@jsii/spec/lib/assembly-utils.js:129:15)
    at DependencyResolver.loadAssemblyAndRecurse (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/lib/project-info.js:206:58)
    at DependencyResolver.resolveDependency (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/lib/project-info.js:198:34)
    at DependencyResolver.discoverDependencyTree (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/lib/project-info.js:153:33)
    at loadProjectInfo (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/lib/project-info.js:50:31)
    at Object.handler (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/lib/main.js:81:105)
    at /Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/node_modules/yargs/build/index.cjs:1:8993
    at j (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/Users/marciomiranda/projects/comviva/asa/asa-connector/node_modules/jsii/node_modules/yargs/build/index.cjs:1:9604)
👾 Task "build » compile" failed when executing "jsii --silence-warnings=reserved-word" (cwd: /Users/marciomiranda/projects/comviva/asa/asa-connector)
error Command failed with exit code 1.
```

My construct code in project A does not depend on ajv, but other packages do:
```
├─ @eslint/eslintrc@2.1.0
│  ├─ ajv@^6.12.4

├─ @jsii/spec@1.85.0
│  ├─ ajv@^8.12.0
│  ├─ ajv@8.12.0

├─ ajv@6.12.6

├─ eslint@8.45.0
│  ├─ ajv@^6.10.0

├─ table@6.8.1
│  ├─ ajv@^8.0.1
│  ├─ ajv@8.12.0

```
From the stack trace above it looks like it's a problem with jsii, which actually depends on ajv

This is the .projenrc.ts file from Project A:

```
 import { awscdk } from 'projen';
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Marcio Miranda',
  authorAddress: 'marcio.miranda@druid.com.br',
  cdkVersion: '2.85.0',
  defaultReleaseBranch: 'main',
  jsiiVersion: '~5.0.0',
  name: '@druid-networks/druid-constructs',
  projenrcTs: true,
  prettier: true,
  prettierOptions: { settings: { singleQuote: true } },
  repositoryUrl: 'https://github.com/druid-networks/druid-constructs.git',
  bundledDeps: [
    'deep-diff',
    'deepmerge',
    '@types/deep-diff',
    '@types/npmlog',
    'npmlog',
    'uuid',
    '@types/uuid',
  ],
});

// ignore packages or files
const commonExclude = ['cdk.out', 'yarn-error.log'];
project.npmignore?.exclude(...commonExclude);
project.gitignore.exclude(...commonExclude);

project.synth();
```
.. and this is the .projenrc.ts file from Project B:

```
import { awscdk } from 'projen';
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Marcio Miranda',
  authorAddress: 'marcio.miranda@druid.com.br',
  cdkVersion: '2.85.0',
  defaultReleaseBranch: 'main',
  jsiiVersion: '~5.0.0',
  name: '@druid-networks/asa-connector',
  projenrcTs: true,
  prettier: true,
  prettierOptions: { settings: { singleQuote: true } },
  repositoryUrl: 'https://github.com/marcio.miranda/asa-connector.git',
  deps: ['@druid-networks/druid-constructs'],
  peerDeps: ['@druid-networks/druid-constructs'],
  workflowBootstrapSteps: [
    {
      name: 'Setup NPM Token',
      run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc',
      env: {
        NPM_TOKEN: '${{ secrets.NPM_TOKEN }}',
      },
    },
  ],
});

// ignore packages or files
const commonExclude = ['cdk.out', 'yarn-error.log'];
project.npmignore?.exclude(...commonExclude);
project.gitignore.exclude(...commonExclude);
project.synth();
```

This may or may not be relevant, but in Project A I got a big warning message when upgrading stating that I should use jsii rosetta version 5 instead of 1.x, although projenrc is configured to use jsiiVersion 5.

"You are currently using jsii-rosetta@1.x. We recommend upgrading to jsii-rosetta@5.0.x or later".

Any advice?

**Comment by mrgrain** [comment]
Hi thanks for reporting this. I can't reproduce this with plain `@jsii/spec`. `ajv` is used to validate assemblies of dependencies. So if your Project B depends on Project A, when you are compiling Project B it will use `ajv` to load the assembly for Project A. 

The error is very odd. Googling indicates this might be an issue with old versions of `ajv`. Almost feels like it is suddenly attempting to load the wrong instances of `ajv`. 

> My construct code in project A does not depend on ajv, but other packages do:

This part of the tree you posted seems to indicate a direct dependency on `ajv@6.12.6`
```
├─ ajv@6.12.6
```

**Comment by mrgrain** [comment]
> This may or may not be relevant, but in Project A I got a big warning message when upgrading stating that I should use jsii rosetta version 5 instead of 1.x, although projenrc is configured to use jsiiVersion 5.

Can you post the output of `npm why jsii-rosetta` or `yarn why  jsii-rosetta`?

**Comment by marcioemiranda** [comment]
Hi, thanks for the reply!

Here is some additional info...

Result of `yarn why ajv` shows why ajv@6.12.6 is a dependency (the result is the same in both Project A and B):

```
$ yarn why ajv
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "ajv"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ajv@6.12.6"
info Has been hoisted to "ajv"
info Reasons this module exists
   - Hoisted from "eslint#ajv"
   - Hoisted from "eslint#@eslint#eslintrc#ajv"
info Disk size without dependencies: "1.12MB"
info Disk size with unique dependencies: "1.89MB"
info Disk size with transitive dependencies: "1.93MB"
info Number of shared dependencies: 5
=> Found "table#ajv@8.12.0"
info This module exists because "aws-cdk-lib#table" depends on it.
info Disk size without dependencies: "2.48MB"
info Disk size with unique dependencies: "3.18MB"
info Disk size with transitive dependencies: "3.22MB"
info Number of shared dependencies: 5
=> Found "@jsii/spec#ajv@8.12.0"
info This module exists because "jsii#@jsii#spec" depends on it.
info Disk size without dependencies: "2.48MB"
info Disk size with unique dependencies: "3.18MB"
info Disk size with transitive dependencies: "3.22MB"
info Number of shared dependencies: 5
✨  Done in 0.80s.
```
Here is the result of `yarn why jsii-rosetta`:

```
yarn why  jsii-rosetta
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "jsii-rosetta"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "jsii-rosetta@5.0.17"
info Has been hoisted to "jsii-rosetta"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "40.34MB"
info Disk size with unique dependencies: "123.99MB"
info Disk size with transitive dependencies: "180.32MB"
info Number of shared dependencies: 70
=> Found "jsii-docgen#jsii-rosetta@1.85.0"
info This module exists because "jsii-docgen" depends on it.
info Disk size without dependencies: "2.52MB"
info Disk size with unique dependencies: "86.12MB"
info Disk size with transitive dependencies: "142.51MB"
info Number of shared dependencies: 70
=> Found "jsii-pacmak#jsii-rosetta@1.85.0"
info This module exists because "jsii-pacmak" depends on it.
info Disk size without dependencies: "2.52MB"
info Disk size with unique dependencies: "86.12MB"
info Disk size with transitive dependencies: "142.51MB"
info Number of shared dependencies: 70
✨  Done in 1.02s.
```

I've checked the files changed after running npx projen upgrade, which led to this error.

The following files have changed:

- package.json
- yarn.lock
- pull-request-lint.yml
- tasks.json

The first two were expected. The later two I suspect were changed due to projen releases.

The most relevant info were the changes in package.json. The following dependencies changed:

```
"jsii-diff": "^1.84.0" => "^1.85.0"
"jsii-pacmak": "^1.84.0" => "^1.85.0"
"projen": "^0.71.137" => "^0.71.148"
```

I have noticed that jsii and other dependent packages (jsii@spec etc, which use ajv) had a release on 17-07-2023. This is the changelog:

```
[1.85.0](https://github.com/aws/jsii/compare/v1.84.0...v1.85.0) (2023-07-17)
Bug Fixes
export transliterateAssembly and fix bug with transliterate cli (backport) (https://github.com/aws/jsii/issues/4166) ([6b7eb02](https://github.com/aws/jsii/commit/6b7eb02f3a822941185e8c74be71d677285c741e))
go-runtime: use fatih/color instead of ANSI Escape Code (https://github.com/aws/jsii/issues/4109) ([28b192a](https://github.com/aws/jsii/commit/28b192aa1a3ecdd3b3ce6ee49a5efd32db01e695))
```

So I wonder if the change in jsii caused this break.

Could you confirm the steps required to undo `npx projen upgrade`?

If the undo is successful, what would be the steps to upgrade just the packages that I manage. For example, suppose project B depends on package C (a private package of mine, regular typescript lib, no CDK construct), and I want to upgrade just this package without upgrading for example jsii. Is it enough to add the exact version in the dependencies array of projenrc and then run `npx projen`?

**Comment by mrgrain** [comment]
Hm, that still doesn't really explain the `ajv` issue. You could try deleting `yarn.lock` and `node_modules` and then run `yarn install` in Project B.

--- 

The change in the jsii 1.85.0 release was in `jsii-rosetta` and it's unrelated. The dependencies haven't changed in `@jsii/spec`.

Regarding the rosetta warning, you need to upgrade you version of jsii/docgen.

--- 

You can revert the upgrade simply by reverting the PR or commit. To upgrade only some versions, you can change the version number in `package.json` if the dependency version constraint is not locked by projen.

**Comment by marcioemiranda** [comment]
I've reverted the changes done by `npx projen upgrade` and ran `yarn install` again. The project built fine. Now I am upgrading just my own packages by changing versions in projenrc. Not ideal but worked.

Regarding the jsii/docgen version, this dependency (and version) is added by projen.

**Comment by mrgrain** [comment]
> Regarding the jsii/docgen version, this dependency (and version) is added by projen.

That's correct. It currently doesn't mandate the version used for jsii-docgen though and if you project is relatively old, it would have started out with an older major version of jsii-docgen which projen doesn't upgrade by default. I can see how this is awkward.

**Comment by marcioemiranda** [comment]
The project is new, 1 month or so. So, how do I upgrade then? Just add to devDependencies array with a specific version and it will override it? Which version is recommended?

**Comment by mrgrain** [comment]
Change the version number in `package.json` - But since your project is new. What version is `jsii-docgen` currently on?
