### ISSUE TITLE
Installing with `save=false` in .npmrc fails with `Error: Unable to resolve package name from spec`

### ISSUE THREAD

**Issue by strugee** [projen/projen#2837]
To reproduce: `projen new --from 'git@github.com:projen/projen-github-action-typescript.git'`

Logs:

```
$ projen new --from 'git@github.com:projen/projen-github-action-typescript.git'
/tmp/tmp.eWcDhTwZBt
└── (empty)


added 1 package, and audited 69 packages in 1s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Wrote to /tmp/tmp.eWcDhTwZBt/package.json:

{
  "name": "tmp.ewcdhtwzbt",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "projen": "^0.71.156"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "AJ Jordan <alex@strugee.net>",
  "license": "LGPL-3.0+"
}


👾 installing external module git@github.com:projen/projen-github-action-typescript.git...

added 1 package, and audited 70 packages in 55s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Error: Unable to resolve package name from spec git@github.com:projen/projen-github-action-typescript.git
    at installPackage (/var/home/alex/.local/lib/node_modules/projen/lib/cli/util.js:26:15)
    at initProjectFromModule (/var/home/alex/.local/lib/node_modules/projen/lib/cli/cmds/new.js:231:50)
    at Object.handler (/var/home/alex/.local/lib/node_modules/projen/lib/cli/cmds/new.js:95:26)
    at /var/home/alex/.local/lib/node_modules/projen/node_modules/yargs/build/index.cjs:1:8993
    at j (/var/home/alex/.local/lib/node_modules/projen/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/var/home/alex/.local/lib/node_modules/projen/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/var/home/alex/.local/lib/node_modules/projen/node_modules/yargs/build/index.cjs:1:9604)
    at _.runCommand (/var/home/alex/.local/lib/node_modules/projen/node_modules/yargs/build/index.cjs:1:7231)
    at te.[runYargsParserAndExecuteCommands] (/var/home/alex/.local/lib/node_modules/projen/node_modules/yargs/build/index.cjs:1:58912)
    at _.parseAndUpdateUsage (/var/home/alex/.local/lib/node_modules/projen/node_modules/yargs/build/index.cjs:1:8102)
⬢[alex@toolbox tmp.eWcDhTwZBt]$ projen --verrsion
👾 Unable to find projen project. Use "projen new" to create a new project.

$ projen --version
0.71.156

$ node --version
v16.18.1
```

**Comment by mrgrain** [comment]
Yes this is expected. projen can only install from compiled jsii packages. This git repository is not a compiled jsii package. Amongst other things, it lacks the `.jsii` file.

Can In ask what you are trying to achieve here?

**Comment by strugee** [comment]
Yes, at the time I filed this bug report the affected package was not on npm, only on the author's personal GitHub npm registry. I wanted to provision a project like this to work around the fact that GitHub Packages requires authentication, which is annoying. The package has since been published to npm proper.

If you look at the traceback, you'll see it's not related to not finding a `.jsii` file. I also just realized I forgot to include a critical piece of information - the above traceback only seems to happen when `save=false` is specified in `~/.npmrc`.

**Comment by strugee** [comment]
Even if the bug reported here were fixed, stuff would still be crashing with "unable to find `.jsii` file" errors (I know because I saw them when I removed `save=false`). The reason I expected this to work ok in the first place is this line:

https://github.com/projen/projen/blob/4f7537bb2b994069d65693eac7b1627424c0c787/src/cli/cmds/new.ts#L36

As someone new to projen, my brain didn't really register "jsii" in that sentence. So I thought to myself, oh, well it supports anything npm supports which would include git modules. Maybe projen could emit a warning whenever this situation is detected? (Or maybe it's just user error and not worth doing anything about, though again, the traceback reported in the issue description is definitely a bug.)

**Comment by mrgrain** [comment]
I agree the error message could be much better! Thanks for reporting it. 

Setting `save=false` is interesting and also unexpected. It should only be necessary for the package to be available in `node_modules`.

**Comment by strugee** [comment]
Sure thing. https://github.com/projen/projen/blob/4f7537bb2b994069d65693eac7b1627424c0c787/src/cli/util.ts#L6 is the function you want to look at - AFAICT saving to `package.json` is used to determine which package is actually being installed, presumably so it can be `require()`'d by name later. Take for example this case where you're installing from git and can't tell before install what the package name is.

**Comment by mrgrain** [comment]
Interestingly we already specify `--save-dev` in the install command. I'm surprised the `.npmrc` value takes priority. That should not happen.

**Comment by mrgrain** [comment]
🤦🏻  So turns out we just need to change the command to say `npm install --save --save-dev` to make sure the `save=false` is ignored. It still ends up as a dev dep.
