### ISSUE TITLE
New project type: octoherd-script-ts

### ISSUE THREAD

**Issue by ahammond** [projen/projen#2841]
The perfect pairing for dozens of projen'd repos is OctoHerd https://github.com/octoherd/octoherd . OctoHerd is a way to run scripts at scale across large numbers of GH repos. Perfect for triggering actions or driving through Renovate PRs https://github.com/time-loop/octoherd-script-renovate-library-major-version-driver

Anyway, I think it'd be awesome to have an `octoherd-script-ts` project to manage octoherd scripts.

**Comment by mrgrain** [comment]
Moved to discussion: https://github.com/projen/projen/discussions/2214#discussioncomment-6624884
Although I'd also encourage people to publish by themselves.
