### ISSUE TITLE
Add `.gitattributes` to `.npmignore`

### ISSUE THREAD

**Issue by moltar** [projen/projen#2877]
It looks like `.gitattributes` is being bundled into the NPM package.

While not a big deal, I do think it's a candidate to be added to `.npmignore`.

Even `projen` project itself is doing this :)

https://github.com/projen/projen/blob/3ec10fe44ec7b587b59e910f43abe58a1c75909f/.projenrc.js#L209

**Comment by matt9ucci** [comment]
@moltar @mrgrain The issue might be fixed with #3223
