### ISSUE TITLE
Release mechanism tries to publish existing packages

### ISSUE THREAD

**Issue by vinayak-kukreja** [projen/projen#2921]
Projen is relying on remote package managers to reject publishing request for an existing package. We should validate this even before we start the publishing.

Recently, this mechanism caused an outage for Maven since it was opening staging repositories and abandoning them when the package existed. This lead to creation of multiple abandoned staging repositories which impacted Maven's cleanup process.

**Comment by mrgrain** [comment]
Related to #2763

**Comment by dkershner6** [comment]
@mrgrain , happy to throw a few hours at this, but would like a bit of guidance up front.

I can envision a simple implementation where the `bump` task creates another file.  This file can then be used by the GitHubWorkflow with an if conditional on whether to continue.

I can envision a more global implementation where we implement some kind of Task gains outputs and provides Github (or other CI/CD) them through a translation.

There are likely ideas in between, but what pops in your head?

**Comment by mrgrain** [comment]
My original idea was that `bump` and build etc, does already produce a file `dist/tag.txt` or something. If we read this file, and check if we that's a tag that already exists on the repo, then we can skip the publish jobs.

No idea if that works though.

**Comment by dkershner6** [comment]
@mrgrain , implemented pretty much exactly as you wrote: https://github.com/projen/projen/pull/3252
