### ISSUE TITLE
Interactive mode for 'projen new'

### ISSUE THREAD

**Issue by hoegertn** [projen/projen#293]
I propose running inquirer after running `projen new` if no project type is given.

So instead of just printing out the options, the user would be able to directly select a project type to create.

**Comment by eladb** [comment]
Contributions are welcome. Not 100% sure about how much value this brings but it could definitely be a nice addition.

We've been discussing maybe adding some kind of an annotation to flags that indicate if they are "featured" and only then include them (by default) as commented out options for `projen new`. Perhaps we can use the same annotation to determine if those will be part of the interactive experience.

**Comment by eladb** [comment]
Duplicate with #613
