### ISSUE TITLE
Feature Requesst: Codebuild BuildSpec

### ISSUE THREAD

**Issue by thomasklinger1234** [projen/projen#295]
projen should generate [Buildspec](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html) files.

## Desired Solution

Possible API:

```
const buildspec = new projen.BuildSpec(project, ".codebuild/buildspec.yml", {
  ....buildspec content
})
buildspec.addCommand("phase-name", "echo 'hello world'")
buildspec.addCommands("phase-name", [
  "echo 'hello world'"
])
```

**Comment by pgollucci** [comment]
Are you expecting   ....buildspec content to be yaml?  I believe projen would provide thing API layer similar to mergify

**Comment by thomasklinger1234** [comment]
> Are you expecting ....buildspec content to be YAML? I believe projen would provide thin API layer similar to mergify

Yes, the generated content should be YAML I think. There seems to be support for generated YAML files (GItHub workflows, mergify etc).
