### ISSUE TITLE
local dependency fails with jsii

### ISSUE THREAD

**Issue by jeromevdl** [projen/projen#3006]
Hi, I have a lerna project with 2 `AwsCdkConstructLibrary` projen projects (let's say `foo` & `bar`).

`bar` is depending on `foo`. I tried the following in `bar`:
```
deps: [
    'foo@file:../foo',
],
```

but it fails with jsii and the error: 

```
Declared dependency on version file:../foo of foo, but version 0.0.0 was found
  at DependencyResolver.discoverDependencyTree (...node_modules/jsii/lib/project-info.js:161:23)
  at loadProjectInfo (...node_modules/jsii/lib/project-info.js:50:31)
  ...
```

I also tried to use the tgz in the dist of `foo`, but had the error (plus it's not easy to have the foo project built before bar install): 
```
Error: ENOTDIR: not a directory, open '.../dist/js/foo@0.0.0.tgz/package.json'
  at _resolveVersion (...node_modules/jsii/lib/project-info.js:312:36)
  at DependencyResolver.resolveDependency (...node_modules/jsii/lib/project-info.js:188:58)
```

Is there a way to achieve this without error from projen / yarn / jsii or whatever other tools?

**Comment by mrgrain** [comment]
As discussed in DMs, this seems to be an issue with jsii not supporting dependencies defined using `file:`.

**Comment by jeromevdl** [comment]
https://github.com/aws/jsii/issues/4300
