### ISSUE TITLE
construct dependency is now adding to all projen repos even non-cdk

### ISSUE THREAD

**Issue by tinovyatkin** [projen/projen#3047]
That commits is adding construct dependency to the repo that didn't use it.

See [this](https://github.com/tinovyatkin/appsync-client-node/pull/50) as an example.

**Comment by mrgrain** [comment]
Hi, this was on purpose. Does it cause an issue?

**Comment by tinovyatkin** [comment]
Oops, I didn't notice that such a huge change to projen internals was merged with just 3 NIT comments from a reviewers 😳.
