### ISSUE TITLE
Create repository

### ISSUE THREAD

**Issue by eladb** [projen/projen#310]
This:

```sh
$ projen new PROJECT-TYPE my-new-project # second positional argument should allow a subdirectory name
...Creating GH repo
...Cloning
...Running "projen new"
...Building
...Creating initial commit
...Pushing to repo
```

Here's what I need to do today in order to create a new (jsii) project:

1. Create a github repo
2. Clone it to my machine (or create a local git repo and `add origin` to this new repo).
3. Run `projen new PROJECT-TYPE`
4. Make sure it builds (runs `yarn build`).
5. Commit to `main`
6. Push to origin
7. Go to GitHub UI and add secrets: `NPM_TOKEN` and publishing tokens to all package managers (lots of fun here)

----

First release
1. Enable release in `projen` by setting jsii configuration for each language (`maven`, `nuget`, `pypi`, ...).
2. Run `projen`
3. Commit
4. Push

---

Proposed by @campionfellin

**Comment by campionfellin** [comment]
![out](https://user-images.githubusercontent.com/11984923/99867458-7ab4d380-2b6e-11eb-8b63-cd938fc1524d.gif)
