### ISSUE TITLE
There are no means of setting the `esbuild` format to ESM

### ISSUE THREAD

**Issue by giseburt** [projen/projen#3102]
When building a TypeScript App to bundle with the Bundler, things like top-level await need bundled differently.

`esbuild` provides this control via the `--format=esm` flag: https://esbuild.github.io/api/#format

There's not even a clean escape hatch that doesn't completely blow away the build tasks. (There's no means of adding to a task command, AFAICT, and I'm not sure I'd really want to do that anyway, as it seems terribly fragile.)

This is simple to add, and I'll have a PR for it ready soon.

**Comment by mrgrain** [comment]
> Do we also want to add escape hatches for other unsupported / unknown options in esbuild? Similar to how the AWS CDK NodejsFunction has the [esbuildargs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#esbuildargs)?

@giseburt Yes! That would be awesome!
