### ISSUE TITLE
Feature Request: expressJS app template

### ISSUE THREAD

**Issue by campionfellin** [projen/projen#313]
Would be nice to have `npx projen new express`.

Could probably use https://expressjs.com/en/starter/hello-world.html as the templating.

🚀

**Comment by eladb** [comment]
Besides being a node project with an express dependency, what other value does this abstraction would offer?

**Comment by campionfellin** [comment]
I guess there's a few routes we could go, depending on how much abstraction we want. We could do something simple, like just generating the basic `index.js` file [like here](https://github.com/expressjs/express/blob/master/examples/web-service/index.js).

We could go slightly more complicated and do what `npx express-generator` does (which is to create all of this:

```
.
├── app.js
├── bin
│   └── www
├── package.json
├── public
│   ├── images
│   ├── javascripts
│   └── stylesheets
│       └── style.css
├── routes
│   ├── index.js
│   └── users.js
└── views
    ├── error.pug
    ├── index.pug
    └── layout.pug

7 directories, 9 files
```

[link here](https://expressjs.com/en/starter/generator.html)

Or we could even go as far as combining this with React as a template like [this repo](https://github.com/conor-deegan/web-app-boilerplate)

**Comment by campionfellin** [comment]
Closing. I think you're right, this abstraction doesn't offer a ton of benefit.
