### ISSUE TITLE
CDK projects: configure VSCode debugger

### ISSUE THREAD

**Issue by eladb** [projen/projen#314]
Would be awesome if CDK projects will be configured by default with VSCode debugger.
Follow @tlakomy's blog: https://tlakomy.com/use-vscode-debugger-for-cdk

**Comment by tlakomy** [comment]
I think that I could give it a shot if you're interested! @eladb

**Comment by eladb** [comment]
Yes, would be great.

**Comment by tlakomy** [comment]
Okay, looking into it - what's the best way to create a `AwsCdkTypeScriptApp` with local changes?

**Comment by eladb** [comment]
Just compile `projen` and run `bin/projen` from your local directory.
