### ISSUE TITLE
Bug: IniFile produces invalid syntax for arrays

### ISSUE THREAD

**Issue by straygar** [projen/projen#3143]
Ran into this bug while trying to create a `setup.cfg` file for my custom Python project.

## Reproduction Steps

```
new IniFile(project, 'setup.cfg', {
    obj: {
      flake8: {
        exclude: ['foo', 'barr'],
      },
    },
});
```

## Expected

The produced file would be a valid ini syntax, either:
```
[flake8]
exclude[0]=foo
exclude[1]=barr
```

or the more popular (in the Python ecosystem):
```
[flake8]
exclude =
  foo,
  barr
```

## Actual

Non-standard ini syntax:
```
[flake8]
exclude[]=foo
exclude[]=barr
```

**Comment by straygar** [comment]
To work around this, I'm just turning all arrays into comma-separated strings (`[].join(',')`) (but I imagine there might be cases where this doesn't work).

**Comment by mrgrain** [comment]
Hi @straygar Can you provide some more details on why the generated syntax is "non-standard"?

We are using a third-party library for this that is extremely popular, and this appears the way it's supposed to be:
https://www.npmjs.com/package/ini#usage

**Comment by straygar** [comment]
Yeah, I'm surprised this never came up. I'm not sure if there is a clear standard, or whether Python's built in `configparser` chooses to do things differently, but:

```
exclude[]=.git
exclude[]=.eggs
exclude[]=__pycache__
exclude[]=docs
exclude[]=build

```
raises:
```
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/snng/lib/python3.10/configparser.py", line 1098, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/Users/aigars/workspace/limbic/setup.cfg' [line  8]: option 'exclude[]' in section 'flake8' already exists
```

**Comment by straygar** [comment]
EDIT: My bad, according to [this](https://en.wikipedia.org/wiki/INI_file), `configparser` doesn't support arrays at all, hence all multi-value args are comma-separated strings in `setup.cfg`.

Should we close this issue or consider making this more explciit for python use-cases?
