### ISSUE TITLE
VS Code Recommended Extensions

### ISSUE THREAD

**Issue by henrysachs** [projen/projen#315]
Would be nice to manage recommended Extensions with Projen: https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions 
just a json file with an array of strings.

**Comment by eladb** [comment]
Yes!

**Comment by pgollucci** [comment]
If https://github.com/projen/projen/pull/316 fixes this, then this can be closed. @eladb 

I'm glad I found #316.
