### ISSUE TITLE
Support subproject releases

### ISSUE THREAD

**Issue by Sparkdaddy** [projen/projen#3172]
I took a look through the issues and source code and didn't find a reason this wasn't implemented other than ["By default, GitHub workflows will not be created for subprojects since config files in .github/ only work if they are in the root directory."](https://github.com/projen/projen/blob/main/docs/subproject.md).

I have a use-case where I am defining an SDK for a library as a subproject and would like that specific SDK to be released to npm. It would also be quite nice to have a release for the main project as well. If the workflows reason above is the gist for why it hasn't been implemented then I thought the subproject directory would provide most of the distinction from the other workflows used. For example, `release.yml` for the root and then `release-sdk.yml` for the SDK subproject based on the `sdk` directory. Then you could have a default behavior of using the directory in the `releaseTagPrefix` as well to distinguish the SDK release from the other ones.

Overall, I'm curious if there's a reason besides the root directory needing to have the workflows in Github that this isn't implemented. And if not, what would you think of the above behavior?

**Comment by mrgrain** [comment]
Even that link of yours is just a description of the current state and not a reason.

There is no reason this hasn't been implemented yet other than the it's hasn't been implemented yet and the it's maybe a bit more complicated to generalize as a single project release.

**Comment by Sparkdaddy** [comment]
Totally understand - I'll look into implementing it today and see if I'm worthy enough to make the addition

**Comment by mrgrain** [comment]
I have a half-baked solution ready, but it's highly coupled to the monorepo implementation we use. Hopefully still useful.
- https://github.com/cdklabs/awscdk-service-spec/blob/main/projenrc/monorepo-release.ts
- https://github.com/cdklabs/awscdk-service-spec/blob/main/projenrc/workspace-release.ts

**Comment by dkershner6** [comment]
I half-baked something totally differently than mrgrain and CDKlabs, but i'll take a stab at this since I don't see any in progress PRs on it, maybe I can make all our lives easier.

**Comment by dkershner6** [comment]
Just tried out the new functionality on a 12 library publishing monorepo where I was hacking it together before.

I just deleted my hack, added a compile command for inner-monorepo dependencies to `releaseWorkflowSetupSteps`, and it deployed all 12 like butter.
