### ISSUE TITLE
Generated tsconfig.jest.json doesn't merge/use  jestOptions.typescript

### ISSUE THREAD

**Issue by guillaumemaka** [projen/projen#320]
Hi everyone,

I noticed that jestOptions.typescript is not used. When I provide the configuration it doesn't get merged in tsconfig.jest.json 

```
jest: true,
  jestOptions: {
    ignorePatterns: ['/cdk/', '/node_modules/'],
    typescript: {
      compilerOptions: {
        esModuleInterop: true,
        typeRoots: ['src/types', 'node_modules/@types'],
      },
      exclude: ['cdk', 'node_modules'],
    },
  },
```

https://github.com/projen/projen/blob/dc46e9351f2cc5b6e190789f0a6e9c135f99f08a/src/typescript.ts#L212-L225

Regards

**Comment by kcwinner** [comment]
Looking into this. Will also provider additional options / support for jest options from https://jestjs.io/docs/en/configuration

Also, looking to provide a generic escape hatch (per @eladb).
