### ISSUE TITLE
Configuration problems for ts-jest

### ISSUE THREAD

**Issue by doublecompile** [projen/projen#3224]
The [recent changes related to `ts-jest`](https://github.com/projen/projen/commit/2ccae024e1ee8f00a9066c6dce7e1d0d8b50c4b5) have introduced new issues with ESM projects.

There are two issues: 

1. The property name [`tranformPattern` is misspelled](https://github.com/projen/projen/blob/77532dbaa115d2b8e3e37d6548ab721518fe6b3c/src/typescript/typescript.ts#L228C12-L228C27) (and should be `transformPattern`).
2. The [`useEsm` property needs to be entirely uppercase](https://github.com/projen/projen/blob/77532dbaa115d2b8e3e37d6548ab721518fe6b3c/src/typescript/typescript.ts#L217), i.e. `useESM`. It won't work as-is (see [official documentation](https://kulshekhar.github.io/ts-jest/docs/next/getting-started/options/useESM/)).

**Comment by dkershner6** [comment]
My mess, i'll get it cleaned up.
