### ISSUE TITLE
(AwsCdkPythonApp): Scoped project packages not installing correctly

### ISSUE THREAD

**Issue by automartin5000** [projen/projen#3232]
We use scoped package names. However, in Python projects, the project dependency doesn't seem to be getting set correctly. It's getting left as `@scope/package` instead of being converted to `scope-package`. This is both in requirements.txt and pyproject.toml (with Poetry)

**Comment by mrgrain** [comment]
Pretty sure you are supposed to define `scope-package`. What made you think that you should use `@scope/package`? Just so we can fix the docs.

**Comment by automartin5000** [comment]
> Pretty sure you are supposed to define `scope-package`. What made you think that you should use `@scope/package`? Just so we can fix the docs.

I didn't define anything AFAIK. It's the dependency Projen got from running `npx projen new --from @scope/package`

**Comment by automartin5000** [comment]
> I see. I think this is a duplicate of #2475 Closing in favor of that. LMK if you think it's different.

Thanks, yes that is the same issue. Sorry I missed that one.
