### ISSUE TITLE
feat(npmrc): Registry Auth Tokens

### ISSUE THREAD

**Issue by dkershner6** [projen/projen#3233]
https://docs.npmjs.com/cli/v10/configuring-npm/npmrc#auth-related-configuration

(the separator is not equals)

**Comment by mrgrain** [comment]
Not sure I follow here, but you'll probably create the PR yourself anyway. I'll leave you to it 😅

**Comment by dkershner6** [comment]
Actually I will probably need your help, @mrgrain .

Currently this is implemented as an `IniFile`, which makes sense since even NPM says it is an INI-file.  All examples below are from the page I linked.

This easily supports the patterns we currently have:

`@myscope:registry=https://mycustomregistry.example.org` for example, since INI are separated by equals.

BUT, npmrc has settings NOT separated by equals.  Bolded not supported by our `IniFile`

```
; bad config
_authToken=MYTOKEN # We could support this, if it worked.

; good config
@myorg:registry=https://somewhere-else.com/myorg
@another:registry=https://somewhere-else.com/another
**//registry.npmjs.org/:_authToken=MYTOKEN**
; would apply to both @myorg and @another
**; //somewhere-else.com/:_authToken=MYTOKEN**
; would apply only to @myorg
**//somewhere-else.com/myorg/:_authToken=MYTOKEN1**
; would apply only to @another
**//somewhere-else.com/another/:_authToken=MYTOKEN2**
```

We could move away from IniFile to TextFile, but I don't know all the implications.

**Comment by mrgrain** [comment]
I'm still lost. All of these lines are separated by a `=`? 🤔

Implication of using a TextFile is more work, and we loose the features of IniFile. I'd rather fix the problems with IniFile

**Comment by dkershner6** [comment]
Oh boy...

Just ignore me.  Thanks for the sounding board.

**Comment by mrgrain** [comment]
Another happy customer 😆
