### ISSUE TITLE
bug: changelog update fails when creating a new releasing when a pre-release with the same version is present

### ISSUE THREAD

**Issue by suhussai** [projen/projen#3235]
## Overview

This is what I'm seeing when trying to create a new release using `npm run release`:

```
👾 release » publish:git | '...node/18.17.1/bin/node' '...node_modules/projen/lib/release/update-changelog.task.js'
👾 Changelog already contains an entry for 0.0.1. Skipping changelog update.
👾 release » publish:git | ...
```

In my case, I have other releases that look like this:

```
v0.0.1-beta.0
v0.0.1-beta.1
...
```

## Potential Cause

I believe this is because of the following test:

https://github.com/projen/projen/blob/314fd0c78e994f1cd0cffbdc6f3db4e2291c4e27/src/release/update-changelog.ts#L74

That checks for the existence of the version (`v0.0.1` in this case) in the existing changelog file. Because `v0.0.1` exists in the tag `v0.0.1-beta.1`, I think that this incorrectly assumes that an entry already exists for 0.0.1 in the changelog and skips that step.

Any thoughts on this?

**Comment by mrgrain** [comment]
Looks like you are dealing with an inconsistent state here? You don't have a `v0.0.1` tag yet, but already have a changelog entry for it. projen is quite likely not able to deal with these kind of inconsistency in a way that suits everyone.

What would you expect instead here? A hard error?

**Comment by suhussai** [comment]
Did projen somehow create changelog entry before or was it confused because I already had changelog entries for the previous beta-release tags (like `v0.0.1-beta.0` and `v0.0.1-beta.1`)? I was thinking it was the latter because the tag strings for the beta releases like `v0.0.1-beta.0` (that would be present in the changelog) contain the string `v0.0.1`, so it's possible that based on the check in the line I linked, projen is assuming that the changelog entry already exists.

Does that make sense or am I off-base here?

**Comment by mrgrain** [comment]
No my bad, I think you are right. Misread the code and your comment. 🤦‍♂️

**Comment by suhussai** [comment]
No worries. Should I create a PR to address this?

**Comment by mrgrain** [comment]
Yes please if you can! Make sure you add a test case for it.

I'm guessing the fix will be to have a more elaborate regex to match the version string?
