### ISSUE TITLE
feat(subproject): Only release (GitHub Workflow) when that subproject has changed

### ISSUE THREAD

**Issue by dkershner6** [projen/projen#3247]
This is likely as simple as an `if` on the associated job, but I don't know how to write that conditional.

**Comment by mrgrain** [comment]
It's tricky. You kind of need to know which commit the last one was that got released. In projen this is logic resides within the bump command.

If no bump has occurred, there is nothing to release. If we have bumped, then release something. But it's not super efficient at the moment.

**Comment by dkershner6** [comment]
Very open to ideas, but I am pretty far in over my head on this one.

Not having this is not the end of the world, but it would be kind of nice if in a big monorepo, the changelogs actually associated to the library that received the change.  As is, every library in the monorepo gets every change in its logs, whether it touched the code or not.

It would also cut down on version bumps, of course, which is nice.

**Comment by mrgrain** [comment]
This doesn't happen to be a public repo?

**Comment by mrgrain** [comment]
We are doing something similar [over there](https://github.com/cdklabs/awscdk-service-spec) and our change logs are as expected. Don't think this would be a hard problem to solve. Probably something around how and where the bump command is executed?!

**Comment by dkershner6** [comment]
> This doesn't happen to be a public repo?

I have not tried, if that's what you mean. I was just speaking of monorepos abstractly.

I have a public, projen powered monorepo, though, if we need it.

**Comment by dkershner6** [comment]
> We are doing something similar [over there](https://github.com/cdklabs/awscdk-service-spec) and our change logs are as expected. Don't think this would be a hard problem to solve. Probably something around how and where the bump command is executed?!

Hard for me to parse, lots going on that is custom.  There does seem to be a Releasable Commits concept at play that seems like it would at least be nearby...

**Comment by dkershner6** [comment]
Releasable Commits definitely does affect things, but more changes are required than that it seems, because even when it detects no commits, it still tries to release and publish everything (and erroring due to no version bump).

I also used it incorrectly, because it didnt detect commits anywhere, even when I did change things.

**Comment by mrgrain** [comment]
> > This doesn't happen to be a public repo?
> 
> I have not tried, if that's what you mean. I was just speaking of monorepos abstractly.

Wait are you saying this isn't an issue you actually have observed yet? Just something you think might happen?

**Comment by mrgrain** [comment]
>  because even when it detects no commits, it still tries to release and publish everything (and erroring due to no version bump).

This is indeed the current behavior of it. It's not great, but it works. I think there's an issue here somewhere that is about stopping this earlier.

**Comment by mrgrain** [comment]
I'm sure there are a missing edge cases or the defaults needs to change. If you have a more concrete example we can definitely make it easier.

**Comment by dkershner6** [comment]
All I was experiencing was a simple case of not knowing this feature existed, and the default is not to use it.  The explanations surrounding it in code are great, and it was easy to figure out.  Now I have it "working", and the only bugs I experience are the same or similar to ones already reported, especially the link you provided.  We can continue the conversation there, although I am pretty unfamiliar with this zone of projen to fix this myself.

**Comment by mrgrain** [comment]
The release component is a beast. You might be the person who's second most familiar with it now 😜
