### ISSUE TITLE
Links in README for built-in project types are broken

### ISSUE THREAD

**Issue by MarkSFrancis** [projen/projen#3267]
Links in the README for [built-in projects](https://github.com/projen/projen/tree/main?tab=readme-ov-file#project-types) point to URLs that don't work (like https://projen.io/api/API.html#awscdkjavaapp-).

I assume they should point towards the relevant part in the API docs? For example, for "AWS CDK app in Java", it might point to this page: https://projen.io/docs/api/awscdk#awscdkjavaapp-

Looks like that documentation is autogenerated by [this script](https://github.com/projen/projen/blob/main/scripts/readme-projects.js) but that script imports a file that doesn't exist (`../lib/inventory`). I assume it meant to import from [this file](https://github.com/projen/projen/blob/main/src/inventory.ts) (`../src/inventory`). It's worth noting however that the new file is TS, whereas the old was JS. 

I haven't tested if that new `../src/inventory` generates the correct links. Happy to investigate and create a PR to update the `readme-projects.js` script / README / update `inventory.ts` if that's helpful - let me know!

**Comment by mrgrain** [comment]
**awscdk**
https://projen.io/docs/api/awscdk#awscdkjavaapp-
https://projen.io/docs/api/awscdk#awscdkpythonapp-
https://projen.io/docs/api/awscdk#awscdktypescriptapp-
https://projen.io/docs/api/awscdk#awscdkconstructlibrary-

**cdk8s**
https://projen.io/docs/api/cdk8s#cdk8spythonapp-
https://projen.io/docs/api/cdk8s#cdk8stypescriptapp-
https://projen.io/docs/api/cdk8s#constructlibrarycdk8s-

**java**
https://projen.io/docs/api/java#javaproject-

**jsii** (under cdk)
https://projen.io/docs/api/cdk#jsiiproject-

**nextjs** (under web)
https://projen.io/docs/api/web#nextjsproject-
https://projen.io/docs/api/web#nextjstypescriptproject-

**node** (under javascript)
https://projen.io/docs/api/javascript#nodeproject-

**projen**
https://projen.io/docs/api/projen#project-

**python**
https://projen.io/docs/api/python#pythonproject-

**react** (under web)
https://projen.io/docs/api/web#reactproject-
https://projen.io/docs/api/web#reacttypescriptproject-

**typescript**
https://projen.io/docs/api/typescript#typescriptproject-
https://projen.io/docs/api/typescript#typescriptappproject-
