### ISSUE TITLE
Where to find Project type Docs during Doc Migration to new site?

### ISSUE THREAD

**Issue by jacob-petterle** [projen/projen#3270]
I can't find the project type specific docs anymore and the old url redirects to an empty page:
![image](https://github.com/projen/projen/assets/45721962/8d8b4652-02b9-44dc-976b-7d3db8531720)

Seems like #3267 is a byproduct of this migration as well.

I'd be happy to merge this issue there if this feels like a duplicate.

**Comment by mrgrain** [comment]
Yeah same issue
