### ISSUE TITLE
After upgrading to projen: error TS1110: Type expected.

### ISSUE THREAD

**Issue by markussiebert** [projen/projen#3324]
Hi,

after upgrading "projen": "^0.79.2" to projen": "^0.79.7" my build stops working and complains about:

https://github.com/dbsystel/cdk-sops-secrets/pull/955

```bash
Error: 2-03T08:04:02.659] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
Error: node_modules/@types/node/ts4.8/crypto.d.ts:3495:[17](https://github.com/dbsystel/cdk-sops-secrets/actions/runs/7765551748/job/21180373028#step:9:18) - error TS1110: Type expected.

3495     type UUID = `${string}-${string}-${string}-${string}-${string}`;
                     ~~~
👾 Task "release » build » compile" failed when executing "jsii --silence-warnings=reserved-word" (cwd: /__w/cdk-sops-secrets/cdk-sops-secrets)
```

Anyone else seeing similar issues?

**Comment by mrgrain** [comment]
Yes. `@types/node` has released a version that is not compatible with older versions of TypeScript anymore (you are likely using TS 3.9). 

Best way forward is to upgrade to a current version of TS and jsii.

Alternatively use a pin to use the last working version.

**Comment by mrgrain** [comment]
Also failing tests in projen itself.

**Comment by mrgrain** [comment]
`@types/node@16.18.78` is the last `^16` version that works.
`@types/node^18.11.19` is the last `^18` version that works.

Also tested `@types/node^20` but these never worked, so I'm falling back to ^18 for them.
