### ISSUE TITLE
`projen upgrade` fails due to `pnpx` deprecation

### ISSUE THREAD

**Issue by apkostka** [projen/projen#3332]
`pnpx` has been deprecated in favor of `pnpm dlx` and `pnpm exec`. `projen upgrade` fails with versions of pnpm since v7, when it was removed. [This line](https://github.com/projen/projen/blob/41b610dce6ed2c851e9b395cf92798e5ef704a37/src/javascript/upgrade-dependencies.ts#L240) should replace `pnpx` with `pnpm dlx`.

**Comment by mrgrain** [comment]
I think your link is incorrect ;)

**Comment by apkostka** [comment]
Heh, sorry. I'm terrible with Copy+Paste.
Edited with correct link, which is: https://github.com/projen/projen/blob/41b610dce6ed2c851e9b395cf92798e5ef704a37/src/javascript/upgrade-dependencies.ts#L240
I had planned to make a PR yesterday, but got sidetracked. Hopefully can submit one soon.
