### ISSUE TITLE
(github) Update Deprecated action versions because of Node.js 16 deprecation

### ISSUE THREAD

**Issue by dkershner6** [projen/projen#3337]
Node.js 16 actions are deprecated. We need to update actions to the latest version.

Please include only a single action per PR!

Known actions that require updates:
- [x] setup-go https://github.com/projen/projen/pull/3597
- [x] setup-java https://github.com/projen/projen/pull/3599
- [x] setup-dotnet https://github.com/projen/projen/pull/3598
- [x] Upload/download artifact: https://github.com/projen/projen/pull/3335
- [x] App Token: https://github.com/projen/projen/pull/3338
- [x] Checkout
- [x] pnpm-setup
- [x] setup-node
- [x] setup-python
- [x] create-pull-request
- [x] codecov/codecov-action https://github.com/projen/projen/pull/3531#pullrequestreview-2008379264

---

## Original issue

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, pnpm/action-setup@v2.2.4, actions/setup-node@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by chris-bateman** [comment]
#3335

**Comment by dkershner6** [comment]
https://github.com/projen/projen/pull/3338

**Comment by mrgrain** [comment]
Last PRs are up!

**Comment by mrgrain** [comment]
All done now. 🎉
