### ISSUE TITLE
.gitignore paths for sub projects includes a leading /

### ISSUE THREAD

**Issue by andyphelps** [projen/projen#334]
When creating a sub project containing elements derived from FileBase the .gitignore created for the subproject includes the generated files with a leading / (line 64: file.ts) which means the include does not work.

**Comment by eladb** [comment]
Can you elaborate? Why won't it work with the leading `/`s?

**Comment by andyphelps** [comment]
My apologies.  Purely down to my lack of understanding of .gitignore.
