### ISSUE TITLE
github-app-token action throwing error after yesterday's update

### ISSUE THREAD

**Issue by dkershner6** [projen/projen#3340]
`File not found: '/tmp/ghrxl-1/_actions/tibdex/github-app-token/3eb77c7243b85c65e84acfa93fdbac02fb6bd532/dist/post/index.js'`

https://github.com/projen/projen/pull/3338

@v2 is working fine for us, just not this specific hash.

**Comment by mrgrain** [comment]
Ahhhhhh 💩 

Thanks for noticing. Fix is incoming. You might have to manually intervene with this one 😬

**Comment by dkershner6** [comment]
> Ahhhhhh 💩
> 
> Thanks for noticing. Fix is incoming. You might have to manually intervene to get out of this one 😬

Shouldnt be an issue for us, only hit one repo so far.  Thanks for the quick action, Momo! (@mrgrain )

**Comment by mrgrain** [comment]
@dkershner6 Can you confirm it's working again for you?

**Comment by dkershner6** [comment]
> @dkershner6 Can you confirm it's working again for you?

Testing now, will let you know and ping you in a few minutes.

**Comment by dkershner6** [comment]
Confirmed as working, @mrgrain .

**Comment by mrgrain** [comment]
Thank you, appreciate it!
