### ISSUE TITLE
`FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal`

### ISSUE THREAD

**Issue by garysassano** [projen/projen#3369]
Tried the following:

```sh
❯ npx projen new awscdk-app-ts --package-manager pnpm --cdk-version v2.128.0
👾 Project definition file was created at /home/user/github/.projenrc.ts
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal
 1: 0xc9e850 node::Abort() [node]
 2: 0xb7200e node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 3: 0xec2be0 v8::api_internal::ToLocalEmpty() [node]
 4: 0xca58cc  [node]
 5: 0x7f0effe4d546 
Aborted
```

It should throw the same error as:
```sh
❯ npx projen new awscdk-app-ts --package-manager pnpm --cdk-version 2.128
/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/awscdk/awscdk-deps.js:208
        throw new Error(`"cdkVersion" cannot be parsed as a semver version: ${options.cdkVersion}`);
        ^

Error: "cdkVersion" cannot be parsed as a semver version: 2.128
    at determineFrameworkVersion (/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/awscdk/awscdk-deps.js:208:15)
    at new AwsCdkDeps (/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/awscdk/awscdk-deps.js:18:27)
    at new AwsCdkDepsJs (/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/awscdk/awscdk-deps-js.js:10:1)
    at new AwsCdkTypeScriptApp (/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/awscdk/awscdk-app-ts.js:39:24)
    at evalmachine.<anonymous>:1:28
    at Script.runInContext (node:vm:133:12)
    at Object.runInContext (node:vm:279:6)
    at createProject (/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/projects.js:97:8)
    at Projects.createProject (/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/projects.js:30:9)
    at initProject (/home/user/.npm/_npx/80cfb0dc84733c29/node_modules/projen/lib/cli/cmds/new.js:322:25)
```

**Comment by garysassano** [comment]
Apparently, only yarn accepts the `v` in front of the semver. Both npm and pnpm refuse to accept that.

This works:
```sh
npx projen new awscdk-app-ts --package-manager yarn --cdk-version v2.128.0
```

And since it works, you end up with a `.projenrc.ts` and `package.json` including `v2.128.0`.

**Comment by mrgrain** [comment]
```
npx projen new awscdk-app-ts --package-manager pnpm --cdk-version v2.128.0
```

Works without problems for me. What version of node are you using? 
I don't think projen does anything specifically that would make it prone to `v8 FATAL ERRORS`.

**Comment by garysassano** [comment]
Restarted the WSL2 env and now the problem is gone. Still, I think we should sanitize the parameters and strip out the `v`. It's not normal to have that showing up in your `package.json`.

**Comment by mrgrain** [comment]
NPM also works:
```
npx projen new awscdk-app-ts --package-manager npm --cdk-version v2.128.0
```

---

`^v2.127.0` is a perfectly fine version constraint. You can check this here: https://semver.npmjs.com/
Or run `npm show aws-cdk@^v2.127.0` which will also resolve correctly.

**Comment by mrgrain** [comment]
> Restarted the WSL2 env and now the problem is gone. Still, I think we should sanitize the parameters and strip out the `v`. It's not normal to have that showing up in your `package.json`.

It is only added because you have put it there and it is perfectly valid semver version constraint that is (at least within the node ecosystem) accept by all major package managers. I'm not inclined to artificially restrict valid use cases.

**Comment by garysassano** [comment]
> It is only added because you have put it in the `projen new` command and it is a perfectly valid semver version constraint that is (at least within the node ecosystem) accept by all major package managers. I'm not inclined to artificially restrict valid use cases.
> 
> Happy to update any documentation if we use it somewhere. I agree it's certainly a bit unusual.

Yeah, I know it's a valid semver, but as you said, it's quite unusual to see that. Even if you are the one explicitly passing it as a parameter, I wouldn't expect to see it in the generated files.

**Comment by mrgrain** [comment]
Closing this one as it was due to WSL. You're welcome to open a new issue the discuss the automatic stripping of `v` and gather community support for it.
