### ISSUE TITLE
Projen-generated CDK Pipeline project failing on CodeBuild

### ISSUE THREAD

**Issue by john-tipper** [projen/projen#338]
I have a CDK Pipeline that I am attempting to deploy.  The CDK code is in a directory off the root project called `cdk-pipeline`.  I have created the Typescript project using Projen.

My pipeline consists at the moment of 2 files:

    src/lib/PipelineStack.ts
    src/main.ts

`main.ts` is a very simple wrapper around the pipeline and looks like this:

    const app = new App();
    
    const account = '123456789012';
    const region = 'us-east-1';
    
    new PipelineStack(app, 'PipelineStack', {
      env: {
        account: account,
        region: region,
      },
    });
    
    app.synth();

The synth action within the pipeline is again very simple and varies from the default only to take into account that the `yarn` command is being run from the root of the project directory, not the `cdk-pipeline` directory:

    synthAction: SimpleSynthAction.standardYarnSynth({
        sourceArtifact,
        cloudAssemblyArtifact,

        installCommand: 'yarn --cwd cdk-pipeline install --frozen-lockfile',
        buildCommand: 'yarn --cwd cdk-pipeline run build',
        synthCommand: 'yarn --cwd cdk-pipeline cdk synth',
      })

I can successfully run `yarn run build` from the command line and the project builds, tests and synths ok. However, when I deploy to AWS, the CodeBuild stage fails with the following error:

    [Container] 2020/11/26 20:43:00 Entering phase BUILD
    [Container] 2020/11/26 20:43:00 Running command yarn --cwd cdk-pipeline run build
    yarn run v1.22.5
    $ yarn run test && yarn run compile && pwd && find ./src -name '*' && yarn run synth
    $ rm -fr lib/ && jest --passWithNoTests --updateSnapshot && yarn run eslint
    PASS test/main.test.ts
      ✓ Snapshot (258 ms)
    
     › 1 snapshot updated.
    ------------------------------|---------|----------|---------|---------|-------------------
    File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
    ------------------------------|---------|----------|---------|---------|-------------------
    All files                     |     100 |      100 |     100 |     100 |                   
     PipelineStack.ts             |     100 |      100 |     100 |     100 |                   
    ------------------------------|---------|----------|---------|---------|-------------------
    Snapshot Summary
     › 1 snapshot updated from 1 test suite.
    
    Test Suites: 1 passed, 1 total
    Tests:       1 passed, 1 total
    Snapshots:   1 updated, 1 total
    Time:        5.137 s
    Ran all test suites.
    $ eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test
    $ true
    /codebuild/output/src726342051/src/cdk-pipeline
    ./src
    ./src/main.ts
    ./src/lib
    ./src/lib/PipelineStack.ts
    $ cdk synth
    Cannot find module '/codebuild/output/src726342051/src/cdk-pipeline/srcmain.ts'
    Subprocess exited with error 1
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
    [Container] 2020/11/26 20:43:11 Command did not exit successfully yarn --cwd cdk-pipeline run build exit status 1
    [Container] 2020/11/26 20:43:11 Phase complete: BUILD State: FAILED
    [Container] 2020/11/26 20:43:11 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn --cwd cdk-pipeline run build. Reason: exit status 1

Notice that the issue is that the main entry point is not being recognised, there is no path separator: in `/codebuild/output/src726342051/src/cdk-pipeline/srcmain.ts`.

I have tried editing `.projenrc.js` to have variations on `appEntrypoint`, but nothing seems to inject a path separator in between the src directory and the file:

e.g.
    appEntrypoint: "/main.ts"
    appEntrypoint: "main.ts"
    //  appEntrypoint: "main.ts" commented out

None of these are working - is this a bug or is it something I am not doing correctly please?

**Comment by john-tipper** [comment]
OK, this was due to the fact that the pipeline was synthesized on a Windows development server, and thus the `cdk.json` had this:

`"app": "npx ts-node --prefer-ts-exts src\\main.ts",`

Note the backslash in the path - this is obviously needed in order to be able to run `synth` on the development server, but this is what causes problems on the CodeBuild Lunix server.  What was needed was to run `projen` in the install or build phases, before any calls to `cdk` occur.  As `projen` is installed as a dev dependency in the project, it needs to be installed first before it can be called, despite the fact that it itself calls install of the NPM dependencies, i.e. there's a chicken-and-egg issue meaning you can't just call `projen`.

My pipeline synth definition therefore looks like this:

```
      synthAction: SimpleSynthAction.standardYarnSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        subdirectory: 'cdk-pipeline',

        installCommand: 'yarn --cwd cdk-pipeline install --frozen-lockfile && yarn --cwd cdk-pipeline projen',
        buildCommand: 'yarn --cwd cdk-pipeline run build',
        synthCommand: 'yarn --cwd cdk-pipeline cdk synth',
      }),

```

This successfully allows the synth to occur.  I think there is probably a need to describe in the documentation what a sensible series of steps is for cross-OS development, but I'm not sure what best-practice should look like. Do you have any ideas please, @eladb?  This issue can be closed, as it's not a bug, it's just a gotcha to be aware of.

**Comment by hoegertn** [comment]
This is a good catch. I think it would be great to add a `SimpleSynthAction.standardProjenSynth()` that uses `npx projen` instead of yarn install etc.

I will try this out and update my PR that refactors synth.

https://github.com/aws/aws-cdk/pull/11401
