### ISSUE TITLE
windows: running tasks for projen development on Windows

### ISSUE THREAD

**Issue by gmeligio** [projen/projen#3384]
I want to able to develop `projen` on Windows. Being able to use projects that depend on projen on Windows would be even nicer.

I'm currently focusing on `projen` development and not `projen` usage as a tool/library. It's possible many tasks related to projen usage will be fixed too, but that could be analyzed in other issues (like #2427, for example). I'm contributing to this by creating a PR per projen task. The current tasks I'm paying attention to so far and relevant issues that were raised from those PRs are:
- [x] Windows Github workflow to track progress https://github.com/projen/projen/pull/3520
- [x] `projenrc` root folder for projen configuration logic https://github.com/projen/projen/pull/3520
- [x] bootstrapping https://github.com/projen/projen/pull/3377
- [x] pre-compile 
- [x] compile
- [x] post-compile https://github.com/cdklabs/jsii-docgen/pull/1398
- [x] test https://github.com/projen/projen/pull/3578  https://github.com/projen/projen/pull/3582
- [x] package https://github.com/projen/projen/issues/1933 https://github.com/projen/projen/pull/3723
- [x] package:js
- [x] package:python
- [x] package:java
- [x] package:go

General issues:
- [x] https://github.com/projen/projen/issues/3284

**Comment by mrgrain** [comment]
Note that currently no tests are run on windows because of this: https://github.com/cdklabs/jsii-docgen/pull/1398/files#diff-bda22a3de7550efc76dd29e2a427a8d5abd5863f6e96a339ff47390d9bed7d14R51-R53

**Comment by gmeligio** [comment]
Wonderful! Looking back, I think it would have been tricky for me to find that the issue was in the `jsii-docgen` repository.

I'll look into the glob pattern for tests later this week. Thank you for pointing out the reason.

**Comment by mrgrain** [comment]
> I'll look into the glob pattern for tests later this week. Thank you for pointing out the reason.

I think jest used [micromatch](https://www.npmjs.com/package/micromatch) for these patterns, so we'll have to rewrite the default patterns to work on windows.

**Comment by gmeligio** [comment]
Closing, since all projen tasks can be run on Windows now 🎉 , given that the required system packages used by the tasks are installed.
