### ISSUE TITLE
No Docs for:  The option "dependencies" will soon be deprecated, use "deps" instead (see API docs).

### ISSUE THREAD

**Issue by pszabop** [projen/projen#341]
# Version:    
 "projen": "^0.5.1",
# Details
I get a warning:

        The option "dependencies" will soon be deprecated, use "deps" instead (see API docs)

But there are no docs that describe what `deps` do.

In the end I need to support this kind of dependency for writing an integration test of the module `aws-cdk-serverless-timer`

```
  dependencies: {
    "aws-cdk-serverless-timer": "file:../serverless-timer",
  },

```

**Comment by eladb** [comment]
I am not sure if local file deps are currently supported by `deps`. 

Have you tried:

```ts
deps: [
  'aws-cdk-serverless-timer@file:../serverless-timer'
]
```

Not sure it will work but worth a try.

**Comment by pgollucci** [comment]
This can be closed; long since gone; @eladb
