### ISSUE TITLE
Use eslint rule `import/no-duplicates` instead of `no-duplicate-imports`

### ISSUE THREAD

**Issue by ykageyama-mondo** [projen/projen#3415]
# Problem

The default eslint rules for `TypeScriptProject` uses `no-duplicate-imports` which is known to [cause false positives on type imports](https://github.com/typescript-eslint/typescript-eslint/issues/2315) when used in conjunction with a value import.

## Example

```typescript
import type {MyType} from './hello'
import {myValue} from './hello' // error no-duplicate-imports
```

# Possible solution

Update the default eslint component rules to use [`import/no-duplicates`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md) instead of `no-duplicate-imports`

**Comment by dkershner6** [comment]
On it, will solve us from having to have an interim construct to correct this.
