### ISSUE TITLE
Local Projen Templates Not Working

### ISSUE THREAD

**Issue by rawkode** [projen/projen#3419]
I've created a new JsiiProject within my monorepository and I'm trying to create a new project with it, with the following command:

```
 npx projen new test --from file:../../my-template
```

Unfortunately, this doesn't seem to work and the following error is reported:

```
👾 Module '@rawkodeacademy/projen-grafbase-turso-service' does not look like it is compatible with projen. Reason: Cannot find '@rawkodeacademy/projen-grafbase-turso-service/.jsii'. All projen modules must be jsii modules!
```

While I'm not opposed to publishing, I'd certainly like this local workflow to work while I experiment and work on my custom project.

Hopefully I'm just missing a step.

**Comment by mrgrain** [comment]
Is this a new error @rawkode ? Asking because we just released [v0.80.6](https://github.com/projen/projen/releases/tag/v0.80.6) which made changes to the `projen new` code.

Can you try if this works?
```
 npx projen@0.80.5 new test --from file:../../my-template
```

---

Otherwise, did you build the project inside `my-template`? Does the `.jsii` file exists?

**Comment by mrgrain** [comment]
cc @adamelkhayyat

**Comment by rawkode** [comment]
Apologies, @mrgrain; looks like I did need to run `projen build` within the custom project.

False alarm!
