### ISSUE TITLE
Where do I put Lambda code for a construct?

### ISSUE THREAD

**Issue by pszabop** [projen/projen#342]
CDK Constructs sometimes need Lambda code.  For example see this [non-projen construct](https://github.com/eladb/cdk-dynamo-table-viewer):

The `dynamo-table-viewer` puts the code in `lib/lambda`.  That won't work as projen wipes the lib directory since the files in there are created files.

Putting the code in `src/lambda` won't work either, as the relative path after deploying the construct as a module is `lib/lambda`.

What is the best location to place lambda code for a Construct?

My assumption is the correct way to deploy the code is `Lambda.Code.fromAsset()`.  I just don't know where to put the asset.

**Comment by Chriscbr** [comment]
> The dynamo-table-viewer puts the code in lib/lambda. That won't work as projen wipes the lib directory since the files in there are created files.

It should be possible to change this directory by passing a different name specifying a `libdir` option in the project constructor - would that fix the issue?

**Comment by eladb** [comment]
Why not under `src/lambda` and reference it relative?

**Comment by lukewiwa** [comment]
yeah this is kinda broken as the lambda code in the src directory gets compiled when I'd like to do the work elsewhere and just add a js file
