### ISSUE TITLE
Request for Upgrade: `jsii` 5.1 to 5.3

### ISSUE THREAD

**Issue by rszemplinski** [projen/projen#3457]
I've noticed that projen is currently utilizing jsii version 5.1, which has reached its End-of-Support (EOS). Given the potential risks associated with using an unsupported version, including security vulnerabilities and missing out on the latest features, I'd like to suggest upgrading to the latest stable version, jsii 5.3.

Current warning when building:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                                     !!
!!  The 5.1 release line of jsii has reached End-of-Support.                                           !!
!!  We strongly recommend you upgrade to the current release line (5.3) at your earliest convenience.  !!
!!                                                                                                     !!
!!  Other actively supported release lines include:                                                    !!
!!  - 5.2 (planned End-of-Support date: 2024-06-30T00:00:00.000Z)                                      !!
!!                                                                                                     !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Proposal**:
Could the team consider upgrading jsii from version 5.1 to 5.3 for projen? This upgrade could help ensure the project remains secure, stable, and benefits from the latest improvements in jsii.

**Questions**:
Are there any known compatibility issues or significant changes in jsii 5.3 that might affect projen?
Have there been any considerations or plans already in place for upgrading jsii within projen?

**Comment by mrgrain** [comment]
Yeah we should. FWIW as of the date of this comment, the team behind projen is the same team that's behind jsii. That makes the not updating even worse, but at least I can tell you we are not missing out on much. 😅
