### ISSUE TITLE
bug(upgrade-depdendencies): some dependencies are still attempted to be upgraded by ncu, then reverted by projen

### ISSUE THREAD

**Issue by dkershner6** [projen/projen#3462]
The bug is that a dependency `some-dep@10.0.0` is currently still included in the `ncu` upgrade command. This might cause the dependency to be upgraded to version `10.1.0`. However when projen is synth'ed the next time, this dependency version is reverted to `10.0.0` again. Therefore the ncu upgrade was unnecessary. Instead drop this dependency from the `ncu` command and use the package manager upgrade command to ensure the latest version matching the version constraint is installed.

---

Original title: bug(upgrade-depdendencies): filter for pinned packages is backwards (it includes pinned packages rather than excludes)

Example: https://github.com/projen/projen/blob/8c14559c3ebc5bf58035d9a3e811fa9813bf4d24/.projen/tasks.json#L425

`comment-json` should not be in this list, but `yaml` should be (backwards): https://github.com/projen/projen/blob/8c14559c3ebc5bf58035d9a3e811fa9813bf4d24/.projenrc.ts#L62

Here is the commit that broke it:
https://github.com/projen/projen/commit/cb2d8987439925efc81874f964b1bc03810c9c23

> When `some-dep@^10` is added as a dependency, it is incorrectly included in the list of to-be-upgraded dependencies. This was due to a bug in a boolean expression; with the the code comment stating the clear intention to exclude them.
>
> The reason for this is that ncu would upgrade `some-dep@^10` to a later version. But `projen default` would then revert back to the version defined in code.
>
> While fixing the issue, I realized that while we need to exclude these deps from ncu, we still want them to be included in the package manager upgrade command, so that they receive the latest version for the given version constraint.

I think this comment is backwards too.  `some-dep@^10` SHOULD be upgraded, but `some-dep@10.1.5` should not.

On a side note, I am also not sure that a `^` is sufficient...as `@10` feels like it should also be upgraded (as though it had a `^`), but as least that case can be handled by adding one.

**Comment by dkershner6** [comment]
@mrgrain , happy to PR a fix, but I want to be sure I am reading this correctly first and not missing something.

**Comment by dkershner6** [comment]
I did end up creating a PR, since it was relatively simple and I had the context: https://github.com/projen/projen/pull/3463

**Comment by mrgrain** [comment]
Sounds like we still haven't got this nailed down. The general rule is:

If _any_ version constraint is present, we don't run `ncu`, but we run `<package-manager> upgrade`. This is because a dependency with a version constraint defined in projen will _never_ change. We can only ensure to get the latest version that matches the constraint.

**Comment by dkershner6** [comment]
> Sounds like we still haven't got this nailed down. The general rule is:
> 
> If _any_ version constraint is present, we don't run `ncu`, but we run `<package-manager> upgrade`. This is because a dependency with a version constraint defined in projen will _never_ change. We can only ensure to get the latest version that matches the constraint.
> 
> `some-dep@10.1.5` doesn't need either, because it's always fixed.

I guess that makes sense, though I will say that anything that uses the `^` is effectively the same as nothing present (since `ncu` is set to target `minor`).  I kinda prefer the `ncu` method to package-manager, simply because you can see it work without looking at a lock file, but that is pretty minor preference.

Sounds like you would be advocating for just removing the `^` logic entirely, though, which is obviously easy to do.

**Comment by mrgrain** [comment]
I agree the just checking for `^` isn't enough. 🙈

**Comment by dkershner6** [comment]
> I agree that just checking for `^` isn't enough. 🙈

Yeah, we need some kind of `allowsForMinorPackageUpgrades(semVer)`.

I think my main thought for the moment is to get fully pinned (non `^`) packages to stop doing the back and forth upgrade dance, though.

**Comment by mrgrain** [comment]
> I guess that makes sense, though I will say that anything that uses the ^ is effectively the same as nothing present (since ncu is set to target minor).

No that's not the same. Sorry I missed this comment earlier.

If there is ANY version constraint defined in projen, projen will ALWAYS write the version constraint back to `package.json`, therefor running `ncu` to update the version constraint in `package.json` is pointless because projen will ALWAYS override it again. However `yarn upgrade` et. al. will make sure that the latest version according to the constraint is installed.

**Comment by mrgrain** [comment]
Bringing this back to your original issue:

> `comment-json` should not be in this list, but `yaml` should be (backwards):

- `comment-json` should indeed not be in the ncu list
- `yaml` is correctly omitted from the ncu list because it has a version constraint

**Comment by dkershner6** [comment]
> If there is ANY version constraint defined in projen, projen will ALWAYS write the version constraint back to package.json, therefor running ncu to update the version constraint in package.json is pointless because projen will ALWAYS override it again.

> yaml is correctly omitted from the ncu list because it has a version constraint

OK, I think I am understanding what you are saying, which is different from what I thought, but I think it is critical to point out that I think you mean `at least two part semver version constraint`, because I think otherwise projen does change versions...or at least allows the version to change without changing it back.

To confirm:
DO NOT NCU: ^3.0.0, 3.0.0, 3.0.0-alpha.0, ~3.0.0, ^3.0.
DO NCU: *, 3, 3.x, 3.x.x

Right? @mrgrain

**Comment by dkershner6** [comment]
I think I can actually answer my own question: No, even those versions should be kept as projen puts them in package.json literally, only `*` gets overwritten.

This is simple, and ill change my PR.
