### ISSUE TITLE
Fails to publish a new package to npm

### ISSUE THREAD

**Issue by tmokmss** [projen/projen#3479]
Hi, I initialized a CDK construct library with the latest projen (0.80.12), but the `Publish to npm` job always fails due to the below error:

```
Run npx -p publib@latest publib-npm
....
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm ERR! code EUSAGE
npm ERR! Can't generate provenance for new or private package, you must set `access` to public.
```

#3378 enabled [provenance feature](https://docs.npmjs.com/generating-provenance-statements), but as far as reading the doc, you need to add `--access public` flag If you are publishing a package for the first time.

> If you are publishing a package for the first time you will also need to explicitly set access to public:
> https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions

Workaround: disable provenance feature

```ts
const project = new awscdk.AwsCdkConstructLibrary({
  // ...
  npmProvenance: false,
});
```

**Comment by tmokmss** [comment]
We can set `NPM_ACCESS_LEVEL` environment variable to configure publib.

https://github.com/cdklabs/publib/blob/8e4c9b07140940761511b8d810bada0820b2237f/bin/publib-npm#L62-L70

**Comment by mrgrain** [comment]
Ah thanks for reporting. I thought we had fixed that in a follow up PR 😔

**Comment by mrgrain** [comment]
I think we maybe have to determine the default access level and always set it in `package.json`?

**Comment by mrgrain** [comment]
@tmokmss Quick question: Was your package names scoped (e.g. `@tmokmss/my-package`) or unscoped (e.g. `tmokmss-cool-package`)?

I think the bug depends on the type of package name.

**Comment by tmokmss** [comment]
@mrgrain It was unscoped. Thanks for the fix!

**Comment by mrgrain** [comment]
> @mrgrain It was unscoped. Thanks for the fix!

Yes, that checks out.
