### ISSUE TITLE
spawn does not respect step envrionment variables

### ISSUE THREAD

**Issue by zsstiers** [projen/projen#3493]
Intuitively it seems like
```
const echoTask = project.addTask("echo-example", {
  exec: 'echo "$ECHO_EXAMPLE"',
});

project.addTask("example").spawn(echoTask, {
  env: {
    ECHO_EXAMPLE: "Hello world"
  }
});
```
should emit "Hello world" to stdout when `npx projen example` is run. It instead emits just a blank line.

**Comment by mrgrain** [comment]
Marking as bug, although we are looking to deprecate spawn anyway. This whole concept of reusing tasks and changing them from the outside is a bit flawed. And given that we are a general purpose programming language, reusability can be much better solved in code rather than the task model.
