### ISSUE TITLE
Error when using `NodePackageManager.BUN` with `NodejsFunction`

### ISSUE THREAD

**Issue by garysassano** [projen/projen#3523]
![image](https://github.com/projen/projen/assets/10464497/fdcca5c6-fe87-43ba-ac4c-7cc9090ac28f)
![image](https://github.com/projen/projen/assets/10464497/e5149a79-59ba-436a-bedf-8e4e438eae11)

**Comment by mrgrain** [comment]
CDK doesn't support bun. We can make the error message here better, but that's about it.

**Comment by garysassano** [comment]
Then why the prop in `NodeProject`? Even if Bun isn't supported as a runtime, we could still use it as a package manager.

**Comment by garysassano** [comment]
Then why the prop in `NodeProject`? Despite Bun not being supported as a runtime, we could still use it as a package manager.

**Comment by mrgrain** [comment]
Isn't that exactly what we have today? Your issue report is very specific, so I'm not really sure at all that you are doing and what you are expecting it to do. 🤷‍♂️

**Comment by garysassano** [comment]
I haven't tested it thoroughly, but I'm pretty sure this issue only happens when using `NodePackageManager.BUN` + `NodejsFunction`, as I have used `NodePackageManager.BUN` + `Function` elsewhere without issues. I think the problem may be related to the esbuild bundling that happens on your machine, which may be using bun instead of node, and that would need to be fixed to always use node.

**Comment by garysassano** [comment]
I haven't tested it thoroughly, but I'm pretty sure this error only occurs when using `NodePackageManager.BUN` + `NodejsFunction`, as I have used `NodePackageManager.BUN` + `Function` elsewhere without issues. I think the problem may be related to the esbuild bundling that happens on your machine, which may be using bun instead of node, and that would need to be fixed to always use node.

**Comment by mrgrain** [comment]
I don't think we can action this reasonably. Bun support will need to be improved in AWS CDK for this to work.
