### ISSUE TITLE
Rerunning projen cannot proceed due to existing license.

### ISSUE THREAD

**Issue by raurir** [projen/projen#3533]
Projen can no longer synth. Issue surfaced when upgrading from `0.79.24` to `0.81.0`.

Error is: 
`Error: There is already a file under LICENSE` (https://github.com/projen/projen/blob/9eb1e59076b7cfb954c41b6c0edbd060dcfab726/src/file.ts#L112)

I looked through code changes since .79.24 but to no avail, sorry.

Macos, node v21.2.0

**Comment by mrgrain** [comment]
Thanks for reporting. We'll need your project type and config.

**Comment by raurir** [comment]
> You can probably fix this by removing your LICENSE file manually.

Hi, that was my first attempt... no luck. I have tried quite a few more tricks to narrow down the scope of the problem... no luck.

Re: project type (easy enough) and config, do you want the whole projenrc.ts?

**Comment by mrgrain** [comment]
As much as you can share. I'll just need to reproduce the issue somehow.

**Comment by raurir** [comment]
> As much as you can share. I'll just need to reproduce the issue somehow.

This is a recently adopted project on my half, so not entirely sure for the reasoning behind this approach we are using, but I have narrowed it down to some custom license generation code:

```ts
export const licenseFile = (project: Project) => {
  project.tryRemoveFile("LICENSE");
  new TextFile(project, "LICENSE", { lines: getLongLicense() }); // line 3
};
```

Since we are running a monorepo with multiple projects, the license files were wanted to be added in many places. (ie `licenseFile` is called in multiple spots like `licenseFile(api)`, `licenseFile(website)` etc. Disabling line 3 above fixes the projen synth, but then apache licenses show up everywhere in the repository :)

Created a [repo which demonstrates the above](https://github.com/raurir/projen-license-bug-demo). Thanks in advance!

**Comment by mrgrain** [comment]
Thanks for the reproduction! I'll have a look.

> so not entirely sure for the reasoning behind this approach we are using

My best guess is that you are using a custom/customized license (as in a license text that is not supported by projen).

**Comment by raurir** [comment]
> My best guess is that you are using a custom/customized license (as in a license text that is not supported by projen).

It is simply plain text, I am unsure how it could be unsupported. Anyhow thanks for looking, keen to hear your feedback. :)

**Comment by raurir** [comment]
> Thanks for the reproduction! I'll have a look.

Hi, were you able to reproduce this issue? Thanks in advance.

**Comment by mrgrain** [comment]
Yes, apologies. Here's what's happening:

1. Your code is adding a LICENSE file
2. Your code attempts to remove an existing license with `project.tryRemoveFile("LICENSE");`, but it's executed first, so this has no effect.
4. PDK is then attempting to add a LICENSE file
5. 💥 


To fix this, you need to tell PDK to not add licenses:

```ts
const monorepo = new MonorepoTsProject({
 // other options
  licenseOptions: {
    disableDefaultLicenses: true,
  },
});
```

This is not really a bug, but the error needs to be much better.

**Comment by raurir** [comment]
Unfortunately we are stuck in an upgrade loop, and we need the latest to version of pdk to fix this (licenseOptions does not exist...)

Referencing that upgrade issue here: https://github.com/aws/aws-pdk/issues/784
