### ISSUE TITLE
packaging fails when cdk.out dir is significant in size

### ISSUE THREAD

**Issue by suhussai** [projen/projen#3546]
I found that the following steps began taking longer and longer (>10mins):

```
👾 build » package | if [ ! -z ${CI} ]; then rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist; else npx projen package-all; fi
👾 package-all » package:js | jsii-pacmak -v --target js
```

At first, I thought it was due to the size of our project, but I found that in CICD pipelines, the steps above completed very quickly (<30s).

Later, I realized this was due to the cdk.out directory that had grown to 4.9G as I was developing/testing. When I removed that directory, the packaging process finished much faster.

To fix this potential issue for others, we could:

1. update the following `rsync` command to exclude the `cdk.out` dir
```
... rsync -a . .repo --exclude .git --exclude node_modules && ...
```

2. Add an option to [AwsCdkConstructLibraryOptions](https://projen.io/docs/api/awscdk/#projen.awscdk.AwsCdkConstructLibraryOptions) that allows users to add directories they would like to ignore during the packaging process. This would be similar to [npmignore](https://projen.io/docs/api/awscdk/#projen.awscdk.AwsCdkConstructLibrary.property.npmignore).

**Comment by mrgrain** [comment]
Nice catch! 

I don't like that rsync step anyway. Yet another reason to refactor it. 


One question though:  How come you have a cdk.out directory in a construct library?

**Comment by suhussai** [comment]
The cdk.out dir must be coming from testing. To test the construct I'm building, I run this command in the root dir:
```
npx cdk deploy --app lib/my-construct/integ.default.js
```

**Comment by mrgrain** [comment]
I think this is a simple as adding `cdk.out` to `.gitignore` and `.npmignore` for the ` awscdk-construct` project.

**Comment by suhussai** [comment]
Adding `cdk.out` to `.npmignore` (via `.projenrc.ts`) worked for me!

Thanks!

**Comment by mrgrain** [comment]
Would love a PR ;)

**Comment by suhussai** [comment]
Just need to add a line like this https://github.com/projen/projen/blob/e46da7e648813e326fca17299b63cb75a0484951/src/cdk/jsii-project.ts#L421 to the `awscdk-construct` project here: https://github.com/projen/projen/blob/e46da7e648813e326fca17299b63cb75a0484951/src/awscdk/awscdk-construct.ts#L80 right?

Let me know and I prep a PR to do that.

**Comment by mrgrain** [comment]
Yes that should be it. Run the build locally to update the snapshots and you are good to go!

**Comment by mrgrain** [comment]
I've looked into this more. Long story short, anyone running integ tests should either

- use the [built-in integration test feature](https://projen.io/docs/integrations/aws/#integration-snapshot-tests), or
- use the [experimental integ-runner feature](https://projen.io/docs/integrations/aws/#experimental-integ-runner-integration-tests), or
- use the [CdkConfig](https://projen.io/docs/api/awscdk#projen.awscdk.CdkConfig) component to configure the config for the integ test.

Alls three of these options already prevent this issue from happening. Particularly `CdkConfig` adds the out dir to `.gitignore`.

For anyone choosing a custom implementation (which is reasonable choice) it will be on them to ensure the implementation is complete. Given that we already have 3 viable options for this, I'm not keen to speculatively support custom implementations.

**Comment by suhussai** [comment]
Thanks for the update. Apologies for dropping the ball on this one.
