### ISSUE TITLE
Unable to ignore lines for coverage in projen project

### ISSUE THREAD

**Issue by michanto** [projen/projen#3550]
I have an AwsCdkConstructLibrary with some code I would like ignored:

```
    /* istanbul ignore next */
    if (TreeInspectable.TREE_INSPECTABLE_SERVICE.has(scope)) {
      throw new Error(`Should not be able to get here.  ${scope.node.path} is already inspectable.`);
    }
```

If I run `npm run test` the line counts against me in the coverage report.

If I run `npx jest` the same line is ignored.  I can see (by running npm run test --verbose) that the test command is:

```
jest --passWithNoTests --coverageProvider=v8 --updateSnapshot
```

I have tried:
- `/* istanbul ignore next */`
- `/* istanbul ignore if */`
- `/* c8 ignore next */`
- `/* v8 ignore next */`

In all cases, `npm run test` counts the line against me.

I tried replacing the test command, but I cannot because it already exists.  I tried removing it first, but I cannot because it is referenced elsewhere.  I don't know how to change the test command to allow me to ignore lines.

**Comment by mrgrain** [comment]
Fixing this so you can change the coverage provider.

For `v8` I recommend using `/* c8 ignore start */` + `/*c8 ignore end */`. I have more success with that.
The bug aside, it is obviously not projen's job to make sure the ignore instructions work.
