### ISSUE TITLE
Tasks: allow passing arguments to tasks

### ISSUE THREAD

**Issue by eladb** [projen/projen#356]
Example:

```ts
const hello = project.addTask('hello');
project.exec(`echo Hello, $@!`);
```

```shell
$ pj hello "world"
Hello, world!
```

### Questions

1. The `$@` notation is just an example. Perhaps it would be easiest to support this by injecting the arguments into environment variable(s).
2. Would be amazing if tasks could leverage yargs' engine to parse switches.
3. Should tasks also "register" positional arguments and switches for yargs?

**Comment by pgollucci** [comment]
Another use case
`yarn deploy --profile damadden88`

**Comment by mmuller88** [comment]
Yep and that is actually a regression because that was possible before. The workaround now could be:
```
project.setScript('cdkDeploy', 'cdk deploy');
```
thank you can do again:
```
yarn cdkDeploy --profile damadden88
```

**Comment by asmajlovicmars** [comment]
Oh, thank you all! This is amazing, and exactly what I was looking for! My case is deploying multiple stacks, therefore (for now): 

`project.setScript('deployall', 'cdk deploy --all');`

**Comment by eladb** [comment]
In the meantime, you can simply add a task:

```ts
project.addTask('deploy-all', {
  exec: 'cdk deploy --all'
});
```

And then both of these will work:

```shell
$ pj deploy-all
# or
$ yarn deploy-all
```

**Comment by asmajlovicmars** [comment]
> ```shell
> pj
> ```

Thank you @eladb! This is amazing

**Comment by bigkraig** [comment]
Also poses a problem running `bump` with flags for things like `--prerelease`.

**Comment by Chriscbr** [comment]
Maybe as an escape hatch for all tasks, we could allow extra arguments to be passed automatically after a "--", as in:

```ts
const deploy = project.addTask('deploy');
deploy.exec(`cdk deploy`);
```

```shell
$ pj deploy -- --all
... runs 'cdk deploy --all'
```

And meanwhile, more fancy argument-insertion could be allowed like so:

```ts
const lint = project.addTask('lint');
lint.exec(`eslint --ext .ts,.tsx $@ src tests`);
```

```shell
$ pj lint --fix -- build-tools
... runs 'eslint --ext .ts,.tsx --fix src tests build-tools'
```

**Comment by eladb** [comment]
I am good with this proposal. Only wondering how this will be have in case the task executes more then one command. Which command will accept the additional args (that's the main reason I haven't done this like this yet).

**Comment by wchaws** [comment]
> I am good with this proposal. Only wondering how this will be have in case the task executes more then one command. Which command will accept the additional args (that's the main reason I haven't done this like this yet).

Hi @eladb One of an example is `cdk deploy --context AAA=AAA --context BBB=BBB`

**Comment by eladb** [comment]
Let's keep this open but I am actually not that sure this should be supported. There is something "healthy" in keeping tasks single-purposed and it's always easy to add tasks for various cases in your projenrc. 

But that might be too strong of an opinion (eg "I want to run a specific test")

**Comment by Chriscbr** [comment]
Keep

**Comment by Chriscbr** [comment]
Maybe we can define a "passthrough" option on tasks that's opt-in

**Comment by mckinnsb** [comment]
Of course you can just fall back to things like `yarn test xxx` and `node --runInBand ../path/to/bin`, but one of the nice things I liked about Projen was the potential to have one "glass pane" as a CLI.

**Comment by marciocadev** [comment]
I believe the problem is that we are seeing conflicts with passing parameters to a command and the proposal to keep tasks with a single purpose

I believe that we should maintain a single purpose but with the flexibility to pass pre-defined parameters

For example, to deploy a CDK project with a profile and a SNS for notifications we should specify a specific task for this without affecting the existing deploy task

```ts
project.addTask('deploy-profile', {
  exec: 'cdk deploy --profile @var1 --notifications-arns @var2'
});
```

and run pj setting var1 and var2

```console
$ pj deploy-profile --var1=something --var2=arn:aws:sns...
```
or
```console
$ pj deploy-profile var1=something var2=arn:aws:sns...
```

**Comment by mrgrain** [comment]
Relates to #2051
