### ISSUE TITLE
Tasks: support specifying cwd both at the task level and at the exec() level

### ISSUE THREAD

**Issue by eladb** [projen/projen#358]

**Comment by eladb** [comment]
@pgollucci Want to pick this one?

**Comment by pgollucci** [comment]
Something like this?

### Task Level
```ts
task.cwd('foo');
task.exec('ls');
task.exec('echo bar');
```
results in
```shell
(cd foo ; ls)
(cd foo; echo bar)
```

### exec() level
```ts
task.exec('ls', 'foo');
```
results in
```shell
(cd foo ; ls)
```

## other

- where `exec()` would override the task if set at `Task` level
- if `exec()` dir is unset it would check `Task`, use if set otherwise plain

**Comment by pgollucci** [comment]
Give #356  That API won't work, will need to be Prop style.

**Comment by eladb** [comment]
> Give #356  That API won't work for exec()
> 
> 
> 
> ```ts
> 
> task.exec("ls", {
> 
>   args?: [],
> 
>   cwd?: foo,
> 
> });
> 
> ```

Yes that's what I had in mind.

And also support at the Task level so it applies to all commands (unless they override)
