### ISSUE TITLE
Getting Started on home page is broken

### ISSUE THREAD

**Issue by rgustafson-ie** [projen/projen#3618]
The `Getting Started` link on the home page is broken.  It's pointing to https://projen.io/docs/getting-started/, but should be https://projen.io/docs/introduction/getting-started ?

Perhaps the issue is [here](https://github.com/projen/projen/blob/5c3b4909487ed3cc5b958974491e75ee3b38230f/docusaurus/src/pages/index.js#L30)  in docusaurus, and elsewhere?

**Comment by mrgrain** [comment]
Thank you! I checked and it seems to be just on the landing page. Which makes sense, because docusaurus does check for broken links in markdown files. But apparently it can't do the same in html files.
