### ISSUE TITLE
Mismatching version for `@aws-solutions-constructs`

### ISSUE THREAD

**Issue by garysassano** [projen/projen#3644]
After doing a `npx projen upgrade`, I ended up with this situation:

![image](https://github.com/projen/projen/assets/10464497/1c9cc498-9ab7-4597-8630-398e2d4cf00e)

So I added the extra dependecies to my `.projenrc.ts` and run `npx projen`, thinking it would automatically pull the latest version from npm and match the other two `@aws-solutions-constructs` modules:

![image](https://github.com/projen/projen/assets/10464497/2deb7b9f-7e0a-4de5-ab57-13952f2084d5)

But nope, projen installed the older version instead, so the issue persisted:

![image](https://github.com/projen/projen/assets/10464497/9cea6a60-4e03-48f9-90dd-ba987184ba8b)

I had to manually run the following to fix the issue:

```sh
pnpm add @aws-solutions-constructs/core@latest @aws-solutions-constructs/resources@latest
```

I don't understand why I've never encounered this issue with modules from `@aws-sdk`, which always get updated with synced version, whereas for `@aws-solutions-constructs` it seems to behave differently.

**Comment by mrgrain** [comment]
This doesn't seem like a projen issue, but one with the dependencies you are using.

**Comment by garysassano** [comment]
After the issue of updating the deps got fixed, I could remove `@aws-solutions-constructs/core` and `@aws-solutions-constructs/resources`. 

Shouldn't `npx projen upgrade` correctly handling upgrading modules from the `@aws-solutions-constructs` namespace?

**Comment by garysassano** [comment]
After fixing the issue of updating the deps to the right version, I could remove `@aws-solutions-constructs/core` and `@aws-solutions-constructs/resources`. 

My actual question was: shouldn't `npx projen upgrade` natively handle upgrading modules from the `@aws-solutions-constructs` namespace correctly?

**Comment by mrgrain** [comment]
Projen uses a third party tool and your package manager for upgrading packages. If you can post the starting `package.json`and lock file or at least the full output of the upgrade command, I might be able to help you debug.


But again, upgrading with peer dependency constraints is a somewhat complicated task. It requires the package that's defining the constraint to be downloaded first, so the new peer dependency constraint can be extracted. I've definitely seen ncu (the tool projen uses) struggle with that.
