### ISSUE TITLE
Licenses applied wrong

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [projen/projen#3645]
I've noticed the Apache 2.0 license is not correctly applied. The placeholders are not replaced:

> APPENDIX: How to apply the Apache License to your work.
> 
>       To apply the Apache License to your work, attach the following
>       boilerplate notice, with the fields enclosed by brackets "[]"
>       replaced with your own identifying information. (Don't include
>       the brackets!)  The text should be enclosed in the appropriate
>       comment syntax for the file format. We also recommend that a
>       file or class name and description of purpose be included on the
>       same "printed page" as the copyright notice for easier
>       identification within third-party archives.
> 
>    Copyright [yyyy] [name of copyright owner]

I've also found the same in the GPL licences. e.g. `GPL-3.0-or-later`

>   If the program does terminal interaction, make it output a short
> notice like this when it starts in an interactive mode:
> 
>     <program>  Copyright (C) <year>  <name of author>
>     This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
>     This is free software, and you are welcome to redistribute it
>     under certain conditions; type `show c' for details.

**Comment by mrgrain** [comment]
Nope, these are not placeholders but descriptions on how to possibly apply the license in other scenarios (as a file header in the case or Apache 2.0 and for a terminal program in the case of GPL). 

For what it's worth projen behaves exactly the same as other generators, like the GitHub.
