### ISSUE TITLE
[FEATURE] Maven: Allow defining configuration values at the plugin execution level

### ISSUE THREAD

**Issue by nbarlow23** [projen/projen#3670]
In current Projen, you can define `configuration` only at the `plugin` level: https://github.com/projen/projen/blob/bea813a27d760369505e7c2c3afd248bd32b3ae7/src/java/pom.ts#L358

But maven allows you to also define `configuration` at the `execution` level of a plugin ([docs](https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_.3Cexecutions.3E_Tag)), for configurations that apply only to that execution.

Requesting adding the same configuration option here: https://github.com/projen/projen/blob/bea813a27d760369505e7c2c3afd248bd32b3ae7/src/java/pom.ts#L379-L394

**Comment by mrgrain** [comment]
Makes sense. PRs are welcome!

**Comment by nbarlow23** [comment]
@mrgrain thanks, am getting the project set up 👍. And nice work on all this so far, is definitely an interesting project that I would like to see go far!

**Comment by mrgrain** [comment]
Thank you! LMK if you need any help. We don't have that many Java users yet, so any help in that area will be very welcome.
