### ISSUE TITLE
Auto-update PR branches instead of anti-tamper

### ISSUE THREAD

**Issue by eladb** [projen/projen#371]
As we venture deeper into the world of checked-in synthesized outputs and snapshot tests, I am wondering if instead of failing on anti-tamper checks in PR branches, we should simply push any changes back.

Basically automatically use `@projen rebuild`.

In almost every case, this is what users would want to do.

**Comment by hoegertn** [comment]
Sounds good. Would this also solve the issue that new projen releases fail the build as the package.json changes?

**Comment by mmuller88** [comment]
love the idea. It usually blocks me sometimes those anti-tamper checks and working around it sounds great.

**Comment by smacintyre** [comment]
I vote **no**; the current anti-tamper checks provide a better workflow

### Reasons:
* The anti-tamper checks are a simpler mental model
* Automatic rebuilds violate the principle of least-surprise. 
  * Most users would not expect adding a commit to a PR would potentially result in a change to their branch and require them pull those changes
* It would interupt the developer workflow as now developers would have to wait after pushing a commit to see if their branch has changed and must be pulled into their local branch. 
* It would split responsibility for keeping projen's products up to date.
  * The developer invocation of projen and github action\
* This would make onboarding new developers to projects more difficult  -- especially if are not already experts in git

### Why I love Projen
Projen makes it very easy for junior developers get up and running. It's easy to train team members that all updates flow through `.projenrc.js`. It works well with a fork and submit based workflow, which mean you don't need to upgrade github to use features like protected branches. As a team lead, you can simply manage things and know, thanks to the anit-tamper checks, if anyone has gone and edited files. The failure messages of the build task are very useful. 

### How I think this suggestion would break some of that
* Explaining to junior developers that now their fork's branch can change then they push a commit is going to be tricky. And that they will have to pull and merge the change will be an often forgotten step that will result in a lot of questions of "why can't I push to my branch?"
* My team's usual workflow is to open a "WIP" pull request when starting a new feature branch. Then pushing small commit to that feature branch while working on the feature. Right now, in the worst case, a failed anti-tamper check can be ignored and cleaned up before review. However, with this change, I don't see how we would avoid having to wait for the check and potential rebuild to run to see if we need to pull back the update. Or, alternately, force push to wipe out the work that the rebuild has done. 


Perhaps I'm misunderstanding something. Please let me know. I look forward to your feedback.

**Comment by pgollucci** [comment]
I can't argue with that @smacintyre.

**Comment by eladb** [comment]
@smacintyre Thanks for the inputs. I really appreciate you taking the time.

How about this? I'll add this feature and by default it will only be enabled for PRs with a certain label applied to them. If the label is not applied, and anti tamper failed, the workflow will post a comment explaining why the build failed and will also propose to slap the label if users want auto updates.

Additionally we'll add a switch that will allow enabling this for all PRs. 

This way we will be able to meet experiment with this and see how it feels to have this capability without surprising users and also providing good discoverability.

**Comment by pgollucci** [comment]
> Sounds good. Would this also solve the issue that new projen releases fail the build as the package.json changes?

@hoegertn - details? I haven't hit this?

**Comment by hoegertn** [comment]
I had the issue with several projects that a commit fails on GitHub as the build action uses a newer version of projen and the lock file changes and the package.json is upgraded to a new projen version. Then yarn frozen and anti-tamper throw up.

**Comment by smacintyre** [comment]
>  I'll add this feature and by default it will only be enabled for PRs with a certain label applied to them. 

@eladb  Sounds like a good compromise. Thank you!

**Comment by pgollucci** [comment]
is is covered by the self-mutation and can be closed

**Comment by pgollucci** [comment]
@eladb  close this one

**Comment by eladb** [comment]
I am afraid self mutation is not good enough because it cancels approval workflows. We will need to submit the self mutation as a PR against the PR branch so users will manually merge them...

**Comment by eladb** [comment]
This is now working for non-forks!
