### ISSUE TITLE
`@projen rebuild` failes fails to checkout on PRs coming from private repos

### ISSUE THREAD

**Issue by smacintyre** [projen/projen#373]
The rebuild bot fails on private repos.

### Steps to reproduce
* Create a private repo on an organization
* Fork that repo
* Create a feature branch
* Make and publish a commit to the fork's feature branch
* Open a pull request against the organization's repo
* In the PR comment `@projen rebuild`

### Result
The rebuild will fail on checkout

#### Setup Job

```
Current runner version: '2.274.2'
Operating System
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20201129.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20201129.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'peter-evans/create-or-update-comment@v1'
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-node@v1'
```

#### Post comment to issue

```
Run peter-evans/create-or-update-comment@v1
  with:
    issue-number: 89
    body: _projen_: Rebuild started
    token: ***
  env:
    CI: true
Created comment id '745942593' on issue '89'.
```

#### Get pull request branch

```
Run rm -f /tmp/pr.json
  rm -f /tmp/pr.json
  curl --silent $PULL_REQUEST_URL > /tmp/pr.json
  BRANCH_STR=$(cat /tmp/pr.json | jq ".head.ref")
  REPO_NAME=$(cat /tmp/pr.json | jq ".head.repo.full_name")
  echo "::set-output name=branch::$(node -p $BRANCH_STR)"
  echo "::set-output name=repo::$(node -p $REPO_NAME)"
  shell: /bin/bash -e {0}
  env:
    CI: true
    PULL_REQUEST_URL: https://api.github.com/repos/iglu-network/kpop-metrics/pulls/89
```

#### Checkout

```
Run actions/checkout@v2
  with:
    ref: null
    repository: null
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
  env:
    CI: true
Error: Invalid repository 'null'. Expected format {owner}/{repo}.
```

**Comment by eladb** [comment]
To support private repositories, we will need to add a github OAUTH token to the `query_pull_request` step in order to query the repository name from the pull request.

I think adding `-H "Authorization: token OAUTH-TOKEN"` to the `curl` command will do the trick.

Relevant line: https://github.com/projen/projen/blob/415b2acc5e2ab6cf3d6641cdef604ed515f506cc/src/node-project.ts#L1039



https://github.com/projen/projen/blob/415b2acc5e2ab6cf3d6641cdef604ed515f506cc/src/node-project.ts#L1036

**Comment by pgollucci** [comment]
This can be closed, the `projen @rebuild` is gone

**Comment by pgollucci** [comment]
This can be closed, the projen @rebuild is gone @elad
