### ISSUE TITLE
Race condition during release

### ISSUE THREAD

**Issue by iliapolo** [projen/projen#3761]
Normally, a projen release has the following steps:

> For the sake of the example, assume the latest GitHub tag for a package is `2.3.13`

1. Fetch the latest tag from GitHub to determine the next version number -> 2.3.14
2. Build the source code and populate `package.json` with the version.
3. Publish to NPM -> `https://www.npmjs.com/package/my-package/v/2.3.14`
4. Create GitHub tag --> `https://github.com/cdk8s-team/cdk8s-plus/tree/my-package/v2.3.14`

However, when releases run concurrently, the following can happen:

> For the sake of the example, assume commit B can very soon after commit A.

1. *ReleaseA:* Fetch the latest tag from GitHub to determine the next version number -> 2.3.14
2. *ReleaseB:* Fetch the latest tag from GitHub to determine the next version number -> 2.3.14 
3. *ReleaseA:* Build the source code and populate `package.json` with the version.
4. *ReleaseB:* Build the source code and populate `package.json` with the version.
5. *ReleaseA*:  Publish to NPM -> `https://www.npmjs.com/package/my-package/v/2.3.14`
6. *ReleaseB*: Publish to NPM -> Skipped because the version already exists # Oops, this means commit B isn't released.
7. *ReleaseA*:  Create GitHub tag --> `https://github.com/cdk8s-team/cdk8s-plus/tree/my-package/v2.3.14`
8. *ReleaseB*:  Create GitHub tag --> Not sure what happens, does it override?

Note that steps 7 and 8 can also come in the reverse order, which creates a situation where the GitHub tag differs from the artifact in NPM. 

The race condition is rooted in the fact that GitHub tags are used as a common state. I think this approach should be revisited, but its also a pretty big change. In the meantime, we can limit the release workflow concurrency by [using concurrency](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-concurrency).

**Comment by iliapolo** [comment]
Oh I see concurrency is already available on a workflow:

https://github.com/projen/projen/blob/87aa8cd6e5d7326ff8a80d3a69fc249cf2effc8d/src/github/workflows.ts#L27

Its weird its a string though, as it has multiple configuration options. @mrgrain How do you feel about breaking this API to support both `group` and `cancel-in-progress` and also make the release workflow use this by default?

**Comment by mrgrain** [comment]
> Oh I see concurrency is already available on a workflow:
> 
> https://github.com/projen/projen/blob/87aa8cd6e5d7326ff8a80d3a69fc249cf2effc8d/src/github/workflows.ts#L27
> 
> Its weird its a string though, as it has multiple configuration options. @mrgrain How do you feel about breaking this API to support both `group` and `cancel-in-progress` and also make the release workflow use this by default?

Yes, that is odd. My best guess is that this changed at some point on GitHub's end. Happy to break this, but let's make that a separate PR please.

**Comment by mrgrain** [comment]
> The race condition is rooted in the fact that GitHub tags are used as a common state. I think this approach should be revisited, but its also a pretty big change. In the meantime, we can limit the release workflow concurrency by [using concurrency](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-concurrency).

Do you have any alternatives in mind? The use of GitHub tags is already odd, because there are two different approaches and I cannot decide if one is better than the other:
- (currently) tag after all releases are completed. The tag serves as an indicator that everything went well.
- tag as the trigger. Tag a commit, and the release runs of the tag trigger. Guarantees tags are correct, actual release might fail afterwards.

**Comment by iliapolo** [comment]
@mrgrain as we discussed, there doesn't seem to be a way to solve the race condition without limiting the concurrency. 
As far as the deciding between the two approaches you outlined, i'm not sure...but the tag trigger approach allows us to limit concurrency only on the workflow doing the tagging (which is fast), and have the publishers run concurrently, so thats nice.

But we would have to make sure not to skip publishing jobs "just because a tag exists".
