### ISSUE TITLE
projen dev dependency on `constructs` cannot be overridden

### ISSUE THREAD

**Issue by ceaess** [projen/projen#3776]
Hello! We are running into a `constructs` version issue we think is due to projen itself using constructs version `10.0.0`. This prevents us from fixing it on our end. Our best guess is that this is leaking somehow into our project's `devDependencies` from `projen`. We have specified `10.2.70` for `deps`, `devDeps`, and `peerDeps` in our `.projenrc.ts`. Regardless of edits made to our `.projenrc.ts` or `package.json`, every time we run `projen`, the `package.json` is updated to `"constructs": "^10.0.0",`. This isn't happening in any of our build scripts, we've narrowed it down to `projen` as the only potential culprit. That projen itself is using constructs `10.0.0` seems to corroborate this theory. Honestly, we only noticed because we're getting this warning every time we run projen.

```
warning package.json: "dependencies" has dependency "constructs" with range "^10.2.70" that collides with a dependency in "devDependencies" of the same name with version "^10.0.0"
warning PROJECT_NAME@0.0.0: "dependencies" has dependency "constructs" with range "^10.2.70" that collides with a dependency in "devDependencies" of the same name with version "^10.0.0"
```

Our `.projenrc.ts` looks like this
```
const project = new cdktf.ConstructLibraryCdktf({
...
  cdktfVersion: '^0.19.0',
  constructsVersion: '^10.2.70',
...
  deps: [
    'constructs@^10.2.70',
...
  devDeps: [
    'constructs@^10.2.70',
...
  peerDeps: [
    'constructs@^10.2.70',
...
```

This causes `projen` to generate a `package.json` that looks like and triggers the issue with `yarn install --check-files`
```
...
  "devDependencies": {
    "constructs": "^10.0.0",
...
  "peerDependencies": {
    "constructs": "^10.2.70"
...
  "dependencies": {
    "constructs": "^10.2.70",
...
```

It seems like you're not opposed to updating the version of constructs used, e.g., https://github.com/projen/projen/pull/3309 but it's unclear why `projen`'s own dependencies haven't been updated.

**Comment by mrgrain** [comment]
Hi @ceaess sorry this is a bit confusing. I'm not exactly sure why this is happening yet, but if you define the construct version _less_ often you may get what you need.

The usual case is that you want `constructs` as a peer dev and as a pinned dev dep. It's enough to use `constructsVersion` for that. When creating a new project with the following command, that does exactly this and produced the correct `package.json`.
```console
npx projen new cdktf-construct --constructs-version="^10.2.70" --cdktf-version="^0.19.0"
```

Sometimes you want a regular dependency instead, you can get this like that:
```ts
project.deps.removeDependency('constructs', DependencyType.BUILD);
project.deps.removeDependency('constructs', DependencyType.PEER);
project.deps.addDependency('constructs@^10.2.70', DependencyType.RUNTIME);
```

Having `constructs` as dep, devDep & peerDep is a bit unusual. But you can achieve it by setting `constructsVersion` and 

```ts
project.deps.addDependency('constructs@^10.2.70', DependencyType.BUILD);
project.deps.addDependency('constructs@^10.2.70', DependencyType.RUNTIME);
``` 

---

Please bear with me while I figure out the unexpected behavior when all 3 deps are set as construct options.

**Comment by ceaess** [comment]
For what it's worth, it ended up all 3 places in an attempt to resolve warnings asking for it in peer and dev deps, we didn't start there.

**Comment by mrgrain** [comment]
> For what it's worth, it ended up all 3 places in an attempt to resolve warnings asking for it in peer and dev deps, we didn't start there.

Yeah I can imagine. It's not a great DX right now. 😞 

As a tip for the future, setting up a projen project has kind of two phases: Construction phase & Imperative phase.
So for most options, the order of operation is usually:
- What you provide in `.projenrc.ts` (Construction phase)
- What the libraries think should be happening (Construction phase)
- Your imperative code (`project.deps.removeDependency() etc)

If you can't get an option to work in the construction phase, it's usually possible to "force" it in the imperative phase.

**Comment by mrgrain** [comment]
Here's what's happening in the background currently, in the order of execution:
1. `NodeProject` adds `constructs as a devDep because projen needs it 
2. `ConstructLibraryCdktf` adds `constructs` as a peerDep via `constructsVersion`
3. Much later during the synth, the peerDep code tries to add a devDep version of itself. This has two code paths:
  a. If there is already a runtime dependency (`deps`) on `constructs`, do nothing. This keeps `constructs` at the unwanted version number.
  b. Otherwise add a devdep. Because this happens after 1), it overwrites the unwanted version constraint.

---

Possible fixes:
- Peer deps code needs to always check for an existing devDep and overwrite it
- `ConstructLibraryCdktf` can explicitly remove the constructs version

---

How urgent is this fix for you? Do the workarounds unblock you for now?

**Comment by ceaess** [comment]
It's not urgent, just odd behavior and not ideal.
