### ISSUE TITLE
Can You Edit Automatically Generated Release Workflow?

### ISSUE THREAD

**Issue by hakenmt** [projen/projen#3786]
My workflow is running on a self-hosted runner using CodeBuild for an AWS CDK project. One of the automatically created workflows for `release` includes a `release-pypi` job. One of the steps in that automatically created jobs is `setup-python`, which fails since Amazon Linux isn't supported. You can't manually remove it locally since it's recreated during the build, is there a programmatic way in the projen.ts file to remove that step?

**Comment by mrgrain** [comment]
Yes you can, you need to use the [low-level file patching API](https://projen.io/docs/concepts/escape-hatches#object-file-patches). Something like this:

```ts
project.github?.tryFindWorkflow('release')?.file.patch(...)
```

---

However the `release-pypi` job is only added if you have configured to release to PyPI. I suggest you are not configuring a PyPI release and then you should not need to change the workflow at all.
