### ISSUE TITLE
Version class only compatible with Node projects as of v0.86.2

### ISSUE THREAD

**Issue by cgatt** [projen/projen#3806]
PR #3801 modified the `Version` class by moving the addition of the version bump dependency from `NodeProject` to `Version`. While this makes sense intuitively, the `Version` class was previously written in a way that could be run against any project type provided the running environment had npx installed. It did not actually require `commit-and-tag-version` (previously `standard-version`) to be added to the project's dependencies.
This causes a problem if you were using the `Version` class with, say, a `JavaProject`, as it attempts to add the invalid `commit-and-tag-version` dependency to the project's pom file:
```
invalid maven coordinates in dependency named "commit-and-tag-version". format is "<groupId>/<artifactId>". For example "org.junit.jupiter/junit-jupiter-engine"
```
I'm unsure what the best approach to resolve this is as I agree that `Version` should somehow indicate that it requires Node, npx and commit-and-tag-version, though clearly adding it to the project's build dependencies only works for Node projects.
The options I see are:
- Each project type is responsible for implementing its own `Version` class, using an appropriate package for that language
- The pattern of using utilities in workflows via npx is supported regardless of project language
- Node tools like commit-and-tag-version are packaged with projen so that they can be invoked from the language specific JSII bundle (e.g. via mvn exec instead of npx for Java projects)

**Comment by mrgrain** [comment]
A funky, my bad! Thanks for the report! 

Yes this is an odd one, but I reckon in short term there should be an easy fix with a couple of extra conditions.

In general the versioning tasks for non node projects is currently relying on npx which isn't great but works. It's even less great to not have the version locked, but okay. 

I guess ideally, each language/ecosystem would define its own way of bumping versions in a safe way?! And then the  release component could stay language independent. 🤔
