### ISSUE TITLE
‼️ Build and Release workflows failing with `Unknown command`

### ISSUE THREAD

**Issue by nicolaracco** [projen/projen#3820]
### Issue

On August 19, 2024 GitHub [announced](https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/) that the default behavior of the `upload-artifact` action will change to not upload hidden files as they might contain sensitive information. On September 2, 2024 this change was released as a new minor version. Because projen does not lock GitHub's first-party actions to a specific release, any workflows that relied on hidden files being uploaded started failing.

**Update 2024-09-05 12:31 UTC**
We are making progress in making projen compatible with changes in `upload-action`. We have identified the following required changes. You can track the progress on each PR.
- https://github.com/projen/projen/pull/3819
- https://github.com/projen/projen/pull/3821
- https://github.com/projen/projen/pull/3827

**Update 2024-09-04 09:29 UTC**
GitHub has [locked the conversion](https://github.com/actions/upload-artifact/issues/602#event-14120239369) around a potential roll-back or adjustment of the feature. As it stands today, this prevents projen from automated roll-out of the fix.
**We recommend you follow our instructions to apply the fix or workaround.**

Please note that the current solution is to rollback to a previous version of the action. Projen is not yet fully capable of not uploading hidden files. We are working on the respective fixes.

**Update 2024-09-03 10:24 UTC**
We are working on improved instructs to apply the update manually and a script to run if you are managing a lot of repositories. However there is still no path to a zero-touch resolution.

We observe [pressure from the community mounting](https://github.com/actions/upload-artifact/issues/602) on the GitHub Actions team to roll-back the breaking change. If you can, waiting a couple days might be the easiest course action. If you need to release, follow the provided instructions.

**Update 2024-09-02 22:55 UTC**
With default configuration, upgrade workflows depend on a hidden file name `.repo.patch`. Since the file is no longer uploaded, the upgrade workflow cannot complete. **There is currently no known of fully automatic resolution.**

### Status: Partially resolved
**Fix**: Manual fix available
**Rollout**: Under investigation
**Workaround**: Available

### Fix
Upgrade to [v0.86.7](https://github.com/projen/projen/releases/tag/v0.86.7)

You can verify if the fix was successfully applied if all occurrences of the `upload-artifact` action in GitHub Workflow files use `v4.3.6`.

With default configuration, upgrade workflows depend on a hidden file name `.repo.patch`. Since the file is no longer uploaded, the upgrade workflow cannot complete. Manual intervention is likely required.

#### Apply upgrade to a single repo

You have two options: 

1. Run `npx projen upgrade` and merge the suggested changes. This must upgrade projen to at least `v0.86.7`.
2. Manually change the version constraint on projen to `^0.86.7` (require a minimal version of v0.86.7) in your dependency file (`package.lock`, `requirements.txt` etc). Then run package install and merge the changes.

#### Scripted application

For GitHub users, a bash script exists than can be adapted for bulk upgrades: https://github.com/projen/projen/issues/3820#issuecomment-2326266677

### Workaround
Manually set the version of the `upload-artifact` action to a compatible version:

```ts
project.github.actions.set("actions/upload-artifact", "actions/upload-artifact@v4.3.6");
```

You can verify if the fix was successfully applied if all occurrences of the `upload-artifact` action in GitHub Workflow files use `v4.3.6`.

This workaround is requires at least [v0.67.56](https://github.com/projen/projen/releases/tag/v0.67.56).
See [documentation](https://projen.io/docs/integrations/github/?_highlight=workflow#actions-versions) for more details on this feature.

---

### Original issue

Hello, a library I'm working on (https://github.com/condensetech/cdk-constructs) today started failing the release steps without any apparent reason. When the release actions are being executed any "npx projen package:<something>" returns an Unknown command error.

I tried downloading the artifact by hand and can obviously confirm that projen gives that error. But I'm not sure what's causing it. I also upgraded the libs to the last version.

**Comment by mrgrain** [comment]
Thanks for the report. It's due to this: https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/

Working on a fix.

**Comment by mrgrain** [comment]
### Workaround
Manually set the version of the `upload-artifact` action to a compatible version:
```ts
project.github.actions.set("actions/upload-artifact", "actions/upload-artifact@v4.3.6");
```

This workaround is requires at least [v0.67.56](https://github.com/projen/projen/releases/tag/v0.67.56).
See [documentation](https://projen.io/docs/integrations/github/?_highlight=workflow#actions-versions) for more details on this feature.

**Comment by mrgrain** [comment]
### Fix
PR in progress https://github.com/projen/projen/pull/3822

ETA: 60min

**Comment by mrgrain** [comment]
### Fix
Upgrade to [v0.86.7](https://github.com/projen/projen/releases/tag/v0.86.7).
Most users should receive this upgrade automatically via the upgrade workflow. 
Because Workflow executions are affected by this issue, this might require manual intervention.

**Comment by mrgrain** [comment]
Re-opening because the upgrade workflows use a "hidden" file name. Currently no known automatic path to resolution.

**Comment by moltar** [comment]
I think we should ask gh to remove change from minor bump and re release with a major bump on their side. They aren't playing nice.

**Comment by mrgrain** [comment]
For reference, the issue in the `upload-artifact` repo:
https://github.com/actions/upload-artifact/issues/602

**Comment by moltar** [comment]
So looks like they _are_ reverting v3 back to the old behaviour! 👍🏼

**Comment by mrgrain** [comment]
**Update 2024-09-03 10:24 UTC**
We are working on improved instructs to apply the update manually and a script to run if you are managing a lot of repositories. However there is still no path to a zero-touch resolution.

We observe [pressure from the community mounting](https://github.com/actions/upload-artifact/issues/602) on the GitHub Actions team to roll-back the breaking change. If you can, waiting a couple days might be the easiest course action. If you need to release, follow the provided instructions.

**Comment by mrgrain** [comment]
### Requirements

- [GitHub CLI](https://cli.github.com/)
- Authenticated with GitHub CLI

### Usage

```bash
 ./upgrade-projen.sh <org/repo> [upgrade task]

# Examples
 ./upgrade-projen.sh projen/projen
 ./upgrade-projen.sh projen/projen upgrade-dev-deps
```
A PR will be created by the user authenticated with the GitHub CLI

If you have a list of all effected repositories, this script could be used to bulk update repos.

### Script

```bash
#!/usr/bin/env bash

REPO=$1
UPGRADE=${2:-upgrade}
WORKING_DIR=$(mktemp -d -t upgrade-projen)

cd $WORKING_DIR;
echo $WORKING_DIR
gh repo clone $1 .
git switch --create automation-local/fix-upgrade
npx --yes projen install:ci
npx projen $UPGRADE
git add .
git commit -m "chore(deps): upgrade projen dependencies"
git --no-pager show --summary
git push -u origin HEAD
gh pr create --title "chore(deps): upgrade projen dependencies" --body "Automated PR to upgrade projen dependencies"

# Comment in to delete the temporary working directory
# rm -rf $WORKING_DIR
```

**Comment by mrgrain** [comment]
**Update 2024-09-05 12:31 UTC**
We are making progress in making projen compatible with changes in `upload-action`. We have identified the following required changes. You can track the progress on each PR.
https://github.com/projen/projen/pull/3819
https://github.com/projen/projen/pull/3821
https://github.com/projen/projen/pull/3827

**Comment by mrgrain** [comment]
**Update 2024-09-06 12:19 UTC**
With the release of projen [v0.87.0](https://github.com/projen/projen/releases/tag/v0.87.0), all default GitHub Workflows are now compatible with the change in `actions/upload-artifacts` to not include hidden files by default.

While there is still no automated way to roll-out the fixes, it seems unlikely at this change that this is going to change. With the required changes made in projen, we consider this issue resolved.
