### ISSUE TITLE
Subproject synthesis order causes early file cleanup

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#383]
I noticed that if you have a root project and node-based subproject, the `loadDependencies` pre-synthesis step of the subproject fails because the generated file `package.json` will have been deleted. A side effect of this is that whenever you run `npx projen`, it will keep telling you in the console that your dependencies were updated:

```
🤖 jest: * => ^26.6.3
🤖 @types/jest: * => ^26.0.19
🤖 ts-jest: * => ^26.4.4
🤖 eslint: * => ^7.16.0
🤖 eslint-import-resolver-node: * => ^0.3.4
🤖 eslint-import-resolver-typescript: * => ^2.3.0
🤖 eslint-plugin-import: * => ^2.22.1
🤖 json-schema: * => ^0.2.5
```
...even if they haven't changed.

The root cause of this is the way synthesis of project is handled (see https://github.com/projen/projen/blob/master/src/project.ts#L233):

1. Root project gets pre-synthesized
2. All generated files (including those of the subproject!) get cleaned up
3. Subproject pre-synthesizes
4. Subproject cleans up its files (most of these are probably already deleted from step 2)
5. Subproject synthesizes all config files
6. Subproject post-synthesizes (e.g. installs dependencies)
7. Root project synthesizes all config files
8. Root project post-synthesizes

**Comment by Chriscbr** [comment]
A couple solutions:

1. Change `synth()` ordering so that all projects get pre-synthesized before the cleanup-phase occurs (follow-up: if so, should postSynthesize() calls occur together as well?)
2. Use `addExcludeFromCleanup()` ([src](https://github.com/projen/projen/blob/master/src/project.ts#L229)) to prevent the subproject files from being cleaned up early.
3. Add some mechanism for projects to track explicitly what files they are generating, rather than globbing and looking for projen's special markers (see [cleanup.ts](https://github.com/projen/projen/blob/master/src/cleanup.ts))

Some care needs to be taken also for users using subprojects with `outdir: '.'`. It's also worth considering what if the user has nested subprojects in subprojects, and if we want to explicitly handle that case.

Option 2 might be easiest, but all of them have merit

**Comment by pgarbe** [comment]
I'm running into a similar issue. I've one root project and another one in a subfolder with separate .projenrc.js files. But whenever I run `pj` in root folder it deletes some files in my subfolder (e.g. .gitignore). And even worse the yarn.lock file gets upates and build fails because of outdated lockfile.

Why does projen clean up files in subfolders? Because this set up worked some time ago. Also `addExcludeFromCleanup()` doesn't help...

**Comment by eladb** [comment]
@Chriscbr I'd go with option 2 - add clean exclusion overrides - I think the parent project needs to automatically exclude all subproject directories.
