### ISSUE TITLE
[BUG] Can't publish to NPM via Github workflow

### ISSUE THREAD

**Issue by bracki** [projen/projen#3846]
I have a freshly [set up project](https://github.com/superluminar-io/config-kitty/blob/main/.projenrc.ts). It fails when publishing to NPM.

```
Run npx -p publib@latest publib-npm
npm warn exec The following package was not found and will be installed: publib@0.2.886
Publishing under the following dist-tag: latest
npm warn tarball tarball data for file:dist/js/**.tgz (null) seems to be corrupted. Trying again.
npm warn tarball tarball data for file:dist/js/**.tgz (null) seems to be corrupted. Trying again.
npm error code ENOENT
npm error syscall open
npm error path /home/runner/work/config-kitty/config-kitty/dist/js/**.tgz
npm error errno -2
npm error enoent ENOENT: no such file or directory, open '/home/runner/work/config-kitty/config-kitty/dist/js/**.tgz'
npm error enoent This is related to npm not being able to find a file.
npm error enoent

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-09-17T15_35_25_274Z-debug-0.log
ERROR
Error: Process completed with exit code 1.
```

https://github.com/superluminar-io/config-kitty/actions/runs/10906325955/job/30267363705

What exactly is going wrong here? It seems that the publishing component is looking for a `*.tgz`, but there is none.

**Comment by mrgrain** [comment]
Confirmed. The package task seems to be empty for some reason.

**Comment by mrgrain** [comment]
Okay, this is silly. The bottom line here is that at some point in the past it was decided that the an "app" is not intended to be released, and therefore it disables releases and packaging.

https://github.com/projen/projen/blob/ba5b2d2be69d17cdeb749f1b3d3aaa2a666e20df/src/typescript/typescript.ts#L801

**Comment by mrgrain** [comment]
@bracki  To fix your immediate issue, you can manually set `package: true`.

But you might also want to consider to just switch to `TypeScriptProject` (without `App`). The other thing `TypeScriptAppProject` currently does is disabling peerDependencies by default.

**Comment by mrgrain** [comment]
@bracki please let me know if the latest version fixed this for you

**Comment by bracki** [comment]
Works for me. Thanks a lot.
