### ISSUE TITLE
release workflow failing on "Create js artifact"

### ISSUE THREAD

**Issue by marcioemiranda** [projen/projen#3866]
Hello,

I've just upgraded an old CDK construct project to the latest projen version and CDK v2.
Everything is fine locally, I can build the project without any problems.

After pushing the project to Github, the release workflow is triggered. The release job executed successfully but the "Publish to Npm" job failed.

Looking at the details I could notice two things:

**Restore build artifact permissions**: The step failed with the output bellow, but the job per se didn't.
`
  cd dist && setfacl --restore=permissions-backup.acl
  shell: /usr/bin/bash -e {0}
setfacl: .npmignore: No such file or directory
setfacl: .prettierrc.json: No such file or directory
setfacl: .gitignore: No such file or directory
setfacl: .gitattributes: No such file or directory
setfacl: .github: No such file or directory
setfacl: .github/pull_request_template.md: No such file or directory
setfacl: .github/workflows: No such file or directory
setfacl: .github/workflows/pull-request-lint.yml: No such file or directory
setfacl: .github/workflows/release.yml: No such file or directory
setfacl: .github/workflows/build.yml: No such file or directory
setfacl: .jsii: No such file or directory
setfacl: .projenrc.ts: No such file or directory
setfacl: .prettierignore: No such file or directory
setfacl: .mergify.yml: No such file or directory
setfacl: .eslintrc.json: No such file or directory
setfacl: .projen: No such file or directory
setfacl: .projen/deps.json: No such file or directory
setfacl: .projen/files.json: No such file or directory
setfacl: .projen/tasks.json: No such file or directory
Error: Process completed with exit code 1.`

Create js artifact: The step failed with error bellow and that causes the job to fail
```
cd .repo && npx projen package:js
  shell: /usr/bin/bash -e {0}
Unknown command: package:js
Error: Process completed with exit code 1.
```

I've compared the Job steps with other projen projects that I have and they looked the same, ie, they are up to date.

I've also compared the execution of this job with the execution of other CDK construct projects and the first error on "Restore build artifact permissions" didn't happen so I suspect this is causing the other error.

Any ideas.

**Comment by mrgrain** [comment]
Let's ignore the "Restore artifacts permissions" step for now. It's not important to succeed, although the failure also points to what might be wrong. 


Did you run `npx projen` before committing? 
Did your update go through a PR? Did the build succeed there? If not can you try creating a PR and see if it works? 
Have you made any customizations to the workflow in your projenrc file? They will likely need upgrading. 
Is the project public? Will be easier to debug. 
Can you post your .projenrc.ts file?

**Comment by marcioemiranda** [comment]
Hello @mrgrain thanks for the response.

> Did you run npx projen before committing?
Yes. I am also comparing with other CDK construct projects that work and they look exactly the same. The only difference being the git organization they belong to (and also the corresponding plan).

> Did your update go through a PR? Did the build succeed there? If not can you try creating a PR and see if it works?
No I have not use a PR, but again I don't use it in the other project and it works.

> Have you made any customizations to the workflow in your projenrc file? They will likely need upgrading.
No customizations to the workflow

> Is the project public? Will be easier to debug.
The repository is private but I could give you access.

> Can you post your .projenrc.ts file?
[projenrc.txt](https://github.com/user-attachments/files/17179031/projenrc.txt)

Maybe I could add some prints to the "Publish to Npm" job. It looks like there is a problem with the artifact, but I don't know what to look for. The previous job, "release", generated an artifact. I have taken a look into the content and it looks very much the same if compared with other projects that work.

**Comment by mrgrain** [comment]
That's very odd. I recommend opening a fake PR to see if the regular build succeeds. I'd expect it doesn't if the release workflow fails. This is just for testing. No need to use PRs going forward.


One more thing, can you confirm and post your version of projen installed in the project by running `npm why projen` or `yarn why projen`.


The artifact should contain a couple text files with version numbers, a change log file, and the JS tarball.

**Comment by marcioemiranda** [comment]
Creating a PR resulted in the same error.
<img width="922" alt="pr_image" src="https://github.com/user-attachments/assets/4b4c987f-2b2f-40d9-879e-010e03b7a445">

Projen version is "projen@0.85.2".

This is the content of the build artifact I've downloaded from Github. It's generated after the release step of the release workflow. Comparing to other projects that work, it seems to have the same content.

<img width="1123" alt="build_artifact_content" src="https://github.com/user-attachments/assets/74304414-ae3a-4f4f-bae3-ca1a54109e92">

**Comment by mrgrain** [comment]
Looks like you're just running into this issue: https://github.com/projen/projen/issues/3820

You'll need to upgrade to at least [v0.87.4](https://github.com/projen/projen/releases/tag/v0.87.4) or follow one of the  workaround described in the linked issue.

**Comment by marcioemiranda** [comment]
Thanks again for the reply. The original error was resolved by upgrading the project to 0.88.

However, it is now failing when publishing the package to npm. Should I open a new ticket?

We have a private git hub repo, but the npm package is public. The error message mentions **GitHub Actions source repository visibility: "private"**. This used to work a few years ago when this lib was first built and published (using projen).

We have other projen CDK construct projects where the GitHub repo and npm package are private and everything work fine. 

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm notice publish Signed provenance statement with source and build information from GitHub Actions
npm notice publish Provenance statement published to transparency log: https://search.sigstore.dev/?logIndex=135616564
npm error code E422
npm error 422 Unprocessable Entity - PUT https://registry.npmjs.org/druid-cdk-construct - Error verifying sigstore provenance bundle: Unsupported GitHub Actions source repository visibility: "private". Only public source repositories are supported when publishing with provenance.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-10-01T01_25_36_083Z-debug-0.log
ERROR
Error: Process completed with exit code 1.
```

**Comment by mrgrain** [comment]
Easy, you'll need to set `npmProvenance: false` then.

**Comment by marcioemiranda** [comment]
Thanks this solved the problem!
