### ISSUE TITLE
Pin Github actions to commit hashes instead of version tags

### ISSUE THREAD

**Issue by NilsDammenhayn** [projen/projen#3879]
The Github actions referenced in the generated workflow ymls are all included via version tag, for example `actions/upload-artifact@v4.4.0` or worse `peter-evans/create-pull-request@v6`. While I understand the simplicity of using `v6` to always get the current version, from a supply chain security perspective it seems better to me to pin the action to a specific version by using the commit hash like this for the [version 6.1.0](https://github.com/peter-evans/create-pull-request/commit/c5a7806660adbe173f04e3e038b0ccdcd758773c) :
```
peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # 6.1.0
```
Tags are mutable Strings and can be altered subsequently, commit hashes can't. Is there any chance this pattern could be included?

**Comment by mrgrain** [comment]
We will need a sustainable way to keep these up to date. 

projen currently offers support for you to manage this yourself:
https://projen.io/docs/integrations/github/#actions-versions

**Comment by NilsDammenhayn** [comment]
Ah this is exactly what I was looking for! Thanks and nevermind the issue, I'll close it 🙏
