### ISSUE TITLE
Cannot use `lts` as `minNodeVersion` in `NodeProject`

### ISSUE THREAD

**Issue by garysassano** [projen/projen#3912]
![image](https://github.com/user-attachments/assets/05dc743a-e1bb-424a-b0ee-8bb93d563d4e)

Allow resolving [node-semvers](https://github.com/kmalakoff/node-semvers#node-semvers):

```md
- x.y.z         A specific SemVer tuple
- x.y           Major and minor version number
- x             Just a major version number
- lts           The most recent LTS (long-term support) node version
- lts/<name>    The latest in a named LTS set. (argon, boron, etc.)
- lts/*         Same as just "lts"
- latest        The most recent (non-LTS) version
- stable        Backwards-compatible alias for "lts".
- [expression]  Engine and semver module expression like "10.1.x || >=12.0.0"
```

I'm used to this convention with the official [actions/setup-node](https://github.com/actions/setup-node#usage) action by GitHub.

**Comment by mrgrain** [comment]
You are looking for [workflowNodeVersion](https://projen.io/docs/api/javascript#projen.javascript.NodeProjectOptions.property.workflowNodeVersion).

`minNodeVersion` is setting the [engines field](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines) which must be semver.

**Comment by garysassano** [comment]
Isn't that redundant tho? If you specify a `minNodeVersion`, that also gets set for the workflows.

**Comment by mrgrain** [comment]
Maybe. Put some people don't want to set the engines field. Others want the engines field and the node version used in workflows to be different.
