### ISSUE TITLE
Trim versions in GitHub Actions workflows

### ISSUE THREAD

**Issue by garysassano** [projen/projen#3964]
I believe the Node and PNPM versions should be trimmed to the major version in GitHub Actions workflows, the same way as it's trimmed in `.projen/deps.json`, as it's very uncommon to see a workflow that specifies the full version.

#### .projenrc
![image](https://github.com/user-attachments/assets/9d8c9842-6351-4b89-8074-8993d7e6b21c)

#### .github/workflows/build.yml
![image](https://github.com/user-attachments/assets/168b8423-6017-4921-bdfa-a8dde4ce71db)

#### .projen/deps.json
![image](https://github.com/user-attachments/assets/59a4d38f-b81a-4705-8cd1-0eb7ab449456)

**Comment by mrgrain** [comment]
`pnpmVersion` - You are in full control of this version. What's stopping you from using what ever you want to use?

`minNodeVersion` - You are suggestion this should work somewhat the opposite of what `minNodeVersion` is supposed to do: ensure that your project works with this minimum version.  But there's a simple fix: Just use `workflowNodeVersion`.

**Comment by mrgrain** [comment]
`@types/node` is trimmed because the non-major part of the `@types/node` version has **not connection** to the node actual version.

**Comment by garysassano** [comment]
> But there's a simple fix: Just use `workflowNodeVersion`.

Ok, I missed there was such prop.

**Comment by garysassano** [comment]
> But there's a simple fix: Just use `workflowNodeVersion`.

Ok, I missed there was such prop.
