### ISSUE TITLE
running projen via npm postinstall

### ISSUE THREAD

**Issue by JohannesKonings** [projen/projen#3983]
Updates of the projen project apply with the command `npx projen` (https://projen.io/docs/introduction/the-projen-workflow#applying-changes).  
Could the projen workflow also be adapted so that projen is called via the npm postinstall script (https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-install)?
That would be helpful for people who are not that deep into projen to not "forget" the projen call.

Currently, this leads to an infinite loop because of the npm install from projen.

**Comment by mrgrain** [comment]
Idea: If projen detects that it runs from a postinstall hook, run install commands with `--ignore-scripts`. Projen needs to run install when the `package.json` has changed. This might be a good compromise.

**Comment by mrgrain** [comment]
This is actually quite tricky to do cross package managers, but potentially very easy for the user:

```ts
project.addDevDeps('skip-postinstall');
project.package.setScript('postinstall', "skip-postinstall || SKIP_POSTINSTALL=1 node ./projen.js");
```

This works perfectly for me!

**Comment by mrgrain** [comment]
After further consideration I think this is much better done in userland. While we could try adding something to projen to make it _slightly_ easier, I think my propsed solution is straightforward enough.

We could also consider making the whole thing (call from post install) an option or even a default. However at this point, I believe it would be diluting the main messaging and behaviour projen wants to get across. I recognise this make sense for individual companies end setups and it's easy to implement mechanism manually and in custom project types.
