### ISSUE TITLE
gpg failed to sign the data for git commit --allow-empty -m "chore: project created with projen"

### ISSUE THREAD

**Issue by sholtomaud** [projen/projen#3991]
```
Error: Command failed: git commit --allow-empty -m "chore: project created with projen"
error: gpg failed to sign the data
fatal: failed to write commit object
```

How do we create a new project if we have gpg signing setup for our git commits?

**Comment by mrgrain** [comment]
Hmm, that's odd. I have gpg signing setup and this works without issues for me. 🤔 

Saying that, you can disable the git integration with the `--no-git` flag:

```console
npx projen new typescript --no-git
```

This will also disable `git init`, but you can easily run this afterwards.

**Comment by mrgrain** [comment]
@sholtomaud Can you confirm if `--no-git` works for you?

**Comment by mrgrain** [comment]
Closing as resolved until we hear otherwise.
