### ISSUE TITLE
test:compile breaks projects with compilerOptions

### ISSUE THREAD

**Issue by hoegertn** [projen/projen#412]
With the introduction of #401 my projects fail as the tsc run uses the `tsconfig.jest.json` which does not inherit the compiler options I provided for TypeScript. 

So in my case, I cannot build anymore, as a critical compiler option is not set as tsc fails.

**Comment by eladb** [comment]
@hoegertn Sorry this broke your workflow...

The `test:compile` task complies your test code with the same tsc config that was already used by jest. This means that technically your previous workflow was already broken. The only reason you didn't see any failures was that jest does not perform type checking.

But you are right, we need the jest config to automatically derive from the src config.

Can you please provide more details about the missing configuration?

**Comment by hoegertn** [comment]
https://github.com/taimos/lambda-toolbox/runs/1614126490?check_suite_focus=true

And yes the test might be broken, but there are none 🙈

**Comment by eladb** [comment]
As a workaround you should be able to define your typescript configuration as part of jestConfig I believe

**Comment by hoegertn** [comment]
Indeed this is possible. Thanks for the pointer.
