### ISSUE TITLE
Allow rebuild-bot workflow to satisfy mergify criteria

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#427]
Currently if you enable `buildWorkflow` and `mergify` on a node project, then a `.mergify.yml` file will be created that requires a build workflow to pass in order for a pull request to get automatically merged.

In the short term, it would be nice to update the mergify rules so that if the `rebuildBot` option is also enabled, then a successful `rebuild-bot` workflow run would also satisfy the criteria for automatically merging a pull request. (In addition to the other criteria of course, like at least one approval).

I believe this is preventing some pull requests from getting merged automatically (see #426). In this issue, a commit that produced a failing build was included in the base pull request, but the rebuild-bot pushed a commit that fixes the build. While this should in theory cause the `build` workflow to run again, it does not because an action in a workflow run (like pushing a commit) can't trigger new workflow runs (see https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536184102).

In the long term, it could be useful to update the AutoMerge component so that a user can specify a list of other workflows that must succeed before merging. Ideally this could support both "OR" logic (at least one workflow must succeed) and "AND" logic (all workflows must succeed).

**Comment by eladb** [comment]
+1 sounds good to me

**Comment by pgollucci** [comment]
https://github.com/p6m7g8/p6-namer/pull/254 instance of it being wanted. It actual is annoying now that I'm spoiled.

**Comment by pgollucci** [comment]
this can be closed rebuilt-bot is gone @eladb
