### ISSUE TITLE
RFC: API Change - Components

### ISSUE THREAD

**Issue by pgollucci** [projen/projen#432]
## Why?

This will help upgrades and provide a consistent user experience.  Developers will have an easier time adding components
as the API will be standardized. This has the benefit of then exposing all the options consistently too. This will also help drive functionality from NodeProject to Project.

## Design

What if (just using gitpod as an example here), but for any component, we should standardize the constructor and post constructor methods. When doing this, defaults can be maintained.  

```ts
const project = new Project({
  // meta options
  // boolean options (to change defaults)
  // no other options
});

project.$COMPONENT.method(props: methodProps);
project.$COMPONENT.methodEscapeHatch(props: any);
```

Above, if I don't call a method, and the default is `true`, then I get the default, but I can then override it with a method call
as shown above.

Today gitpod defaults to false, but assume for the below example it defaults to true.

```ts
// maintain current defaults
const project = new Project({
  // meta options
  // boolean options
  gitpod: false;
  // no other options
});

// Since gitpod is false, this can't be done
// project.addGitpod({});
```

**Comment by pgollucci** [comment]
Readme Example where it doesn't use `SampleFile`

```ts
// readme: true would be default
const project = new Project({
  // meta options
  // boolean options
  // no other options
});

// readme's API is up to itself
project.readme.customize({
  filename: 'readme.md',
  contents: "contents"
  options: {
    toc: true,
    codeOfConduct: true,
    additionalBadges: [
      'some bagde snippet'
  ],
  ...
});
```

**Comment by pgollucci** [comment]
see #428

**Comment by hoegertn** [comment]
I am not sure I really like the general idea.

First of all, I think there are a lot of options that are not boolean and should be in the constructor like author info, licensing, things that are there currently.

For additional components that are not enabled by default, I think the construct model works fine without enabling stuff and then accessing it.

```
const project = new Project({
  // options
});

new Component(project, props);
```

Convenience methods like `project.addComponent(props)` are sometimes helpful for common components.

For really common stuff I would want to stick to

```
const project = new Project({
  component: true,
  componentOptions: {},
  // options
});
```

**Comment by pgollucci** [comment]
I think this can be closed.  @eladb

**Comment by Chriscbr** [comment]
Do you not have permission to close your own issue? @pgollucci
