### ISSUE TITLE
Optional disable JSII for AwsCdkConstructLibrary

### ISSUE THREAD

**Issue by mmuller88** [projen/projen#434]
Understandable JSII hits some walls for translating specific language constructs. It would be cool if we could skip the JSII compile for the sake of still at least publishing it to npmjs and have the other goodies like cdk version managment. 

The current "workaround" is to use a TypeScriptProject which you can see here: https://github.com/mmuller88/aws-cdk-staging-pipeline/blob/master/.projenrc.js

Cheers Martin

**Comment by hoegertn** [comment]
Can you elaborate on what road blocks you encounter? Maybe we can create JSII tickets out of it.

**Comment by mmuller88** [comment]
Hi Holger. Sorry I lost track of this one. I am not sure what you mean. JSII was erroring because it doesn't support higher order functions as parameter. I guess that would be challenging to implement that in JSII. I will have a look in JSII.

But in the meantime I think it is a valid use case do disable the jsii support for AwsCdkConstructs to leverage the power of TypeScript. 

Does that makes sense :) ?
