### ISSUE TITLE
Reliance on bash `rm` command breaks Windows

### ISSUE THREAD

**Issue by john-tipper** [projen/projen#452]
The use of `rm -fr lib/` as the first step within the `test` script of generated projects breaks on Windows. Whilst it is possible to work around this with some hackery (e.g. defining a different test script and using that), it would be nice to strip out the OS dependency.

I think the issue is here: 

https://github.com/projen/projen/blob/e9ca1aa5d92fea64e16e4be8bc6b4a9fd3d2a662/src/typescript.ts#L306

We could do something like use https://github.com/shelljs/shx as a way of using portable Shell commands (I'm sure others may think of other options).  Are there any objections to doing this please? If so, does the library get declared as a dependency of Projen, or a peer dependency?

I'm happy to submit a PR, but I want to make sure others are happy with this approach before I do.

**Comment by Chriscbr** [comment]
I'm not familiar with the portable shell command ecosystem, but the idea sounds reasonable to me.

> If so, does the library get declared as a dependency of Projen, or a peer dependency?

I think shx would be added as a dev dependency because it's only used for running development scripts/tasks (I think this logic applies both for projects using projen, and for projen itself)? But I'm not totally sure.

**Comment by rpawlaszek** [comment]
I have the same issue on Windows with rm -fr. From my side the proposition is to use [rimraf](https://www.npmjs.com/package/rimraf) and have it as a global dependency for projen.

**Comment by john-tipper** [comment]
Yes, the reason I went with [shx](https://www.npmjs.com/package/shx) in #540 was because there are other breaking commands other than `rm` that are used with Projen, such as `mv` and `mkdir`.

**Comment by pgollucci** [comment]
I think you need it in regular deps for when external projects happen.

**Comment by eladb** [comment]
I believe this is resolved by #781
