### ISSUE TITLE
projenrc.gitignore entries ordering unexpected, exclamation entries (!) incorrectly changed

### ISSUE THREAD

**Issue by Auronmatrix** [projen/projen#453]
Fist off. Love the project, really appreciate the work being done here. 

Version: Projen 6.14.9

I'm evaluating projen for a CDK-Construct Lib project. Due to project requirements I have some .gitignore entries that conflict with the project type defaults. I found the `gitginore` property in the `.projenrc.js` file which I've modified as follows:
```
  gitignore: [
    '!lib/',
    '!OtherFileNotToIgnore*'
]
```

**Adding entries to this array I would naturally expect them to be appended to the END of the .gitignore file, since ordering for .gitignore is relevant.** 
**Currently these entries are injected into a random location in the centre of the .gitignore file.**

It seems like this is cause by the entries being added in the base [node-project.ts](https://github.com/projen/projen/blob/392e458303e255d257268c53c4e9b5022972e0cc/src/node-project.ts#L471):
```    
this.addDefaultGitIgnore();
    if (options.gitignore?.length) {
      for (const i of options.gitignore) {
        this.gitignore.exclude(i);
      }
    }
```

After which other projects that extend node-project e.g. [typescript-project](https://github.com/projen/projen/blob/392e458303e255d257268c53c4e9b5022972e0cc/src/typescript.ts#L252)
attach on their ignores. 

In addition, it seems like the `!` is being stripped from the entries in the projenrc.js.gitignore property due to the [replace pattern](https://github.com/projen/projen/blob/392e458303e255d257268c53c4e9b5022972e0cc/src/ignore-file.ts#L21). This is definitely causing usage behaviour to be extremely confusing. 

Should the IngoreFile.Exclude/Include be called depending if the projenrc.js.gitignore array entries contain an `!` or not explicitly?

- Is my assumption that the entries should be appended at the end of the file wrong?
- Is my assumption that if I add an entry with an exclamation (!) in the projenrc.js.gitignore property it should be passed through to the .gitignore file wrong?

If these assumptions aren't wrong, I'll be open to looking into a PR.

**Comment by abrobston** [comment]
I just showed up to say that https://github.com/projen/projen/commit/666798058e42cba5f4662462c03271347f3c33d4#diff-51d06573fd308dcd3587e9a80a602bd15a553afb3047ca7b67dddcd55af40895R22 is a breaking change, but the new PR should fix it.  My issue was that the `gitignore` property of, in my case, `AwsCdkTypeScriptAppOptions` had a negation.

I'm not completely sure that order within `.gitignore` doesn't matter, though.  From https://git-scm.com/docs/gitignore#_pattern_format (emphasis added):

> An optional prefix "!" which negates the pattern; any matching file excluded by a _previous pattern_ will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.

I'd want to ensure that an exclude-include-exclude scenario still works (if that makes sense).  It could be that having all `!` patterns at the end works fine, but I don't have time to test at the moment.
