### ISSUE TITLE
Executable File

### ISSUE THREAD

**Issue by jakepearson** [projen/projen#454]
Is there a way to make an output from `projen` be marked as executable? Specifically, I would like to generate a bash script with my `projen` project and give it `+x`. 

If this doesn't exist and would be useful, I would be happy to try to submit a PR.

**Comment by eladb** [comment]
Not at the moment, but it should be trivial to add that to `TextFile` as an option.

**Comment by jakepearson** [comment]
Thanks, I'll do it right now.
