### ISSUE TITLE
RFC - Agenda Items for Projen's 1st Community Meeting - Wed Jan 20, 2021 12-1p EST

### ISSUE THREAD

**Issue by pgollucci** [projen/projen#457]
Event: https://www.eventbrite.com/e/projen-community-meeting-tickets-135326213347

# Intro 

- by @eladb 

# Attendee Introductions

# Whatever @eladb wants to talk about

# Community Discussion items

- Domain Names
- Most important next major feature
- 1st class Windows support
- NodeProject vs Project
- aws/constructs
- Python
- Docs Site
- How to publish meeting notes

Please add any items.  There is no order in this list currently.

**Comment by abelmokadem** [comment]
MonoRepoProject (Yarn / NPM 7?) 😁 
Decouple GitHub from Projects? Make CI/CD system configurable (GitLab / GitHub / AzureDevOps?)

**Comment by abelmokadem** [comment]
What-are-you-doing-with-projen showcase? Showcase for people that are building libraries based on projen? I think a lot of tips and tricks can be shared and maybe ideas can come up for new things in projen based on showcasing?

**Comment by thomasklinger1234** [comment]
hey, is there a possibility that one can join and listen to the meeting? would be quiet interested to listen to the roadmap etc as I am going to integrate projen as our standardization solution for repositories and currently building a python integration (with an MvP already existing) :)

**Comment by eladb** [comment]
@thomasklinger1234 of course! It's an open meeting: https://www.eventbrite.com/e/projen-community-meeting-tickets-135326213347

**Comment by pgollucci** [comment]
Adding @Chriscbr's Design PR https://github.com/projen/projen/pull/493
