### ISSUE TITLE
how installing dependencies for other nodejs projects in the source

### ISSUE THREAD

**Issue by zxkane** [projen/projen#488]
I’m working on a cdk application. I created a lambda using `lambda-nodejs`, which also uses `package.json` to manage the dependencies of lambda.

In a clean env, the `yarn build` failed on building the source of lambda without installing the dependencies of lambda. What’s the best practice to manage the dependencies of nodejs lambda source in a projen managed cdk app?

**Comment by eladb** [comment]
Reopen if this does not answer your question
