### ISSUE TITLE
Deprecate or rework tips

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#492]
Several minor versions ago, tips stop being rendered in the CLI. But the API still exists in the source code, so possible options are:

- start showing tips again
- deprecate tips API
- rework tips (maybe add an option to disable them? or add a "show tips" command?)

**Comment by pgollucci** [comment]
I see in 0.13.6 ? 

Either way I agree remove this.

**Comment by eladb** [comment]
Remove away!
