### ISSUE TITLE
Make release workflow editable / extendable

### ISSUE THREAD

**Issue by mmuller88** [projen/projen#494]
Hello fellaws.

I think I found a cool use case to make the release workflow editable. Actually I would like to publish a docker image to docker hub and lift as much as possible to projen :D. Actually the probably most convenient way is to use a GitHub  Action.https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images . It has the huge advantage of a secret manager and simplicity. I tried to use Projen Tasks for it but I would need to handle The Docker Hub Password there which is a drag! My suggestion is to implement simple to Tasks:

```
project.github.workflows.tryFind('release');
```

That would return GithubWorkflow and there we easily can set new jobs. What you guys think?

**Comment by Chriscbr** [comment]
This sounds reasonable to me! I know there's some discussion about adding a more complete set of APIs in #298, but being able to access workflows similar to how we can access tasks makes sense. 👍

**Comment by mmuller88** [comment]
Cool I will work on a PR :) many thanks
