### ISSUE TITLE
React typescript project should generate "dom" and "dom.iterable" in tsconfig.json

### ISSUE THREAD

**Issue by NukaCody** [projen/projen#496]
React typescript projects generate a tsconfig.json file with:

```json
  "compilerOptions": {

    // snip...

    "inlineSources": true,
    "lib": [
      "es2018"
    ],
    "module": "esnext",

   // snip...
  },
```

React runs in the browser and typescript needs clarification as to whether it's asking types from the browser or from node. For example, does `URL` refers to the node URL or the browser URLs library? A sensible default would be:

```json
  "compilerOptions": {

    // snip...

    "inlineSources": true,
    "lib": [
      "dom",
      "dom.iterable",
      "es2018"
    ],
    "module": "esnext",

   // snip...
  },
```

**Comment by Chriscbr** [comment]
When I try creating a new react typescript project with `npx projen new react-ts`, the `tsconfig.json` file generated for me includes dom, dom.iterable, and esnext, so I'm not sure how to reproduce this. Can you check what version of projen you're using in your package.json, or see if anything else could be overriding the tsconfig options?

**Comment by NukaCody** [comment]
Odd....I just created a new project with the same command and it's there. Ohhh okay I figured it out...

in projen...

```typescript
  tsconfig: {
    compilerOptions: {                                                         /* Custom TSConfig. */
      // lib: [
      //   "dom",
      //   "dom.iterable",
      //   "es2018"
      // ],
      jsx: 'react-jsx',
      allowJs: true,
      skipLibCheck: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      forceConsistentCasingInFileNames: true,
      module: 'esnext',
      moduleResolution: 'node',
      isolatedModules: true,
      noEmit: true
    },
  },
```

If I try to override any compiler options (even when `lib` is commented out). It writes out the top code piece (in original comment). 

So it seems that if I want to overwrite a specific tsconfig value, I need to also be explicit with `lib` otherwise 'dom' and 'dom.iterable' won't be included in the next `npx projen` command

**Comment by Chriscbr** [comment]
I think this resembles a bug that we had in earlier version of projen, but I thought it was fixed. When I try adding all of the compiler options in your second comment, my tsconfig still retains `lib: ["dom", "dom.iterable", "es2018"]`. Is it possible you're using an older version? If you open `/node_modules/projen/version.json` it should tell you the version you're on.

**Comment by NukaCody** [comment]
Ahh I see. I've been using npx, `npx projen --version` shows `0.6.14`. Global install is also `0.6.14`. I tried doing a manual delete and install of projen but it's giving me permission errors oddly enough. While `aws-cdk` doesn't. But that's most likely a me issue I need to resolve. Thanks for the help!
