### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by davidsteed** [projen/projen#498]
Get the following - which I think is related to the paths not being correct
```
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types
npm ERR! dest C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types' -> 'C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types' -> 'C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types' -> 'C:\Users\david\AppData\Roaming\npm-cache\_npx\10136\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Users\\david\\AppData\\Roaming\\npm-cache\\_npx\\10136\\node_modules\\projen\\node_modules\\.xmlbuilder2.DELETE\\node_modules\\@types',
npm ERR!     dest: 'C:\\Users\\david\\AppData\\Roaming\\npm-cache\\_npx\\10136\\node_modules\\projen\\node_modules\\xmlbuilder2\\node_modules\\@types'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, rename 'C:\\Users\\david\\AppData\\Roaming\\npm-cache\\_npx\\10136\\node_modules\\projen\\node_modules\\.xmlbuilder2.DELETE\\node_modules\\@types' -> 'C:\\Users\\david\\AppData\\Roaming\\npm-cache\\_npx\\10136\\node_modules\\projen\\node_modules\\xmlbuilder2\\node_modules\\@types'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\david\\AppData\\Roaming\\npm-cache\\_npx\\10136\\node_modules\\projen\\node_modules\\.xmlbuilder2.DELETE\\node_modules\\@types',
npm ERR!   dest: 'C:\\Users\\david\\AppData\\Roaming\\npm-cache\\_npx\\10136\\node_modules\\projen\\node_modules\\xmlbuilder2\\node_modules\\@types',
npm ERR!   parent: 'projen'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2021-01-17T09_59_49_956Z-debug.log
Install for [ 'projen@latest' ] failed with code 4294963248
```

**Comment by Chriscbr** [comment]
Could you share what versions of node and npm you're using? Also what command were you running that caused this error?

**Comment by davidsteed** [comment]
npx projen new react-ts --help
npm version 6.14.4

**Comment by JordanSinko** [comment]
I am also able to replicate this. The highest version I can install is 0.13.9. I get the above issue when installing https://github.com/projen/projen/releases/tag/v0.13.10 or above

os: Windows 10 19042.746
node: v14.15.4 (LTS)
npm: 6.14.11

**Comment by Chriscbr** [comment]
Ok I'm able to reproduce the issue on node v14 as well. It can also be reproduced by running `npm install -g projen`. Unfortunately I'm not sure how to fix it yet - part of the difficulty is that it's difficult to test "npm install" using local versions of projen with changes. That said, it appears to be caused by the addition of the `xmlbuilder2` library in projen 0.13.10 ([commit](https://github.com/projen/projen/commit/de8a688137d5dde9cfe084c3e997472c9001fde1)).

The current workarounds I've found:

- Use node v15.x.x or above
- Install projen globally using `yarn global add projen` and run `projen new <project-type>` to bootstrap your project. Then you can run `npx projen` commands inside the project directory normally. Afterwards, you're free to remove the global projen command if you'd like to avoid polluting the global namespace via `yarn global remove projen`.

I'm not really familiar with this kind of bug, but I'd like try pinning different versions of xmlbuilder2 or its dependencies and see if that fixes the bug. Specifically, `xmlbuilder2` has a runtime dependency on `@types/node` which could be causing a conflict of some kind.

**Comment by NukaCody** [comment]
Can confirm the above workaround works for me on Windows

**Comment by campionfellin** [comment]
This is also causing issues with Windows integration tests in `cdk8s`: https://github.com/awslabs/cdk8s/pull/441/checks?check_run_id=1774424564

```
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\RUNNER~1\AppData\Local\Temp\tmp.BBS4eewv9h\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types
npm ERR! dest C:\Users\RUNNER~1\AppData\Local\Temp\tmp.BBS4eewv9h\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 
```

etc

**Comment by misterjoshua** [comment]
I had the same problem, but upgrading to node 15 wasn't an option.

I got projen working in Windows 10 with Node 14.15.4 LTS by using a project-local node_modules. This is what I did:

``
PS E:\Proj> yarn init
PS E:\Proj> yarn add --dev projen
PS E:\Proj> yarn projen new awscdk-construct
```

**Comment by campionfellin** [comment]
Looks like `xmlbuilder2` has fixed the issue and will be releasing a new version this weekend!

**Comment by eladb** [comment]
Brilliant.

**Comment by campionfellin** [comment]
Still waiting on the new version to be published - 

https://www.npmjs.com/package/xmlbuilder2
https://github.com/oozcitak/xmlbuilder2/releases

**Comment by campionfellin** [comment]
Even with that fix, still getting:

```
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\npm\prefix\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types
npm ERR! dest C:\npm\prefix\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\npm\prefix\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types' -> 'C:\npm\prefix\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\npm\prefix\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types' -> 'C:\npm\prefix\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\npm\prefix\node_modules\projen\node_modules\.xmlbuilder2.DELETE\node_modules\@types' -> 'C:\npm\prefix\node_modules\projen\node_modules\xmlbuilder2\node_modules\@types'] {
```

**Comment by Chriscbr** [comment]
@campionfellin I'm getting the same. Maybe post an issue on npm/npx to see if someone with knowledge of npm internals knows what is causing this? Most other postings of this error message online seem to say these are caused by cache or permission issues with npm, but it seems unlikely given that everyone here is running into the same bug.

**Comment by campionfellin** [comment]
@Chriscbr does `npm cache clean --force` fix the issue for you?

**Comment by Chriscbr** [comment]
Unfortunately not. :(
