### ISSUE TITLE
Permissions issue on windows trying to symlink

### ISSUE THREAD

**Issue by jakejscott** [projen/projen#5]
Hi @eladb 

I just tried this out on my windows machine, and ran into an issue with not running my command line as administrator. I was just using the vs code command line interface (but not running as admin)

When I ran as admin it works

```
EPERM: operation not permitted, symlink 'C:\Users\jake\AppData\Roaming\npm-cache\_npx\11080\node_modules\projen' -> 'node_modules\projen'
```

**Comment by eladb** [comment]
Yeah there's a symlink hack for bootstrapping.. we should special-case windows. Happy to take contributions

**Comment by tomgcavanaugh** [comment]
I had a similar issue, it was necessary to run the project generation commands as administrator.  I also installed yarn; but I am not entirely sure that step was required.

**Comment by john-tipper** [comment]
What's the symlink hack for bootstrapping on a Windows machine please? I do not have (and will not have due to work security policies) admin permissions on my work development server.

**Comment by john-tipper** [comment]
I've added a check for whether the OS is Windows and if so, the symlink is created using a Windows `junction` type. PR #328 refers. I can successfully create a project on Windows where I am not an administrator.
