### ISSUE TITLE
Bug: `npx projen new awscdk-app-ts` or `yarn projen:upgrade` breaks projen

### ISSUE THREAD

**Issue by smacintyre** [projen/projen#507]
This is weird. I'm able to repro this 100% of the time on both gitpod and locally. Simply create a new `awscdk-app-ts` or upgrade an existing one and now `yarn projen` tries to run `yarn run cdk synth`.

## Steps to reproduce

1. In a new/empty repo or directory
2. Run: `npx projen new awscdk-app-ts`
3. Run `yarn projen`

## What Occurs 

From this point forward, `yarn projen` actually runs `yarn synth`. Note, the same thing happens when running `npx projen` or if you try to upgrade projen by running `yarn projen:upgrade`.

```sh
$ mkdir projen-upgrade-fails

$ cd projen-upgrade-fails/

$ npx projen new awscdk-app-ts
🤖 Synthesizing project...
🤖 yarn install --check-files
yarn install v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 86.36s.
🤖 Synthesis complete
🤖 Created .projenrc.js for AwsCdkTypeScriptApp

$ yarn projen
yarn run v1.22.10
warning ../../package.json: No license field
$ npx projen
🤖 synth | cdk synth
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.85.0,@aws-cdk/cloud-assembly-schema=1.85.0,@aws-cdk/core=1.85.0,@aws-cdk/cx-api=1.85.0,@aws-cdk/region-info=1.85.0,jsii-runtime=node.js/v15.6.0
    Metadata:
      aws:cdk:path: my-stack-dev/CDKMetadata/Default

✨  Done in 9.38s.
```

## Expected Result

It should regenerate the project's configuration files.

**Comment by hoegertn** [comment]
Maybe: https://github.com/projen/projen/pull/505

**Comment by smacintyre** [comment]
Yes, appears to be. Testing upgrading, moving to the latest, `0.15.6` is what breaks it. And that is #505 

To work around this, we can:
- Delete the `.projen` directory
- Set `projenVersion` to `0.15.5`
- Then run `yarn projen` 

And things will return to normal. We can't upgrade past `0.15.5` for the time being.

**Comment by hoegertn** [comment]
What about projen:synth for the files to not break cdk synth? @eladb any thoughts?

**Comment by eladb** [comment]
as a workaround, delete the "synth" task from your project.
