### ISSUE TITLE
Seeing duplicate entries for node_modules in jest configuration exclude

### ISSUE THREAD

**Issue by abelmokadem** [projen/projen#515]
I've added the following configuration to projen:

```
  jestOptions: {
    typescriptConfig: {
      compilerOptions: {
        lib: [
          'es2015',
          'dom',
        ],
        module: 'ES2015',
        moduleResolution: 'node',
        target: 'ES2015',
      },
      exclude: [
        'node_modules',
        'out',
      ],
    },
  },
```

And I see the following output in tsconfig.jest.json:

```
  "exclude": [
    "node_modules",
    "node_modules",
    "out"
  ]
```

I would expect to see the following output:

```
  "exclude": [
    "node_modules",
    "out"
  ]
```

projen@0.15.13
Mac OS

**Comment by Chriscbr** [comment]
This is handled by the function here (which gets called once in `typescript.ts`):
https://github.com/projen/projen/blob/d6b0611e0a759f2d5103a27bdcc7d15e579ae9e9/src/jest.ts#L669-L689

It probably makes sense to deduplicate the items - should be a simple fix.
