### ISSUE TITLE
Feature Request: Publish NPM package to Github Packages

### ISSUE THREAD

**Issue by Hunter-Thompson** [projen/projen#531]
Can we have a task in the Release workflow that publishes the NPM package to Github?

e.g 

```
publishToGithub: true
```

Is there already a way for me to do this? If yes, can someone guide me to some documentation on how I can achieve this without having to create a new workflow using `project.github.addWorkflow()`

**Comment by guan840912** [comment]
Hi ,here is example repo https://github.com/guan840912/secure-bucket .😎

**Comment by eladb** [comment]
Btw I believe "publishConfig" is not required.

**Comment by Hunter-Thompson** [comment]
> Hi ,here is example repo https://github.com/guan840912/secure-bucket .😎

Thanks for the reference, I am able to update my workflow : - )

> Btw I believe "publishConfig" is not required.

Yes, I did not have to use `publishConfig`.
