### ISSUE TITLE
Predefined options in newly generated projenrc's

### ISSUE THREAD

**Issue by joostvdwsd** [projen/projen#549]
We are building multiple project types for usage with the --from flag. This process really helps in standardisation within our company. 

One thing i'm looking into is adding default configuration options into generated projenrc files (a big wish is to have this as a typescript file)

What I was thinking of is that when the new project is generated that the project class can return a predefined struct of configuration options that are put into the options part of the projenrc file.

Example usage:

```typescript
class MyCustomTypescriptProject extends TypeScriptProject {
  
  generateDemoConfiguration() {
    return {
      ...super.generateDemoConfiguration(),
      environments: {
        staging: {},
        prod: {}
      }
    }
  }
}
```

This would then end up in the projenrc file as:

```typescript
const project = new MyCustomTypescriptProject({
  name: 'project name',
  environments: {
        staging: {},
        prod: {}
      }
})
```

This will give more options in adding things like "best practices", mandatory options, example usages.

**Comment by eladb** [comment]
I like this idea. Let me make sure I fully understand the use case: you want a project attribute to be _optional_ but still appear in the initially generated projenrc. Correct?

I understand the current behavior in which we render all the optional attributes in comments is not good enough. Is it because it's too verbose? One idea that we discussed was to only render comments for optional attributes that have some annotation like `@featured` instead of doing that for all options. Would this be sufficient for your use case? (not entirely sure how this will work with complex types though, so maybe not).

**Comment by joostvdwsd** [comment]
Kinda correct yes. Most of the time its optional but it doesn't have to be. Sometimes you want it mandatory but it can follow a best practice example that can be adjusted after projenrc creation (so no need to ask for it during creation of the project).

I was never a real fan of the commented out options. They are kinda ok but, what you already mentioned, not really good for complex configuration types. And especially for the complex types this is way better.

The side note about projenrc in typescript format actually will help with this. Then your options are checked and probably better with autocompletion (basically the commented out options are then available through code completion including complex types).

**Comment by eladb** [comment]
> Sometimes you want it mandatory but it can follow a best practice example that can be adjusted after projenrc creation (so no need to ask for it during creation of the project).

If the field is mandatory, you can use the `@default` annotation to specify a value that will be automatically added to the generated projenrc.

> I was never a real fan of the commented out options. They are kinda ok but, what you already mentioned, not really good for complex configuration types. And especially for the complex types this is way better.

Yes, I agree. I don't like them either. That's why I'd like to only show a bunch of "featured" options to make it easy for people to get started. But I am not sure about this TBH (@Chriscbr might have an opinion).

> projenrc in typescript 

Definitely on the radar. We already have the basic mechanism to do that (for example, JavaProject produces projenrc in java).

**Comment by Chriscbr** [comment]
> Yes, I agree. I don't like them either. That's why I'd like to only show a bunch of "featured" options to make it easy for people to get started. But I am not sure about this TBH (@Chriscbr might have an opinion).

I'm totally cool with cutting down on the wall of options through some kind of featured label, and including those featured options as uncommented (if it's possible avoid the snag w/ complex types you mentioned).

**Comment by pgarbe** [comment]
I like that idea. If you're not using GitHub, a lot of (useful) defaults needs to be disabled. Although, there might be another solution to my problem as well. Like group these GitHub options somehow together as presets? Have an OpenSourceGitHub preset and one for my company...

**Comment by joostvdwsd** [comment]
This is indeed also about CICD. We have another CICD system and we have a lot of complex types for this to generate the CICD pipelines. I tried to use a yarn link to play with @default but tbh apparently thats not working nicely.

I'm afraid documentation annotations like @default will never be sufficient for complex types, also you want to add logic behind this based on the (sub) project. 
Typescript Annotations/decorators can be used of course but a simple overridable method on Project that can inject defaults in the generated projenrc is a lot easier.

**Comment by joostvdwsd** [comment]
I was actually thinking about the @featured flag. If you can recursively dive into struct types and add that to the project it would already do a lot. One of the issues I will encounter is with the following type i'm using a lot:

```typescript
export interface Environments<E extends EnvironmentOptions> {
  readonly [name: string] : E;
}
```

in that case I would like to return a couple of default environments like:
```typescript
{
  development: {
    loglevel: 'DEBUG'
  },
  testing: {
    loglevel: 'INFO'
  },
  production: {
    loglevel: 'ERROR'
  }
}
```

Both the dynamic keys as the different featured content inside the EnvironmentOptions struct will not be doable by documentation annotation only. Very easy done if you can return a struct to insert into the options

**Comment by pgollucci** [comment]
> I like that idea. If you're not using GitHub, a lot of (useful) defaults needs to be disabled. Although, there might be another solution to my problem as well. Like group these GitHub options somehow together as presets? Have an OpenSourceGitHub preset and one for my company...

The GitLab component should help iron this out

**Comment by Chriscbr** [comment]
Does the "@featured" capability that was added satisfy this issue, or are there still use cases where we want more granular ways to expose options/defaults in the initial projenrc file?

**Comment by joostvdwsd** [comment]
As i already said. The @featured option or any other static option wil never be satisfactory for what we need. Ita mainly about complex types. 

Even if you have nested types this wiuld not work nicely in the structure where we for instance define environments (and others). There you will have different values for the same property based on the context. 

Only real way is to allow the project subclass to return a customizable structure. Its loaded during the new step so it is a small change.
