### ISSUE TITLE
Structured output option

### ISSUE THREAD

**Issue by kiiadi** [projen/projen#574]
Other tools may want to call `projen` for example an IDE that's synthesizing build artifacts; such interactions would require applying regexes/heuristics to the "pretty" CLI output emitted to `stdout` in order to understand and make decisions from it. Please consider including an optional `--json` argument for all command, this option would emit CLI output to `stdout` in the form of a structured json document that can be more easily consumed programmatically.

**Comment by Chriscbr** [comment]
Could you give some examples of how other CLI tools provide structured output for comparison?

**Comment by eladb** [comment]
Keep
