### ISSUE TITLE
bug(cleanup): project file cleanup is broken

### ISSUE THREAD

**Issue by gradybarrett** [projen/projen#578]
System: macOs 10.15.7
Node v14.15.4

This appears to be caused by the `absolute` option in the `glob.sync` file collection step during cleanup. I expected this option to resolve all the returned files into absolute paths, but instead it causes `sync` to return an empty array. Removing the `absolute` option fixes the problem, but then file paths are not absolute.

https://github.com/projen/projen/blob/7c0d17e8fb3100a7d0b3ab0e024e24280aae48c8/src/cleanup.ts#L20-L26

![image](https://user-images.githubusercontent.com/1140074/109350463-626ae980-782c-11eb-8a19-046f91807a22.png)

@hoegertn it looks like you introduced this to resolve directory-specific cleanup issues in #143, but a lot has changed since then. Are absolute paths still necessary in this context? If so any insights from when you added the `absolute` option as to why it would be behaving this way?

**Comment by hoegertn** [comment]
So the original issue for nested projects was that clean up did the file search in the nested folder and returned an array of files. It then tried to delete them in the root folder as they did not contain the sub-path.

I have no idea if this is still needed or why it would return an empty array.

**Comment by gradybarrett** [comment]
Thanks! I think I was expecting associated artifacts to be removed when I removed their corresponding configuration from projenrc, but the current file marking and tracking strategy doesn't allow for that to occur. I'm going to close this and open up a different issue for that behavior.
