### ISSUE TITLE
feature request: eject out of projen

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#596]
Discussed briefly in #337 comments

As a user, it would be nice to be able to "eject" myself out of projen if I wanted to. This should change permissions all projen-controlled files so that they are not readonly (and removing the "Generated by projen" markers, perhaps), as well as exporting the tasks in some kind of uniform way. That is, for NPM projects, all tasks would be rendered in the `scripts` section of `package.json` (currently achievable with `npmTaskExecution: NpmTaskExecution.Shell`), while for other project types (Python, Java, etc.), the tasks could be automatically exported in some universal format like a Makefile or shell script.

Inspired by the similar feature in other CLI tools, such as [create-react-app eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject).

**Comment by eladb** [comment]
Keep

**Comment by Chriscbr** [comment]
Keep
