### ISSUE TITLE
Projen doesn't generate a restricted publishConfig

### ISSUE THREAD

**Issue by mark-ship-it** [projen/projen#610]
For those wanting to create a restricted package, they should be able to either specify a scope `@myorg/package`, or add `npmAccess: NpmAccess.RESTRICTED,` explicitly to their project.

Unfortunately, neither creates the following snippet in package.json:

```
  "publishConfig": {
    "access": "restricted"
  }
```

**Comment by Chriscbr** [comment]
According to the [NPM docs](https://docs.npmjs.com/cli/v6/using-npm/config#access), the default behavior for scoped packages is to be restricted - so projen will just omit this field from package.json by default unless you specify `npmAccess` as public. 🙂 

If you want to include this field anyways, you can manually set it like this:
```ts
project.tryFindObjectFile('package.json').addOverride('publishConfig.access', 'restricted');
```
