### ISSUE TITLE
projen new: interactively ask for required options

### ISSUE THREAD

**Issue by joostvdwsd** [projen/projen#613]
Sometimes there are properties mandatory for a project type without the posibility for auto lookup.
In that case it would be great to have projen ask for the configuration option through the CLI. 

I know i've been asking a couple of idea's for the "new" concept. This is one of the few sections of projen without the posibility of customization. Having a more customizable bootstrap would also be great. 
Also I don't mind sending some pr's but before I do stuff I think its nice to know if the idea's are welcome and will fit within the future idea of projen.

**Comment by joostvdwsd** [comment]
The idea I had was something like this:

@default #Specify your team name

This would generate a cli input line with the specified question

**Comment by mrgrain** [comment]
Prior Art:

https://github.com/projen/projen/pull/2926
https://github.com/projen/projen/pull/2975
