### ISSUE TITLE
dependabot - Docker, GitHub Actions, etc.

### ISSUE THREAD

**Issue by nikovirtala** [projen/projen#620]
The projen dependabot configuration currently supports only the npm ecosystem, but the dependabot supports many other ecosystems, like Docker and GitHub Actions, too. It would be great if one could configure them all using projen. 

How can we make this possible?

- https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
- https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot#about-dependabot-version-updates-for-actions

**Comment by schickling** [comment]
That's the closest I've seen @github-actions to committing self-harm. 🤣

On a more serious note: Yes, would be great if Docker & GitHub Actions were part of the scope of projen.
