### ISSUE TITLE
Add an option to SampleFile to only generate a sample file if the directory does not exist

### ISSUE THREAD

**Issue by abelmokadem** [projen/projen#627]
Add an option to SampleFile to only generate a sample file if the directory does not exist.  

```
new SampleFile(project, 'foo.bar', {
  generateInExistingDirectory: false
})
```

Sometimes you want to generate sample code and let people rename the file. Think of the AWS CDK sample code.

**Comment by Chriscbr** [comment]
I think `SampleDir` handles this, no?
