### ISSUE TITLE
Set GitHub-linguist attributes for generated files

### ISSUE THREAD

**Issue by RomainMuller** [projen/projen#629]
To improve the PR review experience, it would be nice if `projen` maintained a `.gitattributes` file that enabled the `linguist-generated` attribute on files it is in control of (this can include `yarn.lock` files, even through "technically" not generated by `projen` - they are not covered by the default *generated* behavior).

The advantage of this are:
- Diff on those files will be hidden by default on PRs (you can still click-to-load if you want to control them)
- They get excluded from repo statistics (so the "hand-written" code - which relates to maintenance cost / quality - is better reflected)

Ref: https://github.com/github/linguist/blob/master/docs/overrides.md

**Comment by Chriscbr** [comment]
This is a great idea, I didn't know GitHub supported this feature!  +1 from me. 🙂

**Comment by eladb** [comment]
👍 here as well. This can also be combined with hiding generated files in VSCode for example.
