### ISSUE TITLE
feat: resolvable objects

### ISSUE THREAD

**Issue by gradybarrett** [projen/projen#636]
## Feature

It would be nice to be able to pass a resolvable object for lazy resolution.

```typescript
new pj.JsonFile(this.project, this.fileName, {
  marker: true,
  obj: {
    someKey: new BufferedContent(...),
  },
});
```

Right now the resolve function only resolves fundamental JS types.

https://github.com/projen/projen/blob/05025555ef8448978450241a36b4bdfe48536101/src/_resolve.ts#L30-L33

##  Use Case

In this case, `BufferedContent` is an object used to read code from a file. That code is then included in a configuration file. This is useful for things like declaring Auth0 hook scripts for upload through an SPI.

## Workaround

```typescript
const bufferedContent = new BufferedContent(...);

new pj.JsonFile(this.project, this.fileName, {
  marker: true,
  obj: {
    someKey: bufferedContent.resolveContent.bind(bufferedContent),
  },
});
```

**Comment by Chriscbr** [comment]
Hmm, I'm a little rusty with the way `this` bindings operates. Would something like  `someKey: () => bufferedContent.resolveContent()` work in your workaround example, or does that break it?

**Comment by gradybarrett** [comment]
> Would something like `someKey: () => bufferedContent.resolveContent()` work in your workaround example

It would! I'm a bit rusty on the details myself, but I'm pretty sure arrow functions preserve `this` binding. I vaguely recall there being some downsides as well though, but I can't remember what off-hand. 🤔
