### ISSUE TITLE
Add an ARCHITECTURE.md

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#647]
Inspired from reading https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html

I think it could be useful just to document some high level concepts of how the library is written, such as how the library makes use of [constructs](https://github.com/aws/constructs), and how some of the core projen functions work (like the synthesis / cleanup process, and how project options are discovered using jsii).

Some of projen's architecture is still up in the air, e.g.:
- At the last projen meetup, Elad mentioned the possibility of shifting from an inheritence based project model (where there is a strict hierarchy from Project -> NodeProject -> TypeScriptProject -> JsiiProject -> ConstructLibrary -> AwsCdkConstructLibrary) to a more modular project model
- How subprojects are modeled and implemented (there is a system in place, and we have some docs, but I think there's a bit of confusing behavior, and I know monorepos are a priority on the roadmap)

So I might omit writing about those for now.

- [x] I can try to implement this

**Comment by pgollucci** [comment]
The component idea is definitely growing on me.
