### ISSUE TITLE
fix(external-projects): projen as a peerDependency

### ISSUE THREAD

**Issue by gradybarrett** [projen/projen#648]
### Use Case

Given that I have an external project that is built using projen
When people consume that external project
Then they should be able to bring their desired projen version, and it should not clash with the version of projen used to build the external project.

### Context

I've been writing an external project, built using the projen JsiiProject. I've noticed that in order for project creation `--from` an external project to work correctly, I have to declare projen as a full dependency in my external project. But it seems to me that external projects conform to the description of a "plugin" given in the [peerDependencies docs](https://nodejs.org/en/blog/npm/peer-dependencies/). That makes sense to me because I want people to be able to bring the latest and greatest projen to my external project without it clashing with a projen version declared in my external project. If, however, I make projen a peer dependency in my external project it won't yet be available during project synthesis, which means project creation fails b/c peerDependencies of the external project aren't yet satisfied.

https://github.com/projen/projen/blob/b9152631d7f79d83df175cda497fe3f01cb3b46f/src/cli/cmds/new.ts#L437-L442

I can hack this by installing projen alongside the new project, but that feels strange.

```typescript
  }

  logging.info(`installing external module ${spec}...`);
  // new.ts:440
  exec(`yarn add --modules-folder=${baseDir}/node_modules --silent --no-lockfile --dev ${spec}`, { cwd: baseDir });
  exec(`yarn add --modules-folder=${baseDir}/node_modules --silent --no-lockfile --dev projen`, { cwd: baseDir });

  // if package.json did not exist before calling yarn add, we should remove it
```

It would be nice to just use the version of projen used by npx until we get to the point where projen installs all dependencies for me, but I'm not sure if that's easy or possible to do in a consistent way across platforms.

Have I just come at this from the wrong angle? Or is this what it seems, which is a bit of a chicken before the egg situation?

**Edit:** Just a comment on the current experience. If I put projen as a dep and peerDep, projen ends up adding it as a devDep as well, which results in an invalid package.json. And if I try to use `projenDevDependency: false` to remove it, it gets added back b/c of the `pinnedDevDependency` behavior. I can set `peerDependencyOptions.pinnedDevDependency` to false, but that may not be desirable if there are other peer deps present. Lastly, my projen dep and peer dep don't match - both added as bare module name `'projen'`. The peer dep is rendered as `^0.17.17`, but the dep is rendered in locked form `0.17.17`.

So the final config I have to use to produce a valid package.json satisfy jsii is:

```javascript
  peerDeps: ['projen@^0.17.17'],
  deps: ['projen@^0.17.17'],
  peerDependencyOptions: { pinnedDevDependency: false },
  projenDevDependency: false,
```

**Comment by pgollucci** [comment]
I too have this issue I think in p6-projen-project-awesome-list I'll try and take a look

**Comment by pgollucci** [comment]
I confirm this is the same issue I have and the same fix
