### ISSUE TITLE
Bug: projen:upgrade fails when using npm instead of yarn

### ISSUE THREAD

**Issue by seeebiii** [projen/projen#651]
# Expected

I wanted to run `projen:upgrade` to upgrade the `projen` version in my repository, e.g. from `0.16.38` to `0.17.17` (latest version) in my `package.json`.

# Actual

The following error occurs:

```bash
npx projen projen:upgrade
🤖 projen:upgrade | yarn upgrade -L projen
yarn upgrade v1.22.10
error No lockfile in this directory. Run `yarn install` to generate one.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
🤖 Task "projen:upgrade" failed when executing "yarn upgrade -L projen" (cwd: [deleted])
```

I'm using `packageManager: NodePackageManager.NPM` in my project. That's why there's no `yarn` lockfile. You can look at the full [`.projenrc.js`](https://github.com/seeebiii/ses-verify-identities/blob/main/.projenrc.js) if you like.

Do you have any idea how to fix it besides switching to `yarn`? 😄 

If you need anything else from my side, please let me know :)

# Versions

Projen: 0.17.17 (installed globally on my system via `npm i -g`)
Node: v14.15.4
MacOS: 11.2

**Comment by thtliife** [comment]
I have the same behaviour occurring using ppm (`packageManager: NodePackageManager.PNPM`)
It seems the projen cli is hardcoded to use yarn for a few things through [the yarnAdd function](https://github.com/projen/projen/blob/125166e7975158252a62a9b3c36c8dbc49f62013/src/cli/cmds/new.ts#L418)

Would be aweome to have a cli option to specify the preferred package manager, and then have the generated .projenrc.js reflect that

**Comment by pgollucci** [comment]
We don't need an option.  The code is buggy.  It needs to call the wrapper.  This is a good-first-issue @eladb

**Comment by eladb** [comment]
I believe this is resolved by https://github.com/projen/projen/pull/692
