### ISSUE TITLE
Regression: Release 0.17.25  breaks Node subproject builds

### ISSUE THREAD

**Issue by smacintyre** [projen/projen#661]
Looks like #658 which is part of the 0.17.25 release breaks Node subproject's builds.

Our case:
- Frontend web.ReactTypescriptProject in the root of the repository 
- Backend TypescriptAppProject in the backend folder with parent set to the frontend project

In 0.17.20: `yarn --cwd backend build` worked perfect

Since upgrading, we get the following errors:
```
yarn run v1.22.10
$ npx projen build
🤖 build | npx projen
🤖 Unable to find /root/power-configurator/backend/.projenrc.js. Use "projen new" to create a new project.
🤖 Task "build" failed when executing "npx projen" (cwd: /root/power-configurator/backend)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by smacintyre** [comment]
@eladb FYI

**Comment by eladb** [comment]
@smacintyre thanks for reporting. Yeah, I can see why this is happening. We need to either synthesize only at the root project (probably the right thing) or make sure we use the correct `cwd` (probably both).

On it.

**Comment by smacintyre** [comment]
Thank you @eladb  !!!!
