### ISSUE TITLE
Bug(node): projenDuringBuild is set to false, the build action doesn't run projen

### ISSUE THREAD

**Issue by smacintyre** [projen/projen#665]
@eladb Another issue related to #658 

If `projenDuringBuild` is set to `false` the build github action is still changed to not run `projen`. Thus breaking when the builds action is performed.

Expected result: If `projenDuringBuild` is set to `false` the build action, the previous behaviour of running projen in the build github action should be persevered.

**Comment by eladb** [comment]
This is the intended behavior. It allows users to opt out of running projen during builds both in local and CI builds.


Can you describe your use case for wanting this to only be done during CI?

**Comment by smacintyre** [comment]
@eladb We pretty much always have to customize the build command for any project. Usually just resetting it and adding new steps. The most common reason is we want the build command to build the whole project, not just the root project. So we usually create tasks for `build:frontend` `build:backend` `build:infastructure` -- where backend and infrastructure are sub projects. Then `build` just calls these. This probably should be the default for `build` otherwise, the subprojects never get built by the CI builds. So we want to be able to reset the build command and not break the github action.

Second, from a DX perspective, we never want to run projen as part of builds. Projen is really slow, usually taking 5 or 6 minutes to run.  A normal build takes about 90s. That's fine in CI, but we don't want to slow down the developer feedback loop that much. Plus the .projenrc.js file rarely changes after initial project setup so there is no value in rerunning every build. Especially with the self mutation  feature. The average developer never has to run projen unless they want to add a dependency. We use Gitpod, so everything is prebuilt by them so we don't even need to run projen when starting a new environment. Prior to this change, everything mostly just worked. 

I'm sorry, I just don't see the reason for a major breaking change like this. Maybe I'm missing something. But why is the change to run projen as part of the build command even desirable?

**Comment by pgollucci** [comment]
External Projects for on, testing projen itself for another.

**Comment by eladb** [comment]
@smacintyre thanks for the input. Ack. I'll see what I can do.

**Comment by smacintyre** [comment]
@pgollucci @eladb I've updated all our projects to run `projen` as part of the build. So I'll close this. Sorry if I sounded a bit cranky. The change is fine, but I think some more attention is needed for projen monorepos like this.  I feel a lot of the changes don't really take them into consideration, but I think they are one of the strongest cases for projen. All good though. 👍🏼
