### ISSUE TITLE
Pinned DevDep with Version Ranges

### ISSUE THREAD

**Issue by skorfmann** [projen/projen#670]
Given a project with the following defined peer dependency:

```
project.addPeerDeps(`cdktf@^0.x`);
```

`npx projen` is trying to pin version `0.0.0` as the minimal dev dependency, which fails when actually installing via `npm` or `yarn`. 

Perhaps it would make sense to check for an existing dev dependency for the peer dependency. Alternatively, maybe checking for `0.0.0` and replace it with `0.0.1`.

I think that's the part which is responsible for pinning `peerDeps`:

https://github.com/projen/projen/blob/8dbae6be731b6ed9aef8d68e1bf0efb9330b58a8/src/node-package.ts#L708-L722

**Comment by skorfmann** [comment]
Ok, so that seems to be the way to go https://github.com/projen/projen/blob/b9152631d7f79d83df175cda497fe3f01cb3b46f/src/__tests__/integration/cdk8s/cdk8s.projenrc.js#L11-L15

**Comment by pgollucci** [comment]
I believe this can be closed. @skorfmann  @eladb
