### ISSUE TITLE
projenrcJava option is misleading/wrongly documented

### ISSUE THREAD

**Issue by jmgrimes** [projen/projen#671]
Trying out projen in my company's ecosystem, and I love the capabilities, but I hit an early snag that caught me a bit by surprise for Java projects.

Documentation in the projen repository highlights that changes to the project structure can be authored in the .projenrc.js file, but I found when using minimal options for Java projects, once the project is synthesized once, it no longer uses this file, and instead defaults to using the src/test/projenrc.java file.  No updates in the .projenrc.js file will ever be reflected in the project, which frustrated me for quite a while, until I found the --projenrc-java false option.

Shouldn't this flag should be false by default?  Otherwise Java projects operate differently than other projects out of the box, and might surprise (and possibly deter users trying to follow the documentation).  Until I found this option, I was convinced that Java project support wasn't working properly.

**Comment by eladb** [comment]
@jmgrimes, the idea is that for Java projects, we recommend that you manage your projen configuration in Java through the `projenrc.java` file. Have you tried to do that?

**Comment by jmgrimes** [comment]
Yes, I did notice that, and suppose that if the projenrc.js file weren't in the repo when using this option, it might be a little less confusing.  I just saw that updates in the js file weren't reflected in the java file, and it wasn't quite what I had expected at first glance.

Is the longer term intent that the projenrc.java file is the only supported way of managing a java project, or will both be supported with the preferred way being the java file?

**Comment by jmgrimes** [comment]
Playing around a bit more, I see that the npx projen command stops working once I do this, and installing projen directly via npm -g install projen is required to make this work for java projects the way I had intended, so I'll close this.

Thanks!

**Comment by eladb** [comment]
@jmgrimes still feels like docs are not ideal. Have you seen this? https://github.com/projen/projen/blob/main/docs/java.md

**Comment by jmgrimes** [comment]
I hadn't until now, but the docs seem to suggest that --projenrc-java needs to be enabled to write in Java, where this option does in fact need to be disabled if you want to manage with the .projenrc.js file.  Perhaps this issue is a documentation improvement?  I can reopen?

**Comment by eladb** [comment]
Thanks!
