### ISSUE TITLE
(NodeProject) projen silently fails to remove .mergify.yml when setting `mergify: false`

### ISSUE THREAD

**Issue by ilyasotkov** [projen/projen#696]
### Steps to reproduce

In an empty directory:

1. `npx projen new node`.
2. In `.projenrc.js`, add `mergify: false` to `NodeProject` options, then run `npx projen`.

### Observed behavior

`.mergify.yml` is still there

### Expected behavior

`.mergify.yml` is removed

### Other notes

I also tried setting e.g. `npmignoreEnabled: false` and this works as expected. I also tried manually removing `.mergify.yml` but it's still generated by projen despite `mergify: false`.

I can reproduce this in GitHub Codespaces using `node:14.16.1-buster-slim` Docker image.

**Comment by ilyasotkov** [comment]
I ran this through a debugger and discovered that `.mergify.yml` is being generated here

https://github.com/projen/projen/blob/b9104a6550b0c0685b43cf21e372843329116970/src/github/dependabot.ts#L168-L184

and that setting `dependabot: false` in `NodeProject` options stops  `.mergify.yml` from being generated.

**Comment by pgollucci** [comment]
Tagging myself @pgollucci

**Comment by ilyasotkov** [comment]
Closing, fixed by #741
