### ISSUE TITLE
fix(release): fatal: tag 'v0.17.50' already exists

### ISSUE THREAD

**Issue by Hunter-Thompson** [projen/projen#703]
The latest release failed because the tag already exists, but I can't see any logs in any release action that created that tag.

https://github.com/projen/projen/runs/2382525748

Can the release be rerun? A fix for cdk8s-app-ts is waiting to be released : )

**Comment by pgollucci** [comment]
@eladb I believe you need to merge https://github.com/projen/projen/pull/700 to fix https://github.com/projen/projen/pull/683
