### ISSUE TITLE
[RFC]: next.js generated directory structure change

### ISSUE THREAD

**Issue by pgollucci** [projen/projen#708]
This should apply similarly to both js and ts versions, so I am only describing ts here.

### Today, projen generates this (snipped):

```shell
├── next-env.d.ts
├── node_modules
├── package.json
├── pages
│   └── index.tsx
├── postcss.config.json
├── public
│   └── vercel.svg
├── tailwind.config.js*
├── tsconfig.json
└── yarn.lock
```

\* - https://github.com/projen/projen/pull/704

### Use Case Issue:

`projen` sets `rootdir: pages` which means if you add a `components/` parallel to `pages/` it will not be in root dir.  I don’t think it makes sense to put `components/` in `pages`.  Either way, this is decided, the `tsconfig.json` will need to dynamically update includes.

See also https://github.com/projen/projen/issues/183

#### Option 1

Mimic `src/` as `app/` i.e.:

```shell
├── app
│   ├── __test__
│   ├── api
│   ├── components
│   ├── constants
│   ├── content
│   ├── context
│   ├── graphql
│   ├── hooks
│   ├── pages
│   ├── public
│   └── styles
├── next-env.d.ts
├── next.config.js
├── node_modules
├── package.json
├── postcss.config.json
├── tailwind.config.js*
├── tsconfig.json
└── yarn.lock
```

This is pretty similar to `cdk.dev/website` if you rename `frontend` to `app`.  I am not tied to `app`, it can even be configurable. 

This has the benefit that in `tsconfig.json` the `includes` become much simpler and may not need to be dynamic for v1
This also lays ground work for being able to drop in components, themes, bundles, starter kits via projen.

Current:

```json
  "include": [
    "pages/**/*.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
```

Would become:

```json
  "include": [
    "apps/**/*.ts",
    "apps/**/*.tsx",
    "**/*.ts",
    "**/*.tsx"
  ],

#### Option 2

....

### TODO

[  ] - merge https://github.com/projen/projen/pull/704 (or change the default to tailwind.config.js)
[ X ] - split typescript from jest so that next.js can be test before, during, and after this change
        See the circular reference issue: https://github.com/projen/projen/issues/709
[  ] - Add `JsFile` which extends a file component

**Comment by Chriscbr** [comment]
I'd be OK with this change. It seems like both kinds of directory structures are used on the nextjs projects I see on GitHub, though the examples provided by NextJS seem to just put everything in the root directory (https://github.com/vercel/next.js/tree/canary/examples).

It's probably good to ensure both ways are possible, possibly via a config option (with #183).

As a workaround I think adding `"include": ["**/*.ts", "**/*.tsx"]` to tsconfig.json should allow everything to build.

**Comment by pgollucci** [comment]
The only reason I picked apps (or anything) was to make includes easier.  I think there may be some odd edge conditions to that glob but I agree with all that.

**Comment by pgollucci** [comment]
ok, I've been using nextjs for about a week now.

https://github.com/pgollucci/pgollucci.github.io -> https://pgollucci-github-io-pgollucci.vercel.app/ (WIP)

We don't need `apps/`, we can leave it as it is, the tsconfig.js (not JSON) `purge` option and tsconfig.json include options that need to be 'dynamic' based on other things like components et al.

rootdir needs to move from pages to '.' or all the above is moot.

While postcss.config.json is a valid file name you can't use it with tailwind intelligence and you can't have BOTH it and the .js version so it too needs to become js, not JSON.

I was originally optimizing for github pages b/c its free and not additional infra structure and can be done in a projen work flow.  That said you need to much with next.config.js to accomplish this.  IMHO vercel really is the right option, but you can't do that in a gh workflow that I know of and prod approval is manual?

The next option would be a CDK patters static s3 app to host this.  This is  a good plan to pursue.  In which case we should have:

see @smacintyre 's or about hooking this for sub projects.  I now agree with him.

```shell
frontend/
backend/

**Comment by pgollucci** [comment]
EDIT: nextjs actually yells at you if you put components in pages, so that's out.

**Comment by pgollucci** [comment]
I just realized we/I need to add `next.confifg.js` support.  I think `JsFile` is the next obvious step simplest step.
