### ISSUE TITLE
please add eslint:fix to scripts

### ISSUE THREAD

**Issue by ahammond** [projen/projen#715]
```
    "eslint": "npx projen eslint",
    "eslint:fix": "npx projen eslint --fix",
```

**Comment by Chriscbr** [comment]
You can add your own custom tasks to your project through an appropriate method in `.projenrc.js`. The docs [here](https://github.com/projen/projen/blob/main/docs/tasks.md) include plenty of tips for customizing them! 🙂  

```js
project.addTask('eslint:fix', { exec: 'eslint --fix' });
```

**Comment by ahammond** [comment]
@Chriscbr this is cool. Thanks! I still think that it makes sense as a default.

**Comment by eladb** [comment]
Contributions are welcome

**Comment by ahammond** [comment]
It looks like this is the default now. Which is pretty great!
