### ISSUE TITLE
--no-projenrc-java option does not generate .projenrc.js file 

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#745]
Prior to v0.17.70, running `projen new java --no-projenrc-java` this would generate a .projenrc.js file in the root directory. But now, neither the `.projenrc.js` nor `projenrc.java` files get generated.

PR #744 says
> Resolves #671 (no .projenrc.js file for java projects anymore, which was misleading)

But the docs weren't updated, so I'm not really sure if this was intended or not? Also if .projenrc.js is not supported for Java projects anymore, then:

1.  What is the purpose of this flag? If no projenrc file of any kind is generated, so wouldn't this just be one-off project generation (except files are still marked readonly etc.)? Should we deprecate it?
2. How do we test java projects against local versions of projen for dev purposes? AFAIK if you're using projenrc.java, it will always use the version of projen installed as a dependency from Maven (even if I try to synthesize via a relative directory like `../projen/bin/projen`, it seems to ignore whatever local changes I make).

**Comment by eladb** [comment]
Keep
