### ISSUE TITLE
projen new command does not download external library anymore since version 0.17.69

### ISSUE THREAD

**Issue by nikhil-zadoo** [projen/projen#748]
projen new command with external library seems to not download the package since version projen@0.17.69
eg:
```projen new --from @<EXTERNAL_LIB> <TEMPLATE>```

It worked until version 0.17.68

**Comment by kcwinner** [comment]
Taking a look on this

**Comment by kcwinner** [comment]
Found the commit: https://github.com/projen/projen/commit/e4cae23b7296588af47853afae36618ea064c693

Rolling the changes back here shortly.

**Comment by kcwinner** [comment]
Hit other issues around the new project resolution changes. Working through them.

**Comment by kcwinner** [comment]
PR is live
