### ISSUE TITLE
web projects: "build" tasks do not run projen

### ISSUE THREAD

**Issue by eladb** [projen/projen#754]
The various web projects' "build" task overrides the default build task from `Projen` which means that now `projen` is not executed during build (or at all).

I am wondering if we need a more robust model to manage these tasks, but as an interim solution, maybe we can add a switch that will allow disabling the execution of `compile` and `test` as part of `build` (at the `NodeProject` level) and then the web projects will be able to _append_ instead of overriding.

It will also be good to now allow creating new tasks if a task already exist (`addTask` should fail) and add a `deleteTask` to allow explicitly deleting existing tasks if that's the intent.

**Comment by eladb** [comment]
@Chriscbr what do you think?

**Comment by Chriscbr** [comment]
I see, so the current way web projects override the build task somewhat nullifies the rest of the library's effort to compose the `build` task out of smaller pieces -- so changing it to some kind of "append" operation would fix that. I agree.

> It will also be good to now allow creating new tasks if a task already exist (`addTask` should fail) and add a `deleteTask` to allow explicitly deleting existing tasks if that's the intent.

Sounds good. Depending on the implementation, like if it were possible to `deleteTask('build')` and subsequently `addTask('build')`, I think it's possible to have weird sequencing effects where if a component adds a command to the `build` task, and the user deletes and re-adds the task, then it could appear as though the component isn't working. But I suppose this kind of self-sabotaging is already possible with `reset()` anyway.
