### ISSUE TITLE
dependabot no longer works due to github read-only access

### ISSUE THREAD

**Issue by hoegertn** [projen/projen#760]
In projen project (and projen itself) PRs made by dependabot fail as they are not allowed to access the GH status-check API

https://github.com/projen/projen/runs/2506810979?check_suite_focus=true

**Comment by eladb** [comment]
Ack. I think we should add a condition to the check update that will only do it if there were changes that were pushed to the repo.

Dependabot PRs won't be able to push changes to the repo as well, so if the dep upgrade caused a change, the build will fail and require manual intervention (this is basically anti tamper check).

**Comment by njlynch** [comment]
What's weird is that the build succeeds if manually re-run. Does being run manually give it different permissions?

Example:
Failure: https://github.com/cdklabs/jsii-docgen/pull/312/checks?check_run_id=2518570541
Rerun (success): https://github.com/cdklabs/jsii-docgen/pull/312/checks?check_run_id=2518634649

**Comment by hoegertn** [comment]
Yes, it then seems to run under the auth of the user triggering it.
