### ISSUE TITLE
bump: wrong version is selected if there are two versions on the same commit

### ISSUE THREAD

**Issue by eladb** [projen/projen#762]
When resolving the latest version, if the last tag is on the same commit as the previous tag, then the wrong version is chosen.

Repro:

```bash
$ git tag v1.0.0
$ git tag v1.0.1
$ yarn bump
✔ bumping version in package.json from 0.0.0 to 1.0.1
```

Since both tags `v1.0.0` and `v1.0.1` are on the same commit, the `git describe` returns only the first one lexicographically, which will likely not be the one we want.

**Comment by eladb** [comment]
Apparently, `git tag` supports `--sort="version:refname"` which treats tags as versions. How convenient...

Should we change our `describe` to:

```
$ git tag --sort="-version:refname" | head -n1
```

@RomainMuller what do you think?

**Comment by RomainMuller** [comment]
Looks like a good idea. Prereleases may be problematic (require additional configuration), but this isn't a use-case we have right now, is it? (plus the workaround/add'l config is relatively simple).
