### ISSUE TITLE
Use of npm instead of yarn fails

### ISSUE THREAD

**Issue by ozeebee** [projen/projen#766]
Hello guys, first time trying projen.
I would like to create a CDK V2 TypeScript project with `npm` (I don't have `yarn` installed).
I first had much trouble finding how to use `npm` instead of `yarn`.
It is actually implemented but not documented (yet?): `--package-manager npm`

So using projen latest version, I executed this command to generate the project:
```
npx projen new awscdk-app-ts --package-manager npm --projenrc-ts --cdk-version v2.0.0-rc.1
```

So far, so good. The project is generated.
However, when I try to build it with the `build` npm script, I get this error:
```
> Executing task: npm run build <


> aws-codepipeline-custom-trigger-cdk@0.0.0 build
> npx projen build

🤖 build | npx projen
🤖 default | ts-node .projenrc.ts
🤖 Synthesizing project...
🤖 yarn install --check-files
Error: Command failed: yarn install --check-files
/bin/sh: yarn: command not found

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.exec (/Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk/node_modules/projen/src/util.ts:10:24)
    at NodePackage.postSynthesize (/Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk/node_modules/projen/src/node-package.ts:646:5)
    at AwsCdkTypeScriptApp.synth (/Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk/node_modules/projen/src/project.ts:395:14)
    at Object.<anonymous> (/Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk/.projenrc.ts:16:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk/node_modules/ts-node/src/index.ts:1059:12)
🤖 Synthesis failed: Task "default" failed when executing "ts-node .projenrc.ts" (cwd: /Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk)
🤖 Task "build" failed when executing "npx projen" (cwd: /Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk)
npm ERR! code 1
npm ERR! path /Users/ajo/Projects/Tests/aws-codepipeline-custom-trigger-cdk
npm ERR! command failed
npm ERR! command sh -c npx projen build
```

So, it looks like a bunch of scripts (found in the `.projen/tasks.json` file) use `yarn` instead of `npm` (well, actually there is no reference at all to `npm` in these scripts).

Should I conclude that `npm` is not (yet) supported ?

Thanks !

**Comment by Chriscbr** [comment]
I'm having trouble reproducing this issue. Can you check that your `.projenrc.ts` file has the option `packageManager: NodePackageManager.NPM,` added? (When I tried initializing the project with the setup you provided, I had to manually edit this because it raised an error with `packageManager: 'npm'`).

**Comment by ozeebee** [comment]
Strange. I re-created a project with `npx projen new awscdk-app-ts --package-manager npm --projenrc-ts --cdk-version v2.0.0-rc.1`
And now, when building I get this (other) error message:
```
.projenrc.ts:6:3 - error TS2322: Type '"npm"' is not assignable to type 'NodePackageManager | undefined'.
```
I guess this is more inline with what you expect right ?
So, I changed my `.projenrc.ts` to have a valid package manager: `packageManager: NodePackageManager.NPM,`
and now it works.

So the question is: how do I bootstrap a project with npm ?
Because, If i try this, it fails:
`npx projen new awscdk-app-ts --projenrc-ts --cdk-version v2.0.0-rc.1` --> `/bin/sh: yarn: command not found`
I also tried this without success:
`npx projen new awscdk-app-ts --package-manager NodePackageManager.NPM --projenrc-ts --cdk-version v2.0.0-rc.1` --> `Error: unexpected package manager NodePackageManager.NPM`

**Comment by Chriscbr** [comment]
> So the question is: how do I bootstrap a project with npm ?

For now I think the first way you listed (with `--package-manager npm`) is the most correct -- you just have to manually update `.projenrc.ts` after you get started.

I forgot about this before, but if you run `npx projen new awscdk-app-ts --help`, we don't actually show the `--package-manager` option because we don't explicitly support it -- this is because of a small technical issue. (Right now only string, number, and boolean typed options are accepted as CLI args, because we support projenrc files in multiple languages). It could be possible to fix this, but it requires taking a closer look at how we are processing arguments and using jsii.

**Comment by mmcculloh-dms** [comment]
As a workaround for `/bin/sh: yarn: command not found`, if you use `--no-post` you can avoid the post install that would normally fail without yarn:

`npx projen new awscdk-app-ts --projenrc-ts --cdk-version v2.0.0-rc.1 --no-post`

So you can change the package manager in `.projenrc.ts` manually before running anything. Make sure to run `npm i` before `npm run projen` as you'll need ts-node.

**Comment by ozeebee** [comment]
Another problem I see (maybe not directly related to this) is that I don't have any build/compile task invoking the TypeScript compiler `tsc`.
There is a `watch` task that invokes it but the `compile` task seems empty:
```
    "compile": {
      "name": "compile",
      "category": "00.build",
      "description": "Only compile"
    },
```
I don't know if it's intentional or not.

**Comment by Chriscbr** [comment]
@ozeebee Is there a task in your project which runs the `jsii` command? This should automatically run `tsc` under the hood.

**Comment by ozeebee** [comment]
Nope, I don't have any reference to `jsii` in my `tasks.json` file.

Anyway, I fixed the problem by modifying the compile task in my `.projenrc.ts`:
```
project.tasks.tryFind('compile')?.exec('tsc')
```
It's a little bit ugly but it definitely works ;)

**Comment by Chriscbr** [comment]
I did a small test and it looks like the bug is fixed.
