### ISSUE TITLE
projenrc.js does not get synthesized when external project is used

### ISSUE THREAD

**Issue by pgarbe** [projen/projen#778]
When I run `npx new --from mylib myproject` it creates all files except the `.projenrc.js` file. But if I run the command afterwards again, it creates the file as expected. 

The latest successful test was with v0.17.75. It started failing with 0.17.78 and newer (the two releases in between are not available)

Interestingly when at least the packages in node_modules are in the local folder it also works the first time.

**Comment by kcwinner** [comment]
Have you tested this with the latest versions? I saw this around the same time as you but haven't seen it lately

**Comment by pgarbe** [comment]
Totally forgot about that issue. Yes, it has been solved already.
