### ISSUE TITLE
Allow release on demand

### ISSUE THREAD

**Issue by pgarbe** [projen/projen#782]
Since the change to the tag-based release projen makes it impossible to use other release mechanism. 

My use case is to run the "release" task on a developer machine to increase the version, create the changelog, set a tag, and commit everything. In my CodePipeline it publish the package if the commit contains a version tag.

Even with some ~hacks~ escape hatches it's not possible to completely restore the old behavior. Projen will still overwrite the package.json version with "0.0.0" when it runs. The workaround is also very messy as it's not easy to change `versionrc.json`.

**Comment by eladb** [comment]
@pgarbe yes, this use case is not very well supported. I need to think what's the best way to address this.

**Comment by pgollucci** [comment]
What's wrong with what you did in `aws/constructs`?  removing push triggers via `releaseEveryCommit: false`?

**Comment by eladb** [comment]
Keep open please
