### ISSUE TITLE
Feature request: support lambdas written in TypeScript

### ISSUE THREAD

**Issue by haimlit** [projen/projen#783]
### Background

projen generates CDK projects written in TypeScript. Lambda handlers don't support TypeScript natively, and require compiling their code from TypeScript to Javascript/node first. In order to write a construct containing a lambda handler written in TypeScript, a two phased compilation is required - one which is ad-hoc for lambda handlers, compiling them from TS to JS, and another which is the standard TS project compilation.

### Current state

Currently, to perform the ad-hoc lambda handler compilation, additional code is required on projen to add a new task to compile the lambda `*.ts` files. Here's a snippet which does this for a specific lambda handler:

```typescript
const bundleLambdaHandlerTask = project.addTask('bundle:handler/myHandler', {
  description: 'bundle handler/myHandler',
  exec: [
    'esbuild',
    '--bundle',
    `${project.srcdir}/handler/myHandler.ts`,
    '--target="node14"',
    '--platform="node"',
    `--outfile="${project.srcdir}/handler/myHandler.js"`,
    '--external:aws-sdk',
  ].join(' '),
});
project.compileTask.spawn(bundleLambdaHandlerTask);
```

It could be improved by scanning for all files with a pattern of `handler/*.lambda.ts` for example. [Link to `contruct-hub` which does this type of scan](https://github.com/cdklabs/construct-hub/blob/main/.projenrc.js#L138), where a different approach was taken by generating full lambda construct code behind the scenes.

### Feature request

This boilerplate could be saved if projen would have that step support OOTB.
See API proposal below to extend `AwsCdkConstructLibraryOptions`.
All values are also proposed to be the default ones.

```typescript
bundleLambda: {
  // AWS lambdas have AWS SDK available at runtime, which some lambdas use.
  // This flag saves the developer from explicitly declaring AWS SDK under devDeps section.
  addAwsSdkDep: true

  // Suffix to be used to scan for lambdas.
  suffix: 'lambda.ts'

  // Let developer choose whether the compiled lambda handler should be committed or not.
  addToGitIgnore: true
}
```

### Pitfall

On one hand, `aws-sdk` shouldn't be a dependency and get bundled, as it's a runtime dependency only. However, `eslint` doesn't play well with `aws-sdk` being a devDependency, as when a lambda imports `aws-sdk`, `eslint` requires disabling `import/no-extraneous-dependencies` rule. This should probably be part of the solution.

**Comment by eladb** [comment]
Keep
