### ISSUE TITLE
upgrade-deps build fails with "Your lockfile needs to be updated"

### ISSUE THREAD

**Issue by eladb** [projen/projen#800]
The new workflow which was introduced in #652 fails in the "Build" step when dependencies are updated. This is because `projen build` will execute `yarn install --frozen-lockfile` after the `package.json` was changed, so we get this error:

```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

See example [here](https://github.com/cdklabs/cdk-triggers/runs/2608296205?check_suite_focus=true)

**Comment by lym953** [comment]
I still see this error when a workflow runs `npx projen`. Could anyone help with this?
https://github.com/DataDog/datadog-cdk-constructs/actions/runs/13527637337/job/38014208796?pr=362

**Comment by mrgrain** [comment]
> I still see this error when a workflow runs `npx projen`. Could anyone help with this?
> https://github.com/DataDog/datadog-cdk-constructs/actions/runs/13527637337/job/38014208796?pr=362

Pretty straight forward: Dependabot is attempting to upgrade a dependency these you have explicitly declared here: 

https://github.com/DataDog/datadog-cdk-constructs/blob/6814eead55bfc5d17a01a19aa16fd0bc03ae062c/.projenrc.js#L28

Projen protects you from this unintentional change.

**Comment by lym953** [comment]
@mrgrain That answers my question. Thanks!
