### ISSUE TITLE
Feature request: more intuitive way to define job-scope and step-scope envs for Github Actions

### ISSUE THREAD

**Issue by HsiehShuJeng** [projen/projen#815]
# Background  
I initialized a **projen** project for a Typescript app and wanted to make the CICD of the application automatic. Since the default values of `buildWorkflow` and `releaseWorkflow` in Class `AwsCdkTypeScriptApp` are all true, i.e., the definitions of two workflows can be auto-generated. I thought it's quite awesome until I pushed a change to Github. Since the last process in `npx projen build` involves `cdk synth`, at that moment I realized I need AWS credentials which have minimal IAM permissions for making CDK work, or making `cdk synth` passed.

# Current state  
1. There is an argument named `releaseWorkflowSetupSteps`. By some experiment, I do can create a step where environment variables can be defined (and it's always placed before the step where `npx projen build` is going to be executed), yet an environment variable in a step cannot be referenced in another step.  
    ```typescript
    releaseWorkflowSetupSteps: [{ name: 'Before build', env: { TEST_ENV: 'test' } }]
    ```

2. And about global environment variables, either defining in `env` or setting in the `GITHUB_ENV` file, there is no any function that can enable me to do it.  
3. According to *Ken Winner*, there is some tricky way similar to the following that might fulfill my intention.  
    ```typescript
    const steps = [
      {
        name: 'Download build artifacts',
        uses: 'actions/download-artifact@v2',
        with: {
          name: 'dist',
          path: 'dist',
        },
      },
      // {
      //   uses: 'actions/setup-node@v2',
      //   with: {
      //     'node-version': '12.x',
      //     'scope': '@kcwinner',
      //   },
      // },
      {
        name: 'Release',
        run: 'cd dist/js && npm publish',
        env: {
          NODE_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
        },
      },
    ];
    project.releaseWorkflow.file.addOverride('jobs.release_npm.steps', steps);
    ```

# Workaround  
I turned off `buildWorkflow` and `releaseWorkflow`, that means I explicitly made them `false` and defined almost the same content as the auto-generated yaml configurations except environment variables through the following way. (very clumsy)  
```typescript
    const prWorkflow = project.github.addWorkflow('build');
    deployWorkflow.on({
      push: {
        pull_request: {},
        workflow_dispatch: {},
      },
    });
    prWorkflow.addJobs({
      build: {
        runsOn: 'ubuntu-latest',
        permissions: { contents: 'write', contents: 'write' },
        steps: [
          {
            name: 'Checkout',
            uses: 'actions/checkout@v2',
            with: {
              ref: '${{ github.event.pull_request.head.ref }}',
              repository: '${{ github.event.pull_request.head.repo.full_name }}',
            },
          },
          {
            name: 'Install dependencies',
            run: 'yarn install --check-files --frozen-lockfile',
          },
          {
            name: 'Anti-tamper check',
            run: 'git diff --ignore-space-at-eol --exit-code',
          },
          {
            name: 'Set git identity',
            run: 'git config user.name "Automation"\ngit config user.email "github-actions@github.com"',
          },
          {
            name: 'build',
            run: 'npm run build',
          },
          {
            name: 'Check for changes',
            id: 'git_diff',
            run: 'git diff --exit-code || echo "::set-output name=has_changes::true"',
          },
          {
            if: 'steps.git_diff.outputs.has_changes',
            name: 'Commit and push changes (if changed)',
            run: 'git add . && git commit -m "chore: self mutation" && git push origin HEAD:${{ github.event.pull_request.head.ref }}',
          },
          {
            if: 'steps.git_diff.outputs.has_changes',
            name: 'Update status check (if changed)',
            run: 'gh api -X POST /repos/${{ github.event.pull_request.head.repo.full_name}}/check-runs -F name="build" -F head_sha="$(git rev-parse HEAD)" -F status="completed" -F conclusion="success"',
            env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' },
          },
        ],
        env: {
          CI: 'true',
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}',
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}',
          AWS_REGION: 'ap-northeast-1',
        },
      },
    });
```

# What do you expect?  
I expect that there are at least two ways that can help developers to define step-scope and job-scope environment variables directly.
`project.github.addEnvs({ENV1: "hakunamatata", ENV2: "AppRunner"})`: job-scoped
`project.github.addEnv(step.name, {ENV3: "LaLaLand"}};`: step-scoped

just a quick example, more broad consideration related to **projen** and **Github Acitons** might be needed.

**Comment by kcwinner** [comment]
There are a few ways to get what you desire except for the step-scoped path.

## Example 1: Global Env
```js
project.releaseWorkflow.file.addOverride('env', {
  NODE_AUTH_TOKEN: '${{secrets.NPM_TOKEN}}',
  SLACK_WEBHOOK_URL: '${{ secrets.SLACK}}',
});
```

Results in
```
jobs:
  ...
  ...
  ...
env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK}}
```

## Example 2: Job Based Env
```js
project.releaseWorkflow.file.addOverride('jobs.release_npm.env', {
  NODE_AUTH_TOKEN: '${{secrets.NPM_TOKEN}}',
  SLACK_WEBHOOK_URL: '${{ secrets.SLACK}}',
});
```

Results in
```
jobs:
  release:
    ...
    ...
  release_npm:
    name: Release to NPM
    needs: release
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Release
        run: cd dist/js && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK}}
```

**Comment by HassanMahmud** [comment]
I could not figure out how to add global env variables in the workflows as well. I plan to disable the projen workflows for now.

**Comment by eladb** [comment]
@brianfoody @HassanMahmud @HsiehShuJeng I am assuming you need these environment variables as part of build, correct? Will it be sufficient to address your use case if you could add environment variables to the `build` task.

Something like this:

```ts
project.buildTask.addEnv('FOO', 'bar');
```

This will apply both locally and in all workflows that execute this task.

**Comment by drernie** [comment]
@eladb Is there a better solution for this yet?
```
project.buildTask.addEnv('FOO', 'bar');
```
Would work for me...

**Comment by drernie** [comment]
Actually, I was able to get this to work (not sure where I found it):
```javascript
project.tryFindObjectFile('.github/workflows/build.yml')!.addOverride('jobs.build.env', {
  CI: 'true',
  ENVAR: '${{ ENVAR }}',
});
```
Make sure to do it _before_ synth (I did it wrong the first time :0).

**Comment by eladb** [comment]
:D
