### ISSUE TITLE
After updating from 0.17.43 to 0.18.4 having issues with .gitattributes

### ISSUE THREAD

**Issue by smashedtoatoms** [projen/projen#816]
I updated to 0.18.4 and ran into issues with projen.github.GitHub.  I have something that looks like this:

```typescript
export class Project extends projen.Project {
  constructor(props: ProjectProps) {
    super({ clobber: false, name: props.repositoryName });
  ...
    const github = new projen.github.GitHub(this, { mergify: true });
  ...
}
```

I then end up getting an error like this:

```
/Users/me/Code/Stedi/projen/node_modules/projen/lib/file.js:31
            throw new Error(`there is already a file under ${path.relative(project.root.outdir, this.absolutePath)}`);
            ^

Error: there is already a file under .gitattributes
    at new FileBase (/Users/me/Code/Stedi/projen/node_modules/projen/lib/file.js:31:19)
    at new GitattributesFile (/Users/me/Code/Stedi/projen/node_modules/projen/lib/github/github.js:69:9)
    at new GitHub (/Users/me/Code/Stedi/projen/node_modules/projen/lib/github/github.js:22:30)
    at new Project (/Users/me/Code/Stedi/projen/dist/src/index.js:84:28)
```

There is no .gitattributes anywhere in this project, so I am not sure where this is coming from.  I'm sure it is something I am doing, I just have no idea what.  Any ideas would be appreciated.

**Comment by smashedtoatoms** [comment]
It appears that this was introduced in this PR: https://github.com/projen/projen/commit/77edd3de4a41f380e2d79819c4e10251a28cbfbe

**Comment by smashedtoatoms** [comment]
I am not sure what to do to resolve it, but I am going to pin at version 70 for now.

**Comment by eladb** [comment]
The `Project` class already has a `GitHub` component. Instead of creating one you can just access it via `.github`:

```ts
export class Project extends projen.Project {
  constructor(props: ProjectProps) {
    super({ clobber: false, name: props.repositoryName });
  ...
    const github = this.github;
    
  ...
}
```

Closing for now. LMK if this is not a satisfying solution.
