### ISSUE TITLE
Ability to disable all Github Actions workflows more easily

### ISSUE THREAD

**Issue by mwgamble** [projen/projen#828]
Right now I'm not aware of a way to easily disable all Github Actions in an easy manner. To disable the dependency upgrade workflow, I had to pass something like this:

```
// @ts-ignore
depsUpgrade: {
    ignoresProjen: false,
    binder() {},
    bind() {},
},
```

I've been trying to use Projen in a work environment where we use a different CI solution, and Github Actions simply isn't enabled in our GHE appliance.

**Comment by MarkMcCulloh** [comment]
For the specific example of disabling the dependency upgrade workflow, you can do:

`depsUpgrade: DependenciesUpgradeMechanism.NONE`

But the general point still stands. Recently a new workflow was added (stale), so if you want to avoid new workflows being created you have to make sure you stay on top of them and update projenrc as needed.

**Comment by polothy** [comment]
Bonus points: have the ability to easily disable individual workflows vs a single on/off switch.

**Comment by brianfoody** [comment]
Need this also, a client is using CircleCI.

**Comment by mwgamble** [comment]
@eladb I took a look at the PR. From what I can tell, Projen now conflates "github actions" with "github". Is this accurate? From what I can tell, if I wanted Projen to manage issue/PR templates but not Github Actions workflows, I can no longer do this.

**Comment by eladb** [comment]
You are correct. Currently setting `GitHub` to `false` means that all GitHub integration is disabled.

I'll reopen this to address the particular use case of disabling only workflows.
