### ISSUE TITLE
Incorrect Apache-2.0 license file

### ISSUE THREAD

**Issue by wchaws** [projen/projen#830]
The copyright piece in Apache-2.0 is an example source header. it should not be edited. To declare the copyright, we need to use a separated NOTICE file. Check this project as an example https://github.com/apache/kafka/blob/trunk/LICENSE
The original Apache-2.0 license: https://www.apache.org/licenses/LICENSE-2.0.txt

```diff
diff --git a/a b/b
index f49a4e1..3a48601 100644
--- a/a
+++ b/b
@@ -186,7 +186,7 @@
       same "printed page" as the copyright notice for easier
       identification within third-party archives.
 
-   Copyright [yyyy] [name of copyright owner]
+   Copyright 2021 Elad Ben-Israel
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
```

**Comment by eladb** [comment]
TIL. Contributions are welcome
