### ISSUE TITLE
bug: auto-approve actions is not working

### ISSUE THREAD

**Issue by kimisme9386** [projen/projen#860]
## Source code

https://github.com/projen/projen/blob/2a74d1ad6f810a479b9c503a52ffb9acda8421a7/src/github/auto-approve.ts#L56

## Debug

I use [hmarr/debug-action@v2](https://github.com/hmarr/debug-action) to debug GitHub Action event context payload.

Results are in below

https://github.com/kimisme9386/cdk-codepipeline-status/runs/2760884616?check_suite_focus=true#step:2:450

It seems to has no `github.event.pull_request.login` property and  `github.event.pull_request.user.login` is maybe the right property.

**Comment by pahud** [comment]
same here.

I believe it should be

```
github.event.pull_request.user.login == 'github-actions[bot]'
```
