### ISSUE TITLE
Use NPM to add projen and external module instead of Yarn

### ISSUE THREAD

**Issue by mmcculloh-dms** [projen/projen#885]
When using an external project type, projen installs the targeted package with yarn. 
While I understand the desire to use Yarn as much as possible, I think it would make more sense to use the default package manager. This brings a few benefits:

1. Since the user must have node, then they will always be able to use projen regardless of whether or not they have yarn
2. If the project being loaded is configured to use NPM or PNPM, then there really is no reason for yarn to be a part of the process at all and at worse can cause confusion
3. (This could be accomplished without switching to NPM, but still) Peer deps of the external project are installed by default through NPM, which may or may not be necessary for the project to synth
4. `yarn add` has unfortunate behavior when being run in a subfolder of another node project. It attempts to add it to the package.json of the parent folder even though it adds it to the current dir's node_modules. This can make it very slow as it tries to resolve the dependency tree in an unecessary way. NPM would not have this behavior with --prefix, although this could probably be solved in yarn with --cwd

**Comment by eladb** [comment]
Keep

**Comment by mmcculloh-dms** [comment]
This turns out to be even more important when `projen new` is being run in a subdir of another project with a package.json, causing the initial `yarn add` to be extremely slow. Updated the issues with that pain point. I'm going to work out a PR for this later today.
