### ISSUE TITLE
PROJECT-TYPE cli argument not working for external modules with multiple types

### ISSUE THREAD

**Issue by rlmartin** [projen/projen#887]
`ProjectType` is being used for two different concepts:

1. As a definition for a projen project type: https://github.com/projen/projen/blob/main/src/inventory.ts#L26
2. As an enum used for jsii purposes: https://github.com/projen/projen/blob/main/src/project.ts#L523

Because all projects inherit from the `Project` class, the `ProjectOptions` includes the `projectType` property: https://github.com/projen/projen/blob/main/src/project.ts#L84

The `new` cli command exposes `PROJECT-TYPE` as an argument, which gets camelcase-d to `projectType`: https://github.com/projen/projen/blob/main/src/cli/cmds/new.ts#L18

This argument is intended to be used to determine the projen project class to use. But it also sets the `ProjectOption.projectType` property. The config for this property is:

```
{
    "path": ["projectType"],
    "parent": "ProjectOptions",
    "name": "projectType",
    "fqn": "projen.ProjectType",
    "docs": "Which type of project this is (library/app).",
    "type": "ProjectType",
    "kind": "enum",
    "switch": "project-type",
    "default": "ProjectType.UNKNOWN",
    "optional": true,
    "featured": true
}
```

The above clashes with the idea of `projectType` representing the [projen project type](https://github.com/projen/projen/blob/main/src/inventory.ts#L26).

As a result, I am seeing the following error when bootstrapping a new projen project using an external module with multiple project types defined:

```
npx projen new --from "file:../my-projen-types" foo
```

results in

```
evalmachine.<anonymous>:6
  projectType: ProjectType.FOO,
               ^

ReferenceError: ProjectType is not defined
    at evalmachine.<anonymous>:6:16
```

External modules work for a single type, because `PROJECT-TYPE` is not required and thus does not set the `projectType` option, which then results in the default (`ProjectType.UNKNOWN`).

**Comment by eladb** [comment]
Yes, I also ran into this.  

@Chriscbr would you like to take a look at this?

**Comment by rlmartin** [comment]
Thanks! If you're in there fixing things, I noticed a very small bug here: https://github.com/projen/projen/blob/main/src/javascript/render-options.ts#L213 - it will only replace the first `-`; it should instead be: 

```
.replace(/-/g, '_')
```
