### ISSUE TITLE
Next.js with TypeScript EACCES error on next-env.d.ts file

### ISSUE THREAD

**Issue by J-Liciaga** [projen/projen#934]
**Description:** 

Projen nextjs-ts is giving off EACCES errors for the file next-env.d.ts when running the following commands: _yarn dev_ or _yarn build_

Running _yarn start_ prompts the user to run _yarn test_  instead.

**Steps to Reproduce:**

1. Open terminal, cd into your development folder and run the following command: mkdir test-projen && cd test-projen && git init 
2. Once git init has finished running, run the following command: npx projen new nextjs-ts
3. Once the projen process has finished running, run the following command: yarn dev or npm run dev. 

**Errors:**
_test-projen git:(main) yarn dev
yarn run v1.22.10
$ npx projen dev
🤖 dev | env: PATH=/Users/me/.nvm/v...
🤖 dev | next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
[Error: EACCES: permission denied, open '/Users/me/dev/test-projects/test-projen/next-env.d.ts'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/me/dev/test-projects/test-projen/next-env.d.ts'
}
🤖 Task "dev" failed when executing "next dev" (cwd: /Users/me/dev/test-projects/test-projen)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command._

------

test-projen git:(main) yarn build
yarn run v1.22.10
$ npx projen build
🤖 build | env: PATH=/Users/me/.nvm/v...
🤖 build | npx projen
🤖 default | env: PATH=/Users/me/.nvm/v...
🤖 default | node .projenrc.js
✨ Synthesizing project...
🤖 yarn install --check-files
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...

success Saved lockfile.
✨ Synthesis complete
🤖 build » test | env: PATH=/Users/me/.nvm/v...
🤖 build » test » test:compile | env: PATH=/Users/me/.nvm/v...
🤖 build » test » test:compile | No actions have been specified for this task.
🤖 build » compile | env: PATH=/Users/me/.nvm/v...
🤖 build » compile | tsc --build
🤖 build | next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5

> Build error occurred
[Error: EACCES: permission denied, open '/Users/me/dev/test-projects/test-projen/next-env.d.ts'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/me/dev/test-projects/test-projen/next-env.d.ts'
}
info  - Checking validity of types .🤖 Task "build" failed when executing "next build" (cwd: /Users/me/dev/test-projects/test-projen)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Chriscbr** [comment]
Thanks for reporting this :) I've got a PR ready to fix this.

> Running yarn start prompts the user to run yarn test instead.

We've actually taken out the `start` command for now (I think we weren't sure if many people were using it). Though the docs need to be updated as well, so it's good you pointed that out.
