### ISSUE TITLE
Publishing Maven/Java to GitHub Packages

### ISSUE THREAD

**Issue by mKeRix** [projen/projen#947]
Hey,

thanks for creating this cool project! I've started building an AWS CDK construct library for internal use, which I would like to publish to GitHub Packages. In #355 some work was already done to make this possible, but either a change broke it in the mean time or I'm missing something.

I've configured my .projenrc.js like shown below, but the workflow fails with an authorization error in the Release to Maven job. I've also configured the MAVEN_USERNAME secret to match my username.

```javascript
const project = new AwsCdkConstructLibrary({
  publishToMaven: {
    javaPackage: 'com.github.mkerix.something',
    mavenGroupId: 'com.github.mkerix',
    mavenArtifactId: 'something',
    mavenServerId: 'github',
    mavenRepositoryUrl: 'https://maven.pkg.github.com/mkerix/something',
    mavenPassword: 'GITHUB_TOKEN',
  },
} 
```

I believe the issue is that [publishToMaven](https://github.com/projen/projen/blob/88379ed5588e40338fcbc1a3e5b0f37033c64ac8/src/release/publisher.ts#L111) is missing the additional permissions to write to packages. For comparison, [publishToNpm](https://github.com/projen/projen/blob/88379ed5588e40338fcbc1a3e5b0f37033c64ac8/src/release/publisher.ts#L71) sets this based on a conditional check.

Furthermore, the release process to GitHub could be a made a bit nicer by auto-configuring the username to match the repository owner. This would bring it closer to the Maven release process that people are used to from GitHub Actions.

**Comment by eladb** [comment]
@mKeRix thanks for reporting this. Is this something you'd be interested to contribute to the project? Sounds like you have a good sense of what needs to be done :-D

**Comment by mKeRix** [comment]
Gladly! I took a stab at it and opened a PR.
