### ISSUE TITLE
Preflight checks for "new"

### ISSUE THREAD

**Issue by tomcavanaugh** [projen/projen#961]
The getting started section of the README does not mention requirements.  

Suggest updating README or adding preflight checks to "new" command:

•	Verify “git config --global user.name" Is not blank
•	Verify “git config --global user.email" Is not blank
•	Verify yarn is installed
•	Verify node is >= 12

Projen Version: 0.27.13
Environment: New Cloud 9 instance

**Comment by eladb** [comment]
Good idea

**Comment by Chriscbr** [comment]
Keep
