### ISSUE TITLE
Pattern to split Integration from Unit Tests

### ISSUE THREAD

**Issue by pgollucci** [projen/projen#98]
Should be pretty simple with a regex and/or dir split on file names.

**Comment by pgollucci** [comment]
integ.foo.ts 
foo.ts

**Comment by eladb** [comment]
What would you expect projen to do to help here? At the moment, jest will only run files called `test/*.test.ts` as unit tests. When do you expect integ tests to be executed?

**Comment by pgollucci** [comment]
Generate package.json pieces to make the on-demand running simpler / consistent.

**Comment by eladb** [comment]
So like `yarn test:integ` which will just run `jest` with a filter for `test/**/*.integ.ts`?

**Comment by pgollucci** [comment]
exactly

**Comment by Miradorn** [comment]
Hey there, I just stumbled upon this and could also use this functionality.
Maybe i could implement this if you give me some pointers where to start!

Thanks.

**Comment by pgarbe** [comment]
Is there an example how to configure jest? Does it need two different config files?
