### ISSUE TITLE
How to bump from 0.x.x to 1.x.x version?

### ISSUE THREAD

**Issue by ruggero-visintin** [projen/projen#982]
Hi there,

We tried to bump a release containing braking changes but we still get a simple minor bump instead of a major bump (which we would expect). After digging for the root cause, we found [this issue](https://github.com/conventional-changelog/standard-version/issues/539#issue-558765014) that confirms it's intended [here](https://github.com/conventional-changelog/standard-version/issues/539#issuecomment-654832540) and [here](https://github.com/conventional-changelog/standard-version/issues/539#issuecomment-734915168).

That said, we don't understand how we should proceed to bump to a 1.x.x version, and therefore have breaking changes effectively bump major version instead of minor.

We've tried some different approaches but none has succeeded in bumping and releasing a 1.0.0 version.

Hope you can help us,
Thanks a lot!

**Comment by hoegertn** [comment]
Semantic versioning works differently for versions starting with `0.`. Everything before `1.0.0` is considered experimental and breaking changes are only minor version bumps. The moment you feel comfortable you need to bump the version manually to `1.0.0` and then the well-known versioning kicks in where breaking changes bump the major version, features bump the minor and fixes bump the patch version.

**Comment by ruggero-visintin** [comment]
Thanks for the reply.

We've tried to manually bump the version to 1.0.0 but the result is a failure at the Anti-tamper check. So we thought it wasn't the right way to do it.

**Comment by eladb** [comment]
@ruggero-visintin this is not well-documented, but you can just set `majorVersion` of your project to `1` and projen should take care of the rest:

```js
const project = new TypeScriptProject({
  // ...
  majorVersion: 1,
});
```

You can also specify multiple release branches, and set a different major version for each one:

```js
  releaseBranches: {
    '2.x': {
      majorVersion: 2,
    },
    '3.x': {
      majorVersion: 3,
      prerelease: true,
    },
  },
```

I am closing for now, feel free to comment if you still have any questions on the topic.

**Comment by eladb** [comment]
Added minimal docs: https://github.com/projen/projen/pull/1018

**Comment by samson-sham** [comment]
Hi, how is the version be automatically taken care?
I did
```
const project = new awscdk.AwsCdkTypeScriptApp({
  majorVersion: 1,
})
```
and execute `npx projen`, nothing change on my package.json.
I tried git commit with "feat: message", nothing change again.
then execute `npx projen` again, nothing has changed.

Does this require GitHub workflows to work?

**Comment by SuperMohit** [comment]
@samson-sham I also have the same issue. Were you able to resolve this?

**Comment by mrgrain** [comment]
projen uses git tags for versioning, GHA workflows _are_ not required.

It's all documented in the docs: https://projen.io/releases.html
