### ISSUE TITLE
Release workflow idempotence

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#983]
Context: For JSII projects that are configured using projen to publish to multiple package registries (using options like `publishToMaven`, `publishToPyPi`, etc.), the default GitHub workflow generated by projen currently works like the following:

-  a job named `release` bumps the version
- jobs named `release_github`, `release_npm`, `release_pypi` etc. publishes artifacts to the appropriate registries

The command `npx projen release`, which is run as part of the `release` job above, is idempotent by itself (if I run it multiple times locally, it bumps to the same version every time). But the entire workflow is not idempotent altogether.

For example, if the `release` job succeeds and the `release_github` job succeeds, but `release_npm` fails, then re-running the entire workflow manually (because [individual jobs can't be re-run](https://github.community/t/ability-to-rerun-just-a-single-job-in-a-workflow/17234)) causes the version to be bumped _again_ causing the latest commit to be tagged with two versions. I validated this behavior in a test repo.

This is a problem because if one of the release jobs fails (due to a recently expired token, etc.), since there is no way to re-run the job to re-try releasing a package to a registry.

**Comment by eladb** [comment]
+1 basically what we need is to change the bump logic such that it will not bump if there is already a tag on the same commit
