### ISSUE TITLE
git config user.* in build.yml compared to upgrade.yml

### ISSUE THREAD

**Issue by jumic** [projen/projen#988]
I just tried to understand which git user.name/user.email is used in the GitHub workflows. There is one difference which I don't understand at the moment.

In the build workflow, git user.name/user.email will be set.
https://github.com/projen/projen/blob/84a0ddb3e3eaa7d190156ade0c1f7cdf1b367dee/.github/workflows/build.yml#L22-L25

However, in workflow [upgrade](https://github.com/projen/projen/blob/84a0ddb3e3eaa7d190156ade0c1f7cdf1b367dee/.github/workflows/upgrade.yml), those commands are missing.

In both workflows, changes will be committed to the repository. Because of that, it should make sense to set user.name/user.email in both workflows.

Is there any reason why it is not done in the upgrade workflow? Or are these commands missing in this workflow?

As long as user.name/user.email are not set, the commits in the pull request from the upgrade workflow show a real user instead of a bot, e.g. https://github.com/projen/projen/pull/979/commits. (Maybe the repository owner or the user who has created the workflow is used there).

Thanks.

**Comment by eladb** [comment]
No reason, just an oversight. Would be great to normalize this across workflows. Contributions are welcome!

**Comment by akbhuker** [comment]
hey, can I have this issue?
I'm quite new to this so I might need some guidance
