### ISSUE TITLE
Be able to specify the out directory of the top-level parent project

### ISSUE THREAD

**Issue by alexforsyth** [projen/projen#991]
I would like to be able to set the out directory of a top level parent project post construction.

**Comment by eladb** [comment]
Changing the output directory post construction is not going to be trivial (and likely impractical with the current design). There's quite a lot of code that depends on knowing where is the output directory during initialization process.

Can you please provide some more details about your use case? Why is this feature needed? Maybe we can address this need in a different way.

**Comment by alexforsyth** [comment]
Yes, that is a good point, and on consideration doing this smells bad. I will close this for now.
