### ISSUE TITLE
Generated files cleanup issues

### ISSUE THREAD

**Issue by sihil** [projen/projen#996]
Hello :)

There are a couple of issue with cleanup that we've come across.

Firstly, it attempts to ignore files that would be matched by `.gitignore`. In the case that something like `target/` is in `.gitignore` then it will successfully ignore `target/**` in the root of the repo but it doesn't ignore `subdirectory/target/**` (which git would ignore for `target/` but not `/target/`). Note that it behaves as expected if `**/target/` is used, but the behaviour doesn't quite match at the moment.

Secondly, if happens to find a socket then it bails with the error below. I suspect a quick check that it's a normal file would be fine here as projen shouldn't be cleaning up sockets.

```
🤖 warning: failed to clean up generated files: Error: UNKNOWN: unknown error, open '/Users/sihil/code/sbt-riffraff-artifact/project/target/sbt-load.sock'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
```

**Comment by eladb** [comment]
I believe this should be resolved
